### PR TITLE
[Ignore] RichText: try using hooks for wrapper component

### PR DESCRIPTION
**Pull request by ellatrix**
Fixes #

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ellatrix** [comment]
@hypest Both test suites "on Device" are failing. Not sure what I'm doing wrong. It says "The environment you requested was unavailable."

**Comment by hypest** [comment]
I've tried restarting the failing e2e jobs a couple of times to no avail. I now manually pushed a branch with the commit to try and see if CI/Saucelabs will like that better commit from my account.

**Comment by hypest** [comment]
Many tests are still failing on CI, and same when running them locally with `yarn test:e2e:android:local`. Looking at `develop` now since I'm under the impression the tests are failing there as well.

**Comment by hypest** [comment]
It seems that the toolbar is missing its buttons. Verified it locally, and the issue is also there at the video of the test run: https://app.saucelabs.com/tests/a6ea5bace0d14571a693b9946dbb7077?auth=4ef7f039c630a93f326f29de2a1eeccb#4

**Comment by mchowning** [comment]
:wave: @ella. I was looking into these test failures and I took your code and merged it with the latest from gutenberg `master` and gutenberg-mobile `develop`, and pushed it to a test branch ([test_rich-text-hooks](https://github.com/wordpress-mobile/gutenberg-mobile/tree/test_rich-text-hooks)) and the tests just passed for me on that branch: https://circleci.com/workflow-run/e8ee8403-b5b2-460c-be2e-5ca2859b3f0d .

I did recently merge [one fix for the Android e2e tests](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1813), but that was addressing a different issue from the environment-unavailable problem we  were seeing on this. If you want to try updating your branches, it seems like they may pass CI now. But if you get any failures, please let me know because I'm trying to find a way to reproduce the test failure you were seeing before.

**Comment by mchowning** [comment]
> If you want to try updating your branches, it seems like they may pass CI now.

Actually, I think the issue is that e2e tests fail when the PR is from a fork, so updating probably won't help. I'm looking into the cause of this issue.

**Comment by ellatrix** [comment]
@mchowning Thanks for investigating and creating a separate branch to run the tests!

**Pull request closed without merging**
