### PR TITLE
List Block fixes for iOS.

### LINKED ISSUE #886: List block split: item and caret at wrong lines when nested lists
When a list block contains nested lists, the caret fails to land on the correct line when adding a new list item.

ios-list-end-issue

To replicate:
1. Use this html markup to have a set of nested lists:
```
<!-- wp:list -->
<ul><li>line 1<ul><li>line 21</li><li>line 22<ul><li>line 31</li><li>line 32</li></ul></li></ul></li><li>line 3</li><li>line 4</li><li>line 5</li></ul>
<!-- /wp:list -->
```
2. Place the caret at the very end of the list, last line
3. Tap Enter to create a new list item
4. Notice the new list item been created *above* the current line and the caret not being on the new list item

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #886

This PR implements [changes on Aztec-iOS](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1165) that fix an issue on the block list.
There is a related [gutenberg side PR](https://github.com/WordPress/gutenberg/pull/14948) needed to fix an issue pressing enter on List blocks.
Issue: 
ios-list-end-issue

After the fix:
list_block

To test:

- Create a list block with the following content:
```
<!-- wp:list -->
<ul><li>line 1<ul><li>line 21</li><li>line 22<ul><li>line 31</li><li>line 32</li></ul></li></ul></li><li>line 3</li><li>line 4</li><li>line 5</li></ul>
<!-- /wp:list -->
```
- Add a new list item.
- Check that the new list item is properly placed.

### CODE REVIEW

**Comment by hypest** [comment]
👋 , when running `yarn ios` I get this error:
```
$ cd ./ios && carthage bootstrap --platform iOS --cache-builds
*** Checking out AztecEditor-iOS at "f11e3d7176927b931d59931da0e98ff373f73a5d"
*** xcodebuild output can be found in /var/folders/py/vdkc920j69b255sld66fbxt40000gp/T/carthage-xcodebuild.9bUzuR.log
*** Invalid cache found for AztecEditor-iOS, rebuilding with all downstream dependencies
*** Building scheme "Gridicons" in Gridicons.xcworkspace
Could not find any available simulators for iOS
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any tips for how to get past that?

**Comment by diegoreymendez** [comment]
@hypest - Nothing specific, but one starting point would be to make sure you update Carthage - I remember @koke mentioning that fixed the issue on his side.

**Comment by koke** [comment]
Not sure if it upgraded but it was a reinstall (brew uninstall/install carthage)

**Comment by hypest** [comment]
I should have added that the build works OK for me on develop, not sure if it adds any important information. So, it's only on this PR that [the build error](https://github.com/wordpress-mobile/gutenberg-mobile/pull/863#issuecomment-483283274) appears.

**Comment by hypest** [comment]
Update: I can confirm that re-installing (`brew uninstall carthage` followed by `brew install carthage) fixed the build issue for me. In the process, Carthage wen from v0.31 to v0.33.

**Comment by etoledom** [comment]
The Aztec-iOS side PR was merged.
@hypest this is ready for a final review.
Thank you!

**Comment by diegoreymendez** [comment]
I'm not sure what the cause is but I'd imagine this type of block may require changes in how we intercept ENTER events.  I added the above review as a comment as you may decide this is something to tackle incrementally.

**Comment by etoledom** [comment]
Thank you @diegoreymendez !

I saw a crash on enter on another multi paragraph instance of RichText here (first iOS issue described): https://github.com/WordPress/gutenberg/pull/14883#pullrequestreview-224971347

I don't know if they are related but it might be.
If it's not something new from this PR, it's probably to merge and continue on a new PR.

 I'll check that out!

**Comment by etoledom** [comment]
@diegoreymendez @hypest - Indentation and outdentation via Tab / Shift + Tab is definitely broken on Aztec-iOS. 

### Example indent:

From this initial HTML:
```html
<ul>
    <li>Hello</li>
    <li>world</li>
</ul>
```
Pressing Tab in the last list item we should get this:
```html
<ul>
    <li>Hello
        <ul>
            <li>world</li>
        </ul>
    </li>
</ul>
```

But we get this:
```html
<ul>
    <li>Hello</li>
    <li>
        <ul>
            <li>world</li>
        </ul>
    </li>
</ul>
```

### Example undent:

Starting from this HTML:
```html
<ul>
    <li>Hello
        <ul>
            <li>world</li>
        </ul>
    </li>
</ul>
```

Pressing Shift + Tab in the indented list item we should get the original:
```html
<ul>
    <li>Hello</li>
    <li>world</li>
</ul>
```

But we get:
```html
<ul>
  <li>Hello </li>
world
</ul>
````

---
From there is clear that any inconsistency passed to Aztec could cause an out of bounds exception. Even though I haven't been able to crash it yet. But we know that it can happen from @diegoreymendez 's experience.

I think that the correct solution for gutenberg would be to intercept this key bindings and use the Gutenberg's `indentListItems` and `outdentListItems` functionality.

Maybe we could just deactivate the bindings on Aztec Wrapper and work on indentation in a second iteration?

I'll still try to work on a solution on Aztec-iOS level. I have created a PR with breaking Unit Tests here:
https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1174

**Comment by hypest** [comment]
> Maybe we could just deactivate the bindings on Aztec Wrapper and work on indentation in a second iteration?

Sounds good to me. We've already removed the toolbar buttons for nesting the list since it's not well supported yet so, makes sense to also disable the keyboard path to them.

**Comment by hypest** [comment]
> I think that the correct solution for gutenberg would be to intercept this key bindings and use the Gutenberg's indentListItems and outdentListItems functionality.

Agreed, getting closer to handling this as the web via the format-lib is what I'd personally prefer too.

**Comment by etoledom** [comment]
Issue: https://github.com/wordpress-mobile/gutenberg-mobile/pull/888
PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/889

**Comment by diegoreymendez** [comment]
Just to clarify, my comments above were just to give visibility to the problem.

I'm otherwise 100% fine with the direction chosen by you and @hypest.

**Comment by etoledom** [comment]
Thank you @diegoreymendez ! It was great to rise the issue 😁

@hypest if we are fine with this fix. We just need the ✅ to merge.

**Comment by etoledom** [comment]
The Aztec reference has been already updated to a latest point via this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/889

So merging the current PR is not longer needed.

**Pull request closed without merging**
