### PR TITLE
Retrieve react native version from package.json

### PR DESCRIPTION
**Pull request by trackq**
Fixes a 'FIXME' found in the code without an issue.

Making sure no conflicts arise when a new react-native version is used in package.json, but forgotten to update the hardcoded reference.

Refactored code to remove an external dependencies.  Added function to read version number.

To test:
- CI is green
- Run yarn test:e2e:android:local

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by trackq** [comment]
Just to make sure I wasn't doing something obviously wrong, I reverted the file back to the original contents. But the build is still failing.

Now we at least no it's not my changes.

**Comment by mchowning** [comment]
:wave: @trackq ! Thanks for the PR! I believe the tests are failing because CI doesn't currently handle PRs from forks very well. If you would revert 2932bdb so we have changes are back, I'll take a look and see what I can do.

**Comment by trackq** [comment]
👍 Let me know if I can help

**Comment by mchowning** [comment]
Would you go ahead and revert 2932bdb so we have your changes back @trackq . 🙇

**Comment by trackq** [comment]
🙈 I misread that part @mchowning.

Done. ✌️

**Comment by mchowning** [comment]
Thanks @trackq. Could you also merge in the latest changes from `develop`? There have been some updates to the CI setup that we need on this branch.

**Comment by trackq** [comment]
@mchowning good like this?

**Comment by trackq** [comment]
🥳

Send it. Thanks for the help!

**Pull request merged**
