### PR TITLE
Update react-native-video dependency to remove Apache 2.0 dependencies

### PR DESCRIPTION
**Pull request by ceyhun**
Fixes https://github.com/WordPress/gutenberg/issues/19860

react-native-video PR: https://github.com/wordpress-mobile/react-native-video/pull/6

To test:

- Add a Video block check if behaviour stays the same
- Same for Media & Text block with a video
- Same for Cover block with a video

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ceyhun** [comment]
@cameronvoell It works fine for me 😕 
I tried on a Huawei P20 lite with Android 9 from release/14.6 branch of WordPress-Android while a metro server was running on this PR's branch.
I tried with SD version of this video on my phone https://www.pexels.com/video/wind-turbine-on-a-field-at-sunrise-857010/ with a Video block and with both `Choose from device` and `WordPress Media Library`.

**Comment by ceyhun** [comment]
@cameronvoell I was able to reproduce it just now on Android 14.5, Play Store version. As you said, it works fine on iOS.

**Comment by ceyhun** [comment]
I was able to reproduce on iOS as well on 14.6, App Store version with choosing `WordPress Media Library`. But after closing, saving and re-opening the draft it worked.

I think it's this issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/1151 and I'll add a comment over there.

**Comment by cameronvoell** [comment]
> I think it's this issue #1151 and I'll add a comment over there.

Comment looks good over there, thanks for checking and documenting that. This change should be good in the mean time 👍 :shipit:

**Pull request merged**
