### PR TITLE
Integrate AztecEditor-iOS 1.19.4

### PR DESCRIPTION
**Pull request by dcalhoun**
Integrate latest AztecEditor-iOS 1.19.4 release.

* **WordPress-iOS:** wordpress-mobile/WordPress-iOS#15978
* **Gutenberg:** WordPress/gutenberg#29355

To test: Outlined in WordPress/gutenberg#29355.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
Should we also update the gutenberg submodule ref here to point to the latest commit from https://github.com/WordPress/gutenberg/pull/29355?

**Comment by dcalhoun** [comment]
@guarani good catch. I have added the `gutenberg` ref. I'll update it to the merge commit after `gutenberg` is merged.

**Review by guarani — COMMENTED** [review]
Sorry for the piece-meal review, if the gutenberg submodule is updated and we're merging this to WPiOS outside of a release, it occurred to me that we should be running `npm run bundle:ios` and committing the results here.

**Review by guarani — APPROVED** [review]
Tested and LGTM!

**Pull request merged**
