### PR TITLE
Update React Native to 0.61.5

### PR DESCRIPTION
**Pull request by jtreanor**
This is a draft of the first steps for upgrading the project to React Native 0.61.5

I have focussed on verifying that the CocoaPods patch for RN 0.61.x works correctly (https://github.com/facebook/react-native/issues/25349). Here is what I have done so far:

- Updated RN and associated packages in `package.json`.
- Made a few small changes to get it to bundle successfully.
- Updated `bin/generate-podspecs.sh` to work with the new RN version.
- Generated the new podspecs and deleted obsolete ones.

Sister PRs:
* WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10997
~https://github.com/wordpress-mobile/WordPress-Android/pull/10978~
* WP-iOS corresponding PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13116
* Gutenberg PR: 
~https://github.com/WordPress/gutenberg/pull/19167~ https://github.com/WordPress/gutenberg/pull/19369
* `react-native-video` fork PR: https://github.com/wordpress-mobile/react-native-video/pull/4
* `react-native-svg` fork PR: https://github.com/wordpress-mobile/react-native-svg/pull/9

~As you can see from the failing CI, there is quite a bit more to do. However, it already successfully builds in WPiOS (see https://github.com/wordpress-mobile/WordPress-iOS/pull/12699).~

~The biggest outstanding piece of work that I encountered is that `gutenberg.xcodeproj` will have to be completely overhauled to use CocoaPods. It may be helpful to follow the upgrade helper [here](https://react-native-community.github.io/upgrade-helper/?from=0.59.8&to=0.61.2).~

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
> The biggest outstanding piece of work that I encountered is that gutenberg.xcodeproj will have to be completely overhauled to use CocoaPods. It may be helpful to follow the upgrade helper here.

FYI: I updated the project for this version of RN, basically and the dependencies are now added by cocapods instead of having subprojects. This mean that we now have `gutenberg.xcworkspace` that needs to be used instead of the `.xcodeproj` file.

**Comment by hypest** [comment]
👋 @SergioEstevao, perhaps you have some clue here: I get `.../ios/gutenberg/MediaPickCoordinator.swift:4:8: error: cannot load module 'gutenberg' as 'Gutenberg'` while trying to run `yarn ios`. Do we need some extra setup step perhaps?

**Comment by hypest** [comment]
Also, I'm getting a Ruby setup issue while running `yarn ios`:

```
$ yarn ios
yarn run v1.16.0
$ cd ios && (bundle check --path=vendor/bundle > /dev/null || bundle install) && bundle exec pod install
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.0
  2.5.5

rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.3.0
  2.5.5

error Command failed with exit code 127.
```

**Comment by jtreanor** [comment]
@hypest `gem install bundler` should do the trick 😉

**Comment by hypest** [comment]
Thanks @jtreanor ! Installing bundler is what I did locally after all, but I'm still wondering if we need to update the setup instructions (README.MD) somehow.

**Comment by pinarol** [comment]
I was hoping to cherrypick [this fix](https://github.com/facebook/react-native/pull/26986) onto our react native fork since it is blocking Group and Column blocks. Would that be appropriate to do this in this PR? 

The fix got into 0.62-rc but it is not clear when it'll be released. But we won't need to do this cherrypicking again since it will already be in 0.62.

cc @dratwas

**Comment by pinarol** [comment]
An update on my comment: since we don't use our fork anymore we are planning do a [separate PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1762) to get that fix in.

**Comment by hypest** [comment]
Found a red screen on Android:

1. Add a list block
2. Tap on the "set bullet type to numbers" button in the toolbar
3. 💥

screenshot-1579706673908

**Comment by hypest** [comment]
The Android device testsuite is failing on the rotate-and-send-text test which by now is know to be "consistently" flaky so, will go ahead and finish the merge domino.

**Pull request merged**
