### PR TITLE
Release 1.44.0

### PR DESCRIPTION
**Pull request by guarani**
Release for Gutenberg Mobile 1.44.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/27977
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13706
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15570

## Extra PRs that Landed After the Release Was Cut

- [Link settings - Fix updating settings when closing the bottom sheet](https://github.com/WordPress/gutenberg/pull/27997)
- [Fix crash when editing a component that uses RangeControl](https://github.com/WordPress/gutenberg/pull/27987)
- [Mobile - Link settings - Check for onClose](https://github.com/WordPress/gutenberg/pull/28039)
- [Fix: Add Image style settings for hotlinked images](https://github.com/WordPress/gutenberg/pull/28006)

## Changes

- [Add support for xpost suggestions on mobile](https://github.com/WordPress/gutenberg/pull/26211)
- [Full-width and wide alignment support for Columns](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2919)
- [Image block - Add link picker to the block settings and enhance link settings with auto-hide options](https://github.com/WordPress/gutenberg/pull/27292)
- [Link Settings: fixes toggeling of custom rel link field](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2894)

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by mkevins** [comment]
## Sanity tests - iOS

### DarkMode - 1

- [x] Gallery block - Dark mode - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

### Group - 1

- [x] Group - AppenderButton is rendered - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Deep nesting is possible (iOS only) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [x] Group - Check if Group placeholder is visible for the unselected state - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] :question: Group - Nested block have proper margins values - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)

I don't think it's a bug, but the [test screenshot](https://github.com/wordpress-mobile/test-cases/raw/trunk/test-cases/resources/group-margin-root.png) shows two appenders for the nested columns block, but the app doesn't show that. Maybe the test screenshot needs to be updated?

- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

### Spacer - 1

- [x] Spacer block - Spacer is rendered without crash - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [ ] :boom: Spacer block - Settings: Control spacer height using the text input - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

Any changes to the text input on the slider results in a crash.

### Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)

### Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

### Buttons-3

- [x] Buttons block - Wrapping Buttons - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

### Button-6

- [x] Buttons block - Settings: Open in new tab - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [ ] :x: Buttons block - Settings: Link rel - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)

Link rel is not saved. Also, can't add spaces to the rel input.

- [x] Buttons block - Settings: Link URL - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
test needs to be updated because link settings don't show unless there is a link
- [x] Buttons block - Settings: Synchronize with button options - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

Not related:
Link picker only shows same 3 results - known issue.

### Color Settings - 1
- [x] Colors Segmented Controls - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] Scroll color palette to start - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

**Comment by geriux** [comment]
## Sanity tests - Android

### Gallery - 1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC04](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Adding Column with AppenderButton - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


### Columns - 2
- [x] Columns - Max limit of Column number - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Column - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- ~Columns - Deep nesting is possible (iOS only)- [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)~

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is stretched to content in nested structure- [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### MediaText - 1

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

- [x] Media Text block - Insert video from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload - 1

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)


### Cover - 1

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

### Editor Theme - 1

- [x] Default Colors - Check that default colors still load - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [x] Default Gradients - Check that default gradients still load - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)

### Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by guarani** [comment]
Performed [writing flow](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) tests using build 39906 on iPhone 11, iOS 14.2.

### Writing Flow checklist

#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

---

### Issues

####  TC001 - Paste formatted text copied from website

I ran into https://github.com/WordPress/gutenberg/issues/28004 which is not a new regression.

#### TC001 - Bold, Italic, strikethrough buttons

I ran into the existing https://github.com/wordpress-mobile/gutenberg-mobile/issues/2154 (not a blocker).

**Comment by guarani** [comment]
Performed [writing flow](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) tests using build 39948 on iPhone 11, iOS 14.2.

(This additional testing was needed because I forgot to include a new bundle to the Gutenberg Mobile PR. On Android the bundle is not needed since it generates its own bundle.)

### Writing Flow checklist

#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

---

### Issues

####  TC001 - Paste formatted text copied from website

I ran into https://github.com/WordPress/gutenberg/issues/28004 which is not a new regression.

#### TC001 - Bold, Italic, strikethrough buttons

I ran into the existing https://github.com/wordpress-mobile/gutenberg-mobile/issues/2154 (not a blocker).

**Comment by jhnstn** [comment]
Performed writing [flow tests](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) using [build 89176](https://89176-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-13706-build-89176.apk) on Google Pixel 5, Android 11.

### Writing Flow checklist

#### General
  - [x] TC001 - Block insertion flow 
  - [x] TC001 - Paste formatted text copied from website
  - [x] TC001 - Multiline components
      - ❌ - Pullquote: <p> tags per non-wrapping "line" 
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
#### Splitting and merging
  - [x] TC001 - Merge after writing
  - [] TC002 - Merge after selection -> known issue https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format


---

### Issues

TC001 - Multiline components 

Ran into [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2967) while testing the PullQuote. It's not a regression so non blocking.

I also ran into these other existing non blocking issues:  #2498, #27690

**Comment by guarani** [comment]
Tested Android build 89534 the changes and bug fixes listed above:

- [x] [Link settings - Fix updating settings when closing the bottom sheet](https://github.com/WordPress/gutenberg/pull/27997)
- [x] [Fix crash when editing a component that uses RangeControl](https://github.com/WordPress/gutenberg/pull/27987)
- [x] [Mobile - Link settings - Check for onClose](https://github.com/WordPress/gutenberg/pull/28039)
- [x] [Fix: Add Image style settings for hotlinked images](https://github.com/WordPress/gutenberg/pull/28006)
- [x] [Add support for xpost suggestions on mobile](https://github.com/WordPress/gutenberg/pull/26211)
- [x] [Full-width and wide alignment support for Columns](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2919)
- [x] [Image block - Add link picker to the block settings and enhance link settings with auto-hide options](https://github.com/WordPress/gutenberg/pull/27292)
- [x] [Link Settings: fixes toggeling of custom rel link field](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2894)

**Comment by guarani** [comment]
Tested WPiOS build 40102 the changes and bug fixes listed above:

- [x] [Link settings - Fix updating settings when closing the bottom sheet](https://github.com/WordPress/gutenberg/pull/27997)
- [x] [Fix crash when editing a component that uses RangeControl](https://github.com/WordPress/gutenberg/pull/27987)
- [x] [Mobile - Link settings - Check for onClose](https://github.com/WordPress/gutenberg/pull/28039)
- [x] [Fix: Add Image style settings for hotlinked images](https://github.com/WordPress/gutenberg/pull/28006)
- [x] [Add support for xpost suggestions on mobile](https://github.com/WordPress/gutenberg/pull/26211)
- [x] [Full-width and wide alignment support for Columns](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2919)
- [x] [Image block - Add link picker to the block settings and enhance link settings with auto-hide options](https://github.com/WordPress/gutenberg/pull/27292)
- [x] [Link Settings: fixes toggeling of custom rel link field](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2894)

--- 

### Issues

I ran into an issue where Xposts didn't load. The reason is that some sites returned by the Xpost endpoint have URLs that are malformed which break parsing in the apps. Issue created here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2982

**Review by antonis — APPROVED** [review]
This LGTM @guarani 👍

**Comment by guarani** [comment]
> I ran into an issue where Xposts didn't load. The reason is that some sites returned by the Xpost endpoint have URLs that are malformed which break parsing in the apps. Issue created here: #2982

I'm marking this done and moving on with the release because the fix for #2982 does not depend on the release, PR up here: https://github.com/wordpress-mobile/WordPress-iOS/pull/15610

**Pull request merged**
