### PR TITLE
Release 1.33.0

### PR DESCRIPTION
**Pull request by SergioEstevao**
Release for Gutenberg Mobile 1.33.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/24050
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/12480
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14489

- Aztec-iOS: NA
- Aztec-Android: NA

## Extra PRs that Landed After the Release Was Cut

- [x]  We needed to revert a fix for reducing space between label and slider control: https://github.com/WordPress/gutenberg/pull/24109

## Changes

* [***] Media editing support in Media & Text block.
* [***] New block: Social Icons
* [*] Cover block placeholder is updated to allow users to start the block with a background color

## Test plan

- Use the main WP apps to test the changes above. 
- Check WPAndroid and WPiOS PRs if there are specific tests to run.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Release number was bumped in `package.json` and `gutenberg/packages/react-native-editor/package.json`.
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: 'grep WordPressAztec-iOS RNTAztecView.podspec'.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
  - Android: 'grep aztecVersion react-native-aztec/android/build.gradle'.
- [x] Gutenberg 'Podfile' and 'Podfile.lock' inside 'gutenberg/package/react-native-editor/ios/' are updated to the release number.
- [ ] Bundle package of the release is updated.
- [ ] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/RELEASE-NOTES.txt` are updated with all the changes that made it to the release.

### CODE REVIEW

**Comment by mkevins** [comment]
I've done the following tests on Android (Pixel 3a) via this apk: https://62039-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-12480-build-62039.apk

Everything is working smoothly :tada:  The only minor note is that in one test case ([group.md#tc008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)), the behavior differs from test, but I think the test case needs to be updated, since the behavior seems correct to me.

Sanity tests - Android:

DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)


Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] :question: Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

The behavior differs slightly from the test case expectation here, but I think the app's behavior is correct, and perhaps the test case merely needs to be updated (maybe the images too, or just a note that this has changed?).

> Expect only selected block title is visible in Breadcrumbs on root list level

since block icon is shown at root level (and the navigate up icon is not shown).


Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)


Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)


Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)


Buttons-3

- [x] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)


Button-6

- [x] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [x] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

**Comment by lukewalczak** [comment]
Sanity tests - iOS

Gallery-1

- [X] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [X] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [X] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [X] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-3

- [X] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)

NOTE: When have selected one of text style it works as long as the formatted word is not removed. After removing styling control is _highlighted_ but the text is not styled.
<details>

ezgif com-resize (3)

</details>

- [X] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)

🔴 break line doesn't work.

- [X] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

❓ I have one question: after test case `Insert image from device (failing) ` I left in my draft photos which uploading failed and when I generate a preview I've noticed these photos are "displayed" (as a 
white block with border) in the post. Is it intentional? 

draft | preview
--- | ---
IMG_3899 | IMG_3900

**Comment by pinarol** [comment]
> NOTE: When have selected one of text style it works as long as the formatted word is not removed. After removing styling control is highlighted but the text is not styled.

That's a known issue:

https://github.com/wordpress-mobile/gutenberg-mobile/issues/2154
https://github.com/wordpress-mobile/gutenberg-mobile/issues/2337


> Gallery block - Add Gallery Image Caption - steps
> 🔴 break line doesn't work.

I lost track of how the line break was supposed to work in captions, I am happy to update the test case accordingly if somebody tells me the latest state. @SergioEstevao knows maybe?

> ❓ I have one question: after test case Insert image from device (failing) I left in my draft photos which uploading failed and when I generate a preview I've noticed these photos are "displayed" (as a
white block with border) in the post. Is it intentional?

That's a good question, I think it is one of those things we don't have a complete win-win scenario. If we strip out failed media then we take the ability to retry the upload easily. If we leave it this way then we'll see empty tiles because the media URL is the local url. IMO since the user clearly sees that the upload is failed they can easily make sense about why they see empty tiles. But I agree that this is not super ideal. I just don't have a better suggestion.

**Comment by SergioEstevao** [comment]
> I have one question: after test case Insert image from device (failing) I left in my draft photos which uploading failed and when I generate a preview I've noticed these photos are "displayed" (as a
white block with border) in the post. Is it intentional?

Yep, because the preview is done on the server, and those images that failed are represented with local urls, this will happen.

> I lost track of how the line break was supposed to work in captions, I am happy to update the test case accordingly if somebody tells me the latest state. @SergioEstevao knows maybe?

So the current method (replicate the web) is that break lines don't work in the middle of the caption paragraphs, and if you do a break at the end of the caption text, it will insert a new paragraph bellow the block.

**Comment by mchowning** [comment]
### [Writing Flow tests](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow) on Android

- [ ] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text format

**Comment by mchowning** [comment]
### [Writing Flow tests](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow) on iOS

**Found no new issues 🎉** 

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by mchowning** [comment]
Looks like we've run all our sanity tests and there are no issues to block the release. 🙂 

cc: @SergioEstevao

**Comment by SergioEstevao** [comment]
For the record, I tested the folowing in WP-iOS and they are working correctly:

- Media editing support in Media & Text block.
- Cover block placeholder is updated to allow users to start the block with a background color

**Comment by mchowning** [comment]
I tested the following on WPAndroid:
* Media editing support in Media & Text block.
* Cover block placeholder is updated to allow users to start the block with a background color
* Social Icons

**Pull request merged**
