### PR TITLE
Feature/toolbar component ui

### PR DESCRIPTION
**Pull request by marecar3**
### Description

This PR resolves part of the [Toolbar issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/55). It implements Toolbar and Toolbar Button style by the specs.

### What's done : 
Implement Toolbar Style
- [x] Implement toolbar button style by specs
- [x] Implement toolbar style by specs

selected_state

### How has this been tested?

It is tested against this [PR](https://github.com/WordPress/gutenberg/pull/11827)

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
This looks great overall! I'm not sure if this is the place to raise the request, but I have a couple minor requests:

* Can we make sure the Inserter icon is the filled version, and using the primary WP blue?

* I think the padding around the Inserter button could be tightened up. The padding on the left side of the first divider above can be removed so that the button (44x44) and divider are flush, unlike the other tools. The same thing will be applied to undo/redo if we decide to add those to the toolbar. 

For reference: 
screen shot 2018-11-13 at 5 00 51 pm

**Comment by marecar3** [comment]
UI is updated by latest specs.
@etoledom now it's ready for review!

**Comment by etoledom** [comment]
Hey @marecar3 ! 
I see you are still working on the gutenberg side (https://github.com/WordPress/gutenberg/pull/11827)

I did a fast test and I noticed something odd on iOS, it looks like the selection colors are inverted:

screen shot 2018-11-20 at 9 02 28 pm

**Comment by marecar3** [comment]
Hey @etoledom!

It seems that you maybe don't have the latest code on your local machine. You can pull it and you will have the latest changes. 

Also, we have moved a conversation to gutenberg - https://github.com/WordPress/gutenberg/pull/11827
sorry about that!

**Pull request merged**
