### PR TITLE
Gallery Block - Shows "Choose images" instead of "Choose image"

### LINKED ISSUE #2632: Pluralize "Choose Image" heading on Gallery Block
**Describe the bug**
When selecting images for the Gallery Block, the heading on the popup should say "Choose Images" rather than "Choose Image" 
 
**To Reproduce**
1. Add the Gallery Block 
2. Click on 'Add Media'
3. Notice the heading on the popup menu

**Screenshots**
IMG_D41AB521A108-1

@jd-alexander @iamthomasbishop

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #2632 
Updates the Gallery Block's Picker Title to "Choose images" instead of "Choose image"
To test:
Use the instructions in https://github.com/WordPress/gutenberg/pull/25634 to test.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
@jd-alexander Just reminding that we'll be cutting the 1.38 release branch later in the day Monday 9/28. Please try to get this merged by then or bump the milestone. Thanks much 🙇

**Review by etoledom — APPROVED** [review]
Approved via: https://github.com/WordPress/gutenberg/pull/25634#pullrequestreview-500102866

**Comment by etoledom** [comment]
@jd-alexander - since https://github.com/WordPress/gutenberg/pull/25634 is merged, it would be great to update this PR before merging. Thanks! 🙏

**Comment by jd-alexander** [comment]
Thanks, @etoledom will do 🙏

**Comment by jd-alexander** [comment]
These tests are failing again. I will investigate today to see what's causing it.

**Comment by jd-alexander** [comment]
@etoledom I have a question about this PR as well that I was getting some failure with. Since the associated PR was merged and I would need to update that so that this could be merged would I then close this one? I guess in the future it's good to merge in this PR as soon as possible but yes, as I was getting up to speed with how the test infrastructure and flow works this ending up not being merged in soon enough.

**Comment by ceyhun** [comment]
@jd-alexander We'll be cutting the 1.39 release soon, you have 3 options: 
1. merge the PR as soon as possible 
1. bump the PR to the next milestone
1. remove the milestone from the PR

**Comment by jd-alexander** [comment]
Hi, I am closing this PR because the associated PR https://github.com/WordPress/gutenberg/pull/25634 has been merged in and the test failure I was investigating here was due to the `gutenberg` ref being outdated. There has been no issues with this change due to newer PRs pulling in this code so it's safe to close.

**Pull request closed without merging**
