### PR TITLE
Incorporate fixes to some recent regressions

### PR DESCRIPTION
**Pull request by hypest**
Update Gutenberg ref to incorporate fixes to some recent regressions

Fixes included for the following regressions:
1. https://github.com/WordPress/gutenberg/pull/14815#issuecomment-566196330 ([Gutenberg PR](https://github.com/WordPress/gutenberg/pull/19190))
2. https://github.com/WordPress/gutenberg/pull/19097#issuecomment-566442149 ([Gutenberg PR](https://github.com/WordPress/gutenberg/pull/19196))

To test:

CI should be green.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by ellatrix** [comment]
Is there any way these tests can be run for Gutenberg?

**Comment by ellatrix** [comment]
Asking because, even if native files were updated, there's no way to know for sure if everything works correctly.

**Comment by hypest** [comment]
👋 @ellatrix , assuming you mean running them in the Gutenberg repo, I guess we are not there yet, but we are heading that way, to incorporate native mobile e2e tests into the Gutenberg repo.

In the meantime, may I take this opportunity to suggest that, it would be useful if at least for changes in the RichText components you open PRs here in the mobile repo to test and merge? To do so, It basically boils down to updating the Gutenberg git submodule to point to the desired Gutenberg commit and push a branch and PR it. Happy to elaborate more if needed. WDYT?

**Comment by hypest** [comment]
This PR is not needed anymore since the latest from Gutenberg was brought in by https://github.com/wordpress-mobile/gutenberg-mobile/pull/1631.

**Comment by ellatrix** [comment]
@hypest Sure, would love to do it for the bigger rich text PRs. Looking forward to have those tests in the main repo though!

**Pull request closed without merging**
