### PR TITLE
Audio Block - I

### PR DESCRIPTION
**Pull request by etoledom**
This PR updates the gutenberg ref to test https://github.com/WordPress/gutenberg/pull/27401
`WPiOS` side PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/15420
`WPAndroid` PR: https://github.com/wordpress-mobile/WordPress-Android/pull/13808

To test:

- Please refer to https://github.com/WordPress/gutenberg/pull/27401

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by jd-alexander** [comment]
Bumping the milestone to 1.44, feel free to ping me if it needs to make it to 1.43 this week.

**Comment by guarani** [comment]
Hi @jd-alexander, we're cutting the release now so I'll bump this to 1.45.0. Please let me know if you think it needs to be included in this release and we can arrange that.

**Comment by cameronvoell** [comment]
>Hi @jd-alexander, we're cutting the release now so I'll bump this to 1.45.0. Please let me know if you think it needs to be included in this release and we can arrange that.

Bumping to 1.46.0, let me know if there are any issues with that.

**Review by jd-alexander — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/27401#pullrequestreview-574597733

**Pull request merged**
