### PR TITLE
Try to fix RN0.64 upgrade WPAndroid insert link crash

### PR DESCRIPTION
**Pull request by hypest**
Fixes #

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/32517
WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14802

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
Tried the WPAndroid installable build built off https://github.com/wordpress-mobile/gutenberg-mobile/pull/3597/commits/c727eff6e298b4b8cbf9d8571b2d6b203105f06c and it doesn't crash for me when trying to add a link inside a paragraph by tapping on the link toolbar button! 🎉

**Comment by hypest** [comment]
[Installable build](https://github.com/wordpress-mobile/WordPress-Android/pull/14802#issuecomment-857630117) still works ok (smoke testing) after all the deps updates.

At this point @ceyhun , I think we can consider merging the all the "extra PRs" into the main 0.64 upgrade PRs, let me know what you think.

**Comment by hypest** [comment]
### Android Writing Flow checklist

Android 11, physical Pixel 2XL - using [WPAndroid installable build 109148](https://github.com/wordpress-mobile/WordPress-Android/pull/14802#issuecomment-857630117), Gutenberg hash https://github.com/WordPress/gutenberg/pull/32517/commits/a6ce9082e19e4301d209561aac7201b56c07c643.

#### General
- [x] TC001 - Paste formatted text copied from website => I don't see the images being pasted, but same happens on develop so, the RN upgrade doesn't introduce an issue. In fact pasting with images included works OK if copied from a site like lipsum.com
- [x] TC001 - Multiline components
  - [x] Quote block
  - [x] Verse block
  - [x] Preformatted block
  - [ ] Code block (DEV only)
  - [x] Pullquote block

#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by SiobhyB** [comment]
### iOS Writing Flow checklist

iOS 14.4, physical iPhone XR - using [WordPress iOS installable build 50172](https://github.com/wordpress-mobile/WordPress-iOS/pull/16665#issuecomment-858693647)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
  - [x] Quote block
  - [x] Verse block
  - [x] Preformatted block
  - [ ] Code block (DEV only)
  - [x] Pullquote block
  
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by hypest** [comment]
The failed Check Correctness job (with a lint issue with `eslint-plugin-jsdoc`) is [already fixed in develop](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3605).

**Comment by hypest** [comment]
Fix has been included in the [main RN 0.64 upgrade PRs](https://github.com/WordPress/gutenberg/pull/29118) already and those got merged already so, closing this 🎉.

**Pull request closed without merging**
