### PR TITLE
Release 1.112.0

### PR DESCRIPTION
**Pull request by derekblank**
Release for Gutenberg Mobile 1.112.0

## Related PRs

- https://github.com/WordPress/gutenberg/pull/58540
- https://github.com/wordpress-mobile/WordPress-Android/pull/20093
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22513

## Changes

* [Change 1](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6575): Fix crash occurring on large post on Android
* [Change 2](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6522):  Upgrade React Native to version 0.71.15
* [Change 3](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6550): Prevent images from temporarily disappearing when uploading media

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
> **Release Submission Checklist**
> Verify Items from test plan have been completed

@derekblank we usually perform the testing plan the week after the release. Not sure if you already covered this, although I don't see comments in this PR related to testing. Let me know if we should leave it unchecked. Thanks 🙇 !

**Comment by fluiddot** [comment]
In https://github.com/wordpress-mobile/gutenberg-mobile/pull/6597/commits/5d9a47fd0849cc6f47a035704101ed9d2097f26e, I noticed that some E2E tests failed:

### Test iOS on Device – Full iPhone

- Gutenberg Editor Visual test for Gallery Block › should be able to render a gallery correctly
  - There are visual differences



### Test iOS on Device – Full iPad

- Gutenberg Editor iPad Visual test for Horizontal layouts should show the right columns placeholders and alignments case 1
  - The scroll positions don't match by some pixels.

case 1

- Gutenberg Editor iPad Visual test for Horizontal layouts should show the right columns placeholders and alignments case 2
  - The device didn't rotate.

case 2

<hr>

I'm going to retry the tests but if they fail again, it would be great to investigate them further.

**Comment by fluiddot** [comment]
> I'm going to retry the tests but if they fail again, it would be great to investigate them further.

[They keep failing](https://buildkite.com/automattic/gutenberg-mobile/builds/8464), so I'm going to take a deeper look.

**Comment by fluiddot** [comment]
> ### Test iOS on Device – Full iPhone
> * Gutenberg Editor Visual test for Gallery Block › should be able to render a gallery correctly
>   
>   * There are visual differences
> 
> 

It's a bit subtle but I noticed that the images seem one pixel taller, this seems causing the first failure. I wonder if https://github.com/wordpress-mobile/gutenberg-mobile/pull/6550 has impacted somehow the size.

**UPDATE:** I confirmed that https://github.com/wordpress-mobile/gutenberg-mobile/pull/6550 added 1 pixel.

**Left (old) | Right (new):**
Screenshot 2024-02-01 at 19 29 08

**Comment by fluiddot** [comment]
> It's a bit subtle but I noticed that the images seem one pixel taller, this seems causing the first failure. I wonder if #6550 has impacted somehow the size.
> 
> **UPDATE:** I confirmed that #6550 added 1 pixel.

I presume that the extra pixel was unintended. However, since it doesn't produce a critical change to the editor, I'll proceed with updating the screenshots. @derekblank let me know if you'd rather remove the extra pixel. If so, we could update the screenshots again. Thanks 🙇  !

**Comment by fluiddot** [comment]
> ### Test iOS on Device – Full iPad
> * Gutenberg Editor iPad Visual test for Horizontal layouts should show the right columns placeholders and alignments case 1
>   
>   * The scroll positions don't match by some pixels.
> 
> case 1
> 
> * Gutenberg Editor iPad Visual test for Horizontal layouts should show the right columns placeholders and alignments case 2
>   
>   * The device didn't rotate.
> 
> case 2

This case is the same as the one shared in https://github.com/wordpress-mobile/gutenberg-mobile/pull/6597#issuecomment-1921960772. The one-pixel size difference in the image frame makes the visual check to fail. I'll proceed to update the screenshots.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

Pre-approving the PR upon waiting E2E tests to pass after the following fixes:
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/6597/commits/a4ea932d43aac02cd8d128be8f8992498973ae43
- https://github.com/wordpress-mobile/gutenberg-mobile/pull/6597/commits/4a0a8a4ef3333b84f10d3fbf2f9b9de704765470

**Comment by derekblank** [comment]
> I presume that the extra pixel was unintended. However, since it doesn't produce a critical change to the editor, I'll proceed with updating the screenshots. @derekblank let me know if you'd rather remove the extra pixel.

@fluiddot The extra pixel is actually intended, but I didn't realize that the E2E screenshots would be that sensitive to detect such a small visual change. It makes sense, however, so thanks for updating the screenshots. We can keep them as-is.

To provide more technical detail on the 1 pixel change, the extra pixel comes from a non-visible FastImage instance that acts as a preloader using its `onLoad` method to download the network image data and smoothly transition between the local and network image states when the network image data is ready. This non-visible image is a workaround due to the FastImage [preload](https://github.com/DylanVann/react-native-fast-image?tab=readme-ov-file#fastimagepreload-source--void) method not returning a Promise or callback to hook into. There is more discussion and explanation on this change in the iOS section of the internal ref `p2-p9ugOq-4lR`. It's worth noting that the `onLoad` behavior from this non-visible image does not fire if the image does not have a width/height of at least `1`. We did try using `0` as the dimension value, and the `onLoad` method did not work as intended ([ref](https://github.com/WordPress/gutenberg/pull/57869#discussion_r1462206190)).

Also noting that @dcalhoun and I consider this change a progressive-enhancement interim fix while we explore longer-term solutions for the Image component as a group, and potentially moving away from FastImage due to lack of maintenance.

**Comment by derekblank** [comment]
## 🟢 Writing Flow checklist - Android

* **Build:** [jpandroid-24.2-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/24.2-rc-1)
* **Device:** Samsung Galaxy S20 FE 5G

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Comment by derekblank** [comment]
## 🟢    Unsupported Block Editor - Android

* **Build:** [jpandroid-24.2-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/24.2-rc-1)
* **Device:** Samsung Galaxy S20 FE 5G

- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc001) - User can edit unsupported blocks on Simple WP.com sites
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc002) - User can discard edits to an unsupported block on Simple WP.com sites
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc003) - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc004) - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc005) - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc006) - Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by derekblank** [comment]
## 🟢  Functionality Test Suite 2 - Android

* **Build:** [jpandroid-24.2-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/24.2-rc-1)
* **Device:** Samsung Galaxy S20 FE 5G

### DarkMode - 1

- [x] Gallery block - Dark mode - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/darkmode.md#tc003)

### Group - 1

- [x] Group - Deep nesting is possible (verify iOS does not crash) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/group.md#tc001)
- [x] Group - Check if Group placeholder is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/group.md#tc002)
- [x] Group - Check if Group placeholder is render in nested structure - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/group.md#tc003)
- [x] Group - Nested block have proper border styling - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/group.md#tc004)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/group.md#tc005)

### Buttons-1

- [x] Buttons block - Button's wrapper grows properly - [TC019](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc019)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Wrapping Buttons - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc003)

### Button-2

- [x] Buttons block - Buttons alignment options - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Settings: Open in new tab - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc007)
- [x] Buttons block - Settings: Link rel - [TC008](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc008)

### Button-3

- [x] Buttons block - Settings: Link URL - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Settings: Remove link - [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Synchronize with button options - [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/buttons.md#tc009)

### Color Settings - 1
- [x] Scroll color palette to start - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/color-settings.md#tc003)

### Image - 1
- [x] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc001)
- [x] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc002)
- [x] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc003)
- [x] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc004)
- [x] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc005)

### Drag and Drop Blocks - 1
- [x] Drag and Drop Blocks - Drag block to the top of the content - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/drag-and-drop-blocks.md#tc001)
- [x] Drag and Drop Blocks - Drag block to the bottom of the content - [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/drag-and-drop-blocks.md#tc002)

### VideoPress - 2
- [x] VideoPress block - Player - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/videopress.md#tc003)
- [x] VideoPress block - Private video - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/videopress.md#tc005)
- [x] VideoPress block - Upload limit for Free users - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/videopress.md#tc006)

**Comment by derekblank** [comment]
## 🟢  Writing Flow checklist - iOS

* **Build:** [pr22539-1bfe5e4](https://github.com/wordpress-mobile/WordPress-iOS/pull/22539#issuecomment-1926059852)
* **Device:** iPhone SE

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Comment by derekblank** [comment]
## 🟢    Unsupported Block Editor - iOS

* **Build:** [pr22539-1bfe5e4](https://github.com/wordpress-mobile/WordPress-iOS/pull/22539#issuecomment-1926059852)
* **Device:** iPhone SE

- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc001) - User can edit unsupported blocks on Simple WP.com sites
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc002) - User can discard edits to an unsupported block on Simple WP.com sites
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc003) - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc004) - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc005) - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#tc006) - Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by derekblank** [comment]
## 🟡   Functionality Test Suite 3 - iOS

* **Build:** [pr22539-1bfe5e4](https://github.com/wordpress-mobile/WordPress-iOS/pull/22539#issuecomment-1926059852)
* **Device:** iPhone SE

### Gallery - 2
- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3
- [x] Gallery block - Settings: Column number - [TC013](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [TC014](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc014)

### MediaText - 3
- [ ] Media Text block - Insert video from device (failing) - [TC001-v](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc001-v)
- [ ] Media Text block - Close/Re-open post with an ongoing video upload - [TC003-v](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc003-v)

~⚠️ I could not get video uploads to succeed on iOS.~ **Retested, and succeeded.** 

<details>
<summary>Video Example</summary>

<video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/7d5799dd-6d9c-42e4-8589-4b37cd6e64f3" />

</details>


### MediaText - 4
- [x] Media Text block - Media & Text alignment - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/media-text.md#tc007)

### Shortcode-1
- [x] Shortcode block - Add a youtube link - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/shortcode.md#tc001)

### Cover - 2

- [ ] Cover - Add Video Background from WordPress Media library - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc004)

~⚠️ I could not get video to insert from WordPress Media Library into the Cover block. Nothing happens.~ **Retested, and succeeded.** 

<details>
<summary>Video Example</summary>


<video src="https://github.com/wordpress-mobile/gutenberg-mobile/assets/643285/c91870ff-98c9-493c-ad18-9416509c169d" />



</details>

- [ ] Cover - Replace media - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc005) ~*_only succeeded with Images, see above_~ **Retested, and succeeded.**
- [x] Cover - Gradient background is rendered properly - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient overlay is rendered properly - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/cover.md#tc007)

### Image - 2
- [x] Image block - Border style setting - [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc006)
- [x] Image block - Image size setting - [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc007)
- [ ] Image block - Link to setting - [TC008](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/image.md#tc008)


I believe the Story tests are no longer relevant due to Stories being removed from the mobile apps. I added a Story block from web and confirmed it shows up as Unsupported in the mobile app:

### Story block - 1
- [ ] Story block - Verify is available in Block Picker - [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc001)
- [ ] Story block - Verify is not available in Block Picker- [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc002)
- [ ] Story block - Add media to empty Story block - [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc003)
- [ ] Story block - Add media to non-empty Story block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc004)
- [ ] Story block - Close/Re-open post with an ongoing Story upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/jetpack/story.md#tc005)

**Pull request merged**
