### PR TITLE
Release 1.61.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.61.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/34880
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/15335
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/17169

- ~~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~~
- ~~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Show always the symbol icon in the block picker for reusable blocks
- **PR:** https://github.com/WordPress/gutenberg/pull/34873

This PR fixes a crash that was identified in version `18.2` related to the reusable blocks in the block picker.

**Internal discussion:** p1631673738335600-slack-C6UJ0KRKQ

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by geriux** [comment]
## 🟢 Writing flow tests (iOS)
**Device**: iPhone 12 Pro
**Build**: [56595](https://github.com/wordpress-mobile/WordPress-iOS/pull/17169#issuecomment-920967017)

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by fluiddot** [comment]
## 🟢  Writing flow tests (Android)
**Device**: Samsung Galaxy S20 FE 5G (Android 10)
**Build**: `115456`

### Writing Flow checklist

#### General
- [x] TC001 - Block insertion flow
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by geriux** [comment]
## 🟢 New changes (iOS)
**Device**: iPhone 12 Pro
**Build**: [56595](https://github.com/wordpress-mobile/WordPress-iOS/pull/17169#issuecomment-920967017)

- [x] [RNMobile] Show always the symbol icon in the block picker for reusable blocks

**Comment by fluiddot** [comment]
## 🟢 New changes (Android)
**Device**: Samsung Galaxy S20 FE 5G (Android 10)
**Build**: `115456`

- [x] [RNMobile] Show always the symbol icon in the block picker for reusable blocks

**Comment by fluiddot** [comment]
## 🟢 Unsupported Block Tests (Android)
**Device:** Samsung Galaxy S20 FE 5G (Android 10)
**Build:** `115456`

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] ~TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites~ Skipped because of [this](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#editing-unsupported-blocks-is-disallowed-on-classic-enabled-atomic-sites).
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by geriux** [comment]
## 🟢 Unsupported Block Tests (iOS)
**Device**: iPhone 12 Pro
**Build**: [56595](https://github.com/wordpress-mobile/WordPress-iOS/pull/17169#issuecomment-920967017)

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [ ] ~TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites~ Skipped because of [this](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#editing-unsupported-blocks-is-disallowed-on-classic-enabled-atomic-sites).
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Review by geriux — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/34880#pullrequestreview-756501529 🚀

**Pull request merged**
