### PR TITLE
Release 1.47.0

### PR DESCRIPTION
**Pull request by antonis**
Release for Gutenberg Mobile 1.47.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/29037
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14081
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15894
- ~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~
- ~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~

## Extra PRs that Landed After the Release Was Cut

- Fix crash when Column block width attribute was empty. https://github.com/WordPress/gutenberg/pull/29015
- [Mobile] - RichText - Restore onSelectionChange when its focused https://github.com/WordPress/gutenberg/pull/29074
- [RNMobile] Fixes crash when selecting a gradient style https://github.com/WordPress/gutenberg/pull/29072
- [RNMobile] Add Stories bridge methods for iOS https://github.com/WordPress/gutenberg/pull/29083
- Merge 1.46.1 beta fix release to 1.47.0 #3159

## Changes

- Documentation: Update README.md with Note about Android Studio/Xcode #3063 
- Correct blockWidth #3079 
- [FIX] Bottom-sheet height after using back button #3080
- Update gutenberg hash for contact info inner blocks bugfix #3071
- Fixing gutenberg hash to merge commit hash for contact info #3082
- Enable Audio Block #3070
- Update unsupported block test data for UI tests #3087
- Fix download button in File block #3102
- Move custom indicator to be rendered above the colors #3098
- Audio Block shallow rendering tests #3093
- Update `npm run start` to include cleanup #2970
- [RNMobile] Using deferredEventEmitter to wait for the Editor to be mounted before issuing replaceBlock signal #2949
- Audio block UI test #3091
- Invert the expect matcher values of the e2e tests #3110
- JS Performance improvements #3088
- Show "Add to beginning" and "Add to end" option for all blocks when long-pressing the inserter button #3074
- Update gutenberg hash for changing block mover wording #3049
- Contact Info - Adding Feature Flag + Jetpack API Version Check #3001 
- Temporary gutenberg update to test media files type #3113
- Move release note for a feature that wasn't released when expected #3141
- Update Appium dependency version to 1.20.2 #3121
- Add Cover block media settings #3028
- Fixes insertion of paragraph block at the begging when tapping at the empty space #3147

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Review by dcalhoun — COMMENTED** [review]
This is looking good to me so far.

**Review by antonis — COMMENTED** [review]
At this stage this LGTM 🎉

**Comment by geriux** [comment]
Sanity tests for **iOS**, using an iPhone 12 Pro with build: 42266 from https://github.com/wordpress-mobile/WordPress-iOS/pull/15894#issuecomment-779885170

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Gallery - 4

- [x] Gallery block - Settings: Link to - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)
- [x] Gallery block - Settings: Column number - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

### MediaText - 3

- [x] Media Text block - Insert video from device (failing) - [TC001-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [x] Media Text block - Close/Re-open post with an ongoing video upload - [TC003-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

### MediaText - 4

- [x] Media Text block - Media & Text alignment - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

### Cover - 2

- [x] Cover - Add Video Background from WordPress Media library - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [x] Cover - Replace media - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient background is rendered properly - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
  ⚠️🔴 Updating the gradient colors from the mobile editor makes it crash. (https://github.com/wordpress-mobile/gutenberg-mobile/issues/3157)
- [x] Cover - Gradient overlay is rendered properly - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

### Social Icons - 2
- [x] The link sheet is opened automatically when adding new icon - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc004)
- [x] Ghost placeholder is visible when no icon is active - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc005)
- [x] Social icon forwarding to the link - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc006)

### Image - 2
- [x] Image block - Switch to classic editor with an image block in page - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc006)
- [x] Image block - Border style setting - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc007)
- [x] Image block - Image size setting - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)
- [x] Image block - Link to setting - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)

### Story block - 1
Not released on iOS yet.

**Comment by dcalhoun** [comment]
### 🟡 iOS: Writing Flow checklist 

* iPhone SE 
* iOS 14.4 
* Build `42266` from https://github.com/wordpress-mobile/WordPress-iOS/pull/15894#issuecomment-779885170.

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
  - 🟡 Previously captured https://github.com/wordpress-mobile/gutenberg-mobile/issues/3089 continues to occur.
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing 
    - 🟡 Splitting, merging, and splitting results in the incorrect text in both of the two blocks from splitting. https://github.com/WordPress/gutenberg/issues/29046
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by antonis** [comment]
## Android Sanity Tests (Test Suite 4)
* Test device: Google Pixel 2 XL (Android 11)
* [Build](https://96313-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14081-build-96313.apk) from [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14081)

### DarkMode - 2

- [x] Spacer block - Dark mode - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] Buttons block - Dark mode - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] Group - Dark mode - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc006)
- [x] Columns - Dark mode - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

### Group - 2

- [x] Group - Navigation up button works as expected - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [x] Group - Navigation down works according to parent-first approach - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [x] Group - Cross navigation between blocks works as expected - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [x] Group - Ungroup button works as expected - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [x] Group - Check if in DarkMode all components gets proper colors - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [x] Group - Check if nested Placeholder block can be replaced - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

### Spacer - 2

- [x] Spacer block - Settings: Available height range is correct - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [x] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [x] Spacer block - Spacer in horizontal layout works as expected - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

### Buttons - 4

- [x] Buttons block - Render custom text color - [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
- [x] Buttons block - Render custom background color - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
- [ ] Buttons block - Render gradient background color - [TC018](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018) => **Fails**: [Issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3157)
- [x] Buttons block - Check if selection / caret color matches font color - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
- [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

### Buttons - 5

- [x] Buttons block - Edit text styles - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
- [x] Buttons block - Render theme colors - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
- [x] Buttons block - Settings: Change Button border radius - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

### Buttons - 7

- [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] Buttons block - Toolbar link button is active when Button has link - [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

### Editor Theme - 2
- [ ] Custom Gradients - Check that custom gradients load in the editor - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004) => **Fails**: [Issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3157)
- [x] Offline Support - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

### Color Settings - 2
- [x] Pressing color swatch - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
- [ ] Customize gradient color - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005) => **Fails**: [Issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3157)
- [x] Custom color picker - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by dcalhoun** [comment]
### 🟡 Android: Writing Flow checklist 

* Samsung Galaxy S20 5G FE 
* Android 11
* Build `96313` from https://github.com/wordpress-mobile/WordPress-Android/pull/14081#issuecomment-779934314

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
  - 🟡 Previously captured #3096 continues to occur.
  - 🟡 Android keyboard is occasionally not displayed when adding a block (present in Play Store release, possibly related to WordPress/gutenberg#28748). https://github.com/WordPress/gutenberg/issues/29048
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
    - 🟡 Unable to merge multiple blocks, only one https://github.com/WordPress/gutenberg/issues/29047
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
# Summary: Manual Tests Round 1

## Regressions in Release
* 🔴 [iOS and Android] Updating the gradient colors from the mobile editor makes it crash. (#3157)
* 🟡 [iOS] Splitting, merging, and splitting results in the incorrect text in both of the two blocks from splitting. (WordPress/gutenberg#29046)
* 🟡 [Android] Unable to merge multiple blocks, only one. (WordPress/gutenberg#29047)

## Preexisting Bugs
* 🟡 [Android] Keyboard is occasionally not displayed when adding a block. (WordPress/gutenberg#29048)
* 🟡 Previously captured #3089 continues to occur.

**Comment by dcalhoun** [comment]
### 🟢 Android: Writing Flow checklist (round 2)

* Samsung Galaxy S20 5G FE
* Android 11
* 🟡 Build `96604` from https://github.com/wordpress-mobile/WordPress-Android/pull/14092#issuecomment-780479456. (p1613599084219300/1613598561.218900-slack-C0126N6JH7Z)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
### 🟢 iOS Writing Flow checklist (round 2)

* iPhone SE
* iOS 14.4
* 🟡 Build `42425` from https://github.com/wordpress-mobile/WordPress-iOS/pull/15905#issuecomment-780471552 (p1613599084219300/1613598561.218900-slack-C0126N6JH7Z)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by antonis** [comment]
## 🟢Android Sanity Tests (Test Suite 4) - round 2
* Test device: Google Pixel 2 XL (Android 11)
* [Build](https://96645-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14081-build-96645.apk) from [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14081)

### DarkMode - 2

- [x] Spacer block - Dark mode - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] Buttons block - Dark mode - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] Group - Dark mode - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc006)
- [x] Columns - Dark mode - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

### Group - 2

- [x] Group - Navigation up button works as expected - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [x] Group - Navigation down works according to parent-first approach - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [x] Group - Cross navigation between blocks works as expected - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [x] Group - Ungroup button works as expected - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [x] Group - Check if in DarkMode all components gets proper colors - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [x] Group - Check if nested Placeholder block can be replaced - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

### Spacer - 2

- [x] Spacer block - Settings: Available height range is correct - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [x] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [x] Spacer block - Spacer in horizontal layout works as expected - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

### Buttons - 4

- [x] Buttons block - Render custom text color - [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
- [x] Buttons block - Render custom background color - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
- [x] Buttons block - Render gradient background color - [TC018](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)
- [x] Buttons block - Check if selection / caret color matches font color - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
- [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

### Buttons - 5

- [x] Buttons block - Edit text styles - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
- [x] Buttons block - Render theme colors - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
- [x] Buttons block - Settings: Change Button border radius - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

### Buttons - 7

- [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] Buttons block - Toolbar link button is active when Button has link - [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

### Editor Theme - 2
- [x] Custom Gradients - Check that custom gradients load in the editor - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
- [x] Offline Support - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

### Color Settings - 2
- [x] Pressing color swatch - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
- [x] Customize gradient color - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005)
- [x] Custom color picker - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by geriux** [comment]
## 🟢 iOS Sanity Tests - Test Suite 3

- Device: iPhone 12 Pro
- OS 14.4
- Build [42460](https://github.com/wordpress-mobile/WordPress-iOS/pull/15894#issuecomment-779885170)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Gallery - 4

- [x] Gallery block - Settings: Link to - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)
- [x] Gallery block - Settings: Column number - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

### MediaText - 3

- [x] Media Text block - Insert video from device (failing) - [TC001-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [x] Media Text block - Close/Re-open post with an ongoing video upload - [TC003-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

### MediaText - 4

- [x] Media Text block - Media & Text alignment - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

### Cover - 2

- [x] Cover - Add Video Background from WordPress Media library - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [x] Cover - Replace media - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient background is rendered properly - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
- [x] Cover - Gradient overlay is rendered properly - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

### Social Icons - 2
- [x] The link sheet is opened automatically when adding new icon - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc004)
- [x] Ghost placeholder is visible when no icon is active - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc005)
- [x] Social icon forwarding to the link - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc006)

### Image - 2
- [x] Image block - Switch to classic editor with an image block in page - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc006)
- [x] Image block - Border style setting - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc007)
- [x] Image block - Image size setting - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)
- [x] Image block - Link to setting - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)

### Story block - 1
*Not available on iOS yet*

**Comment by antonis** [comment]
### 🟢 Android: Writing Flow checklist - round 3
* Test device: Google Pixel 2 XL (Android 11)
* [Build](https://96645-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14081-build-96645.apk) from [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14081)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
### 🟢 iOS Writing Flow checklist (round 3)

* iPhone SE
* iOS 14.4
* Build `42460` from https://github.com/wordpress-mobile/WordPress-iOS/pull/15894#issuecomment-779885170.

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
# 🟡 Summary: Manual Tests Round 3

* 🟢 All [previous regressions](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3155#issuecomment-780104598) fixed.
* 🟡 Discovered https://github.com/WordPress/gutenberg/issues/29116, but this also occurs in the latest Play Store WPAndroid `16.6`, so it does not appear to be a regression for `1.47.0`.

**Comment by antonis** [comment]
At this stage this LGTM 🎉

**Review by dcalhoun — APPROVED** [review]
LGTM. We just need to decide on a strategy to fix/validate the frozen [Gutenberg CI tests](https://github.com/WordPress/gutenberg/pull/29037), then we are good to merge.

**Pull request merged**
