### PR TITLE
[Experimental] Cross platform `Box` component to replace `View`

### PR DESCRIPTION
**Pull request by dratwas**
See - https://github.com/wordpress-mobile/gutenberg-mobile/issues/1386
Gutenberg PR - https://github.com/WordPress/gutenberg/pull/17673

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
Any learnings we can pick out of this PR? Can we close otherwise?

**Comment by dratwas** [comment]
Hey @hypest my takeaways from these experiments (button and box) are listed here https://mobilegutenpagesp2.wordpress.com/2020/01/14/x-platform-button-experimental/

**Comment by hypest** [comment]
Aha, thanks for the pointer Piotr! Seems to me that resuming work on this PR is not scheduled yet so, I wonder if we can close this PR in the meantime? We can always re-open if needed. WDYT?

**Comment by dratwas** [comment]
> We can always re-open if needed. WDYT?

Agree :)

**Pull request closed without merging**
