### PR TITLE
Try/device tests

### PR DESCRIPTION
**Pull request by JavonDavis**
Reduces the number of tests ran until issues with tests and sauce labs can be resolved. These subset of tests seem to not result int the server issues. 

To test: Check that everything passes in CI, maybe rerun the workflow to make sure everything is ok.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by etoledom** [comment]
- All tests were ✅ 
- Just had re-run the workflows and both iOS and Android UI tests failed.
- Re-running them again.

**Comment by JavonDavis** [comment]
@etoledom everything ok for this to merge?

**Comment by etoledom** [comment]
Thank you @JavonDavis for your big effort! 🙏

**Comment by hypest** [comment]
👋 @JavonDavis, can you open a ticket to track the re-instate of the skipped tests? Thanks!

**Pull request merged**
