### PR TITLE
Assure destination directory presence for localization strings files output

### PR DESCRIPTION
**Pull request by fluiddot**
This PR adds logic to both scripts in charge of generating the localization strings files (`strings2android` and `strings2swift`), in order to assure that the destination directory provided to the script is always present.

To test:
1. Run command `rm -rf bundle && npm run bundle`.
2. Observe that no errors are thrown and that bundles are generated.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
I confirmed that running `npm run bundle` after having deleted the bundle results in a new bundle. 

I see the following changes after the new bundle has been generated and I didn't expect to see changes because I was simply re-generating the bundle. Do you know why these changes occur?

```
	modified:   ios/App.js
	modified:   ios/App.js.map
	deleted:    ios/assets/gutenberg/packages/blocks/src/api/i18n-block.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ar.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/bg.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/bo.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ca.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/cs.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/cy.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/da.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/de.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/el.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-au.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-ca.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-gb.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-nz.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/en-za.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-ar.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-cl.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es-cr.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/es.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/fa.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/fr.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/gl.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/he.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/hr.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/hu.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/id.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/is.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/it.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ja.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ka.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ko.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nb.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nl-be.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/nl.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pl.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pt-br.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/pt.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ro.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ru.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sk.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sq.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sr.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/sv.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/th.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/tr.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/uk.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/ur.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/vi.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/zh-cn.json
	deleted:    ios/assets/gutenberg/packages/react-native-editor/i18n-cache/data/zh-tw.json
	deleted:    ios/assets/jetpack/projects/plugins/jetpack/extensions/index.json
```

**Comment by fluiddot** [comment]
> I see the following changes after the new bundle has been generated and I didn't expect to see changes because I was simply re-generating the bundle. Do you know why these changes occur?

Yep, this is expected after the merge of the RN 0.66 upgrade. Prior to 0.66 version, the JSON files referenced in the bundle were being duplicated by Metro upon generation as asset files, however, JSON files are part of the JS code of the bundle, so those files are redundant and not really used ([bug reference](https://github.com/facebook/metro/pull/593)). @dcalhoun opened [this draft PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4401) in order to address it, I don't think it's a high priority task but I could take over it if you agree.

**Review by guarani — APPROVED** [review]
> Yep, this is expected after the merge of the RN 0.66 upgrade. Prior to 0.66 version, the JSON files referenced in the bundle were being duplicated by Metro upon generation as asset files, however, JSON files are part of the JS code of the bundle, so those files are redundant and not really used ([bug reference](https://github.com/facebook/metro/pull/593)). 

Ok, thanks for the explanation!

> @dcalhoun opened [this draft PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4401) in order to address it, I don't think it's a high priority task but I could take over it if you agree.

Thanks for pointing out that PR. I agree it doesn't seem high-priority either 👍

**Comment by guarani** [comment]
I left an approval 👍 Thanks @fluiddot!

**Pull request merged**
