### PR TITLE
iOS: Use firstChild and lastChild when parsing lists from MS Word

### LINKED ISSUE #4145: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 't._parentNode=null')
**Sentry issue:** https://sentry.io/share/issue/83edfe1cf6ea4b7fbb2bdc853e6201eb/

Here is the desymbolyzed JS stacktrace for version WPiOS 18.4 (GB-mobile 1.63.0):
```
gutenberg-mobile/gutenberg/node_modules/jsdom-jscore-rn/lib/jsdom/level1/core.js:631:Node.prototype.removeChild
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/ms-list-converter.js:57:msListConverter
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:117:filters.forEach$argument_0
forEach@(null):(null)
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:111:Array.from.forEach$argument_0
forEach@(null):(null)
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:108:deepFilterNodeList
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:109:Array.from.forEach$argument_0
forEach@(null):(null)
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:108:deepFilterNodeList
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:109:Array.from.forEach$argument_0
forEach@(null):(null)
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:108:deepFilterNodeList
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/utils.js:137:deepFilterHTML
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/paste-handler.js:203:flatMap$argument_1
gutenberg-mobile/gutenberg/node_modules/lodash/lodash.js:653:arrayMap
gutenberg-mobile/gutenberg/node_modules/lodash/lodash.js:9621:map
gutenberg-mobile/gutenberg/node_modules/lodash/lodash.js:9325:flatMap
gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/paste-handler.js:177:pasteHandler
gutenberg-mobile/gutenberg/packages/block-editor/src/components/rich-text/index.native.js:450:useCallback$argument_0
gutenberg-mobile/gutenberg/packages/rich-text/src/component/index.native.js:534:RichText#onPaste
value@(null):(null)
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:22:invokeGuardedCallbackImpl
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:40:invokeGuardedCallback
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:53:invokeGuardedCallbackAndCatchFirstError
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:72:executeDispatch
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1018:executeDispatchesAndReleaseTopLevel
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:349:forEachAccumulated
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1053:batchedUpdates$argument_0
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7817:batchedUpdatesImpl
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:999:batchedUpdates
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1030:_receiveRootNodeIDEvent
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1071:ReactNativePrivateInterface.RCTEventEmitter.register$argument_0.receiveEvent
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:__callFunction
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:__guard$argument_0
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:365:__guard
gutenberg-mobile/gutenberg/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:callFunctionReturnFlushedQueue
value@(null):(null)
```

A quick exploration of the stacktrace tells that the issue is most likely related to pasting content from MS Word/MS Word Online that can't be parsed in the native version:

- [gutenberg-mobile/gutenberg/packages/rich-text/src/component/index.native.js:534:RichText#onPaste](https://github.com/WordPress/gutenberg/blob/bf867e9812996cbae99841ec52a6ba1789234593/packages/block-editor/src/components/rich-text/index.native.js#L450-L456)
- [gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/paste-handler.js:177:pasteHandler](https://github.com/WordPress/gutenberg/blob/bf867e9812996cbae99841ec52a6ba1789234593/packages/blocks/src/api/raw-handling/paste-handler.js#L177-L216)

- [gutenberg-mobile/gutenberg/packages/blocks/src/api/raw-handling/ms-list-converter.js:57:msListConverter](https://github.com/WordPress/gutenberg/blob/bf867e9812996cbae99841ec52a6ba1789234593/packages/blocks/src/api/raw-handling/ms-list-converter.js#L57)
**NOTE:** By the name of the converter function (`ms-list-converter`), it looks related to MS Word. More information about the raw handling when pasting [here](https://github.com/WordPress/gutenberg/tree/bf867e9812996cbae99841ec52a6ba1789234593/packages/blocks/src/api/raw-handling#raw-handling-paste).

**To Reproduce**
Unknown, yet to be defined.

**Expected behavior**
Pasting content shouldn't produce JS exceptions.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPad (8th generation)
 - OS: iOS 15.0.2
 - Version: 18.4.0.3

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by twstokes**
Fixes #4145

### Related PRs:
- https://github.com/WordPress/gutenberg/pull/36019

### To test:
See [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/36019) for testing instructions.

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
@hypest would you mind providing a review for this? Thank you!

**Comment by fluiddot** [comment]
Hey @twstokes !
We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!

**Comment by twstokes** [comment]
Hey @fluiddot 👋! Thanks for the ping, I just now added this PR to the milestone and wondered if you could give it a look. The Gutenberg counterpart has been merged. Thank you!

**Comment by fluiddot** [comment]
> Hey @fluiddot 👋! Thanks for the ping, I just now added this PR to the milestone and wondered if you could give it a look. The Gutenberg counterpart has been merged. Thank you!

No problem, if the Gutenberg PR is already merged it would be quick to review it 💨 .

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Comment by hypest** [comment]
Friendly suggestion @twstokes , it's usually best to avoid merging any parts of the PR "domino" (main apps/gb-mobile/Gutenberg PR chain) until all PRs get green and LGTM'd. It's not a guarantee but, that usually helps avoid surprises when a PR ends up needing some more work but the other is already merged. Thanks!

**Comment by twstokes** [comment]
> Friendly suggestion @twstokes , it's usually best to avoid merging any parts of the PR "domino" (main apps/gb-mobile/Gutenberg PR chain) until all PRs get green and LGTM'd. It's not a guarantee but, that usually helps avoid surprises when a PR needs ends up needing some more work but the other is already merged. Thanks!

Thanks @hypest, that's true - I had it in my mind that GB Mobile wasn't "complete" until pointed to the GB trunk hash, but that's definitely trickier if things need more work. Will do!

**Pull request merged**
