### PR TITLE
Make inserter to show options on long-press to add before/after

### LINKED ISSUE #1433: Proposal: Long-press on inserter to show options for "add above" and "add below"
Long-pressing on the inserter button (`(+)` on the quick toolbar) should show options to `Add Block Before` and `Add Block After` the currently selected block. If there is no selection these options could be `Add to beginning` and `Add to end`. On iOS, this could be an `ActionSheet` and Android a `BottomSheet`.

Example:

IMG_0645

Note: I think we could expand on this pattern in the future, but I've found myself wanting to do add blocks before the selected one quite often, especially now that we have InnerBlocks.

We might also want to add these options to the `•••` menu on the inline toolbar when we get a chance, similar to web.

### PR DESCRIPTION
**Pull request by ceyhun**
Fixes #1433 

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/18791

For detailed test cases and screenshots, please check out https://github.com/WordPress/gutenberg/pull/18791

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@ceyhun do you mind to update the branch with the latest changes on develop?

We have some updates there that sort some of the issue with the e2e tests, that  I would like to see running on this PR :).

**Comment by ceyhun** [comment]
@SergioEstevao I merged develop and also rebased gutenberg PR onto develop's hash. Still all e2e tests are failing.

**Comment by mchowning** [comment]
>@SergioEstevao I merged develop and also rebased gutenberg PR onto develop's hash. Still all e2e tests are failing.

:wave: @ceyhun!  I know that it used to be the case that e2e tests would fail for PRs from forks ([comment on PR from April with similar issue](https://github.com/wordpress-mobile/gutenberg-mobile/pull/847#issuecomment-487704434)). I'm guessing that is why you updated the submodule ref to point at your gutenberg fork. I nevertheless pushed your code to branches with the same name on `gutenberg-mobile` and `gutenberg` to see if it would make any difference, but the Android tests are still failing. 😞

**Comment by ceyhun** [comment]
Hello @mchowning  🤔 Before it was failing on both iOS and Android, last test run seems to be behaving differently now. Let me see if I reproduce this when I run locally.

**Comment by ceyhun** [comment]
@mchowning I was able to reproduce locally. So I merged develop and also changed the gutenberg ref to the most recent changes of my gutenberg PR and then I ran again locally. Some of them passed this time but there are still failing ones. Then I tried running e2e tests locally on the `develop` branch of `gutenberg-mobile` instead of my branch and it's the same result. Could `develop` of `gutenberg-mobile` be broken or is there some flakiness involved when ran locally? 

Can you please try again with these changes I pushed? Maybe they fail locally but will run successfully on CI?

**Comment by mchowning** [comment]
And now the device tests for both platforms in addition to the jest tests for ios are failing. 😱  

I [pushed your code to the project repo](https://github.com/wordpress-mobile/gutenberg-mobile/compare/develop...issue/1433-long-press-on-inserter-to-show-add-before-after) and the device tests are passing, but it's got a single failure with the jest tests on iOS. 😕 I can reproduce that failure locally if I run `TEST_RN_PLATFORM=ios yarn test` (have to manually set the platform to `ios` since it defaults to `android` otherwise). It seems like the device tests are likely flakiness/fork issues, so let's see if we can get all the jest tests passing on both platforms.

When I run the jest tests locally I only see the same single iOS test failure that [CI is reporting](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/20459?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), so if you're seeing more failures than that, let me know. In that case there may be some kind of setup issue we need to resolve.

**Comment by ceyhun** [comment]
Thanks for trying again @mchowning :) For some reason I don't understand yet
```
<>
  <Component/>
</>
```
when rendered to JSON returns an array on Android but an object on iOS.
So instead of using `toJSON` method of react-test-renderer I used the `findByProps` method. Now it should pass on both platforms.

**Comment by mchowning** [comment]
I just merged `develop` into [the branch](https://github.com/wordpress-mobile/gutenberg-mobile/compare/develop...issue/1433-long-press-on-inserter-to-show-add-before-after) I created with your code since we have a fix for the runtime crash you saw merged into `develop` now. Let's see how that build does.

**Comment by ceyhun** [comment]
Thanks again @mchowning 👍 I had a conflict in my gutenberg PR so I rebased it and also merged develop here again. Android issues seem to be fixed now for me.

**Comment by ceyhun** [comment]
Currently having issues running [iOS](https://app.circleci.com/jobs/github/wordpress-mobile/gutenberg-mobile/24660) and [Android](https://app.circleci.com/jobs/github/wordpress-mobile/gutenberg-mobile/24658) device tests on forks. Opened a new PR from gutenberg-mobile branch as a workaround until it's fixed: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1835

**Pull request closed without merging**
