### PR TITLE
Add support for heading alignment buttons

### LINKED ISSUE #1880: Add text-alignment support to Headings
We currently only have text-alignment support on the paragraph block. More often than not, left-aligned text works fine, but sometimes you want centered heading text. For example, on a Cover block (which is in progress):

<a href="https://user-images.githubusercontent.com/1200432/74270484-ea895a00-4cd0-11ea-87fd-a443f2ad9d59.jpeg"></a>

Another use case: centered section text ([example](https://cloudup.com/ch3jzIS2UYZ))

// cc @mchowning @hypest

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1880 

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/20745

This PR updates the GB reference to add support to alignment on the Heading block.
In the process, the heading block was refactored to share all the edit method with the web and that that involved using the new Text component that needed the adding of [the emotion style library](https://emotion.sh/docs/@emotion/native).
We now have support for dropdown menu in the block control. The implementation uses a BottomSheet to show the options when tapped.

To test:
 - Open the demo app
 - Add a Heading block
 - Check if the alignment options are visible on the block toolbar
 - Check if the alignment options work correctly.
 - Check if the header size show and work correctly on the toolbar

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Thank you for working on this! It'll be beneficial for a bunch of blocks/features <3

**Comment by SergioEstevao** [comment]
@mchowning is going to check why the align command don't work on Android.

**Comment by mchowning** [comment]
I have opened an [AztecEditor-Android PR](https://github.com/wordpress-mobile/AztecEditor-Android/pull/899) that should address the alignment issue we're seeing here on Android.

**Comment by marecar3** [comment]
We're freezing `1.24.0 `today. If you think it is ready and if you'd like to ship it with `1.24.0`please merge it into develop branch. Otherwise, we can bump it to `1.25.0.` @SergioEstevao  @Tug

**Comment by SergioEstevao** [comment]
I'm merging this PR and doing a follow up PR to disable the options to align in Android if Aztec Android is not until next Friday.

**Pull request merged**
