### PR TITLE
Gallery block fix: restore focus caption prop for native

### LINKED ISSUE #3510: The editor Crashes when adding a Caption to a Gallery block
**Describe the bug**
The editor Crashes when adding a Caption to a Gallery block

**To Reproduce**
Follow the steps on [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/gallery.md#tc003) or:
1. Add a Gallery block
2. Add some images from the device or media library
3. Tap on the gallery caption
4. **Notice** the the editor crashes

The **Crash** occurs both on **Android and iOS**

**Expected behavior**
The user is able to add a gallery caption.

**Screenshots**

https://user-images.githubusercontent.com/304044/118486426-463b6200-b722-11eb-9ae9-7b613ea62e17.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL, iPhone SE
 - OS: Android 11.0, iOS 14.4
 - Version Gutenberg Mobile [1.53.0](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3506)

### PR DESCRIPTION
**Pull request by hypest**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/3510

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/32029

Alternative to https://github.com/WordPress/gutenberg/pull/31938.

To test:

1. Add a Gallery block
2. Add some images from the device or media library
3. Tap on the gallery caption
4. Verify that the editor doesn't crash

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
All tests passed on https://github.com/wordpress-mobile/gutenberg-mobile/pull/3534/commits/9b2b03571a414fd4e5fd1b29f6f2daca33cbd02b and we merged the GB side PR. I've updated the hash here and we can merge when all green.

@fluiddot , added you as a reviewer at this stage since I want to avoid self-merging :) 

@AmandaRiu , feel free to cherry-pick the fix for a betafix when you get online, thanks!

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

_Tested on Samsung Galaxy S20 FE 5G (Android 10) and iPhone 11 (iOS 14.2)._

**Comment by fluiddot** [comment]
@hypest Before merging this PR, I think it would be nice to rename the PR's title, could I remove the `Test GB PR 32029` part?

**Comment by hypest** [comment]
> @hypest Before merging this PR, I think it would be nice to rename the PR's title, could I remove the Test GB PR 32029 part?

Good point, went ahead and did it 👍

**Comment by fluiddot** [comment]
Since this fix will be included in the beta fix `1.53.1`, I've just assigned it that milestone.

**Pull request merged**
