### PR TITLE
Ensure that empty posts are not published

### LINKED ISSUE #369: Make sure an empty draft can't be published
As reported by @rachelmcr:

---

I’m able to save a completely empty post (no title or content). That shouldn’t be possible. To reproduce:

1. Start a new Gutenberg post.
2. Tap into the post content area. This makes a new paragraph block appear.
3. Tap the ellipsis menu and select “Save as Draft.”

You can also try to publish an empty post, although it fails. The “Publish” button shouldn’t be enabled in that case:

1. Start a new Gutenberg post. (You don’t have to enter any content or tap anywhere in the post title or content area.)
2. Tap the Publish button.

---

I'm adding this one for the alpha assuming it's a quick fix, since Aztec already behaves that way.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #369

This just updates the GB reference in order that empty posts autosaves are sent to the bridge method.

Check this GB PR for the changes: https://github.com/WordPress/gutenberg/pull/23233

To test:
 - Test using this WP-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14329
 - Create a new post
 - Write some text on a paragraph
 - Remove the paragraph using the block toolbar trash option
 - Make sure the publish button is disabled when the post is empty

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
👋  @SergioEstevao   ! We're close to merging the monorepo changes 🎉 , and we will be cutting the release branches as soon as the monorepo changes are merged to gutenberg-mobile. As a result, we may be cutting the 1.31 release branches earlier than normal.

If these changes can wait until 1.32, please bump this to the 1.32 milestone and wait to merge this until after the release branches are cut. That way we don't add more changes to the 1.31 release than are necessary—this release is already going to have a lot more changes than a normal release because of the monorepo changes. If it is important that this PR make the 1.31 release, however, let me know and I'll review it first thing in the morning so we can get it merged before we cut the release. 🙇

**Comment by mchowning** [comment]
👋 @SergioEstevao ! Since we're getting ready to cut the 1.32 branch, I'm bumping this to the 1.33. Obviously, feel free to undo that if this needs to make the 1.32 release.

(Also, sorry I haven't reviewed this 😔)

**Comment by hypest** [comment]
Is this PR still relevant? The original ticket it tries to address is closed by now.

**Comment by SergioEstevao** [comment]
While the original issue is indeed closed, this PR was an improvement on top of the fix, in order to make the "Publish" completely disabled when the post was empty.

Because of the way, we implemented this and after @etoledom reviewed it, we decide to not included in the original fix, because it involved changes on the auto-save mechanism that we feel we're not safe.

Check the GB for more details on the implementation: https://github.com/WordPress/gutenberg/pull/23233

**Pull request merged**
