### PR TITLE
Add git submodule dep updates via Dependabot

### PR DESCRIPTION
**Pull request by hypest**
Experimental git-submodule dependency updates being done semi-automatically via Dependabot

Should be doable based on this older news post that Dependabot [supports git submodules updates](https://dependabot.com/blog/dependabot-now-supports-git-submodules/), plus the [related documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem).

FWIW, here's the list of PRs that Dependabot has opened in this repo in the past: https://github.com/wordpress-mobile/gutenberg-mobile/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed

To test:
I think that we can't test something while this PR is unmerged. After we merge we can check whether Dependabot indeed opens new PRs to auto-update the git submodule references.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
Tests are currently failing due to a Node version issue on CI and will be fixed by https://github.com/wordpress-mobile/gutenberg-mobile/pull/2763.

**Review by ceyhun — APPROVED** [review]
Let's try and see 👍

**Comment by hypest** [comment]
Currently the Android device tests fail with ENOMEM but that's not related to this PR. So, will go ahead and merge as approved.

Edit: I can't seem to be able to merge since a "Required" CI job is failing and I'm the author of this PR. We don't need to rush this anyway, especially if it means we'll get automated PRs that will fail with ENOMEM anyway. Will wait until we have the ENOMEM issue resolved.

**Comment by hypest** [comment]
Tests are now green after updating from develop so, merging now.

**Pull request merged**
