### PR TITLE
Release 1.47.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.47.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/29669
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14218
- ~~WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/~~ **(None because this is a WPAndroid hotfix)**

- ~~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~~
- ~~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

 - Reduce the number of items per page when fetching reusable blocks to prevent a crash: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3227

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
All the conflicts are produced because the version `1.48.0` was already merged into `trunk` and this PR was branched off from version `release/1.47.0`.

**Comment by geriux** [comment]
## Smoke tests

**Device**: Redmi Note 8T
**OS**: Android 10
**Build**: [98677](https://github.com/wordpress-mobile/WordPress-Android/pull/14218#issuecomment-793731835)


- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved

**Comment by fluiddot** [comment]
## Android - Smoke tests

**Device:** Samsung Galaxy S20 FE 5G
**OS:** Android 10
**App:** WPAndroid 16.8.1
**Build:** [98677](https://github.com/wordpress-mobile/WordPress-Android/pull/14218#issuecomment-793711463)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Verify that the crash is fixed (https://github.com/WordPress/gutenberg/pull/29626)

**Review by geriux — APPROVED** [review]
LGTM!

**Comment by fluiddot** [comment]
⚠️ I'm afraid I can't merge this into `trunk` because it will point to an older Gutenberg reference as the version `1.48.0` was already merged in that branch. For now I'm going to leave it open and close it once we apply the hotfix changes via the `1.48.1` betafix ([PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3237)).

**Comment by fluiddot** [comment]
This release (`1.47.1`) has been merged into `trunk` via the `1.48.1` betafix release 🎊 .

**Pull request merged**
