### PR TITLE
Adding remove NUX script for Unsupported Block Editor.

### PR DESCRIPTION
**Pull request by etoledom**
Adding custom js-script for Unsupported Block Fallback to remove wpcom NUX UI.
This script is not used in this repo, but it's here to be used from the client apps.

gutenberg PR: https://github.com/WordPress/gutenberg/pull/24658
WPiOS side PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/14683
WPAndroid side PR: https://github.com/wordpress-mobile/WordPress-Android/pull/12795

To test:

Please refer to https://github.com/wordpress-mobile/WordPress-iOS/pull/14683 for testing steps

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
Hey 👋 @etoledom 
The android part of the fix is ready for testing. Feel free to mark this PR ready for review if you think that we have everything that we wanted to have? thanks.

**Comment by marecar3** [comment]
Hey @etoledom 👋 
I have updated the description with the WPAndroid side PR.

**Comment by cameronvoell** [comment]
Hey @etoledom please aim to merge this first half of the day 8/31 if we're still aiming for 1.36, otherwise I'll suggest we bump the target 1.37. Thanks!

**Comment by jd-alexander** [comment]
Hi @etoledom we'll be cutting the 1.37 release branch at the end of next week. Please try to get this merged by then or bump the milestone. Thanks much 🙇

**Comment by etoledom** [comment]
Tested on WPiOS and WPAndroid and this seems to work great in both!

**Review by mchowning — APPROVED** [review]
Tested via https://github.com/wordpress-mobile/WordPress-Android/pull/12795 and this is working well. Since @guarani [already tested the WPiOS side of this](https://github.com/wordpress-mobile/WordPress-iOS/pull/14683#pullrequestreview-486079816), I think we're good to :shipit:

**Comment by jd-alexander** [comment]
Hi @etoledom we'll be cutting the 1.37 release branch at the beginning of next week. Please try to get this merged by then or bump the milestone. Thanks much 🙇

**Pull request merged**
