### PR TITLE
Release 1.101.2

### PR DESCRIPTION
**Pull request by derekblank**
Release for Gutenberg Mobile 1.101.2

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/53936
- WPAndroid: N/A
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/21418

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Change 1
- **PR:** https://github.com/WordPress/gutenberg/pull/53895
- **Issue:** https://github.com/wordpress-mobile/WordPress-iOS/issues/21399

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by geriux** [comment]
## 🟢 Writing Flow checklist (iOS)
**Device**: iPhone 14 Pro OS 16.6
**Build**: [jetpack-installable-builds #5899](https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/releases/5899)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Review by geriux — APPROVED** [review]
LGTM!

**Comment by derekblank** [comment]
@geriux Should these conflicts be expected? 🤔

**Comment by geriux** [comment]
> @geriux Should these conflicts be expected? 🤔

Yes because this a release behind that the one is in `trunk` I'll fix the conflicts.

**Pull request merged**
