### PR TITLE
Release 1.77.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.77.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/41497
- ~~WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/16688~~ **(This release will only be released on iOS)**
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/18812

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Change 1
- **PR:** https://github.com/WordPress/gutenberg/pull/41482
- **Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/4918

Fixes a crash on iOS related to JSI and Reanimated.

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
## 🟢  Test new changes (iOS)

**Build**: [`pr18812-fc7189e`](https://github.com/wordpress-mobile/WordPress-iOS/pull/18812#issuecomment-1144690466)
**Device**: iPhone 11 (iOS 15.4)

- [x] https://github.com/WordPress/gutenberg/pull/41482

**Comment by fluiddot** [comment]
## 🟢  Writing Flow checklist (iOS)

**Build**: [`pr18812-fc7189e`](https://github.com/wordpress-mobile/WordPress-iOS/pull/18812#issuecomment-1144690466)
**Device**: iPhone 11 (iOS 15.4)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md#tc001) - Multiline components
  - [x] Quote block
  - [x] Verse block
  - [x] Preformatted block
  - [x] Code block (DEV only)
  - [x] Pullquote block
#### Rich Text Format
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc001) - Bold, Italic, strikethrough buttons
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc001) - Highlight selected text
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc001) - Highlight text without selection
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc002) - Alignment buttons
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc003) - Alignment Split
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc004) - Link button works without selection
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc005) - Link button works with a selected word
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc006) - Adding a link from a copied URL
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC008](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc008) - Test formatting doesn't remove leading or trailing whitespace
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc006) - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/undo-redo.md#tc001) - Undo/redo block actions
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/undo-redo.md#tc002) - Undo/redo text
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/undo-redo.md#tc003) - Undo/redo text format

**Comment by fluiddot** [comment]
> ## ⚪️ Test new changes (iOS)
> **Build**: [`pr18812-fc7189e`](https://github.com/wordpress-mobile/WordPress-iOS/pull/18812#issuecomment-1144690466)
> **Device**: iPhone 11 (iOS 15.4)
> 
> * [ ]  [[RNMobile] Bump `react-native-reanimated` version to `2.4.1-wp-3` WordPress/gutenberg#41482](https://github.com/WordPress/gutenberg/pull/41482)

I'm not able to reproduce the crash described in https://github.com/wordpress-mobile/gutenberg-mobile/issues/4918, @geriux since you managed to reproduce it, would you mind testing it for me? Thanks 🙇 !

**Comment by geriux** [comment]
> I'm not able to reproduce the crash described in #4918, @geriux since you managed to reproduce it, would you mind testing it for me? Thanks 🙇 !

All good! 🟢 I no longer experience the crash when opening and closing the editor or when rotating to landscape. I did experience another issue, the `Don't try to clone an object backed by a different Runtime`, but it's not related to this fix. 👍

**Review by geriux — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
