### PR TITLE
Release 1.103.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.103.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/54217
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/19144
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/21503

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Fix long-press gestures not working in RichText component [Android]
- **PR:** https://github.com/WordPress/gutenberg/pull/54213
- **Issue:** https://github.com/WordPress/gutenberg/issues/54210

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
## 🟢   New changes (Android)
**Build**: `pr19144-6441dd1` - https://github.com/wordpress-mobile/WordPress-Android/pull/19144#issuecomment-1708708015
**Device**: Samsung Galaxy S20 FE 5G (Android 13)

- [x] https://github.com/WordPress/gutenberg/pull/54213

**Comment by fluiddot** [comment]
## 🟢  Writing flow (Android)
**Build**: `pr19144-6441dd1` - https://github.com/wordpress-mobile/WordPress-Android/pull/19144#issuecomment-1708708015
**Device**: Samsung Galaxy S20 FE 5G (Android 13)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website

#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
      - 🟡 **Experienced the known issue:** [Android] Heading block stops being rendered as a header when deleting the first word https://github.com/wordpress-mobile/gutenberg-mobile/issues/3106
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Comment by fluiddot** [comment]
## 🟢  New changes (iOS)
**Build**: `pr21503-6b568a7` - https://github.com/wordpress-mobile/WordPress-iOS/pull/21503#issuecomment-1708752999
**Device**: iPhone 11 (iOS 15.4.1)

- [x] https://github.com/WordPress/gutenberg/pull/54213

**Comment by fluiddot** [comment]
## 🟢  Writing Flow (iOS)
**Build**: `pr21503-6b568a7` - https://github.com/wordpress-mobile/WordPress-iOS/pull/21503#issuecomment-1708752999
**Device**: iPhone 11 (iOS 15.4.1)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [ ] Paragraph
  - [ ] Heading

**Review by twstokes — APPROVED** [review]
LGTM @fluiddot!

**Pull request merged**
