### PR TITLE
Fix missing context prop in BlockEdit component

### LINKED ISSUE #29471: Adding Spacer block generates an error
## Description

Adding a Spacer block to the content generates the following error:
```
TypeError: Cannot read property 'orientation' of undefined

This error is located at:
    in SpacerEdit (at with-instance-id/index.js:18)
    in WithInstanceId(SpacerEdit) (at with-dispatch/index.js:96)
    in WithDispatch(WithInstanceId(SpacerEdit)) (at edit.native.js:17)
    in Edit (at align.js:149)
...
```

## Step-by-step reproduction instructions

1. Go to a post/page.
2. Add a Spacer block.
3. Observe the error.

## Expected behaviour

Spacer block shouldn't generate any error when adding it to the content.

## Actual behaviour

It generates the error described above.

## Screenshots or screen recording (optional)

N/A

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes

## Device information
- Device: iPhone 8 - Simulator
- Operating system:  iOS 14.2
- WordPress app version:  16.7 (DEV)

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/29479

Fixes https://github.com/WordPress/gutenberg/issues/29471

To test:
Instructions are described in the the "How has this been tested?" section of the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29479).

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by cameronvoell — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/29479.

Looks like iOS file test failed on first attempt, but I think it was just a flake, as I tested the file block on iOS and the file test passed when I enabled full suite of tests. 

Let's see if test passes on second attempt after restart. If that passes we'll be ready to merge after updating the gutenberg ref 👍

**Comment by fluiddot** [comment]
> Approved via [WordPress/gutenberg#29479](https://github.com/WordPress/gutenberg/pull/29479).
> 
> Looks like iOS file test failed on first attempt, but I think it was just a flake, as I tested the file block on iOS and the file test passed when I enabled full suite of tests.
> 
> Let's see if test passes on second attempt after restart. If that passes we'll be ready to merge after updating the gutenberg ref 👍

All the [tests passed](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/10704/workflows/b0e2ee3d-308d-49ce-8563-0367f5029035) so I'm going to update the Gutenberg reference with the merge commit from `trunk` and merge the PR.

**Comment by enejb** [comment]
Should this change make it into 1.48.0 ? release

**Comment by fluiddot** [comment]
> Should this change make it into 1.48.0 ? release

This fix is only required to be included if we include the changes from the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29133) that introduced the bug.

I see that the release was branched off from a commit before that one so it's not needed, thanks for the heads-up 🙇 .

Screenshot 2021-03-03 at 18 48 07

**Comment by jd-alexander** [comment]
> Looks like iOS file test failed on first attempt, but I think it was just a flake, as I tested the file block on iOS and the file test passed when I enabled full suite of tests.

Hi @cameronvoell Just to chime in here, did you by any chance have a look at the error log for this failure? Because I utilized sleep calls to ensure that the media picker bottom sheet is shown before making a selection and it was flaky in the past but I thought it was resolved now. I also know that other issues have been taking place in the UI tests, so I want to assist in any way possible to reduce the flakiness, as I know it impacts developer productivity.

**Pull request merged**
