### PR TITLE
Reduce spacing between label and slider control

### PR DESCRIPTION
**Pull request by antonis**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2126

## Related PRs:
gutenberg https://github.com/WordPress/gutenberg/pull/23580

## Description
Reduces spacing between label and slider control by:
* 14px on iOS
* 24px on Android

## How has this been tested?
* Add a block that has as slider control in the settings (e.g. spacer)
* Press on the settings button
* Verify that the space between the label and the slider control is appropriate

## Screenshots

|Android|iOS|
|---|---|
|Screenshot_1593521798|Simulator Screen Shot - iPhone 11 - 2020-06-30 at 15 52 30|

## Types of changes
Enhancement

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](docs/Release-notes.md) and have added them to `[RELEASE-NOTES.txt](RELEASE-NOTES.txt)` if necessary.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@antonis Thank you so much for tackling this one — it's been bothering me for a while 😄 2 quick questions:

* Is there a way you can overlay keylines/metric lines so I can see the spacing/margins in more detail? I've seen this done on Android PR's but I'm not sure how it's done (or if it's even possible on iOS). If not I can also pull these screenshots into Figma to compare against my component library.
* Would it be possible to align the left side of the slider track on Android with the 16px keyline/margin ([example](https://cloudup.com/cb9nwa-z47k))? I'm guessing there is a small inset that comes with the native component, but I'd like to align this if possible.

**Comment by antonis** [comment]
Hello @iamthomasbishop 👋 

Thank you for the quick feedback. I tried to align the content but it brakes when the material design animation enlarges the toggle and drops the shadow.
android

I'll check If I can add the keylines on both platforms and get back to you on your other question.

**Comment by iamthomasbishop** [comment]
> I tried to align the content but it brakes when the material design animation enlarges the toggle and drops the shadow.

@antonis ahh okay so the overflow is hidden, that makes sense. Let's ignore that for now, we can address it later.

**Comment by antonis** [comment]
Hello @iamthomasbishop,
I'm attaching an Android screenshot with the keylines/metric lines.

I didn't find something similar on iOS.

**Comment by iamthomasbishop** [comment]
@antonis These measurements should work pretty well. I have 2 tiny requests, both of which we can attack separately at a future time if we need to keep moving. Other than these things, feel free to ship this as-is!

1. I still have the concern about Android's track not aligning to the left 16 key line, but it's not a blocker specific to this.
2. I would like to at some point update the style of the text inputs on the Slider cells slightly -- it would look [something like this](https://cloudup.com/cgiSVBgQJ9a), and align more closely to the native platforms.

Side note: For consistency, I pulled these into Figma and aligned with my library 👍

**Comment by antonis** [comment]
Gutenberg PR merged https://github.com/WordPress/gutenberg/pull/23580

**Pull request closed without merging**
