### PR TITLE
Release 1.39.0

### PR DESCRIPTION
**Pull request by ceyhun**
Release for Gutenberg Mobile 1.39.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/26064
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13119
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15086

## Extra PRs that Landed After the Release Was Cut

- Prepare mobile columns for different units: https://github.com/WordPress/gutenberg/pull/26095
- Unsupported Block Editor: Inject css on both page visible and page started: https://github.com/WordPress/gutenberg/pull/26071
- Unsupported Block Editor: cannot view or interact with the classic block on jetpack sites: https://github.com/WordPress/gutenberg/pull/26168
- Fix appender to add new buttons when a Button is selected no longer showing: https://github.com/WordPress/gutenberg/pull/26203

## Changes

* Full-width and wide alignment support for Video, Latest-posts, Gallery, Media & text, and Pullquote block: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2605
* Fix unsupported block bottom sheet is triggered when device is rotated: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2710
* Unsupported Block Editor: Fixed issue when cannot view or interact with the classic block on Jetpack sites: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2709

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Known Issues

- Post previews show black nav bar after user visits Unsupport Block Editor: https://github.com/wordpress-mobile/WordPress-Android/issues/13133

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [x] Gutenberg 'Podfile.lock' inside 'gutenberg/package/react-native-editor/ios/' is updated to the release number.
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by ceyhun** [comment]
Testing with WPiOS

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format  

      
Tested the changes and extra PRs in the description with WPiOS as well and everything looks good!

**Comment by cameronvoell** [comment]
Testing with WPAndroid

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format  

Checks look all good!

**Review by cameronvoell — APPROVED** [review]
Tested all new PRs and everything was working correctly on WPAndroid. Looks good!

**Comment by ceyhun** [comment]
Tested with iPhone 11 Pro iOS 14:

DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [x] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)
Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

Buttons-3

- [x] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

Button-6

- [x] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014) ⚠️ Wasn't able to add a new `Link Rel` because I couldn't type a space as the iOS keyboard was showing a URL entry keyboard. Issue present on previous version as well, created this: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2733
- [x] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

Color Settings - 1 

- [x] Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] Scroll color palette to start - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

**Comment by enejb** [comment]
DarkMode-1

✅  Gallery block - Dark mode 
✅ Shortcode block - Dark mode 
✅ Media Text block - Dark mode 



Group-1

✅  Group - AppenderButton is rendered 
✅  Group - Deep nesting is possible (iOS only)
✅  Group - Check if Group placeholder is visible for the unselected state 
✅  Group - Check if Group placeholder is render in nested structure
✅  Group - Nested block have proper border styling 
✅  Group - Nested block have proper margins values 
✅ Group - Breadcrumbs on FloatingToolbar is properly displayed 

Spacer-1


✅ Spacer block - Spacer is rendered without crash 
✅ Spacer block - Settings: Control spacer height using the slider 
✅ Spacer block - Settings: Control spacer height using the text input )


Buttons-1

✅ Buttons block - Buttons block is added with focused Button with gray background color and white text color 
✅ Buttons block - Buttons inline appender 
✅  Buttons block - Add another Button inside Buttons using inserter
✅  Buttons block - Button's wrapper grows properly 

Buttons-2

✅ Buttons block - Removing Button along with Buttons block 
✅ Buttons block - Removing exactly one Button (when Buttons contain more of them) 

Buttons-3

✅ Buttons block - Wrapping Buttons 
✅  Buttons block - Buttons alignment options 


Button-6

✅  Buttons block - Settings: Open in new tab 
✅ Buttons block - Settings: Link rel 
✅  Buttons block - Settings: Link URL 
🔴  Buttons block - Settings: Remove link - "Remove link" doesn't exits.
✅  Buttons block - Settings: Synchronize with button options - Not sure if this setting 


Color Settings-1

✅ Colors Segmented Controls 
✅ Scroll color palette to start 
✅ Scroll color palette to the end

**Pull request merged**
