### PR TITLE
Merge release 1.48.1 to develop

### PR DESCRIPTION
**Pull request by fluiddot**
The purpose of this PR is to merge into `develop` all the changes of `1.48.1` release.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
It's weird that after generating the bundle it added so many new localized strings 🤔 . I tried to generate the bundle in `develop` branch and generated the same output so I think it's safe to keep them.

**Comment by jd-alexander** [comment]
@fluiddot just verifying here, that there does not need to be any Gutenberg ref bumps in the diff.

**Comment by fluiddot** [comment]
> @fluiddot just verifying here, that there does not need to be any Gutenberg ref bumps in the diff.

That's a good question, I decided to leave the same Gutengerg reference we currently have in `develop`, but maybe it makes sense now that we have the Gutenberg PR merged to point to that commit, wdyt?

**Comment by jd-alexander** [comment]
> That's a good question, I decided to leave the same Gutengerg reference we currently have in develop, but maybe it makes sense now that we have the Gutenberg PR merged to point to that commit, wdyt?

Yeah, it wouldn't hurt. But also when I think about it, the next gb-mobile PR that's created will be based on `trunk` in `gutenberg` so that is going to bring in the changes due to it being a commit hash that after the `1.48.1` merge to `trunk` so it should be fine either way.

**Review by jd-alexander — APPROVED** [review]
Looking good. LGTM 🚢

**Pull request merged**
