### PR TITLE
Set and reference heading anchors

### LINKED ISSUE #1816: Add support for setting anchors and referring to them from links
The mobile block editor currently does not support editing the "HTML Anchor" setting of the Heading block. We should be adding this if we want to support editing anchors.

- Heading block 👉 [PR in Review](https://github.com/WordPress/gutenberg/pull/27935)
- Other blocks 👉 WordPress/gutenberg#28363

We should also fix referring to an anchor from the url field with `#my-anchor` for instance. Currently this is not supported as it's considered as an invalid url, so it won't persist.

### PR DESCRIPTION
**Pull request by dcalhoun**
Fixes #1816

- **Guntenberg:** WordPress/gutenberg#27935
- ~**WordPress iOS:** wordpress-mobile/WordPress-iOS#15567~
- ~**WordPress Android:** wordpress-mobile/WordPress-Android#13705~

To test: Test plan outlined in Gutenberg PR description.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by dcalhoun** [comment]
Failing CI e2e tests are due to the branch within a forked repository. #2965 showcases the changes with passing e2e tests.

**Review by ceyhun — APPROVED** [review]
Approved via: https://github.com/WordPress/gutenberg/pull/27935
Maybe we can close this one and move on with: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2965. After the gutenberg PR is merged, updating the gutenberg ref in the gb-mobile PR should be enough before merging.

**Comment by dcalhoun** [comment]
@ceyhun do you believe the CI failures are of concern or should I go ahead and merge this PR? I restarted the CI multiple times, but it continues to fail. I'm happy to look into the cause further if you believe it's worthwhile. I don't intend to place that debugging on you. Thanks for your thoughts!

**Comment by dcalhoun** [comment]
Closing as these changes were merged into `develop` in c7ef7ff27620314a814b4b7626a3b04d9e6f178a.

@hypest if I am mistaken in this approach, will you please let me know?

**Comment by hypest** [comment]
> @hypest if I am mistaken in this approach, will you please let me know?

Closing is the way to go in these cases where the submodule ref has been bumped via a different PR, all good here ✅, thanks for checking David!

**Comment by fluiddot** [comment]
👋 @dcalhoun since this is going to be included in version `1.46.0`, I've just assigned the PR to the version milestone.

**Comment by dcalhoun** [comment]
@fluiddot thank you!

**Pull request closed without merging**
