### PR TITLE
Add Image Caption Styling

### PR DESCRIPTION
**Pull request by mchowning**
Updating the gutenberg submodule ref to include the changes for adding image caption styling. Description of the changes is in the [associated gutenberg PR](https://github.com/WordPress/gutenberg/pull/14883).

### CODE REVIEW

**Comment by etoledom** [comment]
Hey @mchowning ! 

I tried to run the branch but I'm getting this error:

Screenshot_20190409-163007

If you don't see it locally, you can try `yarn clean:install` and `yarn start:reset`.
That should clean everything up. It also could be a local problem on my side, so if everything still works well for you, please let me know.

The error itself doesn't seem to be related to your changes. Keeping the branches updated from the base branches usually help in these cases 👍 

Let me know!

**Comment by mchowning** [comment]
Hey @etoledom !

Not sure how this ended up in that state. Anyway, should be good to go now. Sorry about that.

**Comment by etoledom** [comment]
Thank you for the update @mchowning . It's working now! 🎉

**Comment by mchowning** [comment]
Switched this PR to target a `feature/caption` feature branch at @etoledom 's [suggestion](https://github.com/WordPress/gutenberg/pull/14883#issuecomment-487183739).

**Comment by etoledom** [comment]
Thank you @mchowning !

Now that https://github.com/WordPress/gutenberg/pull/14883 was merged into a local branch, updating the Gutenberg reference should make the CI run properly 🤞

**Comment by mchowning** [comment]
Looking into the test failures ([ios](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/4201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), [android](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/4203?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)), I'm seeing intermittent test failures locally on Android with the same "The environment you requested is not available" message that Circle CI reports. The error seems to _often_ be device specific: (my Pixel 3 (Android 9.0) seems to always fails, but an emulated Nexus 5X (Android 9.0), and emulated Nexus S (Android 8.0) always pass. The one exception to this is my Pixel 1 device (Android 9.0), which passes approximately 90% of the time, but intermittently fails.

It sounds like these kinds of failures are a known issue based on this from the [README's section on UI Tests](https://github.com/wordpress-mobile/gutenberg-mobile#ui-tests):

> Note, you might experience problems that seem to be related to the tests starting the Appium server, for example errors that say... The requested environment is not available. Sorry about that this is still a WIP, you can manually start the Appium server via appium desktop or the cli, then change the port number in the tests while optionally commenting out related code in the beforeAll and afterAll block.

This makes me wonder if these failures might be due to some flakiness in the tests. It seems unlikely that it would be flaky on both platforms at the same time, and I don't see any other builds that failed with this issue recently on Circle CI, so I'm far from convinced that this is just test flakiness. But, since I do get intermittent failures locally, I think it's worth retriggering the builds to see if what a second run on Circle CI gets us. 

What do you think @etoledom?

**Comment by etoledom** [comment]
Thank you for the investigation @mchowning !
I'm retriggering the builds and cc @JavonDavis

**Comment by mchowning** [comment]
Tests still failed on the rebuild ([ios](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/4211), [android](https://circleci.com/gh/wordpress-mobile/gutenberg-mobile/4212)).

As a sanity check I force pushed to the source branch for this PR (`mchowning:issue/image_caption_styling`), reverting my update to the gutenberg ref (so the branch would be unchanged), and adding a commit that does nothing but add an empty text file, and the e2e tests still fail (needless to say, this PR should NOT be merged until I revert this change). So Circle CI just doesn't like me! 

Sanity check: 
- [X] The target branch (`feature/caption`) and `develop` are both on commit 42d8443fd74a1837f70f20689182d700cc47f31f at this time. 
- [X] The source branch is identical to that except for the b895a2e commit I just added, which only adds a small text file to the root of the project (just wanted something in there so there would be a diff between the branches).

**Comment by mchowning** [comment]
@etoledom helped confirm that the UI tests were failing because this PR's source branch was coming from a fork. @etoledom has taken care of merging the code from  b895a2e (the commit before I force pushed a test commit to this PR) into the `feature/caption` branch in #940, so closing this PR.

**Comment by JavonDavis** [comment]
Thanks for helping out on this @etoledom!

**Comment by JavonDavis** [comment]
> Looking into the test failures (ios, android), I'm seeing intermittent test failures locally on Android with the same "The environment you requested is not available" message that Circle CI reports. The error seems to often be device specific: (my physical Pixel 3 (Android 9.0) seems to always fails, but an emulated Nexus 5X (Android 9.0), and emulated Nexus S (Android 8.0) always pass. The only device that gives inconsistent results is my physical Pixel 1 device (Android 9.0), which passes approximately 90% of the time.

@mchowning thanks a lot for highlighting this, I've made a note of it... There are still some things to work out with the environment startup and this is definitely something we're planning to address. **Could you confirm** that for the failures the only error you saw was `The environment you requested is not available` or something that seemed related to that? Just wanted to make sure that there weren't any failures with the tests themselves on the different devices for you, thanks 🙂

**Comment by mchowning** [comment]
> Could you confirm that for the failures the only error you saw was The environment you requested is not available or something that seemed related to that?

:wave: @JavonDavis ! Yes, the only failure I observed was the "The environment you requested is not available" failure.

It did seem like my Pixel 1 device was more likely to fail when I ran the tests immediately after restarting my computer. I tried to confirm this, and it definitely did not always fail after restarting my computer though, so it is entirely possible that I just imagined that correlation.

Let me know if there's any testing I can do to help you out tracking this down.

**Pull request closed without merging**
