### PR TITLE
[Experimental][emotion] Add button component

### PR DESCRIPTION
**Pull request by dratwas**
This is an exploration of x-platform style system. wordpress-mobile/gutenberg-mobile#1411
This is the second iteration on wordpress-mobile/gutenberg-mobile#1386

Gutenberg PR - https://github.com/WordPress/gutenberg/pull/19179

### CODE REVIEW

**Comment by hypest** [comment]
Any learnings we can pick out of this PR? Can we close otherwise?

**Comment by dratwas** [comment]
Hey @hypest my takeaways from these experiments (button and box) are listed here https://mobilegutenpagesp2.wordpress.com/2020/01/14/x-platform-button-experimental/

**Comment by hypest** [comment]
Thanks for the pointer Piotr!

I understand that the this PR is not scheduled for resuming yet so, WDYT about closing? We can always re-open if needed.

**Comment by dratwas** [comment]
Yeah, let's close it :)

**Pull request closed without merging**
