### PR TITLE
Feat: Open Group block for production

### LINKED ISSUE #1824: Open Group block for production
Let's remove the DEV flag from Group block and open it to prod.

To Test:

- Generate bundles
- Open WPiOS and WPAndroid PRs
- Verify Group block is visible in the block picker 
- Verify it is working as expected, try to break it, use try portrait & landscape modes and try nesting it more than expected

note: We don't need to merge WPiOS and WPAndroid PRs, we can use them for testing purposes.

### PR DESCRIPTION
**Pull request by jbinda**
Fixes #1824

PR opens `Group` block for production..

Please also refer to:
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/20004)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1824)

`WordPress iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13367
`WordPress Android` -> https://github.com/wordpress-mobile/WordPress-Android/pull/11231

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pinarol** [comment]
@jbinda hi 👋 Could you address below items in this PR:

- [ ] Generate bundles and open WPiOS and WPAndroid PRs
(This is necessary to be able to test this because we should test with metro off.)

- [ ] Add release notes.

See similar PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1594

**Comment by pinarol** [comment]
@chipsnyder @geriux  After main APP PRs are created, could you please take one platform for yourself and test the Group block? I recommend using the peril links main app PR will give us and directly installing the apps in real device. 

Recommended test steps can be found [here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1824) but no need to limit yourselves with those. Thanks!

**Comment by geriux** [comment]
Hey @chipsnyder 👋 I'll check it out on iOS 🍎

**Comment by jbinda** [comment]
merged ! 🎉

**Pull request merged**
