### PR TITLE
Fix for node.rel crash

### PR DESCRIPTION
**Pull request by hypest**
Addresses at least one case of "Pasting from some sources causes a red screen ([related comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/617#pullrequestreview-205427915))" from #624

To test:

0. On the mobile, open the browser and copy the "Gravity Forms" text (it's a link) from https://designsbytierney.com/2010/01/how-to-add-edit-format-text-in-a-wordpress-post-or-page/
1. Run the demo app
2. In a paragraph block, paste
3. It should work and the link be available in the block

### CODE REVIEW

**Comment by hypest** [comment]
Thanks for the pass @diegoreymendez !

I will actually need to update this PR to host a different solution as, I closed [the Gutenberg side PR](https://github.com/WordPress/gutenberg/pull/13983) as invalid. Will report here again soon.

**Comment by hypest** [comment]
Ready for another pass!

This time, the solution [uses this PR](https://github.com/iamcco/jsdom-jscore-rn/pull/1) opened against the `jsdom-jscore` library repo we're using.

**Comment by mkevins** [comment]
> This time, the solution [uses this PR](https://github.com/iamcco/jsdom-jscore-rn/pull/1) opened against the `jsdom-jscore` library repo we're using.

I think this will make a lot of things easier. Does this mean we can move some (maybe all?) of the jsdom-patches?

**Comment by hypest** [comment]
> Does this mean we can move some (maybe all?) of the jsdom-patches?

Most probably, but let's wait until after our release this coming days so we don't shake things up too much.

**Comment by hypest** [comment]
`jscore-jsdom-rn` upstream accepted our PR so, will update this branch to use the upstream.

**Pull request merged**
