### PR TITLE
Update the way we determine how a post has been edited

### LINKED ISSUE #227: Try to have a change-detection solution that doesn't depend on computing hashes
#225 adds an md5-based content change detection mechanism to inform the parent app of whether the content is modified or not. We'd like to avoid computing hashes for this and perhaps rely on solution similar to Gutenberg-web's. Opening this ticket to keep this in our radar.

Some context: https://github.com/wordpress-mobile/gutenberg-mobile/pull/225#issuecomment-436638366

### PR DESCRIPTION
**Pull request by Tug**
Fixes #227
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/266

This PR uses the `isEditedPostDirty` selector from the `core/editor` store to determine if a post was edited or not and needs to be saved on the server.

### Testing instructions

- Run the project from WordPress-Android `feature/gutenberg-mobile` branch:
    - `git checkout feature/gutenberg-mobile`
    - `git submodule update --init`
    - `cd libs libs/gutenberg-mobile`
    - `git fetch -a && git checkout update/compare-html`
    - `git submodule update --init`
    - `yarn install`
    - Start an AVD or connect a physical Android device in debug mode
    - `yarn wpandroid`
- Click on a page to edit, close
- Page shouldn't appear as being modified
- If you navigate to http://localhost:8081/debugger-ui/ and enable debugging in the Android app, you should see the `isEditedPostDirty false` in the console
- Click on a page to edit, edit the content
- Page should appear as being modified
- you should see the `isEditedPostDirty true` in the console

### CODE REVIEW

**Comment by hypest** [comment]
As mentioned over Slack too, it seems that some posts still manage to trigger the dirtiness flag when exiting the editor so, additional investigation/solution is needed to avoid having the editor report self-inflicted "dirtiness".

**Comment by hypest** [comment]
Is this PR still relevant/active? Can we close it if not? Thanks!

**Comment by koke** [comment]
I've changed the target branch to `develop`, which is right now the same commit as `master`, so there shouldn't be any issue

**Comment by koke** [comment]
I'm guessing this might be obsolete, or will be with the BlockList refactor. Should we close it?

**Comment by hypest** [comment]
With the BlockList refactor already well progressed, is this PR still relevant @Tug ?

**Comment by Tug** [comment]
Closing as it looks obsolete now

**Pull request closed without merging**
