### PR TITLE
[UI tests] Run tests sequentially

### PR DESCRIPTION
**Pull request by Stojdza**
Fixes #

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
I had the same too-long-with-no-output-failures-on-iOS that you're seeing here when I tried reducing the number of workers from 3 to 2 [in this draft PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1980), and I couldn't see why it was happening.

**Comment by Stojdza** [comment]
@mchowning In [Saucelabs](https://app.saucelabs.com/tests/2272c2e8fcce4c309ffa0c5f92cc36c8#127) when I open iOS execution, I see that tests started but I'm also seeing message `Test did not see a new command for 90 seconds. Timing out.` I will need to take a deeper look why is this happening.

**Comment by mchowning** [comment]
> In Saucelabs when I open iOS execution, I see that tests started but I'm also seeing message Test did not see a new command for 90 seconds. Timing out.

I saw that same error with my PR too. Weird that I got it with setting either 2 or 1 workers, and you're getting it with `--runInBand`. I guess 3 is just the magic number! 😆😢😭

**Comment by Stojdza** [comment]
@mchowning Increased [`no_output_timeout`](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2094/commits/708bc3c2d5611ad8465aa4d8d302aabb89dd254c) solved the issue. But execution time is 📈 😬 

| Device | **runInband** | **2 workers** | **3 workers** | **4 workers** | **6 workers** |
|---|---|---|---|---|---|
| **Android** | 15m46s | 8m12s | 11m23s | 4m34s | 4m14s |
| **iOS** | 49m31s | 23m57s | 17m03s | 14m22s | 12m44s |

**Comment by mchowning** [comment]
That's great info @Stojdza ! Thanks for recording that.

Do you have any idea why iOS consistently takes around 3x as long as Android?

**Comment by Stojdza** [comment]
Nope, not really. Looking into video and I can say it's tooooo slow! I will investigate further.

**Pull request closed without merging**
