### PR TITLE
Release 1.53.0

### PR DESCRIPTION
**Pull request by ceyhun**
Release for Gutenberg Mobile 1.53.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/31838
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14650
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16498

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

- [iOS: Fixes frozen editor scrolling in landscape on iPhone](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3504)
- [Add Reusable blocks to the inserter menu](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3054)
- [Merge release 1.52.2 to develop](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3501)
- [Add editor onboarding capability](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3437)
- [Exclude non-native files when extracting localization strings](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3493)
- [Add `enableCaching` param to fetch request on Android](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3419)
- [Generic Embed Block placeholder UI](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3346)
- [Rich text: fix native block implementation](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3477)
- [Bottom-sheet: Limit layout animation to header changes](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3470)
- [Merge release 1.52.1 to develop](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3468)
- [Add missing ToolbarDropdownMenu import](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3464)
- [Fixes color picker segmented control rendering and scrolling issues](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3394)
- [Merge release 1.52.0 to develop](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3446)
- [Merge release 1.42.0 to develop](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3445) 
- [Bottom-sheet: Add custom header](https://github.com/WordPress/gutenberg/pull/30291)

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [ ] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Review by mchowning — APPROVED** [review]

**Comment by antonis** [comment]
## Sanity Tests - Android ([Test Suite 3](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md#test-suite-3))
These were tested on a Pixel 2 XL running Android 11 using the [APK](https://105894-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14650-build-105894.apk) from the [Android PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14650).

### Gallery - 2
- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3
- [ ] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003) ⚠️ [Crash](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3510)
- [ ] Gallery block - Add Gallery Image Caption - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004) ⚠️ [Bug](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3511)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Gallery - 4
- [x] Gallery block - Settings: Link to - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)
- [x] Gallery block - Settings: Column number - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

### Columns - 2
- [x] Columns - Max limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Columnn - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [ ] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is streched to content in nested structure- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### Columns - 4
- [x] Columns - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc018)

### MediaText - 3
- [x] Media Text block - Insert video from device (failing) - [TC001-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [x] Media Text block - Close/Re-open post with an ongoing video upload - [TC003-v](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

### MediaText - 4
- [x] Media Text block - Media & Text alignment - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

### Shortcode-1
- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

### Cover - 2

- [x] Cover - Add Video Background from WordPress Media library - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [x] Cover - Replace media - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient background is rendered properly - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
- [x] Cover - Gradient overlay is rendered properly - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

### Social Icons - 2
- [x] The link sheet is opened automatically when adding new icon - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc004)
- [x] Ghost placeholder is visible when no icon is active - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc005)
- [x] Social icon forwarding to the link - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc006)

### Image - 2
- [ ] Image block - Switch to classic editor with an image block in page - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc006)
- [x] Image block - Border style setting - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc007)
- [x] Image block - Image size setting - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)
- [x] Image block - Link to setting - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc008)

### Story block - 1
- [x] Story block - Verify is available in Block Picker - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc001) ~❓ Story block is **unavailable with Jetpack v9.7**~
- [x] Story block - Verify is not available in Block Picker- [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc002)
- [x] Story block - Add media to empty Story block - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc003)
- [x] Story block - Add media to non-empty Story block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc004)
- [x] Story block - Close/Re-open post with an ongoing Story upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc005)

**Comment by mkevins** [comment]
## :heavy_check_mark: Sanity Tests iOS - [Test Suite 3](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md#test-suite-3)

Tested on an iPhone 11 (14.4.2) with the [CI IPA build](https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/f4a6953e-f5f8-41fd-857c-10daf0fdd54a/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=a3uhlly3XdVtb2%2FEpKiRWOf1zZVHDWxN1L9n7BINaxI%3D&se=2021-05-18T05%3A25%3A36Z&sp=r).

### DarkMode - 2

- [x] Spacer block - Dark mode - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] Buttons block - Dark mode - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] Group - Dark mode - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc006)
- [x] Columns - Dark mode - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

### Group - 2

- [x] Group - Navigation up button works as expected - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [x] Group - Navigation down works according to parent-first approach - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [x] Group - Cross navigation between blocks works as expected - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [x] Group - Ungroup button works as expected - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [x] Group - Check if in DarkMode all components gets proper colors - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [x] Group - Check if nested Placeholder block can be replaced - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

### Spacer - 2

- [x] Spacer block - Settings: Available height range is correct - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [x] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [x] Spacer block - Spacer in horizontal layout works as expected - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

### Buttons - 4

- [x] Buttons block - Render custom text color - [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
- [x] Buttons block - Render custom background color - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
- [x] Buttons block - Render gradient background color - [TC018](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)
- [x] Buttons block - Check if selection / caret color matches font color - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
- [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

### Buttons - 5

- [x] Buttons block - Edit text styles - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
- [x] Buttons block - Render theme colors - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
- [x] Buttons block - Settings: Change Button border radius - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

### Buttons - 7

- [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] Buttons block - Toolbar link button is active when Button has link - [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

### Editor Theme - 2
- [x] Custom Gradients - Check that custom gradients load in the editor - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
- [x] Offline Support - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

### Color Settings - 2
- [x] Pressing color swatch - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
- [x] Customize gradient color - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005)
- [x] Custom color picker - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by ceyhun** [comment]
## Writing Flow checklist - iOS

Testing on an iPhone 11 Pro (iOS 14.4.2) [writing flow cases](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow) with IPA with build number 48096 from https://github.com/wordpress-mobile/WordPress-iOS/pull/16498#issuecomment-841279082:

---

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by AmandaRiu** [comment]
Testing [writing flow cases](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) with the [apk downloaded from WPAndroid release PR (build number 105894) ](https://github.com/wordpress-mobile/WordPress-Android/pull/14650#issuecomment-841332446)

---

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
## 🟡 iOS Unsupported Block Editor Tests (round 1)

* iPhone SE
* iOS 14.4.2
* Build `48096` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16498#issuecomment-841279082.

- [x] TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 - User can discard edits to an unsupported blocks on Simple WP.com sites
- [x] TC003 - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
  🟡 TC004 encountered preexisting https://github.com/wordpress-mobile/gutenberg-mobile/issues/3461. 
- [x] TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 - Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Comment by AmandaRiu** [comment]
## 🟢  Android Unsupported Block Editor Tests (round 1)

* Pixel 4
* Android 11
* Build `105894` from https://github.com/wordpress-mobile/WordPress-Android/pull/14650#issuecomment-841332446.

- [x] TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 - User can discard edits to an unsupported blocks on Simple WP.com sites
- [x] TC003 - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 - Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Pull request merged**
