### PR TITLE
Resolve Text Entry Errors in Alt Text Settings

### PR DESCRIPTION
**Pull request by SiobhyB**
**Fixes:** 

* https://github.com/WordPress/gutenberg/issues/33857
* https://github.com/WordPress/gutenberg/issues/33856
* https://github.com/WordPress/gutenberg/pull/33057#pullrequestreview-725305368

**Gutenberg:**

* https://github.com/WordPress/gutenberg/pull/33975

## Description

Please refer to [the Gutenberg PR](https://github.com/WordPress/gutenberg/pull/33975) as the central, most up-to-date place for a description and testing steps.

<hr />

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by fluiddot — COMMENTED** [review]
I'm wondering why the [`App.js` file](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3818/files#diff-23ef6a1f03378feb6af13d84bc6d33c90b2c939bccffc87f0db0e034f7d825e0) shows that 2,999 lines have been removed 🤔 , could we take a look at this before merging?

Apart from that the changes have been tested and are approved via https://github.com/WordPress/gutenberg/pull/33975#pullrequestreview-745328627.

**Comment by SiobhyB** [comment]
> I'm wondering why the App.js file shows that 2,999 lines have been removed 🤔 , could we take a look at this before merging?

😱 

Thank you for flagging, I believe that was a result of my not updating the bundle after I stopped updating the installable builds for this PR. There must have been some mix-up between that and merge conflicts somewhere down the line.

As changes to the bundle aren't required for this PR, I rewrote the commit history and updated it to only have changes to the Gutenberg reference. 

Let me know if that looks okay to you! 🙇‍♀️

**Comment by fluiddot** [comment]
> > I'm wondering why the App.js file shows that 2,999 lines have been removed 🤔 , could we take a look at this before merging?
> 
> 😱
> 
> Thank you for flagging, I believe that was a result of my not updating the bundle after I stopped updating the installable builds for this PR. There must have been some mix-up between that and merge conflicts somewhere down the line.
> 
> As changes to the bundle aren't required for this PR, I rewrote the commit history and updated it to only have changes to the Gutenberg reference.
> 
> Let me know if that looks okay to you! 🙇‍♀️

Good idea, since the bundle is not required better to revert those changes 👍 .

**Review by fluiddot — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/33975#pullrequestreview-745328627.

**NOTE:** The Gutenberg ref should point to the merge commit in Gutenberg's `trunk` branch before merging this PR.

**Pull request merged**
