### PR TITLE
1.29.0 Release

### PR DESCRIPTION
**Pull request by mchowning**
Release for Gutenberg Mobile v1.29.0

## Related PRs

- Gutenberg: No changes on [`rnmobile/release-1.29.0`](https://github.com/WordPress/gutenberg/tree/rnmobile/release-1.29.0) for a PR yet
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/12033
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14192
- Aztec-iOS: N/A
- Aztec-Android: N/A

## Additional Changes that Landed After the Release Was Cut

- Fix for editing links, that moves the cursor/caret to after the link: https://github.com/WordPress/gutenberg/pull/22652
- Fix for crash on delete of the Media-Text and Contact Info blocks: https://github.com/WordPress/gutenberg/pull/22677
- Add freeform support to the react native editor: https://github.com/WordPress/gutenberg/pull/22609
- 1.28.2 hotfix, Only release Pullquote block on iOS: https://github.com/WordPress/gutenberg/commit/b96445f4c00caff30dfbff2eb897e32f9d54f86f
- Correct button block merge: https://github.com/WordPress/gutenberg/pull/22708#pullrequestreview-420550206
- Fix footer visibility on buttons blocks when deselecting: https://github.com/WordPress/gutenberg/pull/22711
- Fix removal of buttons when removing all buttons: https://github.com/WordPress/gutenberg/pull/22716
- Fix Color updates when changing between solid and gradient colors: https://github.com/WordPress/gutenberg/pull/22736
- Fix: Add default value to format when start and end are undefined: https://github.com/WordPress/gutenberg/pull/22741

### Incoming

- Button Block Fixes
  - Correct concatenation in Button block merge function: https://github.com/WordPress/gutenberg/pull/22708
  - Fix footer appender in buttons block: https://github.com/WordPress/gutenberg/pull/22711
  - Add onDeleteBlock to the extra data to re-render when it has changes: https://github.com/WordPress/gutenberg/pull/22716

## Changes

- Add support for changing overlay color settings in Cover block: https://github.com/WordPress/gutenberg/pull/22207
- Entry/exit animation in FloatingToolbar: https://github.com/WordPress/gutenberg/pull/22146
- Verse Block: https://github.com/WordPress/gutenberg/pull/21883
- Fix merged of text blocks when a style is active: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2271
- Block toolbar can now collapse when the block width is smaller than the toolbar content: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2220
- Trash icon that is used to remove blocks is moved to the new menu reachable via ellipsis button in the block toolbar: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2220
- Creating undo levels less frequently: https://github.com/WordPress/gutenberg/pull/22492
- Tooltip for page template selection buttons: https://github.com/WordPress/gutenberg/pull/21974
- Fix button alignment in page templates and make strings consistent: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2314
- Add support for displaying radial gradients in Buttons and Cover blocks: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2266

## Test plan

1. Use the main WP apps to test the changes above. 
2. Check WPAndroid and WPiOS PRs if there are specific tests to run.
3. Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
4. Verify that the release notes on the WP app PRs have been correctly updated.

## Release Submission Checklist

- [X] Release number was bumped
- [X] Aztec dependencies are pointing to a stable release
  - iOS: 'grep WordPressAztec-iOS RNTAztecView.podspec'
  - Android: 'grep aztecVersion react-native-aztec/android/build.gradle'
- [ ] Gutenberg 'Podfile' and 'Podfile.lock' inside './ios/' are updated to the release number
- [ ] Bundle package of the release is updated 
- [ ] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release

### CODE REVIEW

**Comment by mkevins** [comment]
Sanity tests Android (tested on a Pixel 3a):

Gallery-1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [x] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-3

- [x] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

MediaText-1

- [x] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

MediaText-2

- [x] Media Text block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)


MultipleUpload-1

- [?] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

:question: I'm not seeing the image load from some reason (image block). The url looks correct in html mode, (it begins with `https://`), but it seems the `?w=889` does not work (the image fails to load, even on web). I will reattempt this tomorrow when I finish the other tests, so see if I can reproduce it consistently.

Cover-1

- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

Columns - 1


- [x] Columns - Columns block is added with default number of Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc001)
- [x] Columns - Adding Column with AppenderButton - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


Columns - 2
- [x] Columns - Max limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [ ] Columns - Removing the only one left Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [ ] Columns - Changing alignment on Columns - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [ ] Columns - Changing alignment on individual Columnn - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [ ] Columns - Alignment attribute is properly passed when adding Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [ ] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

Columns - 3

- [ ] Columns - Check if Column placeholders is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [ ] Columns - Appearance in vertical device position (vertical layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [ ] Columns - Appearance in horizontal device position (horizontal layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [ ] Columns - Mover direction - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [ ] Columns - Check if Column placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [ ] Columns - Unselected Column placeholder is streched to content in nested structure- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

**Comment by mkevins** [comment]
While testing Media & Text, I encountered an issue with the following steps:

1. Add a Media & Text block
2. Delete the block
:boom: crash

It seems the crash does not happen if you first focus on the inner paragraph block. Also, if you leave the post, and re-open it before deleting the Media & Text block, the crash does not occur. The crash results in the same exception as this open issue: https://github.com/wordpress-mobile/WordPress-Android/issues/10491. It's possible it's related to a focus / blur issue with the `RichText` in the inner blocks, but we haven't yet narrowed down the root cause.

**Comment by pinarol** [comment]
> I noticed that the placeholder dotted rectangles do not show the nested structure when the none of the blocks in the hierarchy are selected. Is this expected?

That is normal, they are only shown when the parent is selected. 👍

**Comment by lukewalczak** [comment]
### Sanity tests iOS (tested on a iPhone XS):


#### Dark Mode - 1
- [X] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [X] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [X] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

#### Group - 1
- [X] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [X] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [X] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [X] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [X] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [X] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [X] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

#### Spacer-1

- [X] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [X] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [X] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

#### Buttons-1

- [X] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [X] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)

🔴 : Inline appender is still visible when the different block is selected

Screenshot 2020-05-28 at 13 07 45

- [X] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)

#### Buttons-2

- [X] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)

🔴 : Removing container doesn't work if you add more than one Button and then you are removing one after the other

bugg_one


- [X] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

🔴 : Once removing the text from second Button on build app getting `undefined` in the previous button / on develop there is crash

bug_two

#### Buttons-3

- [X] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [X] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

#### Button-6

- [ ] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [ ] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [ ] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [ ] Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [ ] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

**Comment by etoledom** [comment]
>  I'm not seeing the image load from some reason (image block). The url looks correct in html mode, (it begins with https://), but it seems the ?w=889 does not work (the image fails to load, even on web). I will reattempt this tomorrow when I finish the other tests, so see if I can reproduce it consistently.

This seems to be a problem with Photon with that specific image.

I was able to reproduce the issue using the [provided image](https://upload.wikimedia.org/wikipedia/commons/b/ba/Trupial_on_a_cactus.png), uploading it directly to the WP Media Library (not related to gutenberg).
The image is uploaded successfully but trying to fetch it with the Photon query elements it fails. This seems to be a bug since the image is less than 10MB.

[https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus-2.png](https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus-2.png)

[https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus-2.png?w=400](https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus-2.png?w=400)

Then, using the same image, I exported it to PNG using the MacOS Preview app, and uploaded it again. This one is working just fine:

[https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus_png2.png?w=400](https://mysitefortestingetoledom.files.wordpress.com/2020/05/trupial_on_a_cactus_png2.png?w=400)

So:
- I don’t think it’s a blocker
- The issue seems to be external to gutenberg (Jetpack/Photon)
- It might not be happening too often, just special scenarios with these kind of breaking images. (Doesn’t happen with all heavy images nor all png images).

**Comment by SergioEstevao** [comment]
Testing in iOS the

**Writing Flow** checklist:

- [ ] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text format

**Comment by mchowning** [comment]
Testing **Writing Flow** on Android:

- [ ] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text format

**Comment by mchowning** [comment]
I'm seeing a regression with image and video block captions where the formatting buttons do not update when the caption is initially selected. 

I have reproduced this on both iOS and Android. I do not see this issue with other rich text blocks. I cannot reproduce this with the current 14.9 alpha-224 release, so I believe this is a regression.

#### Steps to Reproduce
1. Create a new image/video block with an image/video so the caption can be selected
2. Select the caption
3. Activate the bold, italic, or strikethrough formatting buttons
4. **Observe that the format button's state does _not_ update**
5. Begin typing text
6. **Observe that after the first character, the formatting buttons update their state, and all the text _after the first character_ has the formatting applied**

image_caption_formatting_issue mp4

**Comment by guarani** [comment]
Testing the **Writing Flow** checklist (Android):

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

#### Comments
- The new remove block bottom sheet is doesn't respond well to changes to light/dark mode unless you exit the editor and open it again
- If text is deleted and then then undo is pressed, the cursor goes to the second last position instead of the last

**Comment by mchowning** [comment]
Retested the Writing Flow on iOS. Only found one small non-blocking issue (addressed in separate comment below).

**Writing Flow** checklist:

- [X] TC001 - Block insertion flow 
- [X] TC001 - Paste formatted text copied from website
- [X] TC001 - Multiline components
- [X] Rich Text Format
  - [X] TC001 - Bold, Italic, strikethrough buttons
  - [X] TC002 - Alignment buttons
  - [X] TC003 - Alignment Split
  - [X] TC004 - Link button works without selection
  - [X] TC005 - Link button works with a selected word
  - [X] TC006 - Adding a link from a copied URL
  - [X] TC007 - Test format detection under the cursor
  - [X] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [X] Splitting and merging
  - [X] TC001 - Merge after writing
  - [X] TC002 - Merge after selection
  - [X] TC003 - Merge after deleting text
  - [X] TC004 - Merge after deleting all
  - [X] TC005 - Merge multiple blocks
  - [X] TC006 - Splitting/merge list block
- [X] Undo / Redo - Test Cases
  - [X] TC001 - Undo/redo block actions
  - [X] TC002 - Undo/redo text
  - [X] TC003 - Undo/redo text format

**Pull request merged**
