### PR TITLE
Update Gutenberg ref to point to text-clipping fix attempt

### LINKED ISSUE #2136: [GlobalStep] Android – The last word on Media Blocks is seen to be missing.
### Description
When adding a Media Block, the messages “Add Image”, “Add Video” or “Add Image or Video” can be read. However, it was observed that on certain devices this message was trimmed and missing the last word of the sentence.
This issue was also tested on Samsung Galaxy S8+ (8.0) but not seen to occur.

### Reproduction Rate
4/4 100%

### Expected behaviour
The whole message should be displayed without issues.

### Actual behaviour
The message of Media Blocks was seen constantly missing its last word.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Create a new Post.
4. Add any Media Block.
##### Tested on the following
One Plus 6 (9.0)

### Submitted by:
Luis Pimenta

### PR DESCRIPTION
**Pull request by hypest**
Fixes #2136 

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/21532
WPAndroid PR to produce an instalable APK: https://github.com/wordpress-mobile/WordPress-Android/pull/11641

To test:
1. If using a device that didn't experience the issue, nothing should change
2. On a device that experiences the issue, the media placeholder link text will hopefully not get clipped. Try adding a Media&Text block to verify.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary. Comment: this fix is quite device specific and for an issue that's not too disruptive that, I don't think we need a release note entry.

### CODE REVIEW

**Comment by hypest** [comment]
👋 @wptester9845, I wonder if you have the opportunity to try https://github.com/wordpress-mobile/WordPress-Android/pull/11641#issuecomment-612068707 that includes this potential fix, on the device that you reported the original issue. Thanks in advance!

**Comment by hypest** [comment]
We got back feedback from GlobalStep that this does fix the issue so, we should go ahead and update and move this PR forward.

**Comment by hypest** [comment]
👋 @cameronvoell , can I bug you to adopt/own this PR set? At this stage it only needs updating and should be good to go. There's no special testing to be done (besides smoke testing) unless you have access to an Opus device to test. Thanks!

**Comment by cameronvoell** [comment]
> 👋 @cameronvoell , can I bug you to adopt/own this PR set?

@hypest Yep, will do! Sorry missed the mention end of last week, I'll take care of this

**Pull request merged**
