### PR TITLE
Audio & Video block - Autoplay BottomSheet Cell help support

### LINKED ISSUE #3169: Add help behavior to the SwitchCell component
## Description

The `help` behavior should be added to the `SwitchCell` component. The use case for this at the moment is with the Video & Audio Block that requires the user to be informed about the usability implications that will be experienced by users if the `autoplay` attribute is enabled on the block in question. 

### Web
autoplay

### Mobile
Image from iOS

The proposed option is # 1  based on design specs below by @iamthomasbishop 

- In-cell subtitles are meant for short labels. 
- Footnotes can get quite long as well, so it's best to utilize them without a divider.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #3169
`Gutenberg PR` https://github.com/WordPress/gutenberg/pull/30885
To test:
Visit https://github.com/WordPress/gutenberg/pull/30885
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Hey @jd-alexander. 👋🏻 We will cut the 1.52.0 release Friday 30 April. I plan to circle back and bump this PR to the next milestone (1.53.0) on Friday, but please let me know if you'd rather us work to include this PR in 1.52.0. Thanks! 🙇

**Review by AmandaRiu — APPROVED** [review]
Approved in the gutenberg PR. :shipit:

**Comment by ceyhun** [comment]
Hey there @jd-alexander 👋 We'll be cutting the 1.53.0 release some time soon today. I'm bumping this PR to 1.54.0 milestone, please let us know if it needs to make it into 1.53.0 instead.

**Comment by jd-alexander** [comment]
> Hey there @jd-alexander 👋 We'll be cutting the 1.53.0 release some time soon today. I'm bumping this PR to 1.54.0 milestone, please let us know if it needs to make it into 1.53.0 instead.

Thanks @ceyhun I was trying to merge it last night but the admin tests on Gutenberg kept failing. Is it too late to include it now?

**Comment by jd-alexander** [comment]
@ceyhun since the release has been cut this can wait until 1.54.0.

**Comment by hypest** [comment]
I [admin-merged the Gutenberg PR](https://github.com/WordPress/gutenberg/pull/30885#issuecomment-842939648) and went ahead and updated this PR as well. Since it's LGTM'd already, I'll have it auto-merge on CI green 👍.

**Comment by fluiddot** [comment]
Heads up that this PR has modified the Jetpack reference to an older commit: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3380/files#diff-2c96c4dc757597cce968020825526dcad5205b57ef92cad5215e587fa9722627

Screenshot 2021-05-18 at 18 39 24

**Comment by jd-alexander** [comment]
> Heads up that this PR has modified the Jetpack reference to an older commit: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3380/files#diff-2c96c4dc757597cce968020825526dcad5205b57ef92cad5215e587fa9722627
> 
> 
> 
> Screenshot 2021-05-18 at 18 39 24
> 
> 

Thanks. I will fix this. It's the tool I use Gitkraken that modifies the jetpack reference when I use it so I normally check before merging and revert. I will open an issue with them. 🙏🏾

**Comment by fluiddot** [comment]
>Thanks. I will fix this. It's the tool I use Gitkraken that modifies the jetpack reference when I use it so I normally check before merging and revert. I will open an issue with them. 🙏🏾

I use [Fork](https://git-fork.com/) and it does the same thing with the submodule references, in my case I always discard the changes when switching branches to prevent this issue.

**Comment by hypest** [comment]
> Heads up that this PR has modified the Jetpack reference to an older commit

Ouch, sorry, didn't catch the Jetpack ref change myself either while looking at the diff 😢

**Pull request merged**
