### PR TITLE
Bump SauceLabs caps

### PR DESCRIPTION
**Pull request by hypest**
Bumping the Appium and iOS versions used on SauceLabs, in an attempt to improve test reliability.

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/33757

To test:
Unfortunately, nothing special to test other than noticing the CI jobs to be green. Ideally we want to have less flakiness in the tests but the change here is not particularly promising for that anyway.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
First real run of the tests on SauceLabs were green 🟢. Will restart the jobs a few times to see what's the success rate for the device tests.

Run # | Android result | iOS result
-|-|-
1st | 🟢 | 🟢
2nd | 🔴 2 Android device canaries tests [failed with wrong assertions](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/13313/workflows/8f7b9fa1-70e6-462f-a221-ebdda5e01cc1/jobs/72494/steps) | 🟢
3rd | 🟢 | 🔴 on iOS with [[quit()] Unexpected data in simpleCallback](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/13313/workflows/7a1674e9-3849-4510-8a10-afe6c040acef/jobs/72505?invite=true#step-116-75). Here's the [video of the run](https://app.saucelabs.com/tests/efa777e990cb4e03ba509edf5fc65067?auth=e3557da072714df2a6aeb99df1687a26), can't really tell what's going wrong.
4th | 🟢 | 🟢
5th | 🟢 | 🟢

**Comment by mchowning** [comment]
Rerunning "Test iOS on Device - Full", which failed.

**Comment by mchowning** [comment]
Failed again. 😞  Rerunning again.

<details><summary>Test failures</summary>

image

</details>

**Review by mchowning — APPROVED** [review]
Gutenberg changes look good! 👍

**Pull request merged**
