### PR TITLE
Enable Cover Block for Production

### PR DESCRIPTION
**Pull request by geriux**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2005 and also fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2052

`Gutenberg PR` -> https://github.com/WordPress/gutenberg/pull/20992

To test check Gutenberg PR description

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by geriux** [comment]
Hey @iamthomasbishop ! Here's the cover build for you to test when you have some time, you can check these [test cases](https://github.com/wordpress-mobile/test-cases/blob/3dd8fd689730ef90e7281d6731a6493a33faf9ff/test-cases/gutenberg/cover.md) of the functionality we have so far.

`WordPress iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13678
`WordPress Android` -> https://github.com/wordpress-mobile/WordPress-Android/pull/11462

**Comment by iamthomasbishop** [comment]
Great work overall! Most of the test scenarios worked as expected, I just have a few bits of feedback:

* Semi-transparent gradient overlays created on the web don’t seem to respect the opacity value. For example, if you set a gradient overlay with a certain opacity %, it’s still shown at 100%. [Example](https://user-images.githubusercontent.com/1200432/77235050-ab2c1400-6b80-11ea-9cd7-d5890fcab02e.jpeg)
* This might have been intentionally excluded, but we might want to consider supporting background colors/gradients of blocks _inside_ the cover block. For example, I created a paragraph block inside the cover and applied a background to see [this on desktop web](https://user-images.githubusercontent.com/1200432/77235146-6a80ca80-6b81-11ea-9253-f3f12c2fab3a.jpeg), versus [this on mobile](https://user-images.githubusercontent.com/1200432/77235205-d9f6ba00-6b81-11ea-9aa3-b9bf28e4c68b.jpeg).

Head’s up: We’ll soon be able to utilize the [color picker](https://github.com/wordpress-mobile/WordPress-iOS/pull/13690) in mobile, so perhaps we can consider adding that in the next iteration of the cover block via block settings? 😄 // cc @lukewalczak

**Comment by geriux** [comment]
> Great work overall! Most of the test scenarios worked as expected, I just have a few bits of feedback:

Thanks for testing!

>Semi-transparent gradient overlays created on the web don’t seem to respect the opacity value. For example, if you set a gradient overlay with a certain opacity %, it’s still shown at 100%. Example

By semi-transparent, you mean using the alpha values? If it is that, I tried changing those values and it works so maybe it's something else?

#### Web

Screenshot 2020-03-23 at 11 12 02

#### Mobile

Screenshot 2020-03-23 at 11 12 29

> This might have been intentionally excluded, but we might want to consider supporting background colors/gradients of blocks inside the cover block. For example, I created a paragraph block inside the cover and applied a background to see this on desktop web, versus this on mobile.

Not really 😅these settings are per block basis so we'd need to modify each block that has support for color / background styles. In this case, we'd need to update the `Paragraph` block to support background styles.

>Head’s up: We’ll soon be able to utilize the color picker in mobile, so perhaps we can consider adding that in the next iteration of the cover block via block settings?

Yay! Can't wait to have that in the next iterations of Cover.

**Comment by iamthomasbishop** [comment]
> By semi-transparent, you mean using the alpha values? If it is that, I tried changing those values and it works so maybe it's something else?

Correct, I did mean alpha, sorry I didn't explain very clearly. Here's what I'm seeing. If you have a background-image _and_ a gradient overlay (at any opacity), the overlay becomes 100% opaque regardless of what the opacity setting is set to. For example, here is the same block on web vs. mobile:

**Web**

<a href="https://user-images.githubusercontent.com/1200432/77332772-7b9c1980-6cf0-11ea-9094-75a0cb1a47e9.png"></a>

**Mobile**

<a href="https://user-images.githubusercontent.com/1200432/77332939-b56d2000-6cf0-11ea-9445-5b514491e173.jpeg"></a>

Hope that helps clarify.

> these settings are per block basis so we'd need to modify each block that has support for color / background styles. In this case, we'd need to update the Paragraph block to support background styles.

Ah, of course, that makes sense, we can tackle that separately.

> Yay! Can't wait to have that in the next iterations of Cover.

🙌 🎉

**Comment by geriux** [comment]
> Correct, I did mean alpha, sorry I didn't explain very clearly. Here's what I'm seeing. If you have a background-image _and_ a gradient overlay (at any opacity), the overlay becomes 100% opaque regardless of what the opacity setting is set to. For example, here is the same block on web vs. mobile:

Ahh I get it now 😅so we haven't added that functionality to set a gradient as an overlay, there's an [open issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1737) but work on it hasn't started yet. That's why you're only seeing the gradient as a background. Maybe @pinarol can tell us about the priority of that one.

**Comment by pinarol** [comment]
@geriux Actually that open issue is for making the gradient settings available in mobile. I was already assuming that we are rendering the alpha level of gradient overlay correctly in this iteration. Can we make that happen? I can help where needed. It would look like a bug as is.

**Comment by iamthomasbishop** [comment]
> we haven't added that functionality to set a gradient as an overlay

Ah ok. I understand not giving the user the ability to set the gradient as an overlay from the mobile editor because we aren't quite ready in terms of color picking/customization, but we should definitely support gradients over the top of images at any user-configured opacity value. It might not be the highest priority thing, but it was confusing to me. It could be a fairly rare use case, so perhaps it's not the highest priority, just wanted to mention it.

**Comment by geriux** [comment]
> @geriux Actually that open issue is for making the gradient settings available in mobile. I was already assuming that we are rendering the alpha level of gradient overlay correctly in this iteration. Can we make that happen? I can help where needed. It would look like a bug as is.

Yeah we are not supporting it yet (as an overlay) since the work done was just to add [them as backgrounds](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1860), I guess it was just a misunderstanding of the task 😅

We can make it happen of course, I was already reviewing what we would need to change so I can work on that tomorrow and put it up for review =)

**Comment by pinarol** [comment]
Technically i was assuming the background and overlay would correspond to the same thing. I wasn’t expecting we’d need to do a separate implementation for overlay. If we put the image at the bottom and put the gradient layer on top of it, it should act as a background when there’s no image. But I might be missing something.

**Comment by iamthomasbishop** [comment]
That's what I was also thinking, @pinarol. I figured the gradient would be a layer with a higher z-index than the background image. This would make both optional and allow them to work in tandem.

**Comment by geriux** [comment]
> Technically i was assuming the background and overlay would correspond to the same thing. I wasn’t expecting we’d need to do a separate implementation for overlay. If we put the image at the bottom and put the gradient layer on top of it, it should act as a background when there’s no image. But I might be missing something.

Yeah, there's no much change technically. I just thought the issue was just for that hence me reviewing the PR and not requesting the overlay. But don't worry I'll have it done by today =)

**Comment by geriux** [comment]
Hey all 👋 changes are done.

This is how it's looking now:

Kapture 2020-03-24 at 9 48 43

I've made a new build for you to test [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/13678#issuecomment-600724410).

Thanks for the feedback!

**Comment by pinarol** [comment]
Wow that was quick 👏 Thank you very much @geriux !

**Comment by chipsnyder** [comment]
@geriux Running the app through metro I'm getting a red screen for one of the block configurations I have set up.

This seems to only happen on one of my blocks so far. Here are the settings I used:
- Cover Block with Image from Media Library.
- Changed the Pixel height in the editor.
- Set a new Focal point
- Overlay with a custom color `#e75548` 
- Adjusted Opacity
- Holds a simple paragraph block with text

Here's the generated block code:
```
<!-- wp:cover {"url":"https://testeisbardev.files.wordpress.com/2020/03/wp-1585058723419.jpg","id":310,"dimRatio":67,"customOverlayColor":"#e75548","focalPoint":{"x":"0.00","y":"0.99"},"minHeight":229} -->
<div class="wp-block-cover has-background-dim-70 has-background-dim" style="background-image:url(https://testeisbardev.files.wordpress.com/2020/03/wp-1585058723419.jpg);background-color:#e75548;background-position:0% 99%;min-height:229px"><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…"} -->
<p class="has-text-align-center">Nessie Custom Color Moved Focal</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->
```


Red Screen:
screenshot-1585060269067

**Comment by chipsnyder** [comment]
Walking through those settings it seems like Focal point seems to be causing the issue

**Comment by geriux** [comment]
> Walking through those settings it seems like Focal point seems to be causing the issue

Thanks Chip! I'll check it out

**Comment by geriux** [comment]
> > Walking through those settings it seems like Focal point seems to be causing the issue
> 
> Thanks Chip! I'll check it out

@chipsnyder So I can't seem to be able to reproduce this, can you please try the builds I made? Thanks!

**Comment by chipsnyder** [comment]
>can you please try the builds I made? 

Using the builds iOS worked fine but I got the same error in Android.

**Comment by iamthomasbishop** [comment]
>  changes are done.

Awesome work! Looks great. I haven't had a chance to test a build yet, but I will check for an update.

**Comment by iamthomasbishop** [comment]
Had a chance to check out the test build — looks great @geriux! 👍

**Comment by mkevins** [comment]
> Using the builds iOS worked fine but I got the same error in Android on a Pixel 3a running API 29 if that becomes important

@chipsnyder I encountered the same or similar validation red screen at one point, on Android Pixel 3a as well, but after reinstalling the app, I couldn't reproduce it, and haven't seen it since - just wanted to note this here, to confirm I also encountered it.

**Comment by mkevins** [comment]
Hi @geriux :wave: Very nice work on this block. This is looking really nice!

I tested out via the test cases, and it's mostly working, with a few issues (TC005 - Android, TC006):


- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc001)
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc002)
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc003)
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc004)
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc007)
- [x] [TC008](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc008)
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc009)
---
- [ ] [TC005](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc005)

For this test case, on iOS everything worked as expected (no sound :mute:), but on Android, the sound :loud_sound:  was turned on during video playback.

---
- [ ] [TC006](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc006)

For this test case, things mostly worked as expected, but I encountered an issue with aspect ratio in certain scenarios. Steps:

1. Create a cover block on web
2. Add an image from the library (choose either a portrait or a landscape image)
3. Add an overlay color
4. Add a focal point
5. Save the post
6. Open the post in the mobile app
7. Tap the background image
8. Tap the replace media icon
9. Select from media library
10. Pick an image with an aspect ratio different from earlier (if portrait, chose a landscape image, etc.)
11. :boom: Observe the image is rendered with a distorted aspect ratio
12. Save and close the post
13. Re-open the post
14. :heavy_check_mark: Observe the image is rendered with the correct aspect ratio again

#### Screenshots

Step 4 | Step 11 | Step 14
-|-|-
cover-overlay-aspect-bug-1|cover-overlay-aspect-bug-2|cover-overlay-aspect-bug-3

I'm not certain whether both steps 3 and 4 are necessary to reproduce this, but I did not encounter the issue when I tried to reproduce it omitting _both_ of those steps.

**Comment by geriux** [comment]
Hey @mkevins ! Thanks for testing and the feedback 😃

>For this test case, on iOS everything worked as expected (no sound 🔇), but on Android, the sound 🔊 was turned on during video playback.

I was trying this one and I can't reproduce it. Were you testing the build from the WordPress Android PR? Which device were you using?

Did it happen in different scenarios? Adding the block from mobile, opening a post?

**Comment by geriux** [comment]
>💥 Observe the image is rendered with a distorted aspect ratio

Regarding this issue, it is solved now =D thanks for spotting that! 

Here are the new builds.

`WordPress-iOS` -> https://github.com/wordpress-mobile/WordPress-iOS/pull/13678#issuecomment-600724410
`WordPress-Android` -> build in progress

**Comment by chipsnyder** [comment]
Tested on iOS with this [build](https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/7c7f5480-656b-4578-b423-36a129af85b4/WordPress%20Alpha.ipa?sv=2018-03-28&sr=c&sig=jqYS7ah2p9wI8cvLx1RmN9%2Bs3k%2FPEIW5eFqSSYUgY%2BI%3D&se=2020-03-26T17%3A51%3A22Z&sp=r)
And on Android with this [build](https://42378-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11462-build-42378.apk)

I was able to see my block without the focal point error once but after that I got the error parsing block message. I see you opened an issue for that though.

Going through the [test cases](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md) it looks pretty solid. I only had one issue/question:
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc001)
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc002)
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc003)
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc004)
- ❓[TC005](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc005)
    - ❓This just showed a gray screen for me with MOV and MP4 files. 
    - I validated the videos via the Video Block as well and they showed the thumbnail there. 
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc006)
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc007)
- [x] [TC008](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc008)
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc009)

**Comment by mkevins** [comment]
> Hey @mkevins ! Thanks for testing and the feedback 
> 
> > For this test case, on iOS everything worked as expected (no sound :mute:), but on Android, the sound :loud_sound: was turned on during video playback.
> 
> I was trying this one and I can't reproduce it. Were you testing the build from the WordPress Android PR? Which device were you using?
> 
> Did it happen in different scenarios? Adding the block from mobile, opening a post?

This occurred in two different scenarios:
* Adding a video from media library on web (and opening that post on the app)
* Adding a captured video directly from the app

I encountered this on Android Pixel 3a (real device), via WordPress-Android `develop` and with metro on. I did not attempt to reproduce with the peril apk.

**Comment by geriux** [comment]
Hey @chipsnyder thanks for testing again!

> ❓[TC005](https://github.com/wordpress-mobile/test-cases/blob/f6ace43a5b31618ca26254c4e610317747cb87ed/test-cases/gutenberg/cover.md#tc005)
>   
>   * ❓This just showed a gray screen for me with MOV and MP4 files.
>   * I validated the videos via the Video Block as well and they showed the thumbnail there.

What do you mean with a gray screen? Missing thumbnail? Was this video already in your WordPress media library? Was this on Android? iOS? both?

**Comment by geriux** [comment]
Hey @mkevins thanks for testing again!

> I encountered this on Android Pixel 3a (real device), via WordPress-Android develop and with metro on. I did not attempt to reproduce with the peril apk.

Since we are enabling this for production, could you please test the peril build instead of running metro on develop? 

Also discussed this with @pinarol if that still happens to you (video with sound) we can keep iterating on it after releasing. Video usage is not that high and it wouldn't be a blocker to release the Cover block. 😃 Same as the focal point issue cc @chipsnyder.

Thank you both for testing this! 🙌

**Comment by chipsnyder** [comment]
@geriux 

>What do you mean with a gray screen? Missing thumbnail? Was this video already in your WordPress media library? Was this on Android? iOS? both?

I'm seeing this on both iOS and Android:


**iOS:** iPhone 11, OS 13.3
**Android:** Pixel 3a, API 29

I tested by:
- Adding Videos on the web, switch to the app and add the video to the cover block
- Taking a new video in the app via a video block, add the video to the cover block
- Upload a video via the media tab, add the video to the cover block.

Testing more this morning though these might be unrelated issues. The videos I took on Android are no longer playing in the Video block.

**Comment by geriux** [comment]
> Testing more this morning though these might be unrelated issues. The videos I took on Android are no longer playing in the Video block.

Hmm looks like it's taking it a bit to process the video/thumbnail. But yeah definitely not related to the block itself.

**Comment by chipsnyder** [comment]
> Hmm looks like it's taking it a bit to process the video/thumbnail. But yeah definitely not related to the block itself.

I assumed it was probably something with my videos. Thanks for confirming :) I'll mess with it and open a different issue

**Comment by pinarol** [comment]
I downloaded the apk and tried with my Huawei p20 lite, Android 9.0. I was able to successfully add a video background with a device recorded video. And the sound was muted as expected.

The video player library we have on react native has some intermittent issues about inline video playing and video previews. That was one of the reasons we wanted to defer the playing to browser/external app on Android for Video block. Cover block video backgrounds are quite rare, thus I am not that worried about it. Even if there's something to fix, it needs to be done in library level so let's try to [report](https://github.com/react-native-community/react-native-video/issues) if we can detect sth reproducible. We can also try updating the lib, we are using 4.4.1 and 4.4.5 seems available, although, couldn't see anything related in the release logs.

**Comment by chipsnyder** [comment]
> I was able to successfully add a video background with a device recorded video. And the sound was muted as expected.

Awesome thank you for testing this! 

> The video player library we have on react native has some intermittent issues about inline video playing and video previews.

This is great background thanks!

**Comment by geriux** [comment]
> I just retested with [this apk](https://42378-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11462-build-42378.apk), and the Video is now muted 🔇 🎉 .
> 
> I also tested this again, and [this commit](https://github.com/WordPress/gutenberg/pull/20992/commits/9319533d9eb118679ab869f0a6baf3219a150866) seems to have fixed the aspect ratio issue.

Yay! Thank you so much for testing!!

**Pull request merged**
