### PR TITLE
Release 1.99.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.99.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/52611
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/18772
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/21098

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Fix crash related to removing a block under certain conditions
- **PR:** https://github.com/WordPress/gutenberg/pull/52595
- **Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/5925

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
## 🟢   Writing Flow (iOS)
**Build**: [pr21098-f41da0d](https://github.com/wordpress-mobile/WordPress-iOS/pull/21098#issuecomment-1634726472)
**Device**: iPhone 11 (iOS 15.4.1)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md#tc001) - Multiline components
  - [ ] Quote block
  - [ ] Verse block
  - [ ] Preformatted block
  - [ ] Code block (DEV only)
  - [ ] Pullquote block
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [ ] Paragraph
  - [ ] Heading
#### Undo / Redo - Test Cases
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/undo-redo.md#tc002) - Undo/redo text

**Comment by fluiddot** [comment]
## 🟢  Release Changes (iOS)
**Build**: [pr21098-f41da0d](https://github.com/wordpress-mobile/WordPress-iOS/pull/21098#issuecomment-1634726472)
**Device**: iPhone 11 (iOS 15.4.1)

- [x] [Fix crash related to removing a block under certain conditions](https://github.com/WordPress/gutenberg/pull/52595)

**Comment by fluiddot** [comment]
## 🟢   Writing Flow (Android)
**Build**: [pr18772-dd0a7f6](https://github.com/wordpress-mobile/WordPress-Android/pull/18772#issuecomment-1634656303)
**Device**: Samsung Galaxy S20 FE 5G (Android 13)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/multiline-components.md#tc001) - Multiline components
  - [ ] Quote block
  - [ ] Verse block
  - [ ] Preformatted block
  - [ ] Code block (DEV only)
  - [ ] Pullquote block
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
    - ⚠️ I experienced the known issue: https://github.com/WordPress/gutenberg/issues/41406
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [ ] Paragraph
  - [ ] Heading
#### Undo / Redo - Test Cases
- [ ] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/undo-redo.md#tc002) - Undo/redo text

**Comment by fluiddot** [comment]
## 🟢  Release Changes (Android)
**Build**: [pr18772-dd0a7f6](https://github.com/wordpress-mobile/WordPress-Android/pull/18772#issuecomment-1634656303)
**Device**: Samsung Galaxy S20 FE 5G (Android 13)

- [x] [Fix crash related to removing a block under certain conditions](https://github.com/WordPress/gutenberg/pull/52595)
**NOTE:** This crash couldn't be reproduced on Android.

**Review by SiobhyB — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/52611#pullrequestreview-1529962976

Note: I've re-run the failed iOS test on this PR, as it looks to have failed due to flakiness.

**Comment by fluiddot** [comment]
The recent failure in the CI job `Check Correctness` will be fixed via https://github.com/wordpress-mobile/gutenberg-mobile/pull/5967. In the meantime, I cherry-picked the fix (https://github.com/wordpress-mobile/gutenberg-mobile/pull/5962/commits/827b8cff2923a5516a6dc6347e5a03b32ed0c462) to confirm it addresses the failure.

**Pull request merged**
