### PR TITLE
Add block inserter onboarding tooltip

### LINKED ISSUE #30624: Add “Tap to add content” tooltip for editor Onboarding Tour
## What problem does this address?
The mobile editor is a powerful tool for creating content, but many users fail to understand the extent of what they can do with it. Specifically, users sometimes do not understand additional blocks may be added to the editor content. 

## What is your proposed solution?
We will add a tooltip indicating how additional blocks can be added to the editor content. The tooltip should be dismissed when the user interacts with _any_ UI displayed on the screen. Once dismissed, the tooltip should not be displayed again. 

Mobile editor insert block tip

### PR DESCRIPTION
**Pull request by dcalhoun**
* **Gutenberg:** https://github.com/WordPress/gutenberg/pull/32001
* **Gutenberg 2:** https://github.com/WordPress/gutenberg/pull/32289
* **WordPress iOS:** https://github.com/wordpress-mobile/WordPress-iOS/pull/16537
* **WordPress Android:** https://github.com/wordpress-mobile/WordPress-Android/pull/14683

Fixes https://github.com/WordPress/gutenberg/issues/30624. Add tooltip for the block inserter as a part of a larger editor onboarding experience.

To test: See test plan within https://github.com/WordPress/gutenberg/pull/32001.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by jhnstn — APPROVED** [review]
Corresponding Gutenberg PR Approved.

**Comment by geriux** [comment]
Hey @dcalhoun 👋 Looks like some of the slash inserter tests are not passing with these changes, could you please check them out? Thanks!

**Comment by dcalhoun** [comment]
> Hey @dcalhoun 👋 Looks like some of the slash inserter tests are not passing with these changes, could you please check them out? Thanks!

@geriux they appeared to be the same two tests that were failing inconsistently for others as well. I ran them locally and they passed, so I'm not sure if it's a valid failure or flakiness at this time. I have rerun them multiple times on the PR with no success. I will take a deeper look in a couple of hours when I come online for the day. 👍🏻

**Comment by geriux** [comment]
> @geriux they appeared to be the same two tests that were failing inconsistently for others as well. I ran them locally and they passed, so I'm not sure if it's a valid failure or flakiness at this time. I have rerun them multiple times on the PR with no success. I will take a deeper look in a couple of hours when I come online for the day. 👍🏻

I'll double check too 👍

**Comment by jhnstn** [comment]
Hey @dcalhoun . We will cut the 1.54.0 release later today. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.54.0. Thanks!

**Pull request merged**
