### PR TITLE
Merge from master - 2019/05/20

### PR DESCRIPTION
**Pull request by hypest**
This PR bring in all latest releases from master, including updating to latest Gutenberg master.

To test:
App should run as normal

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by koke** [comment]
> Submodule gutenberg updated from d08dcd to d2a164

When I look at develop, I see gutenberg is at 6cb4c4da1, which is two commits ahead of d2a164beb. Perhaps it's a bad merge?

**Comment by hypest** [comment]
I guess that's because https://github.com/wordpress-mobile/gutenberg-mobile/pull/919 got merged @koke ? I will do another update to bring this PR up to date.

**Comment by hypest** [comment]
At this point, the only meaningful change in this PR is the bump in the main version name. That's quite trivial on its own so, perhaps this an easy PR to merge at this point @koke , wdyt?

**Comment by hypest** [comment]
We don't normally use the bundles off `develop` but, I will update from develop, create new bundles, push them and merge this PR just so the merged bundles are indeed corresponding to the rest of the code 👍 .

**Pull request merged**
