### PR TITLE
Feature/1675 dark mode android integration

### PR DESCRIPTION
**Pull request by marecar3**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1675

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/21139
WordPress-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11498

ezgif com-video-to-gif (13)

To test:

On devices with API <=28:
1. Open App Settings from Me screen.
2. Notice the App Theme preference.
3. The default value should be set to `Set by Battery Saver`.
4. From the preference, dialog select `Dark` and confirm that the app switches to Dark Theme.
5. Open the Gutenberg Editor and confirm that it has Dark Theme
6. Select `Light` and confirm that the app switches to Light Theme.
7. Open the Gutenberg Editor and confirm that it has Light Theme
8. Select `Set by Battery Saver` and enable Battery Saver on the device.
9. Confirm that Dark Theme is used when Battery Saver is ON.

On devices with API 29+:
1. Open App Settings from Me screen.
2. Notice the App Theme preference.
3. The default value should be set to `System Default`.
4. From the preference, dialog select `Dark` and confirm that the app switches to Dark Theme.
5. Open the Gutenberg Editor and confirm that it has Dark Theme
6. Select `Light` and confirm that the app switches to Light Theme.
7. Open the Gutenberg Editor and confirm that it has Light Theme
8. Select `System Default` and close the app.
9. Enable Dark Theme in Display settings of the device.
10. Launch the app again and confirm that the dark theme is applied.

Note for API 29+: At this moment we aren't able to get the app theme to switch automatically when the Dark Theme is toggled. For now, you need to restart the app for new theme to take effect. @khaykov has created a separate issue for this at https://github.com/wordpress-mobile/WordPress-Android/issues/10748

PR submission checklist:

- [ ] replace "future release" in release notes with some version
- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
Marking this one with **DO NOT MERGE** flag until we don't resolve this blocker: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2056

**Comment by SergioEstevao** [comment]
@marecar3  I'm moving this to 1.26, feel free to move it back to 1.25 if this is something that can be considered a regression.

**Comment by hypest** [comment]
We'll try to target 1.25 with this after all so, changing the milestone accordingly.

**Comment by marecar3** [comment]
Closing in favor: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2098

**Pull request closed without merging**
