### PR TITLE
Do not embed Hermes in the Gutenberg XCFramework. Add to distribution archive instead.

### PR DESCRIPTION
**Pull request by mokagio**
A different approach to the problem https://github.com/wordpress-mobile/gutenberg-mobile/pull/5968 tries to solve.

Under the assumption this approach works, I believe it's simpler than the alternative because it avoids embedding in the first place.

---

- Builds in CI.
- I run WordPress on my machine on device pointing to this podspec and didn't experience a crash.
- Verify whether it builds in CI on the WordPress side (yes) and if the UI test pass (they don't, [but neither do they in the other setup, FWIW](https://buildkite.com/automattic/wordpress-ios/builds/15558#018967ec-8d3b-4062-91b2-dcb1b2416c05)) – See https://github.com/wordpress-mobile/WordPress-iOS/pull/21128
- Check the `otool -L` result in the same way that was done [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5968#discussion_r1266405039) – See below
- [Removed the Catalyst slice](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5973/commits/9fb9062b05419309a86ebc07444039ffcc4233f0)
- I had some doubts about the downstream effects of shipping the 500MB worth of Hermes XCFramework as part of the archive, but it seems the IPA size for WordPress and Jetpack is not affected.

---

`otool -L` output:

```
➜ otool -L DerivedData/Build/Products/Debug-iphonesimulator/WordPress.app/WordPress | grep Gutenberg
	@rpath/Gutenberg.framework/Gutenberg (compatibility version 1.0.0, current version 1.0.0)

➜ otool -L DerivedData/Build/Products/Debug-iphonesimulator/WordPress.app/WordPress | grep hermes
# no result

➜ otool -L DerivedData/Build/Products/Debug-iphonesimulator/WordPress.app/Frameworks/Gutenberg.framework/Gutenberg | grep
Gutenberg
DerivedData/Build/Products/Debug-iphonesimulator/WordPress.app/Frameworks/Gutenberg.framework/Gutenberg (architecture arm64):
	@rpath/Gutenberg.framework/Gutenberg (compatibility version 1.0.0, current version 1.0.0)

➜ otool -L DerivedData/Build/Products/Debug-iphonesimulator/WordPress.app/Frameworks/Gutenberg.framework/Gutenberg | grep
hermes
	@rpath/hermes.framework/hermes (compatibility version 0.12.0, current version 0.12.0)
```

The outcome is different from the one @fluiddot [reported](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5968#discussion_r1266405039) with the version built from #5968. But it doesn't seem to impact the behavior at runtime.

### CODE REVIEW

**Comment by fluiddot** [comment]
> * I also believe @fluiddot solved the huge file size issue for the remainder of the XCFramework in [Flatten embedded frameworks when generating XCFramework #5968](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5968) but I haven't had a chance to look into it.

Hey @mokagio 👋 , the file size issue was solved by having the Hermes framework embedded in the XCFramework Xcode project with the option "Embed & Sign". I tried other options like "Embed without Signing" but it was producing a way larger framework (around 500 MB). I'm not sure what's Xcode doing when enabling that option, but my gut feeling is that it's somehow filtering out unused parts of the framework 🤔.

**Review by fluiddot — APPROVED** [review]
@mokagio I've tested this solution in https://github.com/wordpress-mobile/WordPress-iOS/pull/21021 and confirmed the app is working as expected. I think this PR is good to go, so feel free to set it ready for review anytime. In the meantime, I'll go ahead and preliminary approve it in case you want to merge it right away.

**Branches used:**
* **Gutenberg:** `rnmobile/upgrade/react-native-0.71.8`
* **WP-iOS:** `gutenberg/tweak-pod-deps-by-rn-version`

**Test results using a local build with a local Gutenberg installation:**
  * ✅ Simulator
  * ✅ Device

**Test results using a local build with Gutenberg framework:**
  * ✅ Simulator
  * ✅ Device

**CI build ([`pr21021-1c5fb5f`](https://github.com/wordpress-mobile/WordPress-iOS/pull/21021#issuecomment-1625771872)):**
  * ✅ Device

**NOTE:** The only problem I found is a 💥 crash when opening a post with a VideoPress video, inserting the block doesn't crash. This error seems unrelated to the Hermes framework workaround, so we can omit it for now as it will be solved in a separate PR.

**Comment by mokagio** [comment]
Thanks @fluiddot for the detailed review and for getting this ready to merge.

The Git history is dirtier than I'd like it to be. Shame on me for shipping those "WIP – ..." commits in the first place. I briefly explored rebasing or creating a new branch to cherry pick, but I got conflicts in the submodules and decided to take the hit in terms of non linear history in the interest of moving the work along.

Merging now.

**Comment by fluiddot** [comment]
> Thanks @fluiddot for the detailed review and for getting this ready to merge.
> 
> The Git history is dirtier than I'd like it to be. Shame on me for shipping those "WIP – ..." commits in the first place. I briefly explored rebasing or creating a new branch to cherry pick, but I got conflicts in the submodules and decided to take the hit in terms of non linear history in the interest of moving the work along.
> 
> Merging now.

Another option would be to squash and merge, this option can be helpful when merging into a feature branch like the RN upgrade to keep the Git history simpler and cleaner. In fact, we followed this approach in the Gutenberg PR because we had tons of changes there.

**Comment by mokagio** [comment]
@fluiddot yeah, good point.

**Pull request merged**
