### PR TITLE
Release 1.38.1

### PR DESCRIPTION
**Pull request by ceyhun**
Release for Gutenberg Mobile 1.38.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/26034
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13112
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15083/

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

* Fix unsupported block bottom sheet is triggered when device is rotated: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2710
* Unsupported Block Editor: Fixed issue when cannot view or interact with the classic block on Jetpack site: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2709
* Unsupported Block Editor: Inject css on both page visible and page started: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2715
* Fix/ube cannot view or interact with the classic block on jetpack sites new https://github.com/wordpress-mobile/gutenberg-mobile/pull/2730

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Known Issues

- Post previews show black nav bar after user visits Unsupport Block Editor: https://github.com/wordpress-mobile/WordPress-Android/issues/13133

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [x] Gutenberg 'Podfile.lock' inside 'gutenberg/package/react-native-editor/ios/' is updated to the release number.
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Regarding this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2695
Using the latest WPAndroid build (WordPress-pr-13112-build-77031.apk), I am seeing the classic block on a jetpack site not opening in UBE issue fixed on my Samsung Galaxy S10+ running Android 10, but I do not see that issue fixed on my Samsung Galaxy Tab S3 running Android 9.

image
image

**Comment by guarani** [comment]
> Using the latest WPAndroid build (WordPress-pr-13112-build-77031.apk), I am seeing the classic block on a jetpack site not opening in UBE issue fixed on my Samsung Galaxy S10+ running Android 10, but I do not see that issue fixed on my Samsung Galaxy Tab S3 running Android 9.

FWIW, I couldn't reproduce this while testing https://github.com/wordpress-mobile/WordPress-Android/pull/13122 using a Samsung S10 running Android 10, despite multiple (~10) loads of the UBE. I tested Jetpack connected self-hosted sites, as well as Simple and Atomic WordPress.com sites.

**Comment by cameronvoell** [comment]
I tested the latest of Marko's attempted fixes uses this test PR - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2711#issuecomment-708638443, and I am no longer seeing[ the issue on my Galaxy Tab S3](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2711#issuecomment-708638443). That test PR has this commit as its latest for the gutenberg repo - https://github.com/WordPress/gutenberg/commit/78fa13241c79228bd660e9d53b00f46c8755488e

@marecar3 If we can get these PR's updated with the changes from that last commit, I think this hotfix will be ready to go. Nice job @marecar3 !

**Review by cameronvoell — APPROVED** [review]
Changes all tested successfully :shipit:

**Pull request merged**
