### PR TITLE
Implement copy/paste of images in the file/binary format

### LINKED ISSUE #730: Pasting images should work
Copy pasting an image from the Photos app ( or other apps) should work correctly by creating an image block and starting the upload of the photo to the Media.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #730 

Related Gutenberg PR: https://github.com/WordPress/gutenberg/pull/14802

This PR implements the copy paste of images on the iOS side.
It works by intercepting the paste method on Aztec and passing a url path  array to the JS side to import.

It also implements delegate methods to ask the native, host app to import them in any way it wants.
On the demo app we are just simulating an upload, but on the main WP app we should import the media to the site.

To test:
 - Open the demo app
 - Open the Photos app
- Select one or more images
- Tap on the copy button
- Go back to the demo app
- Select a text block, and tap paste
- See that the images are inserted in the page.

@mzorz do you want to add the android implementation if needed? Can you do copy/paste of a binary image in Android?

### CODE REVIEW

**Comment by mzorz** [comment]
> @mzorz do you want to add the android implementation if needed? Can you do copy/paste of a binary image in Android?

Sure thing @SergioEstevao ! Thanks for the ping, will put this in my ToDo list and try start tomorrow 👍

**Comment by SergioEstevao** [comment]
@pinarol do you mind test this on iOS too?

**Comment by pinarol** [comment]
@SergioEstevao sure thing! I can test this later today or first thing tomorrow.

**Comment by pinarol** [comment]
Hey @SergioEstevao 👋 I did some testing on this, I can paste multiple images pretty well but after that if I try to copy paste normal text it is not working. Also if the block is empty it is removed after the paste. 

text-copy-paste

Other than this I think changes look pretty good.

**Comment by SergioEstevao** [comment]
@pinarol excellent catch, just updated the code to fix the issue you found.

**Comment by pinarol** [comment]
Hey @SergioEstevao 👋 Copy paste seems fixed but I just realized the keyboard down button is not working when caret is at the Image caption. This is not happening on develop. 

image-caption-keyboard-close

**Comment by pinarol** [comment]
Sorry wrong alarm with the right steps I could repro that in develop also

**Pull request merged**
