### PR TITLE
Release 1.40.0

### PR DESCRIPTION
**Pull request by cameronvoell**
Release for Gutenberg Mobile 1.40.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/26466
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13236
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15166

- Aztec-iOS: N/A
- Aztec-Android: N/A

## Extra PRs that Landed After the Release Was Cut

- Fix for CI - https://github.com/WordPress/gutenberg/pull/26455
- Fix for wrong Android emulator on CI - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2763 

## Changes

 - Media Files error handling: https://github.com/WordPress/gutenberg/pull/26008#pullrequestreview-513346975
 - Add yarn to prerequisites: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2739
- Adjust media-text attributes to defaul stacked on mobile to true: https://github.com/WordPress/gutenberg/pull/26041

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by antonis** [comment]
## iOS Sanity Testing Results

Tested with build number: 36877 from App Center on a iPhone SE 2020 with iOS 14.2

### DarkMode-2
* [x] Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
* [x] Buttons block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
* [x] Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)
* [x] Columns - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

### Group-2
* [x] Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
* [x] Group - Navigation down works according to parent-first approach - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
* [x] Group - Cross navigation between blocks works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
* [x] Group - Ungroup button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
* [x] Group - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
* [x] Group - Check if nested Placeholder block can be replaced - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

### Spacer-2
* [x] Spacer block - Settings: Available height range is correct - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
<details>
 <summary>The slider allows to minimum value of 1px. The same holds true for the Web.</summary>

[This seems to be an intentional change](https://github.com/WordPress/gutenberg/pull/25528) and the test case [needs to be updated](https://github.com/wordpress-mobile/test-cases/pull/55).

|Mobile|Web|
|---|---|
|IMG_0011|Screenshot 2020-10-27 at 1 49 20 PM|

</details>

* [ ] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
<details>
 <summary>When setting this in HTML it produces an error on mobile. On the web this seems to work sometimes (like below) but not consistently</summary>
Opened #2761 to track this

|Web|HTML|Mobile|
|---|---|---|
|Screenshot 2020-10-27 at 2 09 35 PM|Screenshot 2020-10-27 at 2 09 49 PM|IMG_E6D78075FC7D-1|

</details>

* [x] Spacer block - Spacer in horizontal layout works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

### Buttons-4
* [x] Buttons block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
* [x] Buttons block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
* [x] Buttons block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)
* [x] Buttons block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
* [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

### Button-5
* [x] Buttons block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
* [x] Buttons block - Render theme colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
* [x] Buttons block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

### Button-7
* [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
* [x] Buttons block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

### Editor Theme - 2

* [x] Custom Gradients - Check that custom gradients load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
* [x] Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

### Color Settings - 2
* [x] Pressing color swatch - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
* [x] Customize gradient color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005)
* [x] Custom color picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by cameronvoell** [comment]
Android Testing ✅ ,  Results below:

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text forma

**Comment by ceyhun** [comment]
Tested with iPhone 11 Pro, iOS 14.1, build 36877:

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by cameronvoell** [comment]
Testing with WPAndroid. 

DarkMode-2
- [x] Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] Buttons block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)
- [x] Columns - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

Group-2
- [x] Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [x] Group - Navigation down works according to parent-first approach - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [x] Group - Cross navigation between blocks works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [x] Group - Ungroup button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [x] Group - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [x] Group - Check if nested Placeholder block can be replaced - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

Spacer-2
- [x] Spacer block - Settings: Available height range is correct - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [x] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [x] Spacer block - Spacer in horizontal layout works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

Button-4
- [x] Buttons block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
- [x] Buttons block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
- [x] Buttons block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)
- [x] Buttons block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
- [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

Button-5
- [x] Buttons block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
- [x] Buttons block - Render theme colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
- [x] Buttons block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

Button-7
- [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] Buttons block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)


Color Settings-2
- [x] Pressing color swatch - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
- [x] Customize gradient color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005)
- [x] Custom color picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by cameronvoell** [comment]
Thanks @ceyhun and @antonis  for the tests! Looks like we're all green except some minor behavior around setting spacer height outside the allowed range through html which @antonis create a ticket for (thank you!). Looks good to go from my perspective 👍

**Review by ceyhun — APPROVED** [review]
:shipit:

**Pull request merged**
