### PR TITLE
MediaUpload and MediaPlaceholder unify props

### PR DESCRIPTION
**Pull request by dratwas**
This PR unifies web and mobile props for MediaUpload and MediaPlaceholder components. It is the first iteration where we do not support multiple select images/videos.

Related gutenberg PR - https://github.com/WordPress/gutenberg/pull/17145
See wordpress-mobile/gutenberg-mobile#1298 and wordpress-mobile/gutenberg-mobile#1299

### CODE REVIEW

**Comment by pinarol** [comment]
@dratwas Could you please put the link of the associated gutenberg PR in the description please? Thanks!

**Comment by pinarol** [comment]
Thanks for the PR! I'll start reviewing this but, a couple of things that caught my attention:

I think the .gitmodules file needs this change in order for reviewers to see your fork's changes:

Screen Shot 2019-08-23 at 17 09 44

But this should be reverted before the merge ☝️ 

Secondly, you should commit & push gutenberg subrepo hash to this PR after you pushed things to the gutenberg PR.

**Comment by pinarol** [comment]
That way reviewer can checkout the PR branch and start testing right after just running a submodule update.

**Comment by koke** [comment]
I tried checking it out locally and it worked for me, even if it fails in CI. I think github exposes external commits that are part of a PR when fetching somehow. My guess is that it might be something that only works on newer git clients, but I don’t really know how that’s working.

**Comment by pinarol** [comment]
To me it was confusing and limiting. First of all I got an error on checkout so it left me with some question marks about having the right things to test. Our CI has the same error: `Fetched in submodule path 'gutenberg', but it did not contain 23ab43f458464675aef9fe10b13796e24bf4b9b3. Direct fetching of that commit failed.` I wanted to go to the subrepo and check if I have the updated version of the branch but I couldn't checkout the remote branch because it didn't exist. After changing my subrepo config I was able to do this and realized that this PR had the old hash pointing to gutenberg repo.

I think it would contain less confusion that way and CI jobs would also succeed hopefully.

**Comment by koke** [comment]
https://github.com/WordPress/gutenberg/pull/17145 was just merged

**Comment by dratwas** [comment]
> After the gutenberg PR is merged please update the gutenberg submodule ref to point to rnmobile/master and revert the .gitmodules file.

Done :)

**Comment by pinarol** [comment]
>  ● Gutenberg Editor paste tests › copies styled text from one paragraph block and pastes in another

@etoledom is this the failing UI test you were referring to ? if so I'll merge this one.

**Comment by pinarol** [comment]
@dratwas  Could you be able to update gutenberg subrepo again to point to the latest `rnmobile/master` ? We just merged and https://github.com/WordPress/gutenberg/pull/17268 it is related with this work

**Comment by etoledom** [comment]
> @etoledom is this the failing UI test you were referring to ? if so I'll merge this one.

Yes, it looks like it. The best way to be sure is to run them locally though.

**Comment by pinarol** [comment]
I ran Android UI tests(yarn test:e2e:android:local) locally by updating `__device-tests__/helpers/caps.js` `deviceName: 'Pixel 2 XL API 28'` since that's the one available in my local. 

They look fine:

```
Test Suites: 8 passed, 8 total
Tests:       21 passed, 21 total
Snapshots:   0 total
Time:        524.039s
Ran all test suites.
✨  Done in 581.71s.
```

**Pull request merged**
