### PR TITLE
1264 - Activate Preformatted block

### LINKED ISSUE #1264: Preformatted block
Support the Gutenberg "Preformatted" block.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1264 

GB PR: https://github.com/WordPress/gutenberg/pull/17906
AztecEditor-Android PR: https://github.com/wordpress-mobile/AztecEditor-Android/pull/869
WP-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10764
WP-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12934

This PR add the preformated block to the list of available blocks.

Pre-light-dark

To make this work some changes were needed in Aztec and on the refreshFont code to be able to handle scenarios were the active font is not the default font, because pre elements need to use a monospace font.

At the moment this PR also needs an Android Dev to make sure that the pre element is formatted correctly on Android.

To test:
 - Open the demo app
 - Add an PreFormatted block to the content
 - Write around on it
 - Try to merge it with other blocks

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
**Update**

It looks that in Android the pre formatting only kicks in when having more that one line in it.

**Comment by SergioEstevao** [comment]
@iamthomasbishop here are some update screenshots for the preformatted block for iOS in light and dark mode.

Pre-light-dark

@marecar3 did you do any updates for Android?

**Comment by iamthomasbishop** [comment]
@SergioEstevao looking pretty good. I have a couple of design requests:

* Can we update the background colors to the following? Light mode: `#f3f6f8` aka `gray light` from the ["old colors"](https://dotcombrand.wordpress.com/colors-archive/). Dark mode: `#101517` (aka `gray-100` from Color Studio). (Side question: can you confirm that the background of the placeholder image block background is `#1d2327` aka `gray-90`? The idea is to make the `pre` block background a shade darker)

* Can we apply the same border-radius to the corners as the placeholder background (see image block on your screenshot for example). I believe this is either 2px or 4px.

I think it's good to go other than that, but I'll take the PR for a spin later today to double check. Nice work!

**Comment by SergioEstevao** [comment]
@iamthomasbishop updated design following your recommendations above:

Pre-light-dark

**Comment by iamthomasbishop** [comment]
Looks great! Thank you! :shipit:

**Comment by SergioEstevao** [comment]
@daniloercoli and @etoledom do you mind review this PR?

**Comment by SergioEstevao** [comment]
@daniloercoli and @etoledom do you mind to give it another look, now that all the issues are sorted.

**Pull request merged**
