### PR TITLE
Block placeholder fixes

### PR DESCRIPTION
**Pull request by SergioEstevao**
Refs: #592, #549, #547

Updates the GB reference to have the placeholder fixes. 
It also makes the title placeholder text o be consistent with the web and localized.

Related GB PR: https://github.com/WordPress/gutenberg/pull/13945

simulator screen shot - iphone xr - 2019-02-19 at 12 44 11

### CODE REVIEW

**Comment by koke** [comment]
I haven't tested yet, but from your screenshot, the placeholder doesn't look left-aligned with the title

**Comment by koke** [comment]
Also cc @Tug for i18n string changes

**Comment by elibud** [comment]
Could we avoid saying "Welcome to Gutenberg", I don't think that would make sense to most of our users. Honestly I would stick with a neutral placeholder like "Add a title".

**Comment by iamthomasbishop** [comment]
I think (iirc) the placeholder label text on the title does say `Add a Title`, unless that has changed.

One other thing that stands out to me is the margins of blocks on the initial canvas. The title feels too close to the navbar – maybe the title block is a little too tall, but it's hard to tell without seeing those boundaries.

For now, can we add a slight bit of space at the top of the canvas (above the title block) so it feels a little more balanced? Maybe 16pt? 

screen shot 2019-02-19 at 9 13 05 am

**Comment by elibud** [comment]
@iamthomasbishop @SergioEstevao yes, looking at the code I can see we are keeping the "Add a Title" label, please ignore me 🤦‍♀️

**Comment by SergioEstevao** [comment]
@iamthomasbishop here is a new screenshot with the new margins and some background color to make it easier to figure margins.

simulator screen shot - iphone xr - 2019-02-19 at 17 30 43

**Comment by koke** [comment]
Keep in mind that those screens are for the example app, we should make sure that the margins look right on the WordPress apps as well

**Comment by iamthomasbishop** [comment]
@SergioEstevao Thanks for the reference. Spacing looks really wonky there – is the title vertically aligned top? That's probably why it looked like a lot of empty space 😄 

In terms of spacing at the top of the canvas, I mocked this up just to get a visual reference, and 16pt/dp feels about right. It looks like this:

image

Left: title focused. Right: static.

I've also uploaded these to the Zeplin project for reference.

**Comment by SergioEstevao** [comment]
@iamthomasbishop the component we use as the base for Aztec that is being used in the title always aligns the text on the top. I changed the dimensions of the component to make it more centred it now
looks like this: 
simulator screen shot - iphone xr - 2019-02-19 at 21 58 04

**Comment by iamthomasbishop** [comment]
That looks a bit better already. Might still be worth adding 16pt of margin to the top of the canvas, but this at least looks cleaner.

Side note, and maybe this is something that can be addressed in a separate issue – I noticed the color on all of the placeholder text labels is different from the preferred `$gray` aka `#87a6bc` – can we match those? Thank you!

**Comment by SergioEstevao** [comment]
@iamthomasbishop updated the colors: 

simulator screen shot - iphone xr - 2019-02-20 at 00 21 32

**Comment by SergioEstevao** [comment]
@daniloercoli do you mind have a look in Android to see if things look ok after these changes?

**Comment by daniloercoli** [comment]
It does seem to work fine on Android!

**Comment by iamthomasbishop** [comment]
Thanks for all of the quick iterations/feedback, @SergioEstevao and @etoledom! When ready, can you share screenshots of the current state on iOS/Android for design review? TY!

**Pull request merged**
