### PR TITLE
Add missing heading options

### LINKED ISSUE #1261: Add missing heading levels
Even though Gutenberg mobile renders them already, user has no way to set H4, H5, H6 via the editor UI. Let's add the missing functionality.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1261 

As discussed with @iamthomasbishop on the ticket above we decided to implement the missing heading options by just adding them to the format toolbar.

Related GB PR: https://github.com/WordPress/gutenberg/pull/17533

Simulator Screen Shot - iPhone 11 - 2019-09-23 at 22 08 31

To test:
 - Start the demo app
 - Check that the heading block has the H4, H5, H6 buttons when selected
 - Use the option and check that the HTML is correctly generated.

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Looking mostly good, I have a couple thoughts.

The font sizes seem a bit small, esp on Android. Here's what I've got them defined as on the design side (in Figma):

* `h1`: 24
* `h2`: 22
* `h3`: 20
* `h4`: 18
* `h5`: 16 (same as "normal" `p` text)
* `h6`: 14

Also, as noted in [this issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/992), the inside block content areas are a bit off. This throws off the vertical rhythm substantially on Android.

**Comment by SergioEstevao** [comment]
@iamthomasbishop I just confirmed that in iOS the sizes match you specify above.

**Comment by iamthomasbishop** [comment]
@SergioEstevao  can you investigate why Android looks different? They look off in the screenshot above but I’m not sure if that’s my eyes playing tricks?

**Comment by hypest** [comment]
👋 @SergioEstevao , love to see this merged! 🎉

I wonder, do you think we could add one or more automated tests in this one? Maybe an Appium e2e test?

**Pull request merged**
