### PR TITLE
Issue/3800 unitcontrol label color

### PR DESCRIPTION
**Pull request by AmandaRiu**
**Fixes**: #https://github.com/wordpress-mobile/gutenberg-mobile/issues/3800
**Gutenberg PR**: https://github.com/WordPress/gutenberg/pull/34057

## To test
Follow the test instructions in the Gutenberg PR: https://github.com/WordPress/gutenberg/pull/34057

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
@AmandaRiu I see that this PR was assigned to `1.58.3` milestone but that was created for a hotfix, if you're aiming to include this in the next release we would need to create the `1.60.1` milestone.

**Comment by AmandaRiu** [comment]
> @AmandaRiu I see that this PR was assigned to `1.58.3` milestone but that was created for a hotfix, if you're aiming to include this in the next release we would need to create the `1.60.1` milestone.

Thanks @fluiddot , yup, I meant this for the next release. I've moved it.

**Comment by geriux** [comment]
Hey @AmandaRiu. We will cut the 1.60.0 release today. I will bump this PR to the next milestone, but please let me know if you’d rather us work to include this PR in 1.60.0. Thanks!

**Comment by mkevins** [comment]
Hey @AmandaRiu. :wave: :smile:  We will cut the 1.61.0 release <s>today</s>. I will bump this PR to the next milestone, but please let me know if you’d rather us work to include this PR in 1.61.0. Thanks!

**Edit:** There is a chance the release cut will be delayed until tomorrow. Since this PR is still awaiting the :heavy_check_mark: , I've bumped the milestone - but let me know if you'd like to get it into 1.61.0. :+1:

**Comment by guarani** [comment]
Thanks @mkevins! I'll be taking over this PR.
Bumping the milestone is fine I think 👍

**Comment by jd-alexander** [comment]
Hey @AmandaRiu .We will cut the 1.62.0 release today so I am bumping this PR to the next milestone.  Let me know if you’d rather us work to include this PR in 1.62.0. Thanks!

**Comment by guarani** [comment]
Thanks @jd-alexander! 
I've taken over this PR and for now I'm going to remove the milestone now though, and re-add it once it's ready.
I'd hoped to get to it sooner 😞.

**Comment by jd-alexander** [comment]
> Thanks @jd-alexander!
> I've taken over this PR and for now I'm going to remove the milestone now though, and re-add it once it's ready.
> I'd hoped to get to it sooner 😞.

No problem @guarani Thanks for the update!

**Comment by guarani** [comment]
👋 I wasn't able to get to this unfortunately, I'd meant to take over as PR author. Apologies for the long delay.
I'll un-assign myself as reviewer and leave this open for someone else to get to if needed.
cc @hypest

**Comment by AmandaRiu** [comment]
Wow, this has been open for a very long time [and the linked PR was already closed](https://github.com/WordPress/gutenberg/pull/34057) two years ago due to being stale. I'm going to go ahead and close this one. It can be reopened in the future if needed.

**Pull request closed without merging**
