### PR TITLE
Image Size Options UI - Add Appium Tests

### PR DESCRIPTION
**Pull request by cameronvoell**
Resolves part of  #1329 

For enabling removal of DEV flag, see connecting size options UI to networking for updating image urls and minor enhancements here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1452 and https://github.com/wordpress-mobile/gutenberg-mobile/pull/1453

**More info:**
Gutenberg side PR: https://github.com/WordPress/gutenberg/pull/17245

image-options-android
ios-size-options

To test:

1. Build Example app
2. Click on an Image block (that already has an image)
3. Press the gear button to bring up Image Options menu
4. Verify new Size option exists, click size options
5. Verify size options are shown and choose one.
6. Re-open Image options menu and verify previously selected size is now shown as selected.

For verifying sizeSlug is correctly submitted to web backend:

1. Run the metro bundler for this branch and build either Android or iOS WordPress app
2. Use a wordpress.com account and navigate to a post, and begin editing in Gutenberg editor.
3. Follow steps above to update Image Size options. Click Update.
4. One the web, log in to the wordpress.com account, navigate to the article, and verify that the new Image size sizeSlug  setting is shown.

Update release notes (hidden behind __DEV__ flag until networking for updating image urls is completed):

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Taking a look at failed tests

**Comment by mchowning** [comment]
:wave: @cameronvoell ! The image block unit test failures aren't related to your PR. They're due to a change on `master` a couple of days ago, and I'm working on them. I expect to have a PR up tomorrow (Thursday). 

I occasionally see that Android device test failure occur seemingly randomly. I think there's a decent chance that one _may_ pass the next time it runs.

**Comment by hypest** [comment]
> They're due to a recent change on gutenberg's master branch, and I'm working on them. I expect to have a PR up tomorrow (Thursday).

Hey @mchowning, seems [there's a PR up](https://github.com/WordPress/gutenberg/pull/17989) now from @dratwas.

**Comment by hypest** [comment]
I'd love it if we added at least one Appium test for this feature @cameronvoell . For example, a test that alters the image size setting of an image block and verifies that the resulting html has the proper tags/attributes/details to correspond to that size setting. Since the Gutenberg side PR has already merged, let's not keep this PR open for too much longer so, I'd suggest adding that test(s) in an addition PR.

**Comment by cameronvoell** [comment]
This PR was left open even though gutenberg-mobile has already incorporated gutenberg changes because this PR was going to be used for adding relevant Appium tests https://github.com/wordpress-mobile/gutenberg-mobile/pull/1454#issuecomment-543644117.  Work on Appium tests was delayed due to this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1482 .

It seems this issue should be moved past 1.17 and likely closed. A new PR can be made for adding Appium tests later.

**Comment by etoledom** [comment]
> It seems this issue should be moved past 1.17 and likely closed. A new PR can be made for adding Appium tests later.

I agree, let's close this one and start a new one for the tests.

**Pull request closed without merging**
