### PR TITLE
[RNMobile] Add "Set as Featured Image" Button to Image Block (iOS Only)

### PR DESCRIPTION
**Pull request by SiobhyB**
Paritial fix for: wordpress-mobile/gutenberg-mobile#1011

`gutenberg`: https://github.com/WordPress/gutenberg/pull/31415
`WordPress-iOS`: https://github.com/wordpress-mobile/WordPress-iOS/pull/16426

The main PR for the branch this individual PR will be merged into, `add/featured-functionality-to-image-block-ios`, can be found here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3449

## Description

This PR will add a **Set as Featured** button to the image block's settings on iOS devices, with the purpose being to make it simpler for users to set a featured image within the post's editor. Users will also be able to **Remove as Featured** directly from the block's setting.

### Main Test Flows

[The Gutenberg PR](https://github.com/WordPress/gutenberg/pull/31415) can be referred to as the central, most up-to-date repository for the main test flows.

### Tracks Verification

[The iOS PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16426) can be referred to for steps to verify that the Tracks events edited/introduced with this PR work as expected.

<hr />

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
I left a review here: https://github.com/WordPress/gutenberg/pull/31415#issuecomment-852388508
I think the bundle changes here (specifically the changes to localized strings) might be fixed when https://github.com/wordpress-mobile/gutenberg-mobile/pull/3565, but not sure.

**Comment by guarani** [comment]
Regarding the changes in translation files seen in the diff here, I wonder if https://github.com/wordpress-mobile/gutenberg-mobile/pull/3565 fixed it and this PR just needs to be updated with the latest from `develop`.

**Comment by guarani** [comment]
Just want to double-check, after bumping the Gutenberg ref, were the bundles updated as well or was that not required? I always run `npm run bundle` when bumping the submodule ref, just to be sure.

**Comment by SiobhyB** [comment]
> Regarding the changes in translation files seen in the diff here, I wonder if #3565 fixed it and this PR just needs to be updated with the latest from develop.

I've updated from `develop` (via the feature branch) now and all looks to be resolved! :)

> Just want to double-check, after bumping the Gutenberg ref, were the bundles updated as well or was that not required? I always `run npm run bundle` when bumping the submodule ref, just to be sure.

I didn't update the bundles, but will do in the future just to be sure. thanks for the heads up on that workflow habit.

**Review by guarani — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/31415#pullrequestreview-692255299

**Pull request merged**
