### PR TITLE
Test Gutenberg PR: "Separator: Add means to control height"

### PR DESCRIPTION
**Pull request by hypest**
No need to merge, this PR only serves as testing out the https://github.com/WordPress/gutenberg/pull/28409 PR.

### CODE REVIEW

**Comment by fluiddot** [comment]
@hypest should we run the full suite of UI tests?

**Comment by hypest** [comment]
Triggered the full suite 👍

**Comment by hypest** [comment]
cc @chipsnyder in case we want to do some manual test on the Spacer block, unless it's already well covered by automated tests.

**Comment by geriux** [comment]
> cc @chipsnyder in case we want to do some manual test on the Spacer block, unless it's already well covered by automated tests.

The `Separator` block is broken with this reference of `Gutenberg` I left a [comment](https://github.com/WordPress/gutenberg/pull/28409#issuecomment-765565849) mentioning the issues.

**Comment by hypest** [comment]
No need for this PR anymore so, closing.

**Pull request closed without merging**
