### PR TITLE
Remove yarn

### PR DESCRIPTION
**Pull request by fluiddot**
This PR removes the `yarn.lock` file and the yarn dependency as any of them are no longer.

We used yarn for installing the dependencies from Jetpack but this has changed recently and now they're installed with pnpm.

Related PRs:
- [Switch to pnpm needed by the Jetpack repo](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3575)
- [Add yarn as a dev dependency](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2781)

To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
LGTM! Thanks Carlos! Only thing is that the iOS e2e test build seems to have failed in the JS bundling phase. I've tried bundling locally and it worked fine, not sure what's causing this issue on CI.

**Comment by fluiddot** [comment]
> LGTM! Thanks Carlos! Only thing is that the iOS e2e test build seems to have failed in the JS bundling phase. I've tried bundling locally and it worked fine, not sure what's causing this issue on CI.

Thanks 🙇 ! 

Oh interesting, looks like it's not finding one of the dependencies from Jetpack 🤔 :
```
ENOENT: no such file or directory, readlink '/Users/distiller/project/jetpack/node_modules/.pnpm/node_modules/@**********/color-studio'.
```

I'll try to re-run it to double-check that is safe to merge the PR.

**Comment by hypest** [comment]
FWIW, the `color-studio` package seems to be giving some trouble in local dev environments as well (internal Slack chat p1623793983431200-slack-C6UJ0KRKQ).

**Comment by fluiddot** [comment]
> FWIW, the `color-studio` package seems to be giving some trouble in local dev environments as well (internal Slack chat p1623793983431200-slack-C6UJ0KRKQ).

Thanks for sharing this ❤️ ! I'm wondering if it has to do with modifying the dependencies from the `package.json` file because it's the only thing that this PR changed 🤔 .

**Comment by fluiddot** [comment]
Looks like it worked on the second run: https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/12778/workflows/be9d76f4-1043-4164-9e09-6b2275a24de3/jobs/69298

**Pull request merged**
