### PR TITLE
Merge 1.46.1 beta fix release to 1.47.0

### PR DESCRIPTION
**Pull request by fluiddot**
This PR includes the changes that were included in the `1.46.1` beta fix into the release `1.47.0`.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
The Gutenberg reference points to the latest commit from `rnmobile/merge_release_1.46.1_to_1.47.0`, once the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29044) gets merged we have to update that reference to the merge commit.

**Comment by fluiddot** [comment]
I also spotted that the Jetpack reference was pointing to an older commit:

From [`60f41b`](https://github.com/Automattic/jetpack/commit/60f41b) to [`609c99`]( https://github.com/Automattic/jetpack/commit/609c99)

It's weird because on `develop` branch the Jetpack reference is also the old one but it shouldn't because a [PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2949/files) modified it (actually the one that originated including the extra changes in `1.46.1`) a couple of weeks ago.

**Review by antonis — APPROVED** [review]
LGTM 🎉

**Review by dcalhoun — CHANGES_REQUESTED** [review]
Still looking into why, but I am seeing this error when loading the demo app locally from `gutenberg-mobile`.

rn-bridge-error

**Review by dcalhoun — APPROVED** [review]
🎉 LGTM now that we have a fix included for the RN error seen previously. I suppose the last steps are merging the sibling `gutenberg` PR and updating the ref here before merging this one.

**Comment by fluiddot** [comment]
> 🎉 LGTM now that we have a fix included for the RN error send previously. I suppose the last steps are merging the sibling `gutenberg` PR and updating the ref here before merging this one.

Yeah exactly.

**Pull request merged**
