### PR TITLE
Ignore column width attribute when empty

### LINKED ISSUE #29017: Editor crash on column block with empty width attribute
<!--

The native editor crashes when a column block contains an empty width attribute.

## Step-by-step reproduction instructions
1. Open the native block editor (React Native editor)
2. Replace the editor contents with the following HTML and observe that the app crashes

```
<!-- wp:columns -->
	<div class="wp-block-columns">
		<!-- wp:column -->
			<div class="wp-block-column"></div>
		<!-- /wp:column -->

		<!-- wp:column {"width":""} -->
			<div class="wp-block-column"></div>
		<!-- /wp:column -->
	</div>
<!-- /wp:columns -->
```

## Expected behaviour
The native editor should ignore the empty width attribute just as the web editor does

## Actual behaviour
The native editor crashes when it encounters an empty width attribute in a column block.

## WordPress information
Current `master` branch: https://github.com/WordPress/gutenberg/commit/6ef9e821a8f88eac7bf93275965fe9f90311a4e4

## Device information
iOS or Android

### PR DESCRIPTION
**Pull request by guarani**
Fixes https://github.com/WordPress/gutenberg/issues/29017

To test:
https://github.com/WordPress/gutenberg/pull/29015

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
👋 I've just updated the Gutenberg submodule reference to leave this PR ready.

**Review by fluiddot — APPROVED** [review]
✅ Tested and approved via https://github.com/WordPress/gutenberg/pull/29015#pullrequestreview-591136999.

**Comment by fluiddot** [comment]
@guarani I was wondering if we should update the title with something similar to the `gutenberg` PR, I think it could be a bit misleading when someone checks the milestone for `1.47`, what do you think?

**Comment by guarani** [comment]
> @guarani I was wondering if we should update the title with something similar to the `gutenberg` PR, I think it could be a bit misleading when someone checks the milestone for `1.47`, what do you think?

Thanks for flagging – updated now! (it took the title of my equally poorly named commit and used it as a title and I hadn't noticed)

**Comment by fluiddot** [comment]
I'm moving this PR to the `1.46.1` milestone because it was integrated in that version.

**Comment by guarani** [comment]
> I'm moving this PR to the `1.46.1` milestone because it was integrated in that version.

Thanks for updating that, @fluiddot!

**Pull request merged**
