### PR TITLE
Video block - don't force full screen on iOS 

### PR DESCRIPTION
**Pull request by SergioEstevao**
Updates the video player to not force fullscreen on the iOS video block.

I also added a prop that allows the explicit setting of fullscreen mode when pressing play for iOS and Android. This can be helpful in the future for the Cover block.

GB PR: https://github.com/WordPress/gutenberg/pull/20436

To test:
 - Run the demo app
 - on iOS check that the video on the demo doesn't go to fullscreen when pressing play
 - check if no layout issues happen
 - on Android check, if the video block still open on an external application
 - check if no layout issues happen

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
We're freezing `1.24.0 `today. If you think it is ready and if you'd like to ship it with `1.24.0`please merge it into develop branch. Otherwise, we can bump it to `1.25.0.` @SergioEstevao

**Comment by hypest** [comment]
Bumped this to 1.25 as it's WIP.

**Comment by SergioEstevao** [comment]
@ceyhun do you mind giving a look to this one?

**Comment by etoledom** [comment]
Does this deserves a release note? 🤔

**Pull request merged**
