### PR TITLE
[Embed Block] Set EmbedLinkSettings URL input cursor at start of link

### LINKED ISSUE #35888: [RNMobile] Improve how URLs are populated in embed blocks from device clipboard
## What problem does this address?

While testing iOS 18.5 I noticed when adding a YouTube embed block with an Instagram url in my clipboard, the link input was auto populated with the domain name (instagram.com) cut off from the view. When I inserted the block an Instagram block appeared. I didn't expect the YouTube embed to accept a url from another embed service. It was also difficult to know I had a URL from a different service in my clipboard since the cursor was placed at the right end of the text hiding the domain name.

## What is your proposed solution?

Embed blocks should not auto populate the link field from the device clipboard if the url is from a different service. 
Additionally we might want to consider placing the cursor of an auto pasted url to the left of the text so the domain name is clear.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes https://github.com/WordPress/gutenberg/issues/35888

To test:
https://github.com/WordPress/gutenberg/pull/36100

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
Hey @jd-alexander  !
We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!

**Comment by SiobhyB** [comment]
👋 @jd-alexander, we plan to cut the 1.67.0 release around 10:00 UTC tomorrow, on Thursday 25th November. I plan to circle back and bump this PR to the next milestone then, but please let me know if you'd rather us work to include this PR in 1.67.0. 

As a reminder, changes in the next (1.68.0) release won't be shipped to users until the 10th January.

Thanks!

**Comment by guarani** [comment]
👋 Hi @jd-alexander. We will cut the 1.68.0 release on Dec 9th. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.68.0. 🙇

**Comment by hypest** [comment]
Joel is currently AFK so, best to remove the milestone assignment for a bit. Will do it now.

**Pull request closed without merging**
