### PR TITLE
Video block ui/ux enhancements

### PR DESCRIPTION
**Pull request by marecar3**
Fixes : https://github.com/wordpress-mobile/gutenberg-mobile/issues/966

**Android Upload Video Example :** 

video_android

**Android Upload Image Example :** 

image_android

More details regarding testing and preview of what is done: https://github.com/WordPress/gutenberg/pull/15551

### CODE REVIEW

**Comment by pinarol** [comment]
hey Marko 👋 I think we might have a side effect about not showing the image placeholder. Normally I should be seeing an image placeholder during the time image loads from media library:

image-block-placeholder

**Comment by marecar3** [comment]
Hey @pinarol , thanks for the feedback, I will look at it.

**Comment by iamthomasbishop** [comment]
@marecar3 Can you please add some screenshots or videos when it's ready for design review? It's a bit hard to see what to review without visuals. Thank you!

**Comment by marecar3** [comment]
Hey @iamthomasbishop you can find it on this PR: https://github.com/WordPress/gutenberg/pull/15551

But I upload here newest videos for both image and video block. Will tag you when that happens.

**Comment by marecar3** [comment]
> hey Marko 👋 I think we might have a side effect about not showing the image placeholder. Normally I should be seeing an image placeholder during the time image loads from media library:
> 
> image-block-placeholder

Fixed! :)

**Comment by marecar3** [comment]
Hey @iamthomasbishop I have updated description with the latest video presenting image/video block feature.

**Comment by pinarol** [comment]
hey Marko 👋 Unfortunately that new icon/index.native.js has a huge regression effect on all types of icons. Demo apps are already crashing

Screen Shot 2019-05-17 at 11 19 19

It looks to me that we shouldn't diverse the mobile side implementation of Icon for this PR, it needs wider testing. We have our own separate js files already for icons like:
image/icon-retry.js
video/icon-retry.js

would that be possible to change those files only and pass the fill color or size if needed? I'll try to look into this a bit.

**Comment by pinarol** [comment]
@marecar3 👋 I looked into that last crash a bit and I think I found a solution that won't effect other icons, let's discuss and I can push the commit if that's OK for you.

**Comment by iamthomasbishop** [comment]
Looking at the updated videos above, some more feedback:

### Video upload progress

Looks a lot cleaner, well done! I noticed there is a _split second_ before the placeholder/uploading state shows, where the inner block collapses. Can we: 

- [ ] Make sure the placeholder shows immediately, so there isn't a jump

### Placeholder/uploading icons

image
(same concept on Image block)

For both video and image block uploading (any progress states), can we make sure:

- [ ] Color of icon is `$gray-lighten-20`
- [ ] Icon is 40x40

**Comment by iamthomasbishop** [comment]
Looking at the updated videos above, some more feedback:

### Video upload progress

Looks a lot cleaner, well done! I noticed there is a _split second_ before the placeholder/uploading state shows, where the inner block collapses. Can we make sure the placeholder shows immediately, so there isn't a jump?

### Placeholder/uploading icons

image

(same concept applies to Image block)

For both video and image block uploading (any progress states), can we make sure:

* Color of icon is `$gray-lighten-20`
* Icon is 40x40

### Transitions

I understand this might be tricky, but it would be great if we could add some transitions when media items are loaded. For example, we could:

* Smoothly transition the height of the inner blocks when the uploaded item is being displayed
* Fade in the video – right now it's just an immediate display upon entrance

### Side Notes

* Caption: there is some extra padding top/bottom on the caption, but this might be related to an issue I reported earlier (#992)

**Comment by pinarol** [comment]
hey @iamthomasbishop thank you for the feedbacks, I think it is ready for another look.

>  noticed there is a split second before the placeholder/uploading state shows, where the inner block collapses. Can we make sure the placeholder shows immediately, so there isn't a jump?

I investigated the issue but couldn't figure the root cause, it is pretty weird that it only happens on Android. iOS part seems OK:

video-block-upload

So I added an item here https://github.com/wordpress-mobile/gutenberg-mobile/issues/687#issuecomment-482011555 It'd be better if an Android dev investigates it. I am assuming this is not a blocker for shipping the video block, please let me know if you have concerns about it.

>For both video and image block uploading (any progress states), can we make sure:
>Color of icon is $gray-lighten-20
>Icon is 40x40

You are right this wasn't correct, I updated this:

Screen Shot 2019-05-17 at 23 41 28

> Caption: there is some extra padding top/bottom on the caption, but this might be related to an issue I reported earlier

I updated caption padding due to designs:

Screen Shot 2019-05-17 at 23 20 51

Screen Shot 2019-05-17 at 23 20 43

> Transitions

Yes transitions are tricky, I think we might not be able to make it until v2. Plus, considering the very little [usage](https://mc.a8c.com/tracks/trends/?eventname=wpios_editor_video_added%2Cwpios_editor_session_start&interval=day&startdate=20190413&stat=uniques) of video blocks currently it might be an over effort currently. But feel free to open a new issue for it and we can estimate and plan how to do it for future releases, does that sound good?

**Comment by iamthomasbishop** [comment]
Thanks @pinarol – these updates look great! From what I can tell from your iOS videos, everything looks to be working properly. Let's fix that issue on Android as soon as we can, but not a blocker for shipping the block.

**Comment by pinarol** [comment]
thank you @iamthomasbishop I've opened an issue to track that: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1005

**Pull request merged**
