### PR TITLE
Hotfix v1.10.3 -> Master

### PR DESCRIPTION
**Pull request by daniloercoli**
PR to merge hotfix 1.10.3 into master

Changes were tested and approved via #1292

Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10389

iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12315

### CODE REVIEW

**Comment by hypest** [comment]
👋 @daniloercoli , can you also link to the WPAndroid and WPiOS PRs that depend on this?

**Comment by daniloercoli** [comment]
> 👋 @daniloercoli , can you also link to the WPAndroid and WPiOS PRs that depend on this?

Both iOS and Android PRs point to the hash atm. We will update to the proper tag once this is merged and tagged.

**Comment by hypest** [comment]
Added @marecar3 as a reviewer here as I'm probably not going to make it today. That said, this PR already looks good, just needs the coordination with the WPAndroid and WPiOS sides.

**Comment by marecar3** [comment]
Thanks, @hypest, I will handle it from here.

**Pull request merged**
