### PR TITLE
Produce Hermes bytecode and use it on Android

### LINKED ISSUE #1660: Use RN's Hermes JS engine for faster and leaner performance on Android
React Native's own JS engine, Hermes, is touting faster performance, smaller app footprint both for the JS bundle and the memory consumption.

It's be good if we switch to it, at least for Android. There are some instruction on [how to do it in the docs](https://facebook.github.io/react-native/docs/hermes/), and [this comment](https://github.com/facebook/hermes/issues/96#issuecomment-535393907) on a related ticket also seems useful with additional instructions.

### PR DESCRIPTION
**Pull request by hypest**
Fixes #1660 

This PR adds the Hermes command line to produce the binary bytecode version of the JS bundle for Android, and sets it as the asset to be loaded by the parent app.

### Changes in this PR:

1. Introduced the `bundle:android:bytecode` yarn script. Is uses the Hermes binary to compile the `App.js` bundle into binary bytecode that Hermes' runtime can use to offer better performance on Android. This script is ran automatically as part of the `bundle` script too.
2. Have JitPack copy the bytecode file into the Android bridge artifact instead of the App.JS bundle it was bundling before.
3. Have the glue code load up `index.android.bytecode` from the assets folder. That's the code the parent app runs to load the bundle so, with this change the parent app will use the binary bytecode file.
4. Include the binary bytecode file (and the accompanying mapping file) into source control. Note the commited artifacts are not really used by any Android app anyway, only included for "parity" with the string JS bundles being there too.

### Comparison on Pixel 2XL Android 10
Without bytecode | With bytecode
-- | --
~4secs loading | ~1sec loading
block-editor-open-slow | block-editor-open-fast

Also measured the same post opening on a Nexus 5X (Android 7.1.2) and loading takes ~3secs.

### Notes

There are more than a few warning emitted by Hermes while compiling the current App bundle into bytecode. Will document here but now sure yet if these are actually important or not. Will probably need to go over these one-by-one to assess:

```
bundle/android/App.js:36:134: warning: the variable "Promise" was not declared in function "isBoldTextEnabled"

bundle/android/App.js:48:3047: warning: the variable "DebuggerInternal" was not declared in function "value 15#"

bundle/android/App.js:110:57098: warning: the variable "setTimeout" was not declared in function "Pi 1#"

bundle/android/App.js:110:83621: warning: the variable "__REACT_DEVTOOLS_GLOBAL_HOOK__" was not declared in function "Xl"

bundle/android/App.js:110:22512: warning: the variable "clearTimeout" was not declared in function " 657#"

bundle/android/App.js:110:89330: warning: the variable "nativeFabricUIManager" was not declared in function " 692#"

bundle/android/App.js:127:795: warning: the variable "setImmediate" was not declared in function "h 7#"

bundle/android/App.js:137:177: warning: the variable "Worker" was not declared in function " 791#"

bundle/android/App.js:152:67: warning: the variable "fetch" was not declared in function " 855#"

bundle/android/App.js:152:81: warning: the variable "Headers" was not declared in function " 855#"

bundle/android/App.js:152:97: warning: the variable "Request" was not declared in function " 855#"

bundle/android/App.js:152:114: warning: the variable "Response" was not declared in function " 855#"

bundle/android/App.js:153:1539: warning: the variable "FileReader" was not declared in function "p 12#"

bundle/android/App.js:153:1973: warning: the variable "Blob" was not declared in function " 864#"

bundle/android/App.js:153:2034: warning: the variable "FormData" was not declared in function " 864#"

bundle/android/App.js:153:2107: warning: the variable "URLSearchParams" was not declared in function " 864#"

bundle/android/App.js:153:6805: warning: the variable "XMLHttpRequest" was not declared in function " 871#"

bundle/android/App.js:197:245: warning: the variable "MessageChannel" was not declared in function " 993#"

bundle/android/App.js:275:840: warning: the variable "requestAnimationFrame" was not declared in function "value 276#"

bundle/android/App.js:325:2651: warning: the variable "clearImmediate" was not declared in function " 1512#"

bundle/android/App.js:353:1238: warning: the variable "cancelAnimationFrame" was not declared in function "componentWillUnmount 3#"

bundle/android/App.js:886:5988: warning: the property "ldquo" was set multiple times in the object definition.

bundle/android/App.js:1477:12736: warning: the variable "alert" was not declared in function "warn"

bundle/android/App.js:1841:2350: warning: the variable "Intl" was not declared in function "x 32#"
```

To test:

1. Use the WPAndroid APK produced on the PR here https://github.com/wordpress-mobile/WordPress-Android/pull/11436 and observe the start-up time of the block editor. It should be faster than before.
2. Smoke test the editor, it should work as normal.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by maxme** [comment]
@rachelmcr can you test the apk linked above on your slower test device(s)?

**Comment by hypest** [comment]
Using the new track, it counted `873ms` on Pixel 2XL and `2400ms` on Nexus 5X.

**Comment by rachelmcr** [comment]
> can you test the apk linked above on your slower test device(s)?

I tested the new WPAndroid APK on my moto e5 play phone, and it _significantly_ improves the load time for me. I checked the new track property and the load time was between `3124ms` and `5513ms` each time (out of 5 times) on the moto e5 play. Thank you!

**Comment by hypest** [comment]
Results of manual tests on this PR:

- [ ] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [ ] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [ ] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)
- [ ] Gallery block - Choose from device (stay in editor) - Successful upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc005)
- [ ] Gallery block - Choose from device (stay in editor) - Failed upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [ ] Gallery block - Choose from device (leave the editor) - Successful upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc007)
- [ ] Gallery block - Choose from device (close and re-open the editor with ongoing uploads) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc008)
- [ ] Gallery block - Take a photo - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)
- [ ] Gallery block - Choose from the free photo library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

- [ ] Image block - Switch to classic editor with an image block in page - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc006)
- [ ] Image block - Add Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc003)
- [ ] Image block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc001)
- [ ] Image block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc002)
- [ ] Image block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc004)
- [ ] Image block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc005)
- [ ] Media Text block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc004-i)
- [ ] Media Text block - Change media text order during upload and close the post - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc005-i)
- [ ] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [ ] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [ ] Media Text block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)
- [ ] Media Text block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [ ] Media Text block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)
- [ ] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

- [ ] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

Gallery-1

- [ ] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [ ] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [ ] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [ ] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc011)

Gallery-3

- [ ] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [ ] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [ ] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)

Gallery-4

- [ ] Gallery block - Settings: Link to - steps
- [ ] Gallery block - Settings: Column number - steps
- [ ] Gallery block - Settings: Crop images - steps

MediaText-1

- [ ] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [ ] Media Text block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

MediaText-2

- [ ] Media Text block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [ ] Media Text block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

MediaText-3

- [ ] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [ ] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

MediaText-4

- [ ] Media Text block - Media & Text alignment - steps
- [ ] Media Text block - Vertical alignment - steps

MultipleUpload-1

- [ ] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

DarkMode-1(iOS)

- [ ] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [ ] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [ ] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

DarkMode-2(iOS)

- [ ] Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [ ] Button block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [ ] Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc006)


Shortcode-1

- [ ] Shortcode block - Add a youtube link - steps

Spacer-1

- [ ] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [ ] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [ ] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)
- [ ] Spacer block - Settings: Available height range is correct - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [ ] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [ ] Spacer block - Spacer in horizontal layout works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

Button-1

- [ ] Button block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc011)
- [ ] Button block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc010)
- [ ] Button block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc012)
- [ ] Button block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc015)

Button-2

- [ ] Button block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc003)
- [ ] Button block - Fallback to default colors in case theme colors are used - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc013)
- [ ] Button block - New Button is created with the gray color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc014)
- [ ] Button block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc009)
- [ ] Button block - The newly created button has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc016)
- [ ] Button block - Tapping `delete` key removes block when Button is empty - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc017)

Button-3

- [ ] Button block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc005)
- [ ] Button block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc006)
- [ ] Button block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc004)
- [ ] Button block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc008)
- [ ] Button block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc007)

Button-4

- [ ] Button block - Link in the clipboard is automaticially added into the empty URL field - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc002)
- [ ] Button block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc018)
- [ ] Button block - Button max width is calculated OK inside inner blocks(iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc001)

Group-1

- [ ] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [ ] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [ ] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [ ] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [ ] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [ ] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [ ] Group - Nested selection cause applying dimmed style on the rest of blocks - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc007)
- [ ] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)
- [ ] Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [ ] Group - Navigation down works according to parent-first approach - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [ ] Group - Cross navigation between blocks works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [ ] Group - Ungroup button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [ ] Group - Check if in DarkMode all components gets proper colors (iOS) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [ ] Group - Check if nested Placeholder block can be replaced - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

- [ ] Video block - Switch to classic editor with a video block in page - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc006)

- [ ] Video block - Add Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc003)

- [ ] Video block - Close post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc005)	
- [ ] Media Text block - Close post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc004-v)

- [ ] Video block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc001)
- [ ] Video block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc002)
- [ ] Video block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/video.md#tc004)

- [ ] Undo-redo [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/undo-redo.md)
- [ ] Copy-paste [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md)
- [ ] Splitting blocks [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md)
- [ ] Multiline components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md)
- [ ] Formatting on rich-text based components [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md)
- [ ] Block insertion [(steps)](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/block-insertion.md)

**Comment by maxme** [comment]
> Undo-redo (steps)

Works fine, but the text cursor is stuck on first character when undoing/redoing text events.

> Copy-paste (steps)

Crash everytime I try it :( - doesn't crash on `develop` (I'll test again in debug mode).

> Multiline components (steps)

Stumbled upon an existing issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1651

> Formatting on rich-text based components (steps) (found an issue with the Strikethrough button)

https://github.com/wordpress-mobile/gutenberg-mobile/issues/729

**Comment by hypest** [comment]
Reminder to self: The Appium tests are bundling the JS app into the demo app [to send it for testing](https://github.com/wordpress-mobile/gutenberg-mobile/blob/a1be0c4e4fa2dc063a19edbc72ac5f2fe85d0cf8/package.json#L115) so, should get the bytecode version there too.

**Comment by maxme** [comment]
> Video block - Switch to classic editor with a video block in page - steps
> Video block - Add Caption - steps
> Video block - Close post with an ongoing video upload - steps

Looks good.

> Media Text block - Close post with an ongoing video upload - steps

Got a crash when adding a button block to a media&text block. Note: No crash on current `develop`

> Video block - Insert video from device (failing) - steps
> Video block - Insert video from device (cancel) - steps
> Video block - Close/Re-open post with an ongoing video upload - steps

Looks good.

**Comment by hypest** [comment]
> > Copy-paste (steps)
>
> Crash everytime I try it :( - doesn't crash on develop (I'll test again in debug mode).

Indeed, crashes for me as well, with `TypeError: Cannot read property 'contains' of undefined`.

**Comment by hypest** [comment]
I've added some (temporary) debugging facility, to quickly switch between the bytecode and Text JS versions of the bundle. To use, add `wp.OFFER_GUTENBERG_TEXT_JS_BUNDLE=true` in your `gradle.settings` file and then go into the App Settings in the app to switch between the two options.

What one can immediately see is that Dark Mode doesn't work in the bytecode version. To me, that's an indication of either the two bundles be out of sync or, indeed the bytecode version has various issues atm.

**Comment by hypest** [comment]
We should also give this experiment a go on RN 0.62 to see if the issues are manifesting there or not.

**Comment by hypest** [comment]
The Hermes bytecode improvement has been merged via https://github.com/wordpress-mobile/gutenberg-mobile/pull/2780 so, closing this PR.

**Pull request closed without merging**
