### PR TITLE
Contact Info - Adding Feature Flag + Jetpack API Version Check

### LINKED ISSUE #2166: Contact Info Jetpack enabled in Production
The Contact-info jetpack block was added to gutenberg-mobile behind a DEV flag in this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1934. This issue is tracking the following required tasks remaining before removing the DEV Flag:

2. [ ] WP API Auth support for checking if jetpack is enabled. 
1. [ ] Design Review - (can be tested with App Center build 27246 [link](https://github.com/wordpress-mobile/WordPress-iOS/pull/13918#issuecomment-614964417))

Screenshot_20200409-014328_WordPress

### PR DESCRIPTION
**Pull request by illusaen**
Fixes #2166 

Added native bridge capabilities for iOS and Android in order to determine whether contact info should be shown or not.

#### Notes (@iamthomasbishop): 
1. When logged in and creating a post in a WPcom site, then switching to a self-hosted site via the top dropdown, the Contact Info and Story blocks still show up as there is no refresh. Is this acceptable?
2. I have Contact Info Jetpack version requirement set to 9.1 currently to match Story block as I'm not sure which version to use.

### Links:
* `gutenberg`: [#28168](https://github.com/WordPress/gutenberg/pull/28168)
* `WPiOS`: [#15634](https://github.com/wordpress-mobile/WordPress-iOS/pull/15634)
* ~~`WPAndroid`: [#13758](https://github.com/wordpress-mobile/WordPress-Android/pull/13758)~~
* `WPAndroid`: [#13804](https://github.com/wordpress-mobile/WordPress-Android/pull/13804)
#### Self-hosted
1. Run WP-iOS app.
2. Create self hosted site on [Jurassic Ninja](https://jurassic.ninja).
3. Create blog post.
4. Open block editor and see that there is no contact info block available.
5. Repeat steps 1-4 for WP-Android app.

#### WPcom site
1. Run WP-iOS app.
2. Open Jetpack enabled site.
3. Create blog post.
4. Open block editor and see that contact info block is available.
5. Repeat steps 1-4 for WP-Android app.

### Screenshots:
| iOS | Android |
| - | - |
|  |  |
|  |  |

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by mzorz** [comment]
> When logged in and creating a post in a WPcom site, then switching to a self-hosted site via the top dropdown, the Contact Info and Story blocks still show up as there is no refresh. Is this acceptable?

This is a bug on iOS, as I verified it doesn't happen like this on WPAndroid. Can you file it (and perhaps fix it) on iOS please @illusaen ? What I understand should happen is that `GutenbergProps` should get updated when a site change happens, before loading Gutenberg again

**Review by mzorz — APPROVED** [review]
The changes here look good to me @illusaen ! 🎉 

One thing I noticed, the gutenberg git submodule commit hash wasn't updated in this PR. We should merge `develop` back into your branch so to update it and then also update and add the `gutenberg` submodule commit hash as well. I've done it in a follow up PR of mine which is targeting this PR of yours so, please hold back from merging this one until mine is merged on top of yours first 👍  (we can chat about it too to coordinate)

Nice job! :shipit:

**Comment by mzorz** [comment]
BTW regarding this @illusaen :
> I have Contact Info Jetpack version requirement set to 9.1 currently to match Story block as I'm not sure which version to use.

To check which version of Jetpack shipped with ContactInfo block originally, you can see the commit history in Jetpack
https://github.com/Automattic/jetpack/commit/f6f313d268c336491c8bca1afcf3e5d3663597ce
it seems it was tagged 8.5.beta https://github.com/Automattic/jetpack/releases/tag/8.5-beta
Also judging from dates it seems like that merge commit was made on April 16, 2020, and release 8.5 of jetpack was made on May 5, 2020.
(see SCREENSHOT here)
Screen Shot 2021-01-18 at 10 51 51

TODO: it would be safer to also check whether the Contact Info block on the web side of things is available from that point on (I think it would probably be the case but, just to double check).

**Comment by iamthomasbishop** [comment]
> When logged in and creating a post in a WPcom site, then switching to a self-hosted site via the top dropdown, the Contact Info and Story blocks still show up as there is no refresh. Is this acceptable?

@illusaen I'm not sure on the technical side, but in terms of behavior from the user's perspective, I would expect the list of blocks to reset to whatever the currently-selected site supports, per @mzorz's comment above.

> I have Contact Info Jetpack version requirement set to 9.1 currently to match Story block as I'm not sure which version to use.

I'm not sure on this, but it looks like Mario might've given you an answer above 😄 

---

Before we move forward, I'd like to do a final design review — would you mind creating test builds for [iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/15634) and [Android](https://github.com/wordpress-mobile/WordPress-Android/pull/13758) so I can give it a spin?

**Comment by illusaen** [comment]
> BTW regarding this @illusaen :
> 
> > I have Contact Info Jetpack version requirement set to 9.1 currently to match Story block as I'm not sure which version to use.
> 
> To check which version of Jetpack shipped with ContactInfo block originally, you can see the commit history in Jetpack
> [Automattic/jetpack@f6f313d](https://github.com/Automattic/jetpack/commit/f6f313d268c336491c8bca1afcf3e5d3663597ce)
> it seems it was tagged 8.5.beta https://github.com/Automattic/jetpack/releases/tag/8.5-beta
> Also judging from dates it seems like that merge commit was made on April 16, 2020, and release 8.5 of jetpack was made on May 5, 2020.
> (see SCREENSHOT here)
> Screen Shot 2021-01-18 at 10 51 51
> 
> TODO: it would be safer to also check whether the Contact Info block on the web side of things is available from that point on (I think it would probably be the case but, just to double check).

Took your Android PR, which is set to 8.5, thanks much!!

**Comment by illusaen** [comment]
Closing in favor of https://github.com/wordpress-mobile/gutenberg-mobile/pull/3090 because there were some weird bundle changes that happened in this branch due to merge issues.

**Comment by mzorz** [comment]
Reopening!

this happened
https://github.com/wordpress-mobile/gutenberg-mobile/pull/3037#issuecomment-770809309

look at the changes in this PR https://github.com/wordpress-mobile/gutenberg-mobile/pull/3037/files
so basically:
1. This PR #3037 had the changes that looked weird to us in this PR but these weren’t merged (the PR was closed)
2. but the jetpack / gutenberg repos got their stuff updated, so this PR #3001 got the latest stuff here
3. given `npm bundle` creates the new stuff out of the other 2 repos as well, this PR has the changes that should have made it into develop if the PR at point 1 above was merged first :) 
✨

**Comment by illusaen** [comment]
Changing this PR to only add in the feature flag + Jetpack API version checks; removing the dev flag change to a later PR so that I can first fix the additional bug that @iamthomasbishop found where selecting and then deselecting the Address block results in an unhideable keyboard.

**Pull request merged**
