### PR TITLE
Release 1.109.2

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.109.2

## Related PRs

- https://github.com/WordPress/gutenberg/pull/56782
- https://github.com/wordpress-mobile/WordPress-Android/pull/19732
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22149

## Changes
- https://github.com/WordPress/gutenberg/pull/56653
- https://github.com/WordPress/gutenberg/pull/56686
- https://github.com/WordPress/gutenberg/pull/56723
- https://github.com/WordPress/gutenberg/pull/56684
- https://github.com/WordPress/gutenberg/pull/56752
- https://github.com/WordPress/gutenberg/pull/56757

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
## 🤖 Android ✅ 

- **Build:**[jetpack-prototype-build-pr19732-4dfda8d.apk](https://d2twmm2nzpx3bg.cloudfront.net/8204deb9481772038e97669f4e11f5a5e6b4f94f/jetpack-prototype-build-pr19732-4dfda8d.apk)
- **Device:** Samsung Galaxy S20 FE 5G (Android 13)

### Writing Flow checklist

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
      - 🟡 Encountered the non-regression https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375.
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

### New Changes
- [x] https://github.com/WordPress/gutenberg/pull/56653
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56686
- [x] https://github.com/WordPress/gutenberg/pull/56723
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56684
- [x] https://github.com/WordPress/gutenberg/pull/56752
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56757

**Comment by fluiddot** [comment]
## 🍎 iOS

- **Build:** [jetpack-installable-builds #7061](https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/releases/7061)
- **Device:** iPhone 11 (iOS 17.0.2)

### Writing Flow checklist

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [ ] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [ ] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [ ] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [ ] Paragraph
  - [ ] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [ ] Paragraph
  - [ ] Heading

### New Changes
- [x] https://github.com/WordPress/gutenberg/pull/56653
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56686
- [x] https://github.com/WordPress/gutenberg/pull/56723
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56684
- [x] https://github.com/WordPress/gutenberg/pull/56752
- [ ] [Only reproducible modifying the source code] https://github.com/WordPress/gutenberg/pull/56757

**Comment by SiobhyB** [comment]
## 🍎 iOS

- **Build:** [jetpack-installable-builds #7061](https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/releases/7061)
- **Device:** iPhone XR (iOS 16.6)

### Writing Flow checklist

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

### New Changes
- [x] https://github.com/WordPress/gutenberg/pull/56653
- [ ] [Couldn't reproduce it] https://github.com/WordPress/gutenberg/pull/56686
- [x] https://github.com/WordPress/gutenberg/pull/56723
- [ ] [Couldn't reproduce it] https://github.com/WordPress/gutenberg/pull/56684
- [x] https://github.com/WordPress/gutenberg/pull/56752
- [ ] [Couldn't reproduce it] https://github.com/WordPress/gutenberg/pull/56757

**Review by SiobhyB — APPROVED** [review]
LGTM! Thank you @fluiddot 🙌

**Pull request merged**
