### PR TITLE
Refactor: BottomSheet controls

### LINKED ISSUE #1365: Make `BottomSheet` controls markup consistent with web usage
According to discussion in #1300 we need to add new layer on top of `BottomSheet` controls to make the markup consistent with the web version.

Please check below screen. After changes code on right (native) should use the same controls name under `PanelBody` as on left side (web).

image

### PR DESCRIPTION
**Pull request by jbinda**
Fixes #1365

Please also refer to:
Merge it first gutenberg-mobile PR [Feat: Cross platform InspectorControls](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1341) and [Feat: cover cross platform RangeControl](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342)
[Related gutenberg PR](https://github.com/WordPress/gutenberg/pull/17569)
[Related gutenberg-mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1365)

It presents:
New layer on top of `BottomSheet.Cells` to use controls placed in BottomSheet in the same way as in web version.

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by pinarol** [comment]
@jbinda is this PR ready for review? It is still marked as draft.

**Comment by jbinda** [comment]
@pinarol its in draft because I also need element for Range cell so first I would like have this PR [Feat: Cross platform InspectorControls](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1341) and [Feat: cover cross platform RangeControl](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342) merged

**Comment by etoledom** [comment]
This refactor looks quite good! 

Since the Range cell is new (afaik), is it really a blocker for this PR? Maybe we could go ahead with this one in parallel.

Unless https://github.com/wordpress-mobile/gutenberg-mobile/pull/1342 is merged soon.

**Comment by jbinda** [comment]
I thought it would be nice to merge it all at once but as you said if this refactor is ok we can merge it now and then add Range.Cell implementation

**Comment by pinarol** [comment]
Agreed, I think we can merge this one first. 👍

**Comment by jbinda** [comment]
great! so I will prepare PR to target `master` in gutenberg repo and remove draft flat

**Comment by jbinda** [comment]
I have revert `.gimodules` and update ref to `master` branch and its also ready to merge after CI passed

**Pull request merged**
