### PR TITLE
Release 1.101.1

### PR DESCRIPTION
**Pull request by SiobhyB**
Release for Gutenberg Mobile 1.101.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/53758
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/18996
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/21353

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Change 1: Fixed images not rendering in Help section on iOS
- **PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/6067
- **Issue:** https://github.com/WordPress/gutenberg/issues/53591

Images displayed within the editor's "Help" section were displaying blank boxes rather than the images themselves on iOS. This issue has now been fixed.

### Change 2: Fix the dynamic height when opening/closing navigation screens within the bottom sheet
- **PR:** https://github.com/WordPress/gutenberg/pull/53608
- **Issue:** https://github.com/WordPress/gutenberg/issues/53591

After closing and re-opening the "Help section", content was obscured by the scroll view only populating 50% of the device height. A fix has been merged for both iOS and Android.

### Change 3: Add optional chaining to `reusableBlock.title`
- **PR:** https://github.com/WordPress/gutenberg/pull/53721
- **Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/5496

We've received multiple reports of Gutenberg Mobile crashing with an error evaluating `n.title.raw`. Although we haven't been able to reproduce the crash, a potential fix has been merged.

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will perform additional testing after the main apps cut their releases.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by SiobhyB** [comment]
## 🟢 Writing Flow checklist (Android)
**Build**: [jetpack-prototype-build-pr18996-b1b4376.apk](https://d2twmm2nzpx3bg.cloudfront.net/8204deb9481772038e97669f4e11f5a5e6b4f94f/jetpack-prototype-build-pr18996-b1b4376.apk)
**Device**: Pixel 6 (Android 13)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
    - ⚠️ Known issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375
  - [x] Heading
    - ⚠️ Known issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2375
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Comment by SiobhyB** [comment]
## 🟢 New changes (Android)
**Build**: [jetpack-prototype-build-pr18996-b1b4376.apk](https://d2twmm2nzpx3bg.cloudfront.net/8204deb9481772038e97669f4e11f5a5e6b4f94f/jetpack-prototype-build-pr18996-b1b4376.apk)
**Device**: Pixel 6 (Android 13)

- [x] [iOS only] https://github.com/wordpress-mobile/gutenberg-mobile/pull/6067 
- [x] https://github.com/WordPress/gutenberg/pull/53608
- [x] https://github.com/WordPress/gutenberg/pull/53721

**Comment by SiobhyB** [comment]
## 🟢 Writing Flow checklist (iOS)
**Build**: [jetpack-installable-builds #5781](https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/releases/5781)
**Device**: iPhone XR (iOS 16.5.1)

#### General
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/copy-paste.md#tc001) - Paste formatted text copied from website
#### Rich Text Format
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007) - Test format detection under the cursor
- [x] [TC009](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc009) - Test autocorrection doesn't apply formatting to Heading
- [x] [TC010](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc010) - Test autocorrection doesn't remove formatting from Heading
##### Splitting and merging
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) - Merge after writing
  - [x] Paragraph
  - [x] Heading
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002) - Merge after selection
  - [x] Paragraph
  - [x] Heading
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003) - Merge after deleting text
  - [x] Paragraph
  - [x] Heading
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004) - Merge after deleting all
  - [x] Paragraph
  - [x] Heading
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005) - Merge multiple blocks
  - [x] Paragraph
  - [x] Heading

**Comment by SiobhyB** [comment]
## 🟢 New changes (iOS)
**Build**: [jetpack-installable-builds #5781](https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/releases/5781)
**Device**: iPhone XR (iOS 16.5.1)

- [x] [iOS only] https://github.com/wordpress-mobile/gutenberg-mobile/pull/6067 
- [x] https://github.com/WordPress/gutenberg/pull/53608
- [x] https://github.com/WordPress/gutenberg/pull/53721

**Review by dcalhoun — APPROVED** [review]

**Pull request merged**
