### PR TITLE
Add CI Check for package-lock.json diffs

### PR DESCRIPTION
**Pull request by etoledom**
This PR adds a CI check for changes on `package-lock.json` after running `npm install`.
With this check we will ensure that our `package-lock.json` is always updated and changes are committed.

To test:
- Check CI results for `check-correctness` job
- Check [this previous run](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/8397/workflows/5a4ea911-4f44-40ef-81a7-33bdb3386bf1/jobs/44605) job with this check failing to see output.
- Feel free to do other tests as desired.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
@etoledom Just reminding that we'll be cutting the 1.38 release branch later in the day Monday 9/28. Please try to get this merged by then or bump the milestone. Thanks much 🙇

**Comment by etoledom** [comment]
@ceyhun - could you take a look at this?
cc @hypest since we were chatting about this CI check too.

**Review by ceyhun — APPROVED** [review]
LGTM! Will trigger CI one last time.

**Comment by etoledom** [comment]
Thank you!

**Pull request merged**
