### PR TITLE
Update React Native to version 0.62.2

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update React Native to 0.62.0

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/19950
WordPressAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/11217
WordPressiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/13752
react-native-video PR: https://github.com/wordpress-mobile/react-native-video/pull/5/
react-native-svg PR: https://github.com/wordpress-mobile/react-native-svg/pull/10

To test: Gutenberg Editor should work as expected. 
Try to run manual tests from the list.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
Bumping this PR to 1.34 (the furthest milestone we currently have) since we're getting ready to cut 1.32. Feel free to update the milestone as appropriate.

**Comment by SergioEstevao** [comment]
The current version of this PR is building and running the demo app correctly, but the E2E tests locally and on CI are failing.

The reason for this is that until now the react-native tools for iOS were build the app in the following folder `gutenberg/packages/react-native-editor/ios/build/gutenberg/Build/Products/Release-iphonesimulator/GutenbergDemo.app`

And for the running the E2E tests we have hardcode this path on the following scripts:

 - `gutenberg/packages/react-native-editor/package.json` on the following steps:
  - `test:e2e:bundle:ios`
  - `clean:build-artifacts`
 - `gutenberg/package/react-native-editor/__device-tests__/helpers/utils,js` on the `defaultIOSAppPath`
 - `.circleci/config.yml`
 - `gutenberg/.github/workflows/rnmobile-ios-runner.yml`
 - `package.json` for the following steps:
  - `test:e2e:bundle:ios`
  - `clean:build-artifacts`

The react-native tools in 0.62.2 now build the app to the default folders that are configured inside Xcode at a global level. 
They are now building somewhere inside the Xcode folders.

To solve this there are two possible solutions:

 - change the scripts above to use the new folder  by grabbing the folder with this command `
xcodebuild -workspace gutenberg.xcworkspace -scheme gutenberg -configuration Release -sdk iphonesimulator -showBuildSettings | grep TARGET_BUILD_DIR | cut -d '=' -f2
`
 - Change the build step of the scripts to force the creation of the build artifacts on the old folder.

**Comment by ceyhun** [comment]
We're getting ready to cut the 1.34 release branch, so I'm bumping this to the 1.35 milestone.

**Comment by cameronvoell** [comment]
> We're getting ready to cut the 1.34 release branch, so I'm bumping this to the 1.35 milestone.

Bumping to 1.36

**Comment by cameronvoell** [comment]
Bumping to 1.37

**Comment by jd-alexander** [comment]
Bumping this milestone to 1.38

**Comment by ceyhun** [comment]
Closing in favor of https://github.com/wordpress-mobile/gutenberg-mobile/pull/2580

**Pull request closed without merging**
