### PR TITLE
Initial Port of Jetpack Tiled Gallery Block

### LINKED ISSUE #4268: Merge Jetpack Phase 1B feature branch into master
Merge `rnmobile/add/tiled-gallery-block` into Jetpack `master` and merge its linked PRs into their respective main branches. We're keeping the Tiled Gallery behind a dev-only flag on the mobile apps, so it's not going to be put in production yet.

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4268

#### Related PRs

* Jetpack: https://github.com/Automattic/jetpack/pull/21849
* Android: https://github.com/wordpress-mobile/WordPress-Android/pull/15619
* iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/17618
* Gutenberg: https://github.com/WordPress/gutenberg/pull/37776

#### To test

Please refer to [the Jetpack PR](https://github.com/Automattic/jetpack/pull/21849) as the "central PR" with the most up-to-date testing instructions.

#### Bundle changes

Note, a number of `json` files were removed after running `npm run bundle` on this PR. This was expected following the recent upgrade to React Native 0.66. All `json` files are no longer created under the bundle folder because their content is already being injected into the JS bundle code, so those files are redundant. 

The removal of the files was reverted for this PR, however. This is so that their removal can be more formally tested/approved in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4401.

#### PR submission checklist

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
Next steps:
- [x] Create a Gutenberg PR (@guarani)
- [x] Check the file changes in each of the PRs above to make sure they make sense (e.g. the Gutenberg Mobile PR seems to include unexpected changes in the bundle files, like git conflict resolution markers) (@SiobhyB)
- [x] Add code to the above to make sure the Tiled Gallery is available only on dev builds (@guarani)
- [x] Clean up all PR descriptions as needed (@SiobhyB)
- [x] Add a changelog entry to the Jetpack PR (that will get rid of one of the failing CI checks we normally see) (@guarani)

Anything else?

**Comment by guarani** [comment]
@SiobhyB I added the 1.70.0 milestone (due next Thursday), since we hope to have an approval on the Jetpack PR by then. I figured we can always change this later if needed, but let me know if you think otherwise.
Of course, the Tiled Gallery won't be available on production builds, but I think the milestone is still useful to know in which Gutenberg Mobile version this block was added on development builds.

**Comment by SiobhyB** [comment]
Sounds good to me @guarani!

**Comment by fluiddot** [comment]
Hey @SiobhyB, we will cut the `1.70.0` release on January 20th. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in `1.70.0`, thanks 🙇.

**Review by guarani — APPROVED** [review]
Tested and Square layout working as expected.

**Pull request merged**
