### PR TITLE
Release 1.48.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.48.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/29680
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14221
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16046

- ~~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~~
- ~~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

Includes the changes from `1.47.1` hotfix:

 - Reduce the number of items per page when fetching reusable blocks to prevent a crash: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3227

And changes from `1.47.2` hotfix:

 - Fixes Stories block replacement: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3246

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
## iOS - Smoke tests

**Device:** iPhone 11
**OS:** iOS 14.2
**App:** WPiOS 16.9
**Build:** [43675](https://github.com/wordpress-mobile/WordPress-iOS/pull/16046#issuecomment-794079434)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved
- [x] Verify that the crash when opening a post on a site with more than 27 reusable blocks is fixed (https://github.com/WordPress/gutenberg/pull/29626)

## Issues

### Navigation back animation of Bottom Sheet is different (https://github.com/WordPress/gutenberg/issues/29785) 🟡 

I noticed that the animation when navigating back within the `BottomSheet` component now doesn't animate the size of the sheet. This is also happening on version `16.8` and `16.7` but not in `16.6` so looks like we introduced this change in the previous versions.

<details><summary><strong>Example</strong></summary>

| WPiOS 16.6 | WPiOS 16.9 |
| --- | --- |
| <video src=https://user-images.githubusercontent.com/14905380/110613536-aeede780-8191-11eb-9d55-c98e9e7d74f8.MP4> | <video src=https://user-images.githubusercontent.com/14905380/110613581-bb724000-8191-11eb-998a-e7de14803e31.MP4> |

</details>

### Story block removes all the blocks when adding media (https://github.com/wordpress-mobile/gutenberg-mobile/issues/3243) 🔴 

After adding media to a Story block, it removes all the blocks from the post.

**How to reproduce it:**
1. Add some blocks to a post.
2. Add a Story block.
3. Add a media item.
4. Tap on the right arrow button to continue.
5. Observe that the previous added blocks are removed.

<details><summary><strong>Example</strong></summary>

https://user-images.githubusercontent.com/14905380/110617558-1efe6c80-8196-11eb-992b-592a66f1324e.MP4

</details>

### Story block crash after discarding a media item from the device (https://github.com/wordpress-mobile/gutenberg-mobile/issues/3244) 🔴 

I found a flow that in the latest build of version `16.9` produces a crash.

I managed to reproduce this issue on TestFlight builds of versions `16.8` and `16.9` too, on those versions the app doesn't crash but the flow for adding media items in any block stops working.

**Sentry issue:** https://sentry.io/organizations/a8c/issues/2250393647/events/389dedd8d5484c5c83b6591500862436/?project=1438083&statsPeriod=14d

**How to reproduce it:**
1. Add a Story block.
2. Tap on ADD MEDIA.
3. Tap on the little square button located at the bottom left.
4. Select any item.
5. Tap on Add button.
6. Tap on X button to discard changes.
7. Tap on Discard button.
8. Add an Image block.
9. Tap on ADD IMAGE.
10. Tap on Choose from device.
11. Select any item.
12. Observe that the app crashes.

<details><summary><strong>Example</strong></summary>

https://user-images.githubusercontent.com/14905380/110620131-f6c43d00-8198-11eb-8694-80e07f3d1975.MP4

</details>

**Comment by fluiddot** [comment]
## Android - Smoke tests

**Device:** Samsung Galaxy S20 FE 5G
**OS:** Android 10
**App:** WPAndroid 16.9
**Build:** [98767](https://github.com/wordpress-mobile/WordPress-Android/pull/14221#issuecomment-794310548)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved
- [x] Verify that the crash when opening a post on a site with more than 27 reusable blocks is fixed (https://github.com/WordPress/gutenberg/pull/29626)

## Issues

### Crash when switching dark mode on/off (https://github.com/WordPress/gutenberg/issues/29730) 🔴 

After adding a Shortcode block, switching dark mode on and then off produces a crash. I checked this behaviour with the rest of blocks and looks like it only happens with this one.

I also tested on production version `16.7` and it's also happening here so it's not a new regression.

**Sentry issue:** https://sentry.io/organizations/a8c/issues/1634562844/?project=1438083&project=1438088&query=is%3Aunresolved+user.email%3Afluiddot%40gmail.com&statsPeriod=14d

**How to reproduce it:**
1. Add a Shortcode block.
2. Enable dark mode.
3. Disable dark mode.
4. Observe that the app crash.

<details><summary><strong>Example</strong></summary>

https://user-images.githubusercontent.com/14905380/110669398-93ec9900-81cc-11eb-90b4-8853edda5019.mp4

</details>

**Comment by jd-alexander** [comment]
## Android - Smoke tests

**Device:** Google Pixel 4 XL
**OS:** Android 10
**App:** WPAndroid 16.9
**Build:** [98767](https://github.com/wordpress-mobile/WordPress-Android/pull/14221#issuecomment-794310548)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved
- [x] Verify that the crash when opening a post on a site with more than 27 reusable blocks is fixed (https://github.com/WordPress/gutenberg/pull/29626)
- [x] Verify that the splitting/merging functionality is intact (https://github.com/WordPress/gutenberg/pull/29680/commits/956cdfc2a3aedfa2594d3adcde8a22ce19df7ba6)

-----

### Issues

- I observed the iOS issues with the Story block as well. 
- I also observed the Shortcode dark mode error.

**Comment by jd-alexander** [comment]
> I noticed that the animation when navigating back within the BottomSheet component now doesn't animate the size of the sheet. This is also happening on version 16.8 and 16.7 but not in 16.6 so looks like we introduced this change in the previous versions.

Good catch! Do you think it's worth creating an issue to track this to dig into it further?

**Comment by fluiddot** [comment]
> > I noticed that the animation when navigating back within the BottomSheet component now doesn't animate the size of the sheet. This is also happening on version 16.8 and 16.7 but not in 16.6 so looks like we introduced this change in the previous versions.
> 
> Good catch! Do you think it's worth creating an issue to track this to dig into it further?

Yeah I think so, I'll open an issue as soon as possible 👍 .

**Comment by fluiddot** [comment]
## Android - Smoke tests - Second round

**Device:** Samsung Galaxy S20 FE 5G
**OS:** Android 10
**App:** WPAndroid 16.9
**Build:** [98996](https://github.com/wordpress-mobile/WordPress-Android/pull/14221#issuecomment-794310548)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved
- [x] Verify that the crash when opening a post on a site with more than 27 reusable blocks is fixed (https://github.com/WordPress/gutenberg/pull/29626)

## Issues

### Styles are not updated after switching dark mode on/off (https://github.com/WordPress/gutenberg/issues/29786) 🟡 

After switching dark mode on, new blocks added have the styles of the light mode. The same happens the other way around, blocks have dark mode styles when switching dark mode off.

**How to reproduce it:**
1. Add some blocks.
2. Switch dark mode on.
3. Add more blocks.
4. Observe that the new blocks have light mode styles instead of dark mode.

<details><summary><strong>Example</strong></summary>

https://user-images.githubusercontent.com/14905380/110788902-863c1f80-826f-11eb-852f-aab5fe7f1c26.mp4

</details>

**Comment by fluiddot** [comment]
## iOS - Smoke tests - Second round

**Device:** iPhone 11
**OS:** iOS 14.2
**App:** WPiOS 16.9
**Build:** [43794](https://github.com/wordpress-mobile/WordPress-iOS/pull/16046#issuecomment-794079434)

- [x] TC001 - Paste formatted text copied from website
- [x] Typing in paragraph and heading block
- [x] Block insertion - Test Cases
- [x] Splitting/merge paragraph block
- [x] Undo/redo text
- [x] Switching dark mode on/off
- [x] Adding an image block and upload an image from device
- [x] Entering/exiting the editor
- [x] Rotate the device in various cases
- [x] Open and dismiss the bottom sheet
- [x] Background the app and foreground it again
- [x] Make some changes in a post, close the app, open it again and verify that the changes are saved
- [x] Verify that the crash when opening a post on a site with more than 27 reusable blocks is fixed (https://github.com/WordPress/gutenberg/pull/29626)
- [x] Verify that the Story block issues mentioned in the [previous comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3237#issuecomment-795130908) are fixed.

Test plan for verifying Story block issues: https://github.com/wordpress-mobile/WordPress-iOS/pull/16059:
  - [x] New Story Post
  - [x] New Post with Story block
  - [x] Editing an existing post
  - [x] Discarding edits to a post
  - [x] Discarding edits in Kanvas

**Comment by fluiddot** [comment]
## Smoke testing results

All fixes have been applied and tests passed, we spotted some issues but none are new regressions and neither critical.

### Issues found
- Navigation back animation of Bottom Sheet is different (https://github.com/WordPress/gutenberg/issues/29785) 🟡
- Story block removes all the blocks when adding media (#3243) 🟢  (solved!)
- Story block crash after discarding a media item from the device (#3244) 🟢  (solved!)
- Crash when switching dark mode on/off (WordPress/gutenberg#29730) 🔴
- Styles are not updated after switching dark mode on/off (https://github.com/WordPress/gutenberg/issues/29786) 🟡

**Review by jd-alexander — APPROVED** [review]
LGTM. All issues have been tracked and all blockers have been resolved. Non-blockers will be triaged and resolved for future releases.

**Pull request merged**
