### PR TITLE
[Embed block] Enable embed preview for a list of providers

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/34446

To test:
Follow testing instructions from `gutenberg` PR: https://github.com/WordPress/gutenberg/pull/34446.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/34446. Need to update Gutenberg reference after the mentioned PR is merged to `trunk`.

**Comment by mkevins** [comment]
Hi @fluiddot :wave: :smile: . We will be cutting the 1.61.0 release either today, or tomorrow, depending on the resolution of another issue. Since this PR is already approved, I haven't bumped the milestone. I see that there is [an unresolved lint issue](https://github.com/WordPress/gutenberg/pull/34446#issuecomment-910461502) on the related Gutenberg PR, so please let me know if you'd like to get this into the 1.61.0 release, or if not, I can bump the milestone. Thanks!

**Comment by fluiddot** [comment]
> Hi @fluiddot 👋 😄 . We will be cutting the 1.61.0 release either today, or tomorrow, depending on the resolution of another issue. Since this PR is already approved, I haven't bumped the milestone. I see that there is [an unresolved lint issue](https://github.com/WordPress/gutenberg/pull/34446#issuecomment-910461502) on the related Gutenberg PR, so please let me know if you'd like to get this into the 1.61.0 release, or if not, I can bump the milestone. Thanks!

Hey @mkevins 👋 , I'd like if possible to get this into `1.61.0`. I've just seen that the lint issue that blocks this PR is already solved so I'll update the branch and merge it. I'll let you know when it's ready, thanks 🙇 !

**Comment by fluiddot** [comment]
The PR is finally merged so it will be included in `1.61.0`.

cc @mkevins @antonis

**Pull request merged**
