### PR TITLE
[UI tests] Run canaries on a PR and optionally full suite

### PR DESCRIPTION
**Pull request by Stojdza**
In this PR I added a couple of options to make test runs more stable. 

1. **Run only a subset of tests (canaries) on every PR** - this will shorten execution time for UI tests jobs in CircleCI. All [tests marked with `@canary`](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2137/files#diff-63d46a3d5d8db0e8f1c48b497cd83222R19) will be part of these. Name of these jobs are _Test Android on Device - Canaries_ and _Test iOS on Device - Canaries_ and they are mandatory for every PR. I marked three tests with the `@canary` and we can change that and choose other tests if needed. @hypest once this PR is approved and ready to merge, we should change required jobs for `develop` branch - canaries should be marked as required and `Test Android/iOS on Device` should be unchecked. 
2. **Optionally run the full suite of UI tests** - If necessary, you can run the full suite. A comment will be posted on a PR, see [example](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2137#issuecomment-611176621) below, which will lead to CircleCI workflow where you can start Android and iOS jobs. I did this with [peril-settings](https://github.com/Automattic/peril-settings/pull/43/files), similar to what we are using in other mobile projects. **EDIT:** Full suite will run every day against `develop`, per schedule https://github.com/wordpress-mobile/gutenberg-mobile/pull/2115
3. **Increase CircleCI timeout** - In the past, we were seeing error `Too long with no output (exceeded 10m0s): context deadline exceeded`. This is happening because some tests are taking too long (more than 10m) without any output during execution, and CircleCI job will fail. I [increased the timeout to 20m](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2137/files#diff-1d37e48f9ceff6d8030570cd36286a61R88) to reduce noise. 

To test:
- Look at the jobs in this PR, compare times. 
- Optionally, add some dummy commit to trigger jobs. Open the link from the comment and trigger full suite jobs. Does it work as expected? 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by rachelmcr** [comment]
@Stojdza There's a lot of repetition between the canary and full jobs in the CircleCI config. What do you think of using a more DRY approach with a single device test job per platform, using a parameter to determine whether it's a full run or just canaries?

That way, for example, we could have a single `android-device-checks` job in the config and just change the parameter in the workflows, instead of `android-device-checks` and `android-device-checks-canary` where most of the steps are the same.

(Sorry for the delay looking at this; I didn't realize until recently that it was still open and waiting for review.)

**Comment by rachelmcr** [comment]
Also, do you know why `ci/circleci: Test Android on Device` and `ci/circleci: Test iOS on Device` still show up as expected checks on this PR? My guess is because they're marked as required in our branch protection rules, but I wanted to point that out in case there's something else involved. (We'll also want to make sure to update the branch protection rules to remove that required check and switch to the Canaries as the required check, I guess?)

**Comment by Stojdza** [comment]
Thanks for looking into this @rachelmcr. It's never too late 😄 

> What do you think of using a more DRY approach with a single device test job per platform, using a parameter to determine whether it's a full run or just canaries?

I agree! I know back then it was easier just to copy and paste, and test jobs. Later I forgot to solve it properly. I can take a look at it later this week if that works?

> Also, do you know why ci/circleci: Test Android on Device and ci/circleci: Test iOS on Device still show up as expected checks on this PR?

Yes. If you take a look [here](https://github.com/wordpress-mobile/gutenberg-mobile/settings/branch_protection_rules/3122421), under _Require status checks to pass before merging_, you'll notice that `Test Android on Device - Canaries` and `Test iOS on Device - Canaries` are not checked/mandatory, and `Test Android on Device` and `Test iOS on Device` are mandatory. While I tested these changes, @hypest changed these settings for me (since I didn't have permissions) and it looked as expected. That's why I put this notice in the description:

>  @hypest once this PR is approved and ready to merge, we should change required jobs for develop branch - canaries should be marked as required and `Test Android/iOS on Device` should be unchecked.

**Comment by rachelmcr** [comment]
> I can take a look at it later this week if that works?

Works for me, thank you! Let me know if you can't fit it in with the other things you're working on now and I can take a look.

> That's why I put this notice in the description

Ah yeah, thanks for confirming! I saw that the first time I read the description but overlooked it when I reread it for this review. :)

**Comment by Stojdza** [comment]
@rachelmcr I added agreed changes. Let me know what do you think. Tests are running as expected - only three tests as canaries and full suite upon approval.

**Comment by Stojdza** [comment]
@maxme @hypest we should sync on this:

> once this PR is approved and ready to merge, we should change required jobs for develop branch - canaries should be marked as required and Test Android/iOS on Device should be unchecked.

Once you're ready to change required jobs we can merge this PR.

**Comment by hypest** [comment]
Thanks for the ping @Stojdza, I made the change and now PRs against develop will only require the Canaries, not the full device testsuite.

Also, can you update the PR description to mention that the full will indeed run anyway, based on a schedule? Thanks!

**Comment by Stojdza** [comment]
Thanks @hypest! I updated PR description.

**Pull request merged**
