### PR TITLE
Align Range Control (Android Slider component) to the left of it's container

### LINKED ISSUE #2667: [Android] Align slider with the content on the left
Sliders on Android aren't aligned with the content on the left. Ideally we can line the slider up with the left of the text:

Screenshot_20200914-232738 png+%2810802160%29+2020-09-23+15-40-21

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #2667
This aligns the Slider component within the Range Control to the left on Android devices
To test:
https://github.com/WordPress/gutenberg/pull/25660
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
@jd-alexander Just reminding that we'll be cutting the 1.38 release branch later in the day Monday 9/28. Please try to get this merged by then or bump the milestone. Thanks much 🙇

**Review by guarani — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/25660#pullrequestreview-501459256.

**Comment by jd-alexander** [comment]
@guarani how can I resolve this since the other PR was just merged? Is there an approach to doing this? I should have linked this in the description of the associated PR. I just realized there's now a gutenberg conflict.

**Comment by ceyhun** [comment]
@jd-alexander We'll be cutting the 1.39 release soon, you have 3 options: 
1. merge the PR as soon as possible 
1. bump the PR to the next milestone
1. remove the milestone from the PR

**Comment by jd-alexander** [comment]
@ceyhun getting this resolved and merged in shortly.

**Pull request merged**
