### PR TITLE
Add support for Story block rendering on mobile gutenberg

### PR DESCRIPTION
**Pull request by mzorz**
This PR adds support for the jetpack Story block to be rendered on mobile-gutenberg.
Related Jetpack PR: https://github.com/Automattic/jetpack/pull/17140
Related Gutenberg PR: https://github.com/WordPress/gutenberg/pull/25242
Related WPAndroid PR: https://github.com/wordpress-mobile/WordPress-Android/pull/12939 and https://github.com/wordpress-mobile/WordPress-Android/pull/13130
Related WPIOS PR: **_TBD_**

To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
So, the tests are failing here because of this:
https://github.com/Automattic/jetpack/blob/d8c065808df80612d1fbec19c35156de4fb00d95/extensions/blocks/story/index.js#L48

The test suite can't find a definition for category, so it falls to this error:
https://github.com/Automattic/jetpack/blob/d8c065808df80612d1fbec19c35156de4fb00d95/extensions/shared/get-category-with-fallbacks.js#L33

We would need to mock `getCategories()` for these kind of things to work on tests.

**EDIT:**

There's already a `getCategories` mock we can use:
https://github.com/wordpress-mobile/gutenberg-mobile/blob/33f2addaab7f5338f791d968680cb6f1e97b4ffa/src/test/index.js#L6

If we change this line with something like this, tests should start passing:
`getCategories: () => [ { slug: 'media'} ],`

**Comment by mzorz** [comment]
> The test suite can't find a definition for category, so it falls to this error:
[...]

Thank you for showing me the insight of it @etoledom 🙇  - fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/2611/commits/7c7430cf026148db0bfea6392cf938f27c43e237

Now the tests are failing because we need to install `@automattic/color-studio` which can be done by running `npm install` within the `gutenberg-mobile/jetpack` submodule, but I'm not really sure how to write that directive in the CI config (https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/.circleci/config.yml#L22) cc @enejb for the pointers and @loremattei maybe you know where / how? 🙏

**Comment by guarani** [comment]
👋 Hi @mzorz, it looks like https://github.com/wordpress-mobile/WordPress-Android/pull/12939 is already merged, and it references a gutenberg-mobile submodule commit from this PR (although not the latest commit). Does that mean this PR, the Gutenberg PR https://github.com/WordPress/gutenberg/pull/25242, are already approved too?

**Comment by mzorz** [comment]
> 👋 Hi @mzorz, it looks like wordpress-mobile/WordPress-Android#12939 is already merged, and it references a gutenberg-mobile submodule commit from this PR (although not the latest commit). Does that mean this PR, the Gutenberg PR WordPress/gutenberg#25242, are already approved too?

Most of the work on the subsequent PRs was approved and even superseded the original work there so yeah :) but I'm holding off until I can fix the tests here and make sure it works alright on CI.
Also I've seen your comments and will address them shortly as well on the PRs where you made comments 👍 - will let you know

**Review by etoledom — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/26721#pullrequestreview-525385586

**Pull request merged**
