### PR TITLE
Update react-native-aztec submodule

### PR DESCRIPTION
**Pull request by mzorz**
This PR just updates the commit hash for `react-native-aztec` submodule to the latest in `master` in that repo - it is of interest to update this as of the following additions / fixes in the Aztec RN wrapper component:
- Add support for placeholder text https://github.com/wordpress-mobile/react-native-aztec/pull/39
- Fix blinking cursor https://github.com/wordpress-mobile/react-native-aztec/pull/41

To test:
```
cd gutenberg-mobile
yarn clean:install
yarn start --reset-cache

(on another window)
yarn android
yarn ios
```

### CODE REVIEW

**Comment by hypest** [comment]
👋 Any highlights to look out for from the latest `react-native-aztec` perhaps?

**Comment by mzorz** [comment]
> Any highlights to look out for from the latest react-native-aztec perhaps?

Good call, just updated the PR description with the particular things that are meaningful for this commit hash to be upgraded 👍

**Comment by hypest** [comment]
Thanks for the updated description @mzorz !

Ah, I see. It seems that these submodule updates are already included in #81 so, if it's OK with you and you 👍 this comment I can go ahead and close this PR.

**Comment by mzorz** [comment]
Sure thing to ahead @hypest ! 🙇

**Comment by hypest** [comment]
Closing in favor of #81 which includes the same updates.

**Pull request closed without merging**
