### PR TITLE
Fix keyboard hide button

### LINKED ISSUE #952: [iOS]Keyboard hide button is not working on post title
**Steps to reproduce:**

Focus on title
Tap keyboard down button
Keyboard is not hidden

**Expected behavior:**

Keyboard is hidden

keyboard-hide

### PR DESCRIPTION
**Pull request by geriux**
Fixes #952

Full description of the fix is in the description of the [related Gutenberg PR](https://github.com/WordPress/gutenberg/pull/17260).

Update release notes:

There aren't any user-facing changes

### CODE REVIEW

**Comment by pinarol** [comment]
Thanks for the gutenberg-mobile PR. This is looking good but let's not merge this one yet since it is brining [another gutenberg PR](https://github.com/WordPress/gutenberg/pull/16932) that makes the editor crash.

Screen Shot 2019-08-23 at 12 02 32

**Comment by pinarol** [comment]
Could you update gutenberg subrepo to point to `rnmobile/master`?

**Comment by pinarol** [comment]
I think CI is failing because it can't checkout submodule `react-native-aztec`, it looks like you'll either need to fork react-native-aztec too or open the PR within gutenberg-mobile repo directly, I gave you access in gutenberg-mobile repo, you should be able to do that.

**Comment by geriux** [comment]
On it! Was waiting to see if I got the other one right. Thanks!

**Comment by geriux** [comment]
Closing, new PR here https://github.com/wordpress-mobile/gutenberg-mobile/pull/1340

**Comment by etoledom** [comment]
> Closing, new PR here #1340

Closing by @geriux [comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1321#issuecomment-526530681)

**Pull request closed without merging**
