### PR TITLE
Sync RichText with web counterparts

### PR DESCRIPTION
**Pull request by SergioEstevao**
This PR updates the rich text components in GB-mobile to be more in line with their web counterparts.

All the work is done in this GB PR: https://github.com/WordPress/gutenberg/pull/17897

To test:
 Because of the nature of the changes a lot of editing experience needs to be retested, please check the following:
 - Selection of text blocks by tapping directly on the text part.
 - Writing on text blocks (paragraph, heading, lists, quotes)
 - Split and merge of text blocks (try on all text blocks and also merges of different kind of blocks)
 - Try split and merge on lists with indents
 - Test copy/paste of:
   - normal text
   - html text
   - images
Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by etoledom** [comment]
Thanks @SergioEstevao for handling this!
I just noticed that the `gutenberg` commit hash seems to be wrong 🤔 
Could you please check that out? Thanks!

**Comment by etoledom** [comment]
Moved this PR to the milestone `1.16`.

If this need to ship on v1.15, please feel free to change back the milestone and reference the release branch.

**Comment by daniloercoli** [comment]
**Update:**
I've found an issue where pasting HTML content that has styling doesn't update the formatting toolbar properly, and inserting new text doesn't apply the styling. 
See the video  https://cloudup.com/cGRbhwsx59Y

- Add a Paragraph block
- Paste HTML content that starts with Bold formatting, and ends with normal formatting

1st issue:
- After the paste is completed the caret is set at the beginning of the block and doesn't have the `B` formatting option enabled on the selection. You see that `B` is not highlighted in the toolbar,  start typing does't use the B style


2nd issue (See the end of the video):
- There are cases where you set the caret to a styled part of text, say Bold, and the formatting toolbar is not highlighted
- More, if you start typing where you set the caret you get normal text
device-2019-10-29-113525

Didn't test on current `develop` though.

**Comment by SergioEstevao** [comment]
@danilo those bugs also happen in develop, it was a explicit option to not make the format toolbar item active when at the start of a format. 

@tug can confirm this.

**Comment by daniloercoli** [comment]
I don't see the same behavior on `develop`.
- I tried by pasting the same content of above, and it does add a new empty paragraph at the end, and the caret is placed there
- When i move the caret between Bold styled text, and normal text, the Toolbar `B` button is properly highlighted. Instead in the video above, you can see at the end that I moved back the caret to Bold text, but the button is kept "off"

Tested on Android 7.1 with Google Keyboard.

**Comment by daniloercoli** [comment]
The issue reported above
> When i move the caret between Bold styled text, and normal text, the Toolbar B button is properly highlighted. Instead in the video above, you can see at the end that I moved back the caret to Bold text, but the button is kept "off"

was fixed with the upgrade of GB to https://github.com/wordpress-mobile/gutenberg-mobile/pull/1437/commits/4f7be60872da1e53fd44a56c287a35e6cd9dddd7

The other behavior is now in par with the web.

**Pull request merged**
