### PR TITLE
Release 1.50.0

### PR DESCRIPTION
**Pull request by guarani**
Release for Gutenberg Mobile 1.50.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/30418
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14386
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16202

## Extra PRs that Landed After the Release Was Cut

- [Gutenberg Plugin: Remove deprecations planned for 10.3 release](https://github.com/WordPress/gutenberg/pull/30417) (needed to fix static analysis error)

## Changes

* [a11y: Screenreader improvements for the UnitControl component](https://github.com/WordPress/gutenberg/pull/29741)
* [Block split/merge fix for a (never shipped) regression (Android only)](https://github.com/WordPress/gutenberg/pull/29683)

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [ ] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by jd-alexander** [comment]
For the task `ci/circleci: Build Android RN Bridge & Publish to Bintray` the output is 
`Build initiated from a feature branch with no pull request: aborting.` I am thinking this means this needs to be re-run?

Re-running since this PR exists.

**Review by mchowning — APPROVED** [review]
Smoke tested the demo app, WPAndroid, and WPiOS and didn't see any issues.

I looked into the merge conflict a little, and it looks like that is occurring because the PR merging `trunk` into `develop` for 1.49.0 squashed the commits after resolving the conflicts, so now the conflicts are reappearing since GitHub doesn't realize they were already resolved. In other words, the presence of conflicts in this PR doesn't seem to indicate that anything is wrong.

**Review by jd-alexander — APPROVED** [review]
Looking good. LGTM 🚢

**Comment by geriux** [comment]
## Android (Test Suite 2) 🟡

- Device: Redmi Note 8T
- Build: [17.1-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/17.1-rc-1)

### DarkMode - 1

- [x] Gallery block - Dark mode - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003

### Group - 1

- [x] Group - AppenderButton is rendered - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] ~Group - Deep nesting is possible (iOS only) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)~
- [x] Group - Check if Group placeholder is visible for the unselected state - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] Group - Nested block have proper margins values - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

### Spacer - 1

- [x] Spacer block - Spacer is rendered without crash - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

### Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)

### Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

### Buttons-3

- [x] Buttons block - Wrapping Buttons - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)
- ⚠️ The `Space between` alignment shows in the toolbar but currently doesn't work because there's no support for it, items remain aligned to the left ([issue](https://github.com/WordPress/gutenberg/issues/30560)) I don't think it's a blocker for the release.

### Button-6

- [x] Buttons block - Settings: Open in new tab - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [x] Buttons block - Settings: Synchronize with button options - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

### Color Settings - 1
- [x] Colors Segmented Controls - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] ❌ Scroll color palette to start - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- ⚠️ It doesn't auto-scroll to the beginning ([issue](https://github.com/WordPress/gutenberg/issues/30566))
- [x] Scroll color palette to the end - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

### Image - 1
- [x] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc001)
- [x] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc002)
- [x] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc003)
- [x] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc004)
- [x] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc005)

### Story block - 1
- [x] Story block - Verify is available in Block Picker - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc001)
- [x] Story block - Verify is not available in Block Picker- [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc002)
- [x] Story block - Add media to empty Story block - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc003)
- [x] ❌ Story block - Add media to non-empty Story block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc004)
- ⚠️ I encountered some issues but not sure if its related to my device or not see video below (issue TBD)
- [x] Story block - Close/Re-open post with an ongoing Story upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc005)


#### ❌ Story block - Add media to non-empty Story block

When trying to edit an non-empty story block I found some issues:

- When opening its all black, you have to select the second story for the content to show up, once you do that you can select the first one and see it too.
- The text added to the first story get removed

https://user-images.githubusercontent.com/4885740/113867380-c16a3980-97ae-11eb-95ca-b1fabb568b10.mp4</p>

**Comment by jd-alexander** [comment]
## Writing Flow - Android

I tested the [writing Flow](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) cases on version [17.1-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/17.1-rc-1)  of the WordPress Android release.

---

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by guarani** [comment]
## Writing Flow - iOS

Testing [Writing Flow](https://github.com/wordpress-mobile/test-cases/tree/trunk/test-cases/gutenberg/writing-flow) cases on 17.1 (17.1.0.0) beta from Test Flight:

---

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components (⚠️ https://github.com/WordPress/gutenberg/issues/30548)
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by geriux** [comment]
Hey @mzorz 👋 while doing some sanity tests for the Story block on Android I encountered an issue and I was wondering if this is known, if it's something new or just specific to the device I used.

Can you please take a look at the issue I described here https://github.com/wordpress-mobile/gutenberg-mobile/pull/3324#issuecomment-814660455 I added a video at the end of the comment. Thanks!

**Comment by geriux** [comment]
**Update**:

#### ❌ Story block - Add media to non-empty Story block

> When opening its all black, you have to select the second story for the content to show up, once you do that you can select the first one and see it too.

This one is being investigated.

> The text added to the first story get removed

There's an open [issue](https://github.com/Automattic/stories-android/issues/581) for this one already.

#### Buttons block - Buttons alignment options - TC007
> ⚠️ The Space between alignment shows in the toolbar but currently doesn't work because there's no support for it, items remain aligned to the left (issue) I don't think it's a blocker for the release.

A PR [was opened](https://github.com/WordPress/gutenberg/pull/30593) to disable this new alignment but this won't be a blocker since it's not a new regression for this release.

**Comment by geriux** [comment]
**Update**:

#### ❌ Story block - Add media to non-empty Story block

It is not a blocker for the Gutenberg mobile release, an [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/14430) was opened to fix it that and will be included either in [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android) or [stories-android](https://github.com/Automattic/stories-android).

With that, there aren't any blockers from Android (Test Suite 2).

**Pull request merged**
