### PR TITLE
Update i18n makepot scripts

### PR DESCRIPTION
**Pull request by mchowning**
This PR addresses #939 by updating our `makepot` script. This PR does _not_ get us any closer to automating the translation of these strings however, they still need to be copied into the native app projects manually in order to get them translated.

### Description

These scripts stopped working because the gutenberg project changed to
only obtain translations from files in the build folder after the
project was built. As a result, gutenberg is not getting translations
for any *.native.js files. This addresses that by:

1. Performing a gutenberg build and obtaining a pot file from`gutenberg/build/`.

2. Generating a gutenberg-mobile pot file based on the contents of`./src/*.js` and `./gutenberg/*.native.js`, while also excluding anything already contained in the gutenberg pot file that was generated in step 1.

### Update release notes

There are no user facing changes, so the release notes have _not_ been updated.

### Test
Run  `yarn makepot` and verify the resulting `gutenberg-mobile.pot` file contains strings that would not have been picked up in the gutenberg translations. Below is what I get in `gutenberg-mobile.pot` when I run this script on dc0f71d8.

<details>
<summary>gutenberg-mobile.pot</summary>
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-13 18:11-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: gutenberg/packages/format-library/build-module/link/modal.native.js:148
#: gutenberg/packages/format-library/src/link/modal.native.js:107
msgid "Link inserted"
msgstr ""

#: gutenberg/packages/format-library/build-module/link/modal.native.js:183
#: gutenberg/packages/format-library/src/link/modal.native.js:141
#: gutenberg/packages/block-library/build-module/image/edit.native.js:288
#: gutenberg/packages/block-library/src/image/edit.native.js:237
msgid "Add URL"
msgstr ""

#: gutenberg/packages/format-library/build-module/link/modal.native.js:193
#: gutenberg/packages/format-library/src/link/modal.native.js:151
msgid "Link Text"
msgstr ""

#: gutenberg/packages/format-library/build-module/link/modal.native.js:195
#: gutenberg/packages/format-library/src/link/modal.native.js:153
msgid "Add Link Text"
msgstr ""

#: gutenberg/packages/block-library/build-module/video/video-player.native.js:81
#: gutenberg/packages/block-library/build-module/video/video-player.native.js:87
#: gutenberg/packages/block-library/src/video/video-player.native.js:55
#: gutenberg/packages/block-library/src/video/video-player.native.js:61
msgid "Problem opening the video"
msgstr ""

#: gutenberg/packages/block-library/build-module/video/video-player.native.js:81
#: gutenberg/packages/block-library/src/video/video-player.native.js:55
msgid "No application can handle this request. Please install a Web browser."
msgstr ""

#: gutenberg/packages/block-library/build-module/video/video-player.native.js:87
#: gutenberg/packages/block-library/src/video/video-player.native.js:61
msgid "An unknown error occurred. Please try again."
msgstr ""

#: gutenberg/packages/block-library/build-module/paragraph/edit.native.js:91
#: gutenberg/packages/block-library/src/paragraph/edit.native.js:80
#: gutenberg/packages/components/build-module/mobile/html-text-input/index.native.js:96
#: gutenberg/packages/components/src/mobile/html-text-input/test/index.native.js:25
#: gutenberg/packages/components/src/mobile/html-text-input/index.native.js:84
#: gutenberg/packages/block-editor/build-module/components/default-block-appender/index.native.js:33
#: gutenberg/packages/block-editor/src/components/default-block-appender/index.native.js:32
msgid "Start writing…"
msgstr ""

#: gutenberg/packages/block-library/build-module/paragraph/index.native.js:29
#: gutenberg/packages/block-library/build-module/image/index.native.js:20
#: gutenberg/packages/block-library/src/paragraph/index.native.js:26
#: gutenberg/packages/block-library/src/image/index.native.js:19
msgid "Empty"
msgstr ""

#: gutenberg/packages/block-library/build-module/heading/index.native.js:32
#: gutenberg/packages/block-library/src/heading/index.native.js:29
#, javascript-format
msgid "Level %s. Empty."
msgstr ""

#: gutenberg/packages/block-library/build-module/heading/index.native.js:34
#: gutenberg/packages/block-library/src/heading/index.native.js:34
#, javascript-format
msgid "Level %1$s. %2$s"
msgstr ""

#: gutenberg/packages/block-library/build-module/missing/edit.native.js:43
#: gutenberg/packages/block-library/src/missing/edit.native.js:24
msgid "Unsupported"
msgstr ""

#: gutenberg/packages/block-library/build-module/image/media-upload-progress.native.js:172
#: gutenberg/packages/block-library/src/image/media-upload-progress.native.js:122
msgid ""
"Failed to insert media.\n"
"Please tap for options."
msgstr ""

#: gutenberg/packages/block-library/build-module/image/edit.native.js:295
#: gutenberg/packages/block-library/src/image/edit.native.js:245
msgid "Alt Text"
msgstr ""

#: gutenberg/packages/block-library/build-module/image/edit.native.js:301
#: gutenberg/packages/block-library/src/image/edit.native.js:252
msgid "Clear All Settings"
msgstr ""

#: gutenberg/packages/block-library/build-module/image/edit.native.js:378
#: gutenberg/packages/block-library/src/image/edit.native.js:329
msgid "Double tap and hold to edit"
msgstr ""

#: gutenberg/packages/block-library/build-module/image/edit.native.js:408
#: gutenberg/packages/block-library/src/image/edit.native.js:352
msgid "Image caption. Empty"
msgstr ""

#: gutenberg/packages/block-library/build-module/image/edit.native.js:410
#: gutenberg/packages/block-library/src/image/edit.native.js:355
#, javascript-format
msgid "Image caption. %s"
msgstr ""

#: gutenberg/packages/block-library/build-module/nextpage/edit.native.js:30
#: gutenberg/packages/block-library/src/nextpage/edit.native.js:28
#, javascript-format
msgid "Page break block. %s"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/cell.native.js:165
#: gutenberg/packages/components/src/mobile/bottom-sheet/cell.native.js:133
#, javascript-format
msgid "%s. Empty"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/cell.native.js:168
#: gutenberg/packages/components/src/mobile/bottom-sheet/cell.native.js:139
#, javascript-format
msgid "%1$s, %2$s"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/cell.native.js:177
#: gutenberg/packages/components/src/mobile/bottom-sheet/cell.native.js:152
msgid "Double tap to edit this value"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/switch-cell.native.js:30
#: gutenberg/packages/components/src/mobile/bottom-sheet/switch-cell.native.js:29
#, javascript-format
msgid "%s. On"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/switch-cell.native.js:32
#: gutenberg/packages/components/src/mobile/bottom-sheet/switch-cell.native.js:34
#, javascript-format
msgid "%s. Off"
msgstr ""

#: gutenberg/packages/components/build-module/mobile/bottom-sheet/switch-cell.native.js:38
#: gutenberg/packages/components/src/mobile/bottom-sheet/switch-cell.native.js:45
msgid "Double tap to toggle setting"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:25
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:26
#, javascript-format
msgid "Move block up from row %1$s to row %2$s"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:25
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:30
msgid "Move block up"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:30
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:35
msgid "Double tap to move the block up"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:35
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:42
#, javascript-format
msgid "Move block down from row %1$s to row %2$s"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:35
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:46
msgid "Move block down"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-mover/index.native.js:40
#: gutenberg/packages/block-editor/src/components/block-mover/index.native.js:51
msgid "Double tap to move the block down"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block-invalid-warning.native.js:17
#: gutenberg/packages/block-editor/src/components/block-list/block-invalid-warning.native.js:14
#, javascript-format
msgid "%s block. This block has invalid content"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block-invalid-warning.native.js:20
#: gutenberg/packages/block-editor/src/components/block-list/block-invalid-warning.native.js:21
msgid "Problem displaying block"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block.native.js:107
#: gutenberg/packages/block-editor/src/components/block-list/block.native.js:89
#, javascript-format
msgid "%s Block"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block.native.js:111
#: gutenberg/packages/block-editor/src/components/block-list/block.native.js:94
#, javascript-format
msgid "Row %d."
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/index.native.js:171
#: gutenberg/packages/block-editor/src/components/block-list/index.native.js:149
msgid "ADD BLOCK HERE"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block-mobile-toolbar.native.js:36
#: gutenberg/packages/block-editor/src/components/block-list/block-mobile-toolbar.native.js:37
#, javascript-format
msgid "Remove block at row %s"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/block-list/block-mobile-toolbar.native.js:40
#: gutenberg/packages/block-editor/src/components/block-list/block-mobile-toolbar.native.js:43
msgid "Double tap to remove the block"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:43
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:36
msgid "ADD IMAGE"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:45
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:38
msgid "ADD VIDEO"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:49
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:42
msgid "Double tap to select"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:52
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:44
msgid "Double tap to select an image"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:54
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:46
msgid "Double tap to select a video"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-placeholder/index.native.js:66
#: gutenberg/packages/block-editor/src/components/media-placeholder/index.native.js:58
#, javascript-format
msgid "%s block. Empty"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/inserter/index.native.js:37
#: gutenberg/packages/block-editor/src/components/inserter/index.native.js:22
msgid "Double tap to add a block"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-upload/index.native.js:24
#: gutenberg/packages/block-editor/src/components/media-upload/index.native.js:24
msgid "Take a Video"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-upload/index.native.js:25
#: gutenberg/packages/block-editor/src/components/media-upload/index.native.js:25
msgid "Take a Photo"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-upload/index.native.js:54
#: gutenberg/packages/block-editor/src/components/media-upload/index.native.js:40
msgid "Choose from device"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/media-upload/index.native.js:62
#: gutenberg/packages/block-editor/src/components/media-upload/index.native.js:42
msgid "WordPress Media Library"
msgstr ""

#: gutenberg/packages/block-editor/build-module/components/url-input/index.native.js:54
#: gutenberg/packages/block-editor/src/components/url-input/index.native.js:27
msgid "Paste URL"
msgstr ""

#: gutenberg/packages/edit-post/build-module/components/header/header-toolbar/index.native.js:61
#: gutenberg/packages/edit-post/src/components/header/header-toolbar/index.native.js:59
msgid "Double tap to undo last change"
msgstr ""

#: gutenberg/packages/edit-post/build-module/components/header/header-toolbar/index.native.js:69
#: gutenberg/packages/edit-post/src/components/header/header-toolbar/index.native.js:66
msgid "Double tap to redo last change"
msgstr ""

#: gutenberg/packages/edit-post/build-module/components/header/header-toolbar/index.native.js:74
#: gutenberg/packages/edit-post/src/components/header/header-toolbar/index.native.js:76
msgid "Hide keyboard"
msgstr ""

#: gutenberg/packages/edit-post/build-module/components/header/header-toolbar/index.native.js:78
#: gutenberg/packages/edit-post/src/components/header/header-toolbar/index.native.js:79
msgid "Tap to hide the keyboard"
msgstr ""

#: gutenberg/packages/editor/build-module/components/post-title/index.native.js:87
#: gutenberg/packages/editor/src/components/post-title/index.native.js:65
msgid "Post title. Empty"
msgstr ""

#: gutenberg/packages/editor/build-module/components/post-title/index.native.js:89
#: gutenberg/packages/editor/src/components/post-title/index.native.js:68
#, javascript-format
msgid "Post title. %s"
msgstr ""
</details>

### CODE REVIEW

**Comment by mchowning** [comment]
@Tug: Should translator's comment be coming through in this file? I don't think they are, for example I'm not seeing https://github.com/WordPress/gutenberg/blob/rnmobile%2Fissue-1303_fix-html-mode-error/packages%2Fblock-editor%2Fsrc%2Fcomponents%2Fblock-list%2Fblock-mobile-toolbar.native.js#L36

**Comment by etoledom** [comment]
Moved to Milestone 1.12

**Comment by joncardasis** [comment]
LGTM @mchowning

**Comment by hypest** [comment]
👋 @mchowning, can we perhaps close this PR with a comment about it's status and what's missing to land it? Thanks!

**Pull request closed without merging**
