### PR TITLE
Release 1.55.2

### PR DESCRIPTION
**Pull request by dcalhoun**
Release for Gutenberg Mobile 1.55.2

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/32895
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14892
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16723

## Extra PRs that Landed After the Release Was Cut

- [Properly handle 404 errors while publishing Android artifacts](https://github.com/WordPress/gutenberg/pull/32860)

## Changes

- [Fix incorrect block insertion point after blurring post title](https://github.com/WordPress/gutenberg/pull/32831)

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by dcalhoun** [comment]
### 🟢 Changes in beta fix `1.55.2` (iOS)

* **Device**: iPhone SE (iOS 14.6)
* **Build**: `51126` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16723#issuecomment-866053922.

- [x] [Fix incorrect block insertion point after blurring post title](https://github.com/WordPress/gutenberg/pull/32831)

**Comment by dcalhoun** [comment]
### 🟢 Changes in beta fix `1.55.2` (Android)

* **Device**: Samsung Galaxy S20 (Android 11)
* **Build**: `110815` from https://github.com/wordpress-mobile/WordPress-Android/pull/14892#issuecomment-866160576.

- [x] [Fix incorrect block insertion point after blurring post title](https://github.com/WordPress/gutenberg/pull/32831)

**Comment by dcalhoun** [comment]
### 🟢 Writing Flow Checklist `1.55.2` (iOS)

* **Device**: iPhone SE (iOS 14.6)
* **Build**: `51126` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16723#issuecomment-866053922.

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

Tomorrow I'll cover the writing flow for Android 👍 .

**Comment by fluiddot** [comment]
### 🟢  Writing Flow Checklist `1.55.2` (Android)

* **Device**: Samsung Galaxy S20 FE 5G (Android 10)
* **Build**: `110815` from https://github.com/wordpress-mobile/WordPress-Android/pull/14892#issuecomment-866160576.

#### General
- [x] TC001 - Block insertion flow
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
### 🟢 Unsupported Block Tests (iOS)

* **Device:** iPhone SE (iOS 14.6) 
* **Build:** `51126` from wordpress-mobile/WordPress-iOS#16723 (comment).

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by fluiddot** [comment]
### 🟢 Unsupported Block Tests (Android)

* **Device**: Samsung Galaxy S20 FE 5G (Android 10)
* **Build**: `110815` from https://github.com/wordpress-mobile/WordPress-Android/pull/14892#issuecomment-866160576.

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Pull request merged**
