### PR TITLE
Release 1.35.0

### PR DESCRIPTION
**Pull request by cameronvoell**
Release for Gutenberg Mobile 1.35.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/24608
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/12709
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14665

## Extra PRs that Landed After the Release Was Cut

- https://github.com/WordPress/gutenberg/pull/24656 - Fix for vertical alignment in column that is added from the inserter menu.

## Changes

* [***] Fixed empty text fields on RTL layout. Now they are selectable and placeholders are visible. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2544
* [**] Add settings to allow changing column widths **=> Doesn't have a gutenberg-mobile PR:** https://github.com/WordPress/gutenberg/pull/24461
* [**] Media editing support in Gallery block. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2496
* [*] Creating undo levels less frequently. https://github.com/wordpress-mobile/gutenberg-mobile/pull/2543

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [x] Gutenberg 'Podfile.lock' inside 'gutenberg/package/react-native-editor/ios/' is updated to the release number.
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by mchowning** [comment]
Completed the **Writing Flow** checklist with **WPAndroid** and found no issues! 🎉 

<details><summary>Specific Tests</summary>

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

</details>

**Comment by cameronvoell** [comment]
iOS Writing Flow:

- [ ] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text format

**Comment by dratwas** [comment]
Hey @cameronvoell Could you please cherry pick this fix to the release branch? https://github.com/WordPress/gutenberg/pull/24656

Thanks! :)

**Review by ceyhun — APPROVED** [review]
:shipit:

**Pull request merged**
