### PR TITLE
Add image size picker improvements

### LINKED ISSUE #1452: Image Block Size Options -  UX Production Ready
This is a follow up to https://github.com/wordpress-mobile/gutenberg-mobile/issues/1329 incorporating feedback from https://github.com/WordPress/gutenberg/pull/17245

- [x] Verify Image Size Options UI updates image URL's accordingly
- [x] Update Constant references to re-use size options from existing web code (Thumbnail, Full Size, etc): https://github.com/WordPress/gutenberg/pull/17245/files#r334790181
- [x] Close Bottom Sheet menu before submenu is opened, reopen initial menu when submenu is closed: https://github.com/WordPress/gutenberg/pull/17245#pullrequestreview-301932626

### PR DESCRIPTION
**Pull request by cameronvoell**
Fixes #1452

### Companion PR's
Gutenberg PR: https://github.com/WordPress/gutenberg/pull/19232
WPiOS PR (for testing): https://github.com/wordpress-mobile/WordPress-iOS/pull/13052

### Changes

- Introduces cycle button UI for updating the size of an image from the BottomSheet menu in an Image Block.
- Removes duplicated default image size declarations and instead utilizes image sizes from the editor settings data store.

### Screenshots
size-changes

See this comment and above comments for context: https://github.com/WordPress/gutenberg/pull/17245#pullrequestreview-301932626

### To Test:
1. Navigate to the Block Editor
2. Add an Image Block and upload an image
3. Click the gear for block settings
4. Tap Image Size row and verify value cycles through available sizes (Thumbnail, Medium, Large, Fullscreen).
5. Verify the Image size changes as you click through the menu.
6. Verify the Image Size is preserved if you update the post, leave, and return.

*Note this PR is mainly covering UI updates, for Image Size error handling with updating URL's from the network etc, see this issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1593

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
👋 Cameron, is this PR still relevant? If yes, let's retarget it, thanks!

**Comment by etoledom** [comment]
Thank you @cameronvoell for the update!

@iamthomasbishop - What do you think about this (temporal) solution for the Image Sizes picker?

size-changes

**Comment by iamthomasbishop** [comment]
@etoledom @cameronvoell  It looks pretty solid overall, based on the test build I grabbed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/13052#event-2896121001). One thing I noticed is that the first time you switch to each different size, the background container (with the image block icon and light gray background) is displayed at full size for a split second. Video for reference: https://cloudup.com/c642ckhMCez

**Comment by cameronvoell** [comment]
@iamthomasbishop The improvements from [this fix](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1757) should make this much less jarring, especially in dark mode.

**Comment by etoledom** [comment]
Moved milestone to v1.22.
Please feel free to re-target if you consider this PR must be shipped together with v1.21.

**Comment by cameronvoell** [comment]
closing as gutenberg changes were brought in to gb-mobile through another PR (still under DEV flag). 

See this PR for removing DEV flag and updating release notes for this feature: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1904

**Pull request closed without merging**
