### PR TITLE
Add audio block to initial html

### PR DESCRIPTION
**Pull request by jd-alexander**
`gutenberg PR` https://github.com/WordPress/gutenberg/pull/29056

To test:
See https://github.com/WordPress/gutenberg/pull/29056

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by ceyhun — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/29056

**Comment by fluiddot** [comment]
👋 I've noticed that this PR was merged with the Gutenberg reference pointing to a [commit](https://github.com/WordPress/gutenberg/commit/73d553) from the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29056) instead to the [merge commit](https://github.com/WordPress/gutenberg/commit/1b65fe94f617afa0e8a287e27ab6fe30ee6a6ed1). I'll make a new PR updating the Gutenberg reference.

**Comment by fluiddot** [comment]
Here is the [PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3195) that fixes it.

**Comment by jd-alexander** [comment]
> 👋 I've noticed that this PR was merged with the Gutenberg reference pointing to a [commit](https://github.com/WordPress/gutenberg/commit/73d553) from the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29056) instead to the [merge commit](https://github.com/WordPress/gutenberg/commit/1b65fe94f617afa0e8a287e27ab6fe30ee6a6ed1). I'll make a new PR updating the Gutenberg reference.

Thanks @fluiddot I thought it was fine to point it to the final commit containing the changes. I will point to the merge commit from now on. 🙏🏾

**Comment by fluiddot** [comment]
> > 👋 I've noticed that this PR was merged with the Gutenberg reference pointing to a [commit](https://github.com/WordPress/gutenberg/commit/73d553) from the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/29056) instead to the [merge commit](https://github.com/WordPress/gutenberg/commit/1b65fe94f617afa0e8a287e27ab6fe30ee6a6ed1). I'll make a new PR updating the Gutenberg reference.
> 
> Thanks @fluiddot I thought it was fine to point it to the final commit containing the changes. I will point to the merge commit from now on. 🙏🏾

No worries, I saw a reference to this topic in an internal post (p9ugOq-1bP-p2) just in case you want to check it, it's described in one of the last bullet points. Although it's true that it doesn't specifically say to have the reference pointing to the merge commit but I think that's the idea.

**Comment by jd-alexander** [comment]
Awesome! Thanks for sharing It makes sense that this is done especially since when the release is being done it's the merge commits that are utilized. 🙏

**Pull request merged**
