### PR TITLE
Centrally Align Multiline Block Titles in the Inserter

### LINKED ISSUE #34748: Inserter: Block title is not center-aligned
## Description

The block title is left-aligned in the inserter menu but it should be center-aligned.

## Step-by-step reproduction instructions

1. Create a reusable block in the web version of the editor and set a long name for the block.
2. Open a post/page in the native version.
3. Tap on the ➕ icon to display the inserter menu.
4. Navigate to the Reusable tab.
5. Observe that the reusable block is displayed in the list.
6. Observe that the reusable block's title is not center-aligned.

## Expected behaviour

Block title should be center-aligned in the inserter menu.

## Actual behaviour

Block title is not center-aligned in the inserter menu.

## Screenshots or screen recording (optional)

Screenshot 2021-09-10 at 19 21 06

## WordPress information
- WordPress version: N/A
- Gutenberg version: N/A
- Are all plugins except Gutenberg deactivated? N/A
- Are you using a default theme (e.g. Twenty Twenty-One)? N/A

## Device information
- Device: iPhone 12 Pro Max
- Operating system: iOS 14.5
- WordPress app version: `develop`

### PR DESCRIPTION
**Pull request by mchowning**
Fixes [#34748](https://github.com/WordPress/gutenberg/issues/34748)

To test:
Follow the testing instructions for [the Gutenberg PR](https://github.com/WordPress/gutenberg/pull/37185).

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by fluiddot — COMMENTED** [review]
@mchowning I'm wondering if we could an entry for this to the release notes as it's a user-facing change, wdyt?

**Review by fluiddot — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/37185#pullrequestreview-829075974.

**Comment by mchowning** [comment]
> I'm wondering if we could an entry for this to the release notes as it's a user-facing change, wdyt?

I was wondering about that too, and I don't remember why I didn't do it 😆 . 

Do we generally add to the release notes here, just in Gutenberg, both?

**Comment by fluiddot** [comment]
> Do we generally add to the release notes here, just in Gutenberg, both?

Usually, we update both. The main difference between GB-mobile release notes and `react-native-editor` package changelog is whether the change is user-facing. In the latter, we add any change while in release notes only the user-facing ones.

**Comment by mchowning** [comment]
Added the release notes. Let me know what you think @fluiddot

**Comment by fluiddot** [comment]
> Added the release notes. Let me know what you think @fluiddot

LGTM! Thanks for updating the release notes and changelog 🙇 .

**Pull request merged**
