### PR TITLE
Update to RN 0.62-rc0

### PR DESCRIPTION
**Pull request by hypest**
Draft PR to track the attempt to upgrade to RN 0.62

Currently based on the 0.61.x effort (https://github.com/wordpress-mobile/gutenberg-mobile/pull/1704).
 
WIP

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by Tug** [comment]
@hypest: @dratwas brought to my attention that this PR will be particularly hard to bring to gutenberg as part of the monorepo effort.

Given the amount of changes here, our best hope could be to just copy and paste the `android` and `ios` folders into their respective folders and commit the changes in gutenberg. We'll lose history but it's probably better than the rebase hell we'll get from pulling the subtree. But then I'm also worried that it will prevent us from bringing other (simpler) changes in because of that.

**Comment by hypest** [comment]
Thanks for the headsup @Tug ! Let's revisit when the 0.62 upgrade reaches a more mature state. For the time being, this looks like more work is needed anyway.

**Comment by SergioEstevao** [comment]
@hypest I think it will be better to start with a clean slate, there is a lot of noise on this PR no?

**Comment by hypest** [comment]
> @hypest I think it will be better to start with a clean slate, there is a lot of noise on this PR no?

Fine by me! Feel free to close if it makes more sense to you @SergioEstevao 👍

**Comment by marecar3** [comment]
Closing this one in favor of https://github.com/wordpress-mobile/gutenberg-mobile/pull/1823/

**Pull request closed without merging**
