### PR TITLE
Release 1.55.1

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.55.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/32782
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14859
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16703

- ~~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~~
- ~~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

- [Fix: RNMobile borderRadius value setting](https://github.com/WordPress/gutenberg/pull/32717)
- [Improve unsupported block message for reusable block](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3621)

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
### 🟢 Writing Flow checklist (iOS)
**Device**: iPhone 11 (iOS 14.2)
**Build**: [50766](https://github.com/wordpress-mobile/WordPress-iOS/pull/16703#issuecomment-863295116)

#### General
- [x] TC001 - Block insertion flow
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by fluiddot** [comment]
### 🟢  Unsupported Block Tests (iOS)

**Device**: iPhone 11 (iOS 14.2)
**Build**: [50766](https://github.com/wordpress-mobile/WordPress-iOS/pull/16703#issuecomment-863295116)

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites (⚠️ Skipped due to a known issue)
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by fluiddot** [comment]
### 🟢  Changes in beta fix `1.55.1` (iOS)

**Device**: iPhone 11 (iOS 14.2)
**Build**: [50766](https://github.com/wordpress-mobile/WordPress-iOS/pull/16703#issuecomment-863295116)

- [x] [Fix: RNMobile borderRadius value setting](https://github.com/WordPress/gutenberg/pull/32717)
- [x] [Improve unsupported block message for reusable block](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3621)

**Comment by antonis** [comment]
### 🟢  Changes in beta fix `1.55.1` (Android)

**Device**: Pixel 2 XL (Android 11)
**Build**: [110053](https://github.com/wordpress-mobile/WordPress-Android/pull/14859#issuecomment-863332107)

- [x] [Fix: RNMobile borderRadius value setting](https://github.com/WordPress/gutenberg/pull/32717)
- [x] [Improve unsupported block message for reusable block](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3621)

**Comment by antonis** [comment]
### 🟢  Writing Flow checklist (Android)

**Device**: Pixel 2 XL (Android 11)
**Build**: [110053](https://github.com/wordpress-mobile/WordPress-Android/pull/14859#issuecomment-863332107)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by antonis** [comment]
### 🟢  Unsupported Block Tests

**Device**: Pixel 2 XL (Android 11)
**Build**: [110053](https://github.com/wordpress-mobile/WordPress-Android/pull/14859#issuecomment-863332107)

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites  (⚠️ Skipped due to a [known issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3544))
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Review by antonis — APPROVED** [review]
Great work wrangling this release @fluiddot 👍 
The code changes LGTM and the apps from the integration PRs work as expected 🎉 

ps. Please make sure we update `RELEASE-NOTES.txt` before merging

**Comment by fluiddot** [comment]
UI optional tests passed 🎊 :
- [Test iOS on Device - Full](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/12649/workflows/092ffdca-2ea3-4d07-a149-63c89b610b3c/jobs/68475)
- [Test Android on Device - Full](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/12649/workflows/668692d3-6388-4662-af73-a2877532a65e/jobs/68470)

**Pull request merged**
