### PR TITLE
Fix full-screen bottom sheet animations

### PR DESCRIPTION
**Pull request by dcalhoun**
## Related PRs

* https://github.com/WordPress/gutenberg/pull/34425

Relates to wordpress-mobile/gutenberg-mobile#3883.

To test: See https://github.com/WordPress/gutenberg/pull/34425. 

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
Hi @dcalhoun :wave: :smiley: . I've been having trouble testing this because of recent changes to the gradle version on the WordPress-Android app (local builds are broken until merged with upstream changes). So, for now, I'll bump the milestone to the next release, but let me know if you think we should still get this into 1.61. Thanks!

**Comment by dcalhoun** [comment]
Hey @mkevins. 👋🏻 Following up as I realized I may have misinterpreted your previous comment. Do I need to update this branch or complete any work to fix testing this work? Thanks!

**Comment by mkevins** [comment]
> Hey @mkevins. 👋🏻 Following up as I realized I may have misinterpreted your previous comment. Do I need to update this branch or complete any work to fix testing this work? Thanks!

Hi @dcalhoun :wave: :smiley:  My apologies if my comment was ambiguous :sweat_smile: . What I meant was that I didn't have a chance to test that prior to the previous release ― due to issues unrelated with your PR. I will test this today (the conflicts need to be resolved before merging, but so far no "code related" conflicts have arisen, so I can test this as is).

**Comment by mkevins** [comment]
Hi @dcalhoun :wave: :smile: 

I tested this on Android (Pixel 3a physical device) and I still encountered the issue with the "ghost" screen:



Though this is not related with this PR (it occurred to me on develop as well).

For me, the animations were a bit rough when I opened the inserter. I'm not sure if this is related with this PR, or something else though :thinking: Were they smooth for you?

Here is a video of how it looks for me

<video src="https://user-images.githubusercontent.com/8507675/133238729-2f3a275b-6862-46ca-b3d5-6113ed25af4d.mp4" width="360">

**Comment by mkevins** [comment]
On iOS (tested on iPhone 11 - physical device) the animations look smoother (however dismissing the inserter sometimes seems to stop at the half-way point, before disappearing, instead of animating all the way down until it is off the screen)..

The buttons block settings all animated very smoothly in my tests.

The link picker animations had some issues, e.g. sometimes the editor toolbar becomes visible during the animation away from fullscreen. Oddly, this seems to depend on whether or not the omni input was cleared before cancelling :thinking: :

<video src="https://user-images.githubusercontent.com/8507675/133242699-d5dba8bf-30ad-4f93-afeb-e5b3e41d3d88.mov" width="360">

This is all hinting that some regressions have been introduced into the bottomsheet navigation at some point (or potentially in the link picker state - or both :man_shrugging: ) - mentioning this here as I encounter these testing your PR, but I will circle back to see if these issues are on develop as well.

The tests you've added here will be great to consider for these other flows as well going forward. Curious if you can reproduce any of the observations I've found above?

**Comment by jd-alexander** [comment]
Hey @dcalhoun  .We will cut the 1.62.0 release today so I am bumping this PR to the next milestone. Let me know if you’d rather us work to include this PR in 1.62.0. Thanks!

**Comment by twstokes** [comment]
Hey @dcalhoun. We will cut the 1.63.0 release today. Please let me know if you’d like to bump this to the next milestone or rather us work to include this PR in 1.63.0. Thanks!

**Comment by dcalhoun** [comment]
Thanks for the ping, @twstokes. I bumped this PR to the next release.

**Comment by geriux** [comment]
Hey @dcalhoun  👋. We will cut the 1.64.0 release on 10/14. I plan to circle back and bump this PR to the next milestone then, but please let me know if you'd rather us work to include this PR in 1.64.0. Thanks!

**Comment by fluiddot** [comment]
Hey @dcalhoun !
We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!

**Comment by dcalhoun** [comment]
Closing this PR as the related Gutenberg changes were included in other work. See https://github.com/WordPress/gutenberg/pull/34425#issuecomment-1004902475.

**Pull request closed without merging**
