### PR TITLE
Audio Block - Audio Player UI 

### PR DESCRIPTION
**Pull request by jd-alexander**
`Gutenberg` https://github.com/WordPress/gutenberg/pull/27467
`WPAndroid` https://github.com/wordpress-mobile/WordPress-Android/pull/13843
`WPiOS` https://github.com/wordpress-mobile/WordPress-iOS/pull/15694
To test:

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
👋  @jd-alexander, we're cutting the release now, however since this PR will be included in the release I'll leave it in the current milestone. Once it's merged please let me know and I'll cherry pick the changes in the release branch, thanks!

**Comment by jd-alexander** [comment]
> 👋  @jd-alexander, we're cutting the release now, however since this PR will be included in the release I'll leave it in the current milestone. Once it's merged please let me know and I'll cherry pick the changes in the release branch, thanks!

Thanks @fluiddot I will keep you updated.

**Comment by jd-alexander** [comment]
The changes that this PR reference were merged in via https://github.com/WordPress/gutenberg/pull/27467 We are closing this PR in favor of https://github.com/wordpress-mobile/gutenberg-mobile/pull/3070 that also contains a reference to enabling this block in production.

**Comment by fluiddot** [comment]
> The changes that this PR reference were merged in via [WordPress/gutenberg#27467](https://github.com/WordPress/gutenberg/pull/27467) We are closing this PR in favor of #3070 that also contains a reference to enabling this block in production.

I'll remove it from the milestone too.

**Pull request closed without merging**
