### PR TITLE
Release 1.58.2

### PR DESCRIPTION
**Pull request by SiobhyB**
Release for Gutenberg Mobile 1.58.2

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/33870
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/15133
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16975

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

- Fix issue with text input in alt text settings: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3784

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by SiobhyB** [comment]
## 🟢 Writing Flow Test Cases (iOS)

_Tested with WPiOS `54239` on a iPhone XR (iOS 14.6)._

#### General
- [x] TC001 - Block insertion
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by SiobhyB** [comment]
## 🟢 Unsupported Block Test Cases (iOS)

_Tested with WPiOS build `54239` on iPhone XR (iOS 14.6)._

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] 🟡 [skipped due to a known issue] ~~TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites~~
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by SiobhyB** [comment]
## 🟢 Test the new changes (iOS)

_Tested with WPiOS build `54239` on iPhone XR (iOS 14.6)._

- [x] Fix issue with text input in alt text settings: #3784

**Comment by fluiddot** [comment]
## 🟢 Writing Flow Test Cases (Android)

_Tested with WPAndroid `113571` on device Samsung Galaxy S20 FE 5G (Android 10)._

#### General
- [x] TC001 - Block insertion
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by fluiddot** [comment]
## 🟢 Unsupported Block Test Cases (Android)

_Tested with WPAndroid `113571` on device Samsung Galaxy S20 FE 5G (Android 10)._

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] 🟡 [skipped due to a known issue] ~~TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites~~
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by fluiddot** [comment]
## 🟢 Test the new changes (Android)

_Tested with WPAndroid `113571` on device Samsung Galaxy S20 FE 5G (Android 10)._

- [x] Fix issue with text input in alt text settings: #3784

**Comment by fluiddot** [comment]
I noticed that the "Test iOS on Device" jobs didn't pass, looks like it failed with the common errors caused by flakiness so I've just restarted it.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**NOTE:** We should wait for the "Test iOS on Device" jobs to finish and pass before merging 🤞.

**Pull request merged**
