### PR TITLE
Release 1.36.0

### PR DESCRIPTION
**Pull request by cameronvoell**
Release for Gutenberg Mobile 1.36.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/24955
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/12848
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14808

- Aztec-iOS: N/A
- Aztec-Android: N/A

## Extra PRs that Landed After the Release Was Cut

- Fix for sliders cutting off at edge of screen - https://github.com/WordPress/gutenberg/pull/25017

## Changes

 - Change 1: [Update Slider to reflect changes immediately](https://github.com/WordPress/gutenberg/pull/22421)
 - Change 2: Pullquote enabled on Android release builds after placeholder fix ([Enable PR](https://github.com/WordPress/gutenberg/pull/24921))([Fix PR](https://github.com/WordPress/gutenberg/pull/22561))
- Change 3: [Remove Gutenberg layouts to be moved to the host app](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2564)

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [ ] Approve and run optional Android and iOS UI tests
- [ ] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [ ] Gutenberg 'Podfile.lock' inside 'gutenberg/package/react-native-editor/ios/' is updated to the release number.
- [ ] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [ ] Bundle package of the release is updated.

### CODE REVIEW

**Comment by guarani** [comment]
Testing WPiOS build 34086 on iOS 14 beta:

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks: ✅ paragraph, ⚠️ header (see comment below)
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

### Comments

- TC001 - Paste formatted text copied from website: Pasting the image gallery results in a long (empty) bulleted list showing up in the editor.
- With the cursor in an empty block, tap the return key: notice that the toolbar "jumps" up and then animates down again, while I would expect it to stay put.
    <details>
    <summary>See screen recording</summary>
    WordPress for iOS screen recording showing toolbar glitch where toolbar jumps up and animates down when the return key is pressed in an empty paragraph block
    </details>
-  TC005 - Merge multiple blocks: In the test here that involves the Header block, I see some words (randomly) become bold after splitting a Header block.
    <details>
    <summary>See screen recording</summary>
    WordPress for iOS screen recording showing header content become bolded after splitting header block
    </details>

**Comment by cameronvoell** [comment]
Android Writing Flow test results below, with extra emphasis on the new Android Pullquote block fix -  no issues to report 🎉 
<details><summary>Specific Tests</summary>

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components - Focusing on new Pullquote on Android ✅ 
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases - Focusing on new Pullquote on Android ✅ 
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

</details>

**Comment by antonis** [comment]
Tested WPiOS with build number: 34086 from App Center on a iPhone SE 2020 with iOS 13.5.1

DarkMode-2

- [x] TC004 - Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] TC005 - Buttons block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] TC006 - Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc006) 
- [x] TC007 - Columns - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

Group-2

- [x] TC009 - Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [x] TC010 - Group - Navigation down works according to parent-first approach - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [x] TC011 - Group - Cross navigation between blocks works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [x] TC012 - Group - Ungroup button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [x] TC013 - Group - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [x] TC014 - Group - Check if nested Placeholder block can be replaced - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

Spacer-2

- [x] TC004 - Spacer block - Settings: Available height range is correct - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [x] TC005 - Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [x] TC006 - Spacer block - Spacer in horizontal layout works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

Buttons-4

- [x] TC017 - Buttons block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)
- [x] TC016 - Buttons block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)
- [x] TC018 - Buttons block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)
- [x] TC020 - Buttons block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)
- [x] TC021 - Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

Button-5

- [x] TC009 - Buttons block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc009)
- [x] TC019- Buttons block - Render theme colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc019)
- [x] TC015 - Buttons block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc015)

Button-7

- [x] TC008 - Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] TC022 - Buttons block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

Editor Theme - 2

- [x] TC004 - Custom Gradients - Check that custom gradients load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc004)
- [x] TC005 - Offline Support - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc005)

Color Settings - 2

- [x] TC004 - Pressing color swatch - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc004)
- [x] TC005 - Customize gradient color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc005)
- [x] TC006- Custom color picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc006)

**Comment by lukewalczak** [comment]
I've noticed regression related to cut-off slider thumb in `Columns` multiple sliders and incorrect spacings.

**Steps to reproduce:**
1. Open a draft
2. Add `Columns` block
3. Press `Cancel` on variation picker
4. Open columns settings
5. Move slider on the maximum value
6. Observe that thumb is cut-off

**Screenshot:** 
Screenshot 2020-09-02 at 12 42 21

**Status:**

Gutenberg PR fixing it: https://github.com/WordPress/gutenberg/pull/25017
Gutenberg-mobile PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2590

**Comment by cameronvoell** [comment]
> I've noticed regression related to cut-off slider thumb in Columns multiple sliders and incorrect spacings.

@lukewalczak Fix merged to master and cherry picked to the release, thanks!

**Comment by enejb** [comment]
Tested using Android Version 9. Samsung Galaxy A8 (2018) 


### Gallery-2

- [x] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
Noticed: If there is only one image that needs to be retied we should not show Retry all button. 

- [x] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)
Noticed: If you finished uploading the image you can't cancel it. The notice shown to the user makes sense. But we should maybe provide more info. If they are looking forward to deleting the image for example. How would they do it? 

### Gallery-3

- [x] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
Noticed: The gallery caption wasn't alignment wasn't working like expected. 

- [x] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Gallery-4

- [x] Gallery block - Settings: Link to - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)
- [x] Gallery block - Settings: Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [x] Gallery block - Settings: Crop images - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

### MediaText-3

- [x] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
I wasn't able to upload the video as expected in the end. 

- [x] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

### MediaText-4

- [x] Media Text block - Media & Text alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

Noticed: that when I am editing the text in the horizontal position there are cases where it wasn't possible to remove the keyboard also the pill sometimes overlaps the text. 


### Shortcode-1

- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)
Noticed: that my keyboard want to enter [YouTube and autocorrects it to that. We should probably allow for [YouTube shortcode as well.


### Cover-2

- [x] Cover - Add Video Background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc005)
- [x] Cover - Replace media - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
Noticed: Should we keep the replace icon in the toolbar when replacing an image the same way that the icon appears for video replacement?  

- [x] Cover - Gradient background is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc007)
Noticed: I wasn't able to edit the colour(s) and of the different gradients. 
- [x] Cover - Gradient overlay is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)
- This part didn't work quite as expected for me. :( 


### Social Icons - 2
- [x] The link sheet is opened automatically when adding new icon - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc004)
- [x] Ghost placeholder is visible when no icon is active - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc005)
Noticed: I can see the ghost placeholder but its really hard to see for me I was using darkmode.
- [x] Social icon forwarding to the link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc006)
Noticed: As a user I was expecting to be able to just type the twitter username to be send to the correct link. 


## Broken/Regressions
#### 1. The most broken part is the custom gradient on the cover. 
If you apply a custom gradient using the web Gutenberg editor and then you go and save the post using the mobile editor. the custom gradient gets overwritten and lost. 
To reproduce: 
1. Add custom gradient. with 3 different colors to the cover block. 
2. Load the post to edit on the mobile editor. 
3. Notice that it doesn't look as expeceted. 
4. Update the post. 
5. Notice that the gradient that you set before isn't set.


#### 2. Gallery block - Add Gallery Caption 
To reproduce:
1. apply an alignment to the gallery caption. 
2. Notice that after saving it doesn't produce the required html. 
See the post https://enejtest3.com/2020/09/02/this-is-a-test-post/ 
The gallery caption should be centered. 

#### 3. Video Uploading doesn't work on the media text block. 
Sometimes I wasn't able to get the media text block to upload the video as expected. It would be uploading but then at the very end it didn't work. 
To Replicate: 
1. Add the media text block. 
2. Select the video to add. 
3. Once it start uploading. Duplicate the block. 
4. Notice that he upload bar is progressing. 
5. The video failed to upload. Retrying Fails again. 
6. Exiting the editor works as expected.

**Comment by cameronvoell** [comment]
Summarizing Outstanding Issues:

### Android Writing Flow => ✅ 

### iOS Writing Flow 🟡 => 3 Issues Raised by @guarani 
1. **Recommend not a blocker:** _TC001 - Paste formatted text copied from website: Pasting the image gallery results in a long (empty) bulleted list showing up in the editor._

I don't think this is an issue because web editor shows the same long bulleted list and it's not clear how the gallery on the "work with us" page is supposed to convert to gutenberg blocks, but if we capture all the images, and we match gutenberg web, I think that seems pretty good.

2. **Recommend not a blocker:** _With the cursor in an empty block, tap the return key: notice that the toolbar "jumps" up and then animates down again, while I would expect it to stay put._

Seems like a legit issue, though I only see the "jump" when the paragraph block is near the bottom of the screen. I created an issue here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2592. 
I also verified that it is not a new issue and existed at least in the last release, see comment https://github.com/wordpress-mobile/gutenberg-mobile/issues/2592#issuecomment-686229603

3. **Unable to reproduce:** TC005 - Merge multiple blocks: In the test here that involves the Header block, I see some words (randomly) become bold after splitting a Header block.

@antonis Could you try and reproduce the last issue in this comment (header block strange bold behavior on block split): https://github.com/wordpress-mobile/gutenberg-mobile/pull/2588#issuecomment-685085231 

### iOS Blocks testing => ✅ 

### Android Block test => 🟡  3 Issues Raised by @enejb 

1st and 2nd seemed to be because of synching issues, and @enej clarified that they no longer seem to be issues. 

 3. **Unable to reproduce:** Video Uploading doesn't work on the media text block.

> Sometimes I wasn't able to get the media text block to upload the video as expected. It would be uploading but then at the very end it didn't work.
To Replicate:
Add the media text block.
Select the video to add.
Once it start uploading. Duplicate the block.
Notice that he upload bar is progressing.
The video failed to upload. Retrying Fails again.
Exiting the editor works as expected.

I was not able to re-create this third issue. Although I do not see a preview for my uploaded videos, that issue is documented here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1151. When I try and upload, other than the image preview, it works as expected. Publishing the post shows the video in articles correctly, and I can still tap on the video block to play and preview the content.

@marecar3 Could you please verify as soon as you can on Thursday whether you can reproduce video upload errors at the very end of this comment https://github.com/wordpress-mobile/gutenberg-mobile/pull/2588#issuecomment-685995028?

**Comment by cameronvoell** [comment]
@pinarol I could use a second opinion on my assessment of issues raised in the release so far here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2588#issuecomment-686232933. 

In particular, I'd like to know if you agree that this Number 2., existing issue @guarani found, the bouncing toolbar when pressing enter at bottom of the editor, should be prioritized as a regular issue, and not block the release: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2592.

**Comment by antonis** [comment]
>@antonis Could you try and reproduce the last issue in this comment (header block strange bold behavior on block split): #2588 (comment)

I confirm that this behaviour is reproduced. The test was performed on iPhone SE 2020 with iOS 14 beta 6
<details>
    <summary>See screen recording</summary>
    Header splitting issue
    </details>

**Comment by pinarol** [comment]
@cameronvoell I agree that findings aren't blockers.

> In particular, I'd like to know if you agree that this Number 2., existing issue @guarani found, the bouncing toolbar when pressing enter at bottom of the editor, should be prioritized as a regular issue, and not block the release: #2592.

Yes agreed. Also keep in mind that [this PR](https://github.com/WordPress/gutenberg/pull/24573) has the potential to fix it. Although I should say this is the 3rd fix attempt and the first 2 was reverted due to other side effects. So I don't recommend trying to include it in the release last minute.

**Comment by antonis** [comment]
I ran a few more tests on an iPhone SE 2020 with iOS 14 beta 6 (WPiOS with build number: 34086 from App Center)

Gallery-1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [x] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-3

- [x] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)

MediaText-3

- [x] Media Text block - Insert video from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-v)
- [x] Media Text block - Close/Re-open post with an ongoing video upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-v)

MediaText-4

- [x] Media Text block - Media & Text alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc006)
- [x] Media Text block - Vertical alignment - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc007)

DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

DarkMode-2

- [x] Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [x] Buttons block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [x] Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)
- [x] Columns - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

Shortcode-1

- [x] Shortcode block - Add a youtube link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/shortcode.md#tc001)

Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

Button-6

- [x] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [x] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

Button-7

- [x] Buttons block - Link from the clipboard is automatically added into the empty URL field in link settings and button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc008)
- [x] Buttons block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc022)

Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [x] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)

Group-2

- [x] Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)

Cover-1

- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)

Cover-2

- [x] Cover - Replace media - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc006)
- [x] Cover - Gradient overlay is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc008)

Columns - 1


- [x] Columns - Columns percentage mechanism - column's preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)

Columns - 2

- [x] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

Columns - 3


- [x] Columns - Check if Column placeholders is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)

Columns - 4


- [x] Columns - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc018)

Color Settings - 1 

- [x] Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] Scroll color palette to start - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

Social Icons - 1

- [x] The newly created Social Icons block is added with 4 icons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

Social Icons - 2

- [x] The link sheet is opened automatically when adding new icon - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc004)
- [x] Ghost placeholder is visible when no icon is active - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc005)
- [x] Social icon forwarding to the link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc006)

**Comment by cameronvoell** [comment]
Last status update before cutting this release:

1. Bouncing toolbar (https://github.com/wordpress-mobile/gutenberg-mobile/issues/2592) is a known issue and we're working on getting in a fix soon, but not recommending it as a blocker. Thanks @pinarol for verifying that. 

2. Heading split adding bold characters sometimes is an ongoing issue but is not 100% reproducible, so we're not recommending blocking the release for the issue. It is documented here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2593. Thanks @Paul and @antonis for finding and verifying this issue.

3. Video upload issue ([3. here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2588#issuecomment-685995028)) could not be reproduced on my side either. I did note that there is one issue with video previews documented here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1151, that can make it look like video upload is not working. @enejb if you think video upload in the media text block has an ongoing issue, please create a issue, preferably with some video so we can take a deeper look into why it might sometimes be happening.

With those three issues verified as not likely new problems in this release, and documented with strategies to move them forward, I think we're ready to cut the release here. Thanks for the help everyone!

**Comment by lukewalczak** [comment]
> Bouncing toolbar (#2592) is a known issue and we're working on getting in a fix soon, but not recommending it as a blocker. Thanks @pinarol for verifying that.

Actually, I have created a [fix](https://github.com/WordPress/gutenberg/pull/24573) for the weird bounciness, however, it's my third attempt to correct the toolbar behaviour, that's why I would rather merge it first to master so developers can catch potential bugs ✌️

**Comment by cameronvoell** [comment]
Noting here that I verified that there are no bundle updates after the last commit: 36226353adb02eecc8e933ffa4f6a9959e26c5f3

**Review by guarani — APPROVED** [review]
Looks good to me! All the outstanding issues seem to be non-blockers (including [the iOS 14 photos permission issue](https://github.com/WordPress/gutenberg/issues/24989#issuecomment-686515149)).

**Pull request merged**
