### PR TITLE
[Embed block] Block settings

### LINKED ISSUE #3283: [Embed block] Block settings
### Description
- Settings bottom sheet opens when pressing the gear icon in the block
- Implement setting for “Resize for smaller devices.” toggle

### PR DESCRIPTION
**Pull request by ceyhun**
Fixes #3283 

To test: See gutenberg PR https://github.com/WordPress/gutenberg/pull/33654

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by jhnstn** [comment]
Hi @ceyhun, We are looking to cut the 1.59.0 release today. How much more time do you need to get this in or is it ok to bump this to the next release?

**Comment by ceyhun** [comment]
> Hi @ceyhun, We are looking to cut the 1.59.0 release today. How much more time do you need to get this in or is it ok to bump this to the next release?

Hey @jhnstn, I bumped it to the next release, 1.60.0.

**Review by fluiddot — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/33654#pullrequestreview-729624889.

**NOTE:** The Gutenberg ref is not pointing to the last commit of https://github.com/WordPress/gutenberg/pull/33654.

**Comment by fluiddot** [comment]
> I have considered if this change warrants user-facing release notes more info and have added them to RELEASE-NOTES.txt if necessary.

The block settings will be enabled for all users so what do you think about adding an entry to the release notes?

**EDIT:** Probably we should also add an entry in the `react-native-editor` package CHANGELOG file.

**Pull request merged**
