### PR TITLE
Release 1.61.2

### PR DESCRIPTION
**Pull request by geriux**
Release for Gutenberg Mobile 1.61.2

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/35156
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/15375
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/17226

- Aztec-iOS: n/a
- Aztec-Android: n/a

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Change 1
- **PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3992
- **Issue:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3987

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by jd-alexander** [comment]
### Writing Flow checklist

Device : iPhone 11 
Build : [18.2.1](https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/c712a3f7-9ee1-4a9f-a82c-48137e58f610/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=fqe6Z2yHwd%2Fjk5LOn85LaTib8Er%2BnLsWZtZ%2B7aOyyN8%3D&se=2021-09-28T18%3A55%3A01Z&sp=r)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by jd-alexander** [comment]
## Test Bug fixes

Device : iPhone 11 
Build : [18.2.1](https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/c712a3f7-9ee1-4a9f-a82c-48137e58f610/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=fqe6Z2yHwd%2Fjk5LOn85LaTib8Er%2BnLsWZtZ%2B7aOyyN8%3D&se=2021-09-28T18%3A55%3A01Z&sp=r)

- [x] **PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3992

**Comment by geriux** [comment]
## Writing Flow checklist (Android)
**Device**: Redmi Note 8T (OS 11)
**Build**: [115748](https://github.com/wordpress-mobile/WordPress-Android/pull/15375#issuecomment-928162880)

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by geriux** [comment]
## Test Bug fixes (Android)

**Device**: Redmi Note 8T (OS 11)
**Build** : [115748](https://github.com/wordpress-mobile/WordPress-Android/pull/15375#issuecomment-928162880) 

- [x] **PR:** https://github.com/wordpress-mobile/gutenberg-mobile/pull/3992

**Review by jd-alexander — APPROVED** [review]
Thanks for these changes @geriux

 I verified that the respective tags point to the appropriate commit hashes. 
On `gutenberg` the tag points to the `changelog` entry and the `gb-mobile` tag also points to that via the submodule reference. 

LGTM 🚢

**Comment by jd-alexander** [comment]
@geriux I understand the necessity of this step `Restore submodules references` but I am not sure I see where in the checklist it is represented? Is this something we need to include in the checklist?

**Comment by geriux** [comment]
> @geriux I understand the necessity of this step `Restore submodules references` but I am not sure I see where in the checklist it is represented? Is this something we need to include in the checklist?

That was a mistake when I merged `trunk` into this branch 😅 I'm not used to merging hotfixes after the next release was merged.

So I accidentally committed these submodule changes but we should keep the newer ones. Sorry for the noise in the commit history.

**Comment by jd-alexander** [comment]
Ah! no problem! Makes even more sense now 😄

**Pull request merged**
