### PR TITLE
Add a new androidReplacements function to comply with Android Typography lint rules

### PR DESCRIPTION
**Pull request by maxme**
Add a new androidReplacements function to comply with Android Typography lint rules

### CODE REVIEW

**Comment by Tug** [comment]
Change looks good 👍 , anything else I should be looking at for the review?

**Comment by maxme** [comment]
> anything else I should be looking at for the review?

This can be tested with current `gutenberg-mobile` develop, before the patch, the following commands will result in a lint error (see this https://github.com/wordpress-mobile/WordPress-Android/pull/11585#issuecomment-608390900), after the patch the same commands will work fine.

```
cd libs/gutenberg-mobile
yarn genstrings
cd ../..
python tools/merge_strings_xml.py
./gradlew :WordPress:lintVanillaRelease
```

**Comment by Tug** [comment]
Don't you mean gutenberg-mobile `master`? On `develop`, `yarn genstrings` is failing because of a tsconfig issue in gutenberg.

**Comment by maxme** [comment]
> yarn genstrings is failing because of a tsconfig issue in gutenberg.
Yes, sorry I forgot about that, I had to apply the patch from https://github.com/WordPress/gutenberg/pull/21324

Thanks for reviewing it!

**Pull request merged**
