### PR TITLE
Pulling in all the latest dev from the GB side

### PR DESCRIPTION
**Pull request by hypest**
Using the latest from GB, including https://github.com/WordPress/gutenberg/pull/5816.

Main changes include a minor file structure change (blocks library now provided by `@wordpress/blocks`) and the update from GB master.

This PR drops `Prettier` in favor of the GB provided eslint config. Unfortunately, the two (Calypso Prettier, GB's eslint) have become incompatible. EDIT: integrated the formatting part by using `prettier-eslint`.

### CODE REVIEW

**Comment by hypest** [comment]
@jsnajdr gave a headsup about a PR that [updates the Calypso Prettier fork to allow for using a config file](https://github.com/Automattic/wp-calypso/pull/24551). Will git it a try here.

**Comment by maxme** [comment]
> This PR drops Prettier in favor of the GB provided eslint config. Unfortunately, the two (Calypso Prettier, GB's eslint) have become incompatible.

Noooo!!!

**Comment by hypest** [comment]
Found some middle ground with the `prettier-eslint` package: using ESLint+Prettier for formatting but only ESLint for checking. See 7e3a19a.

**Comment by hypest** [comment]
With 1e98ed1, the project depends on `"@wordpress/is-shallow-equal": "^1.0.1"` but that version has a known bug that prevents Metro from bundling the app. Need to wait for https://github.com/WordPress/packages/pull/124 to be merged first and we should update the dependency.

**Comment by hypest** [comment]
`@wordpress/is-shallow-equal` got fixed so, lifting the `not ready for review` flag.

**Comment by hypest** [comment]
We're short of RN review capacity atm so, merging this as more work depends on it.

**Comment by jsnajdr** [comment]
@hypest is this the incorrect Prettier formatting of Flow type annotations you mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/pull/43#issuecomment-385449905?

```diff
 import ActionTypes from './ActionTypes';
 
-export type BlockActionType = string => {
+export type BlockActionType = (string) => {
        type: $Values<typeof ActionTypes.BLOCK>,
        uid: string,
 };
```

Also, what about the type parameters wrapped inside `<>` brackets? Wouldn't spaces around them be more consistent with our style?
```js
Values< typeof ActionTypes.BLOCK >
```
I know very little about Flow at the moment, so I don't have any opinion on that.

**Comment by hypest** [comment]
Hey @jsnajdr 👋 ,

> is this the incorrect Prettier formatting of Flow type annotations you mentioned in #43 (comment)?

Yes, the issue was that the Prettier fork demanded that the non-empty arrow function's parenthesis are removed while the GB Eslint config demanded exactly the opposite.

> Also, what about the type parameters wrapped inside <> brackets? Wouldn't spaces around them be more consistent with our style?

Hmm, not sure at this point. Is that a blocker for the work related to the `arrow-parens` rule perhaps? If a blocker let's add the spaces as I don't think it will be a problem for `flow` either way.

**Comment by jsnajdr** [comment]
@hypest If you're interested in experimenting with the latest Prettier version, the `wp-prettier-master` branch in the [forked repo](https://github.com/automattic/wp-prettier) has some basic support for Flow. It should solve the issues you found while working on `gutenberg-mobile`, although it's still a long way to have a complete and bug-free support for Flow.

**Comment by hypest** [comment]
👋 @jsnajdr , haven't forgotten you :). Just haven't got the time to try out the `wp-prettier-master` branch yet. Still on my todo list though :)

**Pull request merged**
