### PR TITLE
Update aztec to 1.16.0

### PR DESCRIPTION
**Pull request by SergioEstevao**
Updates Aztec to version 1.16.0

To test:
 - Start the demo app
 - Smoke test the demo content, especially the list block indents with ordered lists.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
@SergioEstevao - shouldn't this target the release branch? 🤔

**Comment by SergioEstevao** [comment]
@etoledom, because this is not fixing any regression specific for this version we decided to merge to develop. 

Can you review it after the 1.22.0 is merged on develop?

**Comment by mchowning** [comment]
:wave: @SergioEstevao  and @etoledom ! Just wanted to sanity check that it is fine that [`react-native-aztec/ios/Cartfile` still has a "1.15.0" version](https://github.com/wordpress-mobile/gutenberg-mobile/blob/release/1.23.0/react-native-aztec/ios/Cartfile).

**Comment by SergioEstevao** [comment]
Yep it's ok since we upgrade to version 0.61.5 that file is completely ignored, what matter now is what is defined in `RNTAztecView.podspec`

**Comment by mchowning** [comment]
> since we upgrade to RN 0.61.5 that file is completely ignored

Could we delete it?

**Comment by SergioEstevao** [comment]
I think so, now that we deleted the sample project for RNTAztecView I don't
see the need to have this file anymore, I will give it a go.

**Pull request merged**
