### PR TITLE
Release v1.17

### PR DESCRIPTION
**Pull request by hypest**
Release for Gutenberg Mobile v1.17.0

### Related PRs:
- [ ] Gutenberg: https://github.com/WordPress/gutenberg/pull/18426
- [ ] WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/10769
- [ ] WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/12917

### Changes:

* Add mobile Spacer component (in _DEV_ mode) #1436
* Activate Preformatted block #1442 
* Refactor: BottomSheet.RangeCell markup #1471
* Fix Aztec Android "SetSpan" ends beyond length on merging blocks #1507
* Send backspace event to JS in more scenarios #1517
* Generate i18n files for WPAndroid and WPiOS to use #1520
* `shouldInteractWithURL` will return always false to avoid crashes #1523
* Include the block title in unsupported blocks #1533
* Support copy of url in clipboard. #1537
* Remove custom paragraph options for media-text #1538
* Implement client-defined media options. #1539
* Show new block indicator in default appender too #1542
* Media & Text alignment options #1546
* Update to latest version of GB master. #1548
* Update debug configuration for VSCode #1550
* Prevents selection after ZWSP character #1552
* Fix paste in title #1575
* Separate options for capturing photo and video #1579
* Fix Android crash when deleting some blocks #1582

### Test plan

1. Please use the main WP apps to test the changes above. See WPAndroid and WPiOS PRs for a tests checklist.
2. Smoke test the main WP apps for general writing flow

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by marecar3** [comment]
Let's make sure that this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1582
gets merged.

**Comment by hypest** [comment]
I've tested the WPAndroid and WPiOS PRs and this looks good to me 👍!

**Comment by marecar3** [comment]
Hey, @hypest @mchowning and @cameronvoell WPAndroid look nice, but I have found some regressions.

1. Image upload (visual) regression - when a placeholder is presented on the end of upload (when the progress is 100%), the progress bar is on the bottom of the placeholder and it should be on top of the placeholder.

ezgif com-video-to-gif (11)

2. Video upload (visual) regression - when the upload is in progress placeholder isn't good as a background is missing also image in the center should be bigger (similar to the image placeholder)

ezgif com-video-to-gif (12)

It seems that they aren't blockers for a merge 🤔

**Comment by mchowning** [comment]
>Image upload (visual) regression - when a placeholder is presented on the end of upload (when the progress is 100%), the progress bar is on the bottom of the placeholder and it should be on top of the placeholder.

I see this as well. Does look like a regression.

>Video upload (visual) regression - when the upload is in progress placeholder isn't good as a background is missing and also image in the center should be bigger (similar to the image placeholder)

I'm not as certain about this one as @iamthomasbishop recently opened [an issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1544) saying that the image placeholder icon is too big and that it looks like the video block has the proper styling. We should probably get his feedback before doing any changes here.

>It seems that they aren't blockers for a merge 🤔

I think that's right. I don't see any reason either of these should block the release.

**Comment by iamthomasbishop** [comment]
> I'm not as certain about this one as @iamthomasbishop recently opened an issue saying that the image placeholder icon is too big and that it looks like the video block has the proper styling. We should probably get his feedback before doing any changes on this (for the next release).

Yes, you're right, the image block's placeholder icon is incorrect – video uses the proper style.

**Comment by mchowning** [comment]
Updated from `9c19f9c` to `bd25fb8` because I was getting a different bundle when building it locally. Looks like that was just because bundles include references to the local environment, so reverted back to `9c19f9c`.

**Pull request merged**
