### PR TITLE
Audio block UI test

### PR DESCRIPTION
**Pull request by jd-alexander**
gutenberg PR https://github.com/WordPress/gutenberg/pull/28674

This PR updates the gutenberg reference to test the new UI tests for the Audio block.

To test:

CI must be ✅ ( Will be marked as ready for review once tests pass)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by jd-alexander** [comment]
@ceyhun I need some advice on this, the id of the audio block is failing on either Android or iOS on the full test suite, and the id difference is by 1. I am not sure what's causing this.

**Comment by ceyhun** [comment]
>@ceyhun I need some advice on this, the id of the audio block is failing on either Android or iOS on the full test suite, and the id difference is by 1. I am not sure what's causing this.

@jd-alexander I think I found where it came from.

- iOS: 
https://github.com/WordPress/gutenberg/blob/8cfbfb0c8b184e2dc48299b53a91b0c5b91e5d0c/packages/react-native-editor/ios/GutenbergDemo/GutenbergViewController.swift#L106
- Android: 
https://github.com/WordPress/gutenberg/blob/8cfbfb0c8b184e2dc48299b53a91b0c5b91e5d0c/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java#L88


I think it could be better to set Android one to 5 because another media with id=4 already exists on iOS 😄

**Comment by jd-alexander** [comment]
> >@ceyhun I need some advice on this, the id of the audio block is failing on either Android or iOS on the full test suite, and the id difference is by 1. I am not sure what's causing this.
> 
> 
> 
> @jd-alexander I think I found where it came from.
> 
> 
> 
> - iOS: 
> 
> https://github.com/WordPress/gutenberg/blob/8cfbfb0c8b184e2dc48299b53a91b0c5b91e5d0c/packages/react-native-editor/ios/GutenbergDemo/GutenbergViewController.swift#L106
> 
> - Android: 
> 
> https://github.com/WordPress/gutenberg/blob/8cfbfb0c8b184e2dc48299b53a91b0c5b91e5d0c/packages/react-native-editor/android/app/src/main/java/com/gutenberg/MainApplication.java#L88
> 
> 
> 
> 
> 
> I think it could be better to set Android one to 5 because another media with id=4 already exists on iOS 😄 

You have such a good eye. I just remembered that those were declared as such. Thanks @ceyhun 😬

**Review by ceyhun — COMMENTED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/28674

**Review by ceyhun — APPROVED** [review]

**Pull request merged**
