### PR TITLE
Update Appium dependency version to 1.20.2

### PR DESCRIPTION
**Pull request by fluiddot**
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/28890

## Description
Appium dependency has recently included a fix for preventing an error when using NPM version 7 so it would be nice to update it.

To test:
Appium is only used for running the end-to-end tests so we need to verify that they work as expected. It should be enough by verifying that the PR checks pass and by running them locally with the following commands:
1. `npm run test:e2e:ios:local` for iOS
2. `npm run test:e2e:android:local` for Android

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by dcalhoun — COMMENTED** [review]
🟢 Changes look good to me.
🟢 iOS e2e tests passed locally.
🟡 Android e2e tests had oddities locally.

The `gutenberg-editor-audio` tests hang indefinitely for me. I waited several minutes for them to fail, but they never did. I ultimately canceled the run. I asked @jd-alexander and he had not encountered this before. I suppose since this passes on the CI, this should not be a blocker. May just be a local environment issue.

<details>
<summary>Audio block hang</summary>

https://user-images.githubusercontent.com/438664/107797928-18a8dc00-6d21-11eb-876a-99e86e8e8a65.mov

</details>

The `gutenberg-editor-paste` passes on my emulator device, but fails on my physical Samsung S20 5G SE device. I'm wondering if this is something specific to (A) my local setup, (B) Samsung devices, or (C) using a physical device in general. I suppose since this passes on the CI, this should not be a blocker.

<details>
<summary>Paste test failure</summary>

android-paste-failures

https://user-images.githubusercontent.com/438664/107800135-054b4000-6d24-11eb-9776-2426431b6cc8.mp4

</details>

@fluiddot did you encounter anything like this when running the Android e2e tests locally? If not, then it's likely just my local environment.

**Comment by ockham** [comment]
:wave: @fluiddot @dcalhoun It seems that this is blocking https://github.com/WordPress/gutenberg/pull/28890 in the Gutenberg repo, which in turn is required for npm 7 to work with GB. Any chance we'll be able to unblock things anytime soon? :blush: :pray: 

(edit, wrong PR)

**Review by dcalhoun — APPROVED** [review]
As we discussed in Slack, I think the e2e test oddities I encountered locally are likely not of consequence. The CI suite is succeeding and that should give us confidence.

**Comment by fluiddot** [comment]
> As we discussed in Slack, I think the e2e test oddities I encountered locally are likely not of consequence. The CI suite is succeeding and that should give us confidence.

Yeah, I'm going to run a last test on Android just to verify there's no issue locally and then merge it, thanks!

**Comment by fluiddot** [comment]
>Android e2e tests had oddities locally.

>The gutenberg-editor-audio tests hang indefinitely for me. I waited several minutes for them to fail, but they never did. I ultimately canceled the run. I asked @jd-alexander and he had not encountered this before. I suppose since this passes on the CI, this should not be a blocker. May just be a local environment issue.

I also experience this issue the first time I ran them, in my case the audio block was not included in the inserter menu and it was failing. I managed to fix it by uninstall the `Gutenberg` app from the emulator and run the command again, I think in some cases the command doesn't install a fresh build.

>The gutenberg-editor-paste passes on my emulator device, but fails on my physical Samsung S20 5G SE device. I'm wondering if this is something specific to (A) my local setup, (B) Samsung devices, or (C) using a physical device in general. I suppose since this passes on the CI, this should not be a blocker.

I haven't checked e2e tests with a real device locally, I'm wondering if the issue is related to these changes, have you run e2e tests on a device previously?

**Comment by dcalhoun** [comment]
> I haven't checked e2e tests with a real device locally, I'm wondering if the issue is related to these changes, have you run e2e tests on a device previously?

@fluiddot no, I have not run the e2e tests on a physical device prior to this PR. I can attempt to do so on `develop` and see what occurs. I'll report back.

**Comment by dcalhoun** [comment]
@fluiddot after running the `develop` branch e2e tests on a physical device, I can confirm that the paste tests fail in `develop` as well. This should provide additional confidence in merging this PR.

**Comment by fluiddot** [comment]
As we discussed, since the CI suite is succeeding, it should be safe to merge it, thanks for the review @dcalhoun !

If we spot new issues regarding the e2e tests we'll address them in new PRs (like the one when testing with physical device).

**Comment by ockham** [comment]
Thanks a lot, folks! :heart:

**Pull request merged**
