### PR TITLE
Rename snapshot tests.

### PR DESCRIPTION
**Pull request by twstokes**
Updates the filenames for snapshot tests located in `__device-tests__/image-snapshots`:

`for f in *sanity*; do git mv "$f" "$(echo "$f" | sed 's/sanity/functionality/g')"; done`

This is a follow up to https://github.com/wordpress-mobile/gutenberg-mobile/pull/6164.

To test:
- Ensure CI doesn't fail

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
On this PR I'll trigger the full tests. 👍

**Comment by twstokes** [comment]
@fluiddot and @SiobhyB - would you mind giving this PR a look? All tests including the optional ones seem to have passed. Thanks!

**Review by dcalhoun — APPROVED** [review]
🚀

**Review by fluiddot — COMMENTED** [review]
> @fluiddot and @SiobhyB - would you mind giving this PR a look? All tests including the optional ones seem to have passed. Thanks!

I saw the PR is already merged, so I'm leaving my approval as a comment. LGTM 🎊 !

**Pull request merged**
