### PR TITLE
Remove block top/bottom padding

### LINKED ISSUE #393: Paragraph  / Heading blocks have extra bottom margin above block controls
First reported by @iamthomasbishop - there's an extra space in between the end of the content area for Paragraph and Heading blocks, and their corresponding container (with the up/down arrows and trash controls)

iOS:

image from ios 12

Android:
screenshot_20181217-202721

### PR DESCRIPTION
**Pull request by mzorz**
Fixes #393 

Removes the top/bottom padding on `block-container` as it was adding an unneeded extra space.

Before:
screen shot 2018-12-18 at 11 57 55

After:
screen shot 2018-12-18 at 11 56 39

Before (WPAndroid):
screen shot 2018-12-18 at 12 02 18

After (WPAndroid):
screen shot 2018-12-18 at 12 03 29

Before (demo app on iOS):
screen shot 2018-12-18 at 12 13 50

After (demo app on iOS):

screen shot 2018-12-18 at 12 19 03

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Thanks for pinging for review. Unsupported blocks should still maintain that top/bottom padding, so how it was in the "before" examples was proper. Example:

image

Note: each block, regardless of type, has the same padding: 12pt top/bottom, 16pt left/right.

I think we should also think about implementing the styling shown here, but that's for a separate issue.

**Comment by mzorz** [comment]
Updated in 9f21f87dbe6699ea2e8e089d4300483222c1c426, where it's been updated to match that 12dp value for top/bottom for `unsupported` blocks _only_:

#### Before
screen shot 2018-12-18 at 12 58 09


#### After
screen shot 2018-12-18 at 12 58 30


does it look good now @iamthomasbishop ?

**Comment by mzorz** [comment]
> Note: each block, regardless of type, has the same padding: 12pt top/bottom, 16pt left/right.

oops! this is fixed then in a1bdd09

results:

screen shot 2018-12-18 at 13 09 35

**Comment by mzorz** [comment]
ok - ready for another pass @iamthomasbishop , implemented the specs described in  https://github.com/wordpress-mobile/gutenberg-mobile/issues/393#issuecomment-448302105   in 81d9704, this is how it looks like (before/after):

screen shot 2018-12-18 at 15 03 48

**Comment by mzorz** [comment]
Merging as agreed

**Comment by iamthomasbishop** [comment]
As discussed in dm, the block inner body padding/margin stuff looks good here, so feel free to 🚢! 

We can handle this in a separate issue, but the spacings on the inline toolbar (up/down/trash) needs to be slightly tweaked to include a slight (2pt) margin on both left/right edges of the toolbar. This helps to visually align the block content a little better.

image

**Comment by mzorz** [comment]
no worries, opened issue here https://github.com/wordpress-mobile/gutenberg-mobile/issues/409 - let's follow discussion there or on upcoming PR

**Pull request merged**
