### PR TITLE
Add v1.73.0-alpha2 release 

### PR DESCRIPTION
**Pull request by jhnstn**
Fixes https://github.com/wordpress-mobile/WordPress-iOS/pull/18184#pullrequestreview-917510260

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by jhnstn** [comment]
> buildkite/gutenberg-mobile/build-android-rn-aztec-and-publish-to-s3 — Failed (exit status 1)

I pushed the tag before running `npm run bundle`. I'm not sure need to resolve this since `android-rn-bridge` is not dependent on the bundle step in this repo.

**Comment by fluiddot** [comment]
@jhnstn I see that the [tag `v1.73.0-alpha2`](https://github.com/wordpress-mobile/gutenberg-mobile/releases/tag/v1.73.0-alpha2) is pointing to [a commit of this PR](https://github.com/wordpress-mobile/gutenberg-mobile/commit/11773681d976e536d1e2dcd3a5d2ded6564ae712). When I created tags for previous alpha versions, I usually create them after the PR is merged into `trunk`. This way the PR checks related to publishing the Android artifacts won't fail and the tag will point to a merge commit in `trunk`. What do you think about doing it that way?

**Comment by jhnstn** [comment]
> When I created tags for previous alpha versions, I usually create them after the PR is merged into trunk

Thanks @fluiddot, I wasn't sure when to tag the alpha. I can move the tag.

> This way the PR checks related to publishing the Android artifacts won't fail 

Do you know why that would be the case? The tag is still available while the commit is on this branch in the PR?

**Comment by jhnstn** [comment]
> Do you know why that would be the case? The tag is still available while the commit is on this branch in the PR?

nvm, I'm assume the the bridge building script must be looking for the tag on trunk. The `<pr-number>-<commit-sha>` pattern made me think that must be the case.

**Comment by jhnstn** [comment]
@fluiddot, I removed the [alpha2 tag](https://github.com/wordpress-mobile/gutenberg-mobile/tree/v1.73.0-alpha2). Also looks like all the checks have passed. If you think this looks good I'll tag trunk at the merge commit.

**Comment by fluiddot** [comment]
> Thanks @fluiddot, I wasn't sure when to tag the alpha. I can move the tag.

The job that publishes the Android artifacts (i.e. `react-native-editor` and `react-native-aztec`) uses the Git reference passed to the Buildkite job as the ID of the artifact ([reference](https://github.com/wordpress-mobile/docker-android-build-image/blob/trunk/scripts/prepare_to_publish_to_s3_params)). This means that if you create a tag, it will automatically publish the artifacts using that value. However, once the artifacts are created they can't be overwritten, so in this case, moving the tag won't work as we already published artifacts for tag `v1.73.0-alpha2` ([reference](https://buildkite.com/automattic/gutenberg-mobile/builds/2520#75239d6e-c3eb-47ad-a802-1287d8563ad1/190-256)), although not sure why it was published from a totally different branch 😅 .

At this point, once this PR gets merged, we'd need to create a new tag (i.e. `v1.73.0-alpha3`).

> Do you know why that would be the case? The tag is still available while the commit is on this branch in the PR?

I think this is related to [this script](https://github.com/wordpress-mobile/docker-android-build-image/blob/trunk/scripts/prepare_to_publish_to_s3_params). When pushing a commit that has an associated tag, the Android artifacts will be published using the tag instead of the `<pt-number>-<commit-sha>` format. If you removed the tag, re-running the Buildkite job will succeed because it won't detect the Git tag.

> nvm, I'm assume the the bridge building script must be looking for the tag on trunk. The <pr-number>-<commit-sha> pattern made me think that must be the case.

👍 

> @fluiddot, I removed the [alpha2 tag](https://github.com/wordpress-mobile/gutenberg-mobile/tree/v1.73.0-alpha2). Also looks like all the checks have passed. If you think this looks good I'll tag trunk at the merge commit.

Great, I'll approve the PR and once we merge it, we could create the tag and update the GB-mobile reference in the WordPress-iOS PR.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Pull request merged**
