### PR TITLE
[Embed block] - Unavailable preview fallback bottom sheet title update

### PR DESCRIPTION
**Pull request by jd-alexander**
To test:
Utilize the testing instructions at https://github.com/WordPress/gutenberg/pull/34674

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by fluiddot — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/34674#pullrequestreview-752417959.

**Comment by jd-alexander** [comment]
@fluiddot I have the same node and npm version as CI. When I run npm install I and push the diff of the package-lock.json file is still fails. I am not sure what is wrong locally that could be causing this. Do you have any clues ?

**Comment by fluiddot** [comment]
> @fluiddot I have the same node and npm version as CI. When I run npm install I and push the diff of the package-lock.json file is still fails. I am not sure what is wrong locally that could be causing this. Do you have any clues ?

Not really, but I noticed that the last [Dependabot's PR "Bump gutenberg from cb459f8 to e48adc4"](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3955) is also failing due to a mismatch on that file:
```
index 39eb5f8..b79d955 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -6253,8 +6253,8 @@
 			"version": "file:gutenberg/packages/eslint-plugin",
 			"dev": true,
 			"requires": {
-				"@typescript-eslint/eslint-plugin": "^4.15.0",
-				"@typescript-eslint/parser": "^4.15.0",
+				"@typescript-eslint/eslint-plugin": "^4.31.0",
+				"@typescript-eslint/parser": "^4.31.0",
 				"@wordpress/prettier-config": "file:gutenberg/packages/prettier-config",
 				"babel-eslint": "^10.1.0",
 				"cosmiconfig": "^7.0.0",
```

So this might be an incoming breakage from the Gutenberg's `trunk` branch, I'll try it locally in case I found a workaround.

**Comment by fluiddot** [comment]
> > @fluiddot I have the same node and npm version as CI. When I run npm install I and push the diff of the package-lock.json file is still fails. I am not sure what is wrong locally that could be causing this. Do you have any clues ?
> 
> Not really, but I noticed that the last [Dependabot's PR "Bump gutenberg from cb459f8 to e48adc4"](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3955) is also failing due to a mismatch on that file:
> 
> ```
> index 39eb5f8..b79d955 100644
> --- a/package-lock.json
> +++ b/package-lock.json
> @@ -6253,8 +6253,8 @@
>  			"version": "file:gutenberg/packages/eslint-plugin",
>  			"dev": true,
>  			"requires": {
> -				"@typescript-eslint/eslint-plugin": "^4.15.0",
> -				"@typescript-eslint/parser": "^4.15.0",
> +				"@typescript-eslint/eslint-plugin": "^4.31.0",
> +				"@typescript-eslint/parser": "^4.31.0",
>  				"@wordpress/prettier-config": "file:gutenberg/packages/prettier-config",
>  				"babel-eslint": "^10.1.0",
>  				"cosmiconfig": "^7.0.0",
> ```
> 
> So this might be an incoming breakage from the Gutenberg's `trunk` branch, I'll try it locally in case I found a workaround.

I've just noticed that you fixed this in commit https://github.com/wordpress-mobile/gutenberg-mobile/pull/3935/commits/4b66b807d9b33e6d45e77634d6b6ab967670d9ff so I'm not sure yet what's causing this 🤔 .

**Comment by fluiddot** [comment]
I managed to fix it by running the command `npm install @typescript-eslint/eslint-plugin@latest --save-dev` as it's mentioned in the error message:
```
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".

(The package "@typescript-eslint/eslint-plugin" was not found when loaded as a Node module from the directory "/home/circleci/project".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @typescript-eslint/eslint-plugin@latest --save-dev

The plugin "@typescript-eslint/eslint-plugin" was referenced from the config file in ".eslintrc.js » plugin:@wordpress/recommended".
```

However, I'm not sure why we need this is needed now if that package was referenced weeks ago ([reference](https://github.com/WordPress/gutenberg/pull/34055/files#diff-80ec6c18403ec58b2abdf7b2f0e86a7d1cc6a6db135cd69765de3ffa36f049faR42)) 🤔 .

**Comment by fluiddot** [comment]
>  I managed to fix it by running the command npm install @typescript-eslint/eslint-plugin@latest --save-dev as it's mentioned in the error message

I applied this fix in ["Bump gutenberg from cb459f8 to e48adc4" PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3955) and the ["Check Correctness" job](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/14087/workflows/325d2248-cc35-46e1-b167-373190bb2c52/jobs/76721) passed 🟢 .

**Comment by fluiddot** [comment]
> However, I'm not sure why we need this is needed now if that package was referenced weeks ago (reference) 🤔 .

Ok, looks like it's caused by the modification of the `package-lock.json` file, [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3935/commits/5869390634df5e0732fee337c12859f859129e46#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L4059) you can see that the `@typescript-eslint/eslint-plugin` root-level dependency is removed. Nevertheless, it's still unclear to me why it gets removed 🤔 .

**Comment by jd-alexander** [comment]
> Ok, looks like it's caused by the modification of the package-lock.json file, here you can see that the @typescript-eslint/eslint-plugin root-level dependency is removed. Nevertheless, it's still unclear to me why it gets removed 🤔 . 

Ah, understood! I will sync with `develop` once https://github.com/wordpress-mobile/gutenberg-mobile/pull/3955 is merged in. 🙏🏾

**Comment by fluiddot** [comment]
> > Ok, looks like it's caused by the modification of the package-lock.json file, here you can see that the @typescript-eslint/eslint-plugin root-level dependency is removed. Nevertheless, it's still unclear to me why it gets removed 🤔 .
> 
> Ah, understood! I will sync with `develop` once #3955 is merged in. 🙏🏾

I've just merged https://github.com/wordpress-mobile/gutenberg-mobile/pull/3955 into `develop` so feel free to sync it.

**Pull request merged**
