### PR TITLE
Release 1.53.1

### PR DESCRIPTION
**Pull request by AmandaRiu**
Release for Gutenberg Mobile 1.53.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/32071
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14690
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16554
- ~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~
- ~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

- [Gallery block fix: restore focus caption prop for native](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3534)
- [Fix missing title for some unsupported blocks](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3489)

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [ ] Verify Items from test plan have been completed
- [ ] Approve and run optional Android and iOS UI tests
- [ ] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [ ] Bundle package of the release is updated.

### CODE REVIEW

**Comment by dcalhoun** [comment]
## 🟢 iOS Writing Flow checklist (round 1)

* iPhone SE
* iOS 14.4.2
* Build `48731` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16554#issuecomment-845584028.

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
Verified the currently included fixes listed below cause the related bugs to no longer occur on an iPhone SE, iOS 14.4.2, with build `48731` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16554#issuecomment-845584028. 🎉 

- [Gallery block fix: restore focus caption prop for native](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3534)
- [Fix missing title for some unsupported blocks](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3489)

**Comment by dcalhoun** [comment]
## 🟡 iOS Unsupported Block Editor Tests (round 1)

* iPhone SE
* iOS 14.4.2
* Build `48731` from https://github.com/wordpress-mobile/WordPress-iOS/pull/16554#issuecomment-845584028.

- [x] TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 - User can discard edits to an unsupported blocks on Simple WP.com sites
- [x] TC003 - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
  🟡 TC004 encountered a variant of a preexisting issue, captured in https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425#issuecomment-846188216. 
- [x] TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 - Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Comment by AmandaRiu** [comment]
## 🔁 Android Writing Flow Checklist

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by AmandaRiu** [comment]
## 🔁 Android Unsupported Block Editor Tests

* Pixel 4
* Android 11
* _pending_

- [x] TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 - User can discard edits to an unsupported blocks on Simple WP.com sites
- [x] TC003 - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 - Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Review by dcalhoun — APPROVED** [review]
LGTM. Hopefully we can successfully create an Android build soon to verify the changes before merging.

**Comment by AmandaRiu** [comment]
Verify the following fixes on Android (Pixel 4 - Android 11):
- [x] [Gallery block fix: restore focus caption prop for native](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3534)
- [x] [Fix missing title for some unsupported blocks](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3489)

**Pull request merged**
