### PR TITLE
Issue/3055 show disabled block reason artifact generation

### PR DESCRIPTION
**Pull request by jd-alexander**
Purpose:
Utilized to generate artifact for https://github.com/wordpress-mobile/gutenberg-mobile/pull/4005

- iOS installable build: https://github.com/wordpress-mobile/WordPress-iOS/pull/17316

### CODE REVIEW

**Comment by dnalves** [comment]
@jd-alexander The WPAndroid and WPiOS PRs are pointing to the latest commit in this branch. Maybe we should update this with the latest `develop` to make sure we'll test with all the new changes?

**Comment by fluiddot** [comment]
Hey @jd-alexander  !
We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!

**Comment by fluiddot** [comment]
> Hey @jd-alexander ! We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!

@jd-alexander I think we could unassign the milestone to this PR as it's draft, wdyt?

**Comment by jd-alexander** [comment]
> > Hey @jd-alexander ! We will cut the 1.66.0 release on 2021-11-11. I plan to circle back and bump this PR to the next milestone then, but please let me know if you’d rather us work to include this PR in 1.66.0. Thanks!
> 
> 
> 
> @jd-alexander I think we could unassign the milestone to this PR as it's draft, wdyt?

Yes, sounds good. 👍🏾

**Pull request closed without merging**
