### PR TITLE
iOS: Aztec fully wired (v1).

### PR DESCRIPTION
**Pull request by diegoreymendez**
This PR wraps up the initial wiring of Aztec to `gutenberg-mobile`.  It wires Aztec's content to our JavaScript state.

Closes #73.

### Details:

This PR also introduces some changes to how we store `eventCount` in our JS code.

According to https://facebook.github.io/react-native/docs/state:

```text
There are two types of data that control a component: props and state. props
are set by the parent and they are fixed throughout the lifetime of a
component. For data that is going to change, we have to use state.
```

Since `eventCount` was being changed throughout the lifetime of the Aztec TextView component, moving it to `state` made the most sense to adhere to the documentation cited above.

Storing it as a `prop` (that's what I understand we were doing before) was causing issues on iOS's side of the code.  When switching the editor to HTML mode and back, the `eventCount` was being persisted needlessly.  By removing it we were able to simplify the TextView refresh logic considerably.

### Testing:

- Make sure that you can type normally in the Aztec view.
- Switch to HTML and make sure the source code looks good.
- Switch back to visual and make sure the state wasn't lost.'

### Development tests:

✅ Tested in iOS
✅ Tested in Android (had some trouble initially to get the app running, but it was solved by resetting the cache).

### CODE REVIEW

**Comment by diegoreymendez** [comment]
Merged the latest from master into this PR and resolved the conflicts.

**Comment by daniloercoli** [comment]
Is this PR still relevant in the light of #81 being merged soon?

**Comment by diegoreymendez** [comment]
@daniloercoli - Once #81 is merged I can update this one (I'd say let's try to do it in order to be fair with the earlier PRs).

But it includes changes to `block-holder.js` that I need merged.

**Comment by hypest** [comment]
👋 @diegoreymendez , can you expand the PR description with some info on the `eventCount` related changes? I think I see 3 distinct changes (becoming optional, keeping it in the state vs the props and removing it from the call to `props.onChange()`. Thanks!

**Comment by diegoreymendez** [comment]
@hypest - Done.

**Comment by diegoreymendez** [comment]
PS: the first change is not making it optional (it already was).  What the first change does is actually "register" it as a `StateType` property.

**Pull request merged**
