### PR TITLE
Add "Autosave" bridge methods and enable local auto-save of posts

### PR DESCRIPTION
**Pull request by daniloercoli**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/10415

This PR adds the required bridge methods to Android that are used to link the GB side with the native side, and enable auto-save triggered from the GB side.

To tests this PR, follow the instruction on the following wp-android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/10483

cc @etoledom Once the approach is validated we should add the iOS code before merging this PR.

Edit:
`WPiOS` PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12489
`gutenberg` PR: https://github.com/WordPress/gutenberg/pull/17329

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by mkevins** [comment]
Just adding: gb companion PR link: https://github.com/WordPress/gutenberg/pull/17329

**Comment by etoledom** [comment]
Added the iOS side: https://github.com/wordpress-mobile/gutenberg-mobile/pull/1351/commits/4b9881f8a0744ea3009c67fbc1e3b4f670f23707

I also created the WPiOS side PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/12489

In what version we want to ship this?
If it's WP apps v13.3, I think we should target our latest frozen branch? (`1.12.0`)
I'm a bit confused with the release dates.

If that's not the case, we won't be able to merge the WPiOS PR until its own next code freeze, since these changes has breaking changes.

**Comment by koke** [comment]
Don't forget to generate new bundles before merging this, I went to test the iOS PR and I kept wondering why it wasn't working 😅

**Comment by daniloercoli** [comment]
> If that's not the case, we won't be able to merge the WPiOS PR until its own next code freeze, since these changes has breaking changes.

I think we should not touch the frozen branch. So for both iOS and Android we need to wait until next code freeze.

**Pull request merged**
