### PR TITLE
Generic Embed Block placeholder UI 

### LINKED ISSUE #3273: [Embed block] Implement Generic Embed Block placeholder UI
### Description
- Implement Generic Embed Block placeholder UI
- Bottom sheet will be implemented in a separate issue
- When a block placeholder is added, bottom sheet is automatically opened. Therefore any `onPress` prop should be triggered in this case.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #3273

To test:
https://github.com/WordPress/gutenberg/pull/30592

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by dcalhoun** [comment]
Hey @jd-alexander. 👋🏻 We will cut the 1.51.0 release Friday 16 April. I plan to circle back and bump this PR to the next milestone (1.52.0) on Friday, but please let me know if you'd rather us work to include this PR in 1.51.0. Thanks! 🙇🏻

**Comment by jd-alexander** [comment]
> Hey @jd-alexander. 👋🏻 We will cut the 1.51.0 release Friday 16 April. I plan to circle back and bump this PR to the next milestone (1.52.0) on Friday, but please let me know if you'd rather us work to include this PR in 1.51.0. Thanks! 🙇🏻

Thanks, @dcalhoun I bumped it to 1.52.0 🙇🏾

**Comment by cameronvoell** [comment]
Hey @jd-alexander. 👋🏻 We will cut the 1.52.0 release Friday 30 April. I plan to circle back and bump this PR to the next milestone (1.53.0) on Friday, but please let me know if you'd rather us work to include this PR in 1.52.0. Thanks! 🙇

**Review by ceyhun — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/30592. 
@jd-alexander I'm seeing a Jetpack reference update here next to Gutenberg ref update, I think it shouldn't be the case, right?

**Comment by jd-alexander** [comment]
> @jd-alexander I'm seeing a Jetpack reference update here next to Gutenberg ref update, I think it shouldn't be the case, right?

Thanks! Seems the update didn't sync to the latest. Removing it and updating the gb ref.

**Pull request merged**
