### PR TITLE
Update/gutenberg jetpack and package lock

### PR DESCRIPTION
**Pull request by mkevins**
Update Jetpack and Gutenberg reference, and update package lockfile.

To test:
Tests should pass on CI.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by hypest** [comment]
👋 Matthew! Took the liberty to push the package-lock.json that my local `npm install` produces (node v14.17.0, npm v6.14.13 that get installed via `nvm install` inside the gutenberg subfolder). Let's see it that will fix [the mismatch](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/12440/workflows/f94a8788-202b-4008-bf55-3eeb5a0cefba/jobs/67029).

**Comment by hypest** [comment]
The Correctness CI job fails with some eslint issues, most probably related to outdated way we invoke it. I left a [comment on a relevant PR for help](https://github.com/WordPress/gutenberg/pull/25300#issuecomment-858731668) but, take a look too @mkevins if you can get to it, thanks!

**Comment by mkevins** [comment]
>  Matthew! Took the liberty to push the package-lock.json that my local `npm install` produces (node v14.17.0, npm v6.14.13 that get installed via `nvm install` inside the gutenberg subfolder). Let's see it that will fix [the mismatch](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/12440/workflows/f94a8788-202b-4008-bf55-3eeb5a0cefba/jobs/67029).

Thanks Stefanos! Following up on the repllies in the thread of the relevant PR, I updated the version of `eslint-pluging-jsdoc` in `gutenberg-mobile` to align with the version used in `gutenberg`, and that seemingly resolved the issues we were seeing on CI.

I did not track down where / why we have our own dependency on the `eslint-plugin-jsdoc`, or whether it makes sense to remove it. For now, I focused on getting CI green for other PRs (especially the release PRs).

Also, for some reason when I ran `npm run lint` locally (which then runs `eslint . --ext .js`) it seemed to hang indefinitely, with CPU ~ 100%. :man_shrugging:

**Review by antonis — APPROVED** [review]
Thank you @mkevins and @hypest for handling this 🙇 

> I updated the version of eslint-pluging-jsdoc in gutenberg-mobile to align with the version used in gutenberg, and that seemingly resolved the issues we were seeing on CI.

The change LGTM and seems to work fine since the CI is green 🎉 

> I did not track down where / why we have our own dependency on the eslint-plugin-jsdoc, or whether it makes sense to remove it.

That's a good point. Maybe we should revisit this 🤔

**Comment by mkevins** [comment]
Thanks for reviewing Antonis!

**Pull request merged**
