### PR TITLE
Rename tests to use "functionality"

### PR DESCRIPTION
**Pull request by twstokes**
Renames tests to use "functionality" rather than "sanity".

Ref: pc8Hgn-lI-p2

To test:
- Confirm that CI ran successfully

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by twstokes** [comment]
👋 @SiobhyB would you mind reviewing this one for me? Thanks!

**Review by SiobhyB — APPROVED** [review]
Looks great, thank you for this @twstokes 🙌

**Comment by fluiddot** [comment]
Hey @twstokes 👋 , I noticed that E2E tests began to fail in `trunk` after this PR got merged. The cause seems to be related to renaming the test files and not updating [the screenshot files](https://github.com/wordpress-mobile/gutenberg-mobile/tree/trunk/__device-tests__/image-snapshots). We'd need to rename the screenshots according to the new test file names, otherwise, screenshots won't match and tests will fail.

**Comment by twstokes** [comment]
Ah thank you @fluiddot! I'd noticed the tests started failing but didn't know they were ones that hadn't ran on the PR. I'll look into it.

**Comment by fluiddot** [comment]
> Ah thank you @fluiddot! I'd noticed the tests started failing but didn't know they were ones that hadn't ran on the PR. I'll look into it.

I encountered a similar problem the last time I updated E2E tests with visual checks 😅. Let me know if I can help with the fix, thanks!

**Comment by twstokes** [comment]
Thanks! [PR started here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/6169).

**Pull request merged**
