### PR TITLE
Fix crash in mobile paragraph blocks with custom font size

### LINKED ISSUE #2991: Crash when opening a post with fontSize set to a paragraph
**Describe the bug**
The editor is crashing when opening a post that has a custom font size set in a paragraph.

**To Reproduce**
1. On the web, create a simple post with a single paragraph block and set its "Font Size" in the Typography section (see screenshot)
2. Save the post as draft or publish it
3. Go to the WPAndroid and open the post
4. 💥 

**Expected behavior**
The app should not crash.

**Screenshots**
Screenshot 2021-01-11 at 16 03 00

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android 11
 - WPAndroid Version 16.4-rc-3, 16.3, 15.9.1 (at least, probably happening on more versions too)

**Additional context**
* Doesn't seem to happen for me on WPiOS v16.3
* Sentry report: https://sentry.io/share/issue/0244926c0adf4aeda025bc36bae98d3e/ although Sentry conflates this with similar crash reports.

### PR DESCRIPTION
**Pull request by cameronvoell**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2991

#### Related PRs:
- gutenberg: https://github.com/WordPress/gutenberg/pull/28121 <=introduced a crash
- gutenberg: https://github.com/WordPress/gutenberg/pull/28209 <=fixed new crash
- test PR WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13746
- test PR WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15627

### Description
This change fixes a crash when opening a post that has a custom font size set in a paragraph.

### To Reproduce

1. On the web, create a simple post with a single paragraph block and set its "Font Size" in the Typography section (see screenshot)
2. Save the post as draft or publish it
3. Go to the WPAndroid or WPiOS and open the post
4. 💥

### Expected behavior
The app should not crash.

### Screenshots:
image

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
I verified that preformatted block did not have the same issue with custom fontSize causing a crash, but have not completed a full audit on where else this could be broken on mobile yet. Will update here if I feel confident that custom  fontSize is not crashing us outside the paragraph block

**Comment by hypest** [comment]
When we'll be confident about the fix, we'll want to publish it as a hotfix against the production apps, or betafix if it lands too late for a hotfix.

**Comment by cameronvoell** [comment]
> Will update here if I feel confident that custom fontSize is not crashing us outside the paragraph block

The same testing steps were crashing in Heading, and List blocks so I updated the fix and the testing steps. This PR is ready for review now.

**Comment by hypest** [comment]
Tested both WPAndroid and WPiOS and works like a charm!
I'll have a look at the code now.

**Comment by cameronvoell** [comment]
Fix was merged to gutenberg master, and brought to gutenberg-mobile by [betafix merge to master PR](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3016), so I'll close this PR

**Pull request closed without merging**
