### PR TITLE
More block enhancements

### LINKED ISSUE #859: More block
We have a working implementation, but split/merge doesn't work.

We need to decide if we use RichText, or fix #324 to add split/merge support to PlainText

### PR DESCRIPTION
**Pull request by etoledom**
Fixes #859 

As mentioned in  https://github.com/wordpress-mobile/gutenberg-mobile/issues/859#issuecomment-498321249, I opted for modifying the More block to be read only, in order for it to be ready for the next release.

More info and test steps on the gutenberg side PR: https://github.com/WordPress/gutenberg/pull/16005

On the design side, I noticed on web that More block and Page Break block look the same, so I implemented the same design we use for Page Break on mobile too, but I'll wait for @iamthomasbishop 's input on this.

more-block

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
Nice work! A couple of little things I wanted to document – although not specific to the Read More block (also applies to the Page Break block):

* The divider should extend to the ends of the canvas/container
* The label should be sans-serif
* Ideally the divider should be a dashed line, but I think that might've been a compromise bc of CSS limitations in the RN app

**Comment by etoledom** [comment]
Thank you for the review @iamthomasbishop !

> The divider should extend to the ends of the canvas/container

I was able to extend the lines a bit more, until the edge of the block content.

We can extend them more using some negative magic margin values, but I'm not sure if that's what you had in mind, and it might not be a very good idea :) 

> The label should be sans-serif

✅ 

> Ideally the divider should be a dashed line, but I think that might've been a compromise bc of CSS limitations in the RN app

The lines are actually a normal (thin) view with a background color. Not possible to make them dashed with the current component we are using. I'd recommend this to be a future enhancement.

This is an updated screenshot:

more

**Comment by koke** [comment]
> Not possible to make them dashed with the current component we are using. I'd recommend this to be a future enhancement

For reference, some initial effort going (on hold) here: https://github.com/WordPress/gutenberg/pull/14175

**Comment by iamthomasbishop** [comment]
Looks great to me! Thanks for the updates @etoledom! :shipit:

**Comment by etoledom** [comment]
Thank you both!

**Pull request merged**
