### PR TITLE
Merge release 1.66.0 to develop

### PR DESCRIPTION
**Pull request by jhnstn**
Related to https://github.com/wordpress-mobile/gutenberg-mobile/issues/4226

To test: N/A

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
@jhnstn I think we shouldn't close the https://github.com/wordpress-mobile/gutenberg-mobile/issues/4226 automatically when this PR gets merged, as we still need to do the checklist steps of `Clean Up Pending Work` and `Test the Release` sections. For this reason, I've updated the PR description to unlink the issue, please let me know if you have any concerns about this, thanks 🙇 .

**Comment by fluiddot** [comment]
@jhnstn I addressed the issue with the `package-lock.json` file in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4234, which updates the Gutenberg ref to the same commit as this PR. The idea is that once that PR is merged, we update this one with `develop`.

**Comment by jhnstn** [comment]
> @jhnstn I think we shouldn't close the #4226 automatically when this PR gets merged, as we still need to do the checklist steps of Clean Up Pending Work and Test the Release sections. For this reason, I've updated the PR description to unlink the issue, please let me know if you have any concerns about this, thanks 🙇 .

Thanks for catching that! It wasn't my intention to auto close the checklist issue. I just dropped the link in the description (TIL to look out for that later on)

**Comment by fluiddot** [comment]
> Thanks for catching that! It wasn't my intention to auto close the checklist issue. I just dropped the link in the description (TIL to look out for that later on)

No worries 😊 , in the worst case we could have re-opened it.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 !

**Pull request merged**
