### PR TITLE
Send non-deprecated language tags from Android in initialProps

### LINKED ISSUE #4368: Android: Title and Inserter do not honor system language when set to Hebrew
**Describe the bug**
The title text (e.g. "Add title") and block names in the Inserter (e.g. "Heading", "Paragraph") are not translated when the OS is set to use Hebrew and the app's language setting is kept at the default.

**To Reproduce**
1. Set Android's language to Hebrew [[instructions](https://support.google.com/accounts/answer/32047?hl=en&co=GENIE.Platform%3DAndroid)]
2. Clean install WordPress for Android
3. Start a new Post and observe the "Add title" text
4. Open the Block Inserter and observe the block names

**Expected behavior**
The app displays labels in Hebrew for the title and Inserter's block names. The portions of the app outside of the editor also reflect this setting.

**Actual behavior**
The portions of the app outside of the editor reflect this setting only.

**Screenshots**
<div>
Screenshot of the inserter not being translated
</div>

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11
 - Version 18.8-rc-2

**Additional context**
Setting the language to Hebrew from within the app settings (Me -> App Settings -> Interface Language) works correctly. It should be noted that it overrides the system setting. This may affect other languages (maybe just RTL), so those should be tested as well.

### PR DESCRIPTION
**Pull request by mchowning**
Fixes #4368 

See the [related Gutenberg PR](https://github.com/WordPress/gutenberg/pull/37565) for more information.

This PR also updates CI to run the (newly added) unit tests in the react-native-bridge package for Android.

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [X] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by twstokes — APPROVED** [review]
LGTM @mchowning 👍

**Comment by mkevins** [comment]
Hi @mchowning :wave: :smiley:  I noticed that this PR has a release note added to the 1.69.0 section, but I believe this landed after the 1.69.0 release was cut. I think this should land in the unreleased (soon to be 1.70.0) release notes section, does that sound correct?

**Comment by mchowning** [comment]
>  I noticed that this PR has a release note added to the 1.69.0 section, but I believe this landed after the 1.69.0 release was cut. I think this should land in the unreleased (soon to be 1.70.0) release notes section, does that sound correct?

Yes, that's right. Sorry about that and thanks for catching it.

Looks like it's already been fixed on the 1.70.0 release branch, so I don't think there's anything else that needs to be done now, but if there is just let me know.

**Comment by mkevins** [comment]
Thanks for confirming!

**Pull request merged**
