### PR TITLE
Feat: cover cross platform RangeControl

### PR DESCRIPTION
**Pull request by jbinda**
is a part of #1300

[Gutenberg related PR](https://github.com/WordPress/gutenberg/compare/rnmobile/master...callstack:rnmobile/range-control)

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by pinarol** [comment]
@iamthomasbishop could you take a look at the screen captures in the [gutenberg side PR](https://github.com/WordPress/gutenberg/pull/17282 ) and give feedback about color, style etc. ? Thanks!

**Comment by iamthomasbishop** [comment]
Feedback given, done and done! ✅

**Comment by mkevins** [comment]
Hi @jbinda :wave: 

I have been checking out this PR on the Android demo app, and it's looking mostly pretty good :+1: . I did notice one issue with the numerical input, where the numbers seem to be invisible:



Can you take a look at my example usage, and let me know if I'm missing anything?

<details>
<summary>These are the changes I used to test the component on the image block:</summary>

```diff
diff --git a/packages/block-library/src/image/edit.native.js b/packages/block-library/src/image/edit.native.js
index eb84652..015c603 100644
--- a/packages/block-library/src/image/edit.native.js
+++ b/packages/block-library/src/image/edit.native.js
@@ -250,6 +250,15 @@ class ImageEdit extends React.Component {
 					separatorType={ 'fullWidth' }
 					onChangeValue={ this.updateAlt }
 				/>
+				<BottomSheet.RangeCell
+					icon={ 'admin-settings' }
+					label={ __( 'Slider' ) }
+					value={ 1 }
+					minimumValue={ 1 }
+					maximumValue={ 8 }
+					separatorType={ 'fullWidth' }
+					onChangeValue={ () => {} }
+				/>
 				<BottomSheet.Cell
 					label={ __( 'Clear All Settings' ) }
 					labelStyle={ styles.clearSettingsButton }

```
</details>

**Comment by jbinda** [comment]
Hi @mkevins 

Thanks for testing RangeCell components. I currently change the implementation according to @iamthomasbishop notes from [here](https://github.com/WordPress/gutenberg/pull/17282#issuecomment-537686674)

I will also take a look what cause the issue you mentioned and back to you soon.

**Pull request merged**
