### PR TITLE
Enable using the JitPack mode of building from a parent project

### PR DESCRIPTION
**Pull request by hypest**
Addresses #2182

We currently experience high failure rate on JitPack building the gutenberg-mobile artifact for WPAndroid, so this PR tries to enable building the artifact and the JS bundle locally, by reusing the gradle-powered Node/RN build.

This mode is then used by WPAndroid. Related PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11833

To test:
1. CI should be green
2. Integration in the WPAndroid PR should be OK and green too. Nothing special to test out on this side.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mchowning** [comment]
Do we still want jitpack code [in `react-native-gutenberg-bridge`](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/react-native-gutenberg-bridge/android/build.gradle#L130-L150)?

**Comment by hypest** [comment]
> Do we still want jitpack code in react-native-gutenberg-bridge?

Actually, yes. This PR only removes the gutenberg-mobile bridge library building on Jitpack, but we still have the npm package forks be built on JitPack. Those repos are smaller and don't seem to pose an issue yet.

**Comment by hypest** [comment]
The WPAndroid PR will target a release so, this PR shall also target `master`. Will change it to that. Since this PR is introducing integration changes but no functional changes, I'm not planning to bump the library version.

**Comment by hypest** [comment]
cc @geriux since you're currently wrangling a hotfix release and this PR now targets master. Most probably, the hotfix will need to update after this lands on time.

**Comment by geriux** [comment]
> cc @geriux since you're currently wrangling a hotfix release and this PR now targets master. Most probably, the hotfix will need to update after this lands on time.

Cool! thanks for letting me now 👍

**Comment by hypest** [comment]
There's only one CI job pending on the WPAndroid PR ([on this commit](https://github.com/wordpress-mobile/WordPress-Android/pull/11833/commits/bb1e0a022422b56a161d253ce2d375e5da800d41)), which seems to be waiting for Firebase to queue the tests run, for more than 25mins now. I will start the merge domino since everything else is green at this point. Besides, that job will get re-triggered anyway.

**Pull request merged**
