### PR TITLE
Update existing templates to use new blocks

### PR DESCRIPTION
**Pull request by mkevins**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168

#### Related PR

`gutenberg`: https://github.com/WordPress/gutenberg/pull/21857

### Description

This PR updates the mobile pages templates to use new blocks. It also adds some additional starter content.

**To test:**

1. Start a new page, then repeat the following steps for these templates:
   * About
   * Blog
   * Services
2. Tap page template in picker (on the bottom of the screen)
3. Apply the template
4. Scroll through to ensure the content is using the blocks [described here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168#issuecomment-616857093)
5. Ensure additional content [listed here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168#issuecomment-619654811) has been added

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by mkevins** [comment]
Hi @iamthomasbishop :wave: :smile: 

Thanks for providing the [additional content described here](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2168#issuecomment-619654811). I've added that content, and updated the templates with all the new blocks.

<details>
<summary>Here's how the About template looks in desktop preview after it is applied</summary>

spt-about-desktop
</details>

**Note**: the button block alignment is a known issue.

I noticed that we are using slightly different images for the second and third images within the services template (focus and strategy) compared to your mockup. I also noticed a vertical alignment issue (which is probably related, since the image heights differ). Lastly, I see a word wrap issue when we use all 4 columns, so maybe we can reduce that down? Wdyt?

<details>
<summary>Services template applied and previewed in desktop mode</summary>

spt-services-desktop
</details>

**Comment by iamthomasbishop** [comment]
Thanks for the update @mkevins ! I had completely forgotten that on mobile we are only showing a max of 2 columns per row when in landscape orientation even though this results in 4 pretty-narrow columns on desktop. Perhaps we shouldn’t add a fourth column, after all. I think it does look a tad awkward on landscape phone and tablet, but perhaps we can adjust the Columns block to allow up to 3 columns per row (not as part of this work, but as a separate iteration on the Columns block). I think this would probably solve most of the concerns you had in your [latest comment](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2179#issuecomment-622284296).

cc @pinarol @lukewalczak @dratwas — I know we had a lengthy discussion while working on the Columns/Column block about how many column blocks per row we allow, but I think 2 is proving to be a bit too constricting. Should we consider increasing the maximum to 3 columns per row?

> I noticed that we are using slightly different images for the second and third images within the services template (focus and strategy) compared to your mockup

I didn’t swap in updated images for the columns in my mockups, only chose new images for each of the new columns I added. So what already exists in code is what we should continue using. 👍

**Comment by pinarol** [comment]
> cc @pinarol @lukewalczak @dratwas — I know we had a lengthy discussion while working on the Columns/Column block about how many column blocks per row we allow, but I think 2 is proving to be a bit too constricting. Should we consider increasing the maximum to 3 columns per row?

I don't have a strong preference actually, but if you think that would be better let's do that as part of [this issue.](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2197). I expect it'd be a straight forward change. We can also consider making the readable content area bigger than 512 in some wide screen devices and fit there even more columns.

**Comment by mkevins** [comment]
Hi @iamthomasbishop :wave: :smiley: 

I've reverted the addtion of the 4th column in the services template, so it is back to having 3 columns.

<details>
<summary>Services template with 3 columns - desktop preview</summary>

spt-services-desktop2
</details>

I've left the 4 columns with the quotes, since they didn't seem to have wrapping issues. Please let me know if you wanted that reverted as well, or if it's ok to leave it as is. In case of the latter, should we still add the `Needs Copy Review` label to the original issue for the quote?

**Comment by pinarol** [comment]
Can we accelerate the review of this one please? @iamthomasbishop @chipsnyder Let's target merging this till EOD Fri (May 8th) to make it to the next release.

**Comment by iamthomasbishop** [comment]
> Services template with 3 columns - desktop preview

@mkevins Ah, shoot. Just realize that first image is taller than the others — is there a way we can crop that image at the bottom to be the same height/width as the other images?

> I've left the 4 columns with the quotes, since they didn't seem to have wrapping issues. 

I would also move this back to 3 columns. It doesn’t look _terrible_, but wider columns might make for more readable text.

**Comment by mkevins** [comment]
Hi @iamthomasbishop :wave: 

I'll remove that 4th quote then. Thanks for the guidance.

> is there a way we can crop that image at the bottom to be the same height/width as the other images?

We can use the width parameter with Pexels to limit the width of the image, but it seems the problem is coming from their different aspect ratios (the first image has a ratio of 4:3, and the other two have ratios ~ 3:2). If you can provide a similar Pexels image for the first one, with a 3:2 aspect, I can replace it.

**Comment by iamthomasbishop** [comment]
@mkevins Here are some [updated images](https://cloudup.com/cYup77YRQeF), all cropped to 3:2 so we can ensure consistent sizing.

**Comment by mkevins** [comment]
> @mkevins Here are some [updated images](https://cloudup.com/cYup77YRQeF), all cropped to 3:2 so we can ensure consistent sizing.

Thanks Thomas! I've updated the images and removed the 4th column in the about template, and everything is lining up nicely now :tada: .

Template|Landscape|Desktop Preview
-|-|-
About | spt-about-landscape | spt-about-desktop2
Services | spt-services-landscape | spt-services-desktop3

**Comment by pinarol** [comment]
Thank you everyone! I went ahead and merged it when CI was green.

**Comment by mkevins** [comment]
Thanks for testing and reviewing, and thanks Pinar for wrangling the merge! :tada:

**Pull request merged**
