### PR TITLE
Introduce paragraph block and RichText component for mobile

### PR DESCRIPTION
**Pull request by daniloercoli**
<del>This PR is branched on the top of #80 "Update to latest GB master", so don't merge this before.</del>

Pretty simple PR in this repository:
- Changed the demo app that now loads & parses valid Paragraph blocks from HTML code.
- Use an updated version of GB hash that added support for:
-- RichText component on mobile (still need to optimize it a little bit better)
-- Add a Paragraph block for mobile

Most of the work was done in a separate branch/PR in the Gutenberg repository here:
https://github.com/WordPress/gutenberg/tree/rnmobile/port-para-block-use-latest-gb-master-july

iOS: No errors, but para blocks are empty.

### CODE REVIEW

**Comment by daniloercoli** [comment]
Relevant GB PR here: https://github.com/WordPress/gutenberg/pull/8231

**Comment by hypest** [comment]
On the iOS simulator, it seems that something goes wrong with the rendering and Aztec is rendered on what seems to be 2 blocks:
screen shot 2018-07-27 at 10 59 30

Anything we can do about it on this PR? cc @SergioEstevao

**Comment by SergioEstevao** [comment]
I think this need to be update on Aztec library itself, @diegoreymendez may now more details.

**Comment by daniloercoli** [comment]
Validation errors when I start typing into AzteciOS due to `p` tags being introduced in the content. (Those should be `br`).
screen shot 2018-07-27 at 10 46 56

**Comment by diegoreymendez** [comment]
@daniloercoli - I ended up merging [my PR](issue/47-richtext-ios-implementation-2) since the review was finished today.  Once merging the changes in this PR you should see the Aztec iOS issues mentioned above go away.

Let me know if you need help resolving the conflicts.

**Comment by daniloercoli** [comment]
Thanks @diegoreymendez -  Yes, I've been in chat with @SergioEstevao yesterday, and we decided to review your PR first. He is working on making the merge back to this PR.

**Pull request merged**
