### PR TITLE
Rich Image Caption feature branch

### PR DESCRIPTION
**Pull request by etoledom**
This PR merges the Rich Image Caption feature branch.

All this code has been already tested and approved here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/941

A smoke test should be enough to ✅ this PR.
For more detailed test cases, please check out https://github.com/wordpress-mobile/gutenberg-mobile/pull/941

`gutenberg` side PR: https://github.com/WordPress/gutenberg/pull/15571

cc @mchowning

center_caption_resized

IMG_1668

### CODE REVIEW

**Comment by etoledom** [comment]
Updated this PR and https://github.com/WordPress/gutenberg/pull/15571 to incorporate the changes from the video block.

I would appreciate a couple of 👀 from @mchowning and @marecar3 or @pinarol to be sure that everything is in order.

Thank you!

**Comment by marecar3** [comment]
Hey, @etoledom @mchowning this PR looks good :)

However, there is some case where it crashes. So if you try to upload the video, it will crash with red screen.

The issue is in this line of code: https://github.com/WordPress/gutenberg/blob/449c25459c917b546cdfd786dbfd56dd3cb9a43a/packages/block-library/src/video/edit.native.js#L218 

Having that on mind we probably want to remove `( styles[ 'caption-text' ].fontFamily )` and also `import styles from '../image/styles.scss';` from video block 

and maybe to move this : 

`.caption-text {
	font-family: $default-regular-font;
}`

into the corresponding video style file: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/video/style.native.scss

**Comment by etoledom** [comment]
Nice catch @marecar3 !
I have added the missing style (fonts) to the video styles scss file.
It was removed from the Image block since it's not used by RichText.

A better "fix" will be when we use RichText Captions in Video Blocks too (in the future).
Would you mind checking it again?

Thank you!

**Comment by etoledom** [comment]
Thank you @marecar3 !!
I'll wait for https://github.com/wordpress-mobile/gutenberg-mobile/pull/949 to be merged before merging this one. Just in case, to avoid possible conflicts and more troubles merging that fix.

cc @mchowning @hypest

**Comment by etoledom** [comment]
Thank you all, and congrats @mchowning !
Great job 🎉

**Pull request merged**
