### PR TITLE
Implement list settings

### LINKED ISSUE #1304: Editing block on Mobile loses Ordered List Settings
In [gutenberg#15113](https://github.com/WordPress/gutenberg/pull/15113) the web side added settings for changing the start number in an ordered list and reversing the ordered list. Unfortunately, these changes broke mobile because they used components mobile had not implemented. That was fixed in [gutenberg#17070](https://github.com/WordPress/gutenberg/pull/17070), but we have not implemented those additional settings, so any changes on mobile will override (and lose) those settings from web. See [this comment](https://github.com/WordPress/gutenberg/pull/17070#pullrequestreview-276950939) for additional info.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1304 

Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-26 at 12 08 18

To test:
 - Start the demo app
 - Add a new list block
 - Select the ordered list type
 - Add some lines to the list
 - Tap on the settings icon for the list
 - Change the properties start and reversed and see if the block updates correctly.

Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@etoledom Thanks for the great review! Two great catches, I updated the code to address those issues, can you please give it another look?

**Comment by SergioEstevao** [comment]
@marecar3 I tested the lists in Android and I see one bug, if you choose a reversed list without specifying a start value, the values are going from top value to 0. For example if you have 5 items we see:
```
.4
.3
.2
.1
.0
```
While the correct should be: 
```
5.
4.
3.
2.
1.
```

**Comment by marecar3** [comment]
> @marecar3 I tested the lists in Android and I see one bug, if you choose a reversed list without specifying a start value, the values are going from top value to 0. For example if you have 5 items we see:
> 
> ```
> 4.
> 3.
> 2.
> 1.
> 0.
> ```
> 
> While the correct should be:
> 
> ```
> 5.
> 4.
> 3.
> 2.
> 1.
> ```

Hey @SergioEstevao, thanks for the feedback.
I have fixed the problem, please can you do another iteration of testing? Thanks.

**Comment by marecar3** [comment]
Hey @SergioEstevao, you can do another iteration of testing :) Thanks!

**Comment by SergioEstevao** [comment]
@marecar3 Working great now! Thanks for this! Do you need to merge anything in Aztec Android before I merge this?

**Pull request merged**
