### PR TITLE
Bring Code and More back for the prod build

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR "re-registers" Code and More for the prod build. 
Those blocks were disabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/406 

We can re-enable them back since https://github.com/WordPress/gutenberg/pull/13089 does handle `Enter.key` detection better, and does not introduce the UI lag of the previous approach.

To test:

- Start the mobile demo app
- Put the caret somewhere in the more block
- Tap enter on the soft keyboard, or on the hw keyboard
- It should add a new empty (para) block after the current

### CODE REVIEW

**Comment by Tug** [comment]
This looks good to me, not sure why we update gutenberg submodule here though?

**Comment by mzorz** [comment]
Oh I refrained from reviewing since https://github.com/WordPress/gutenberg/pull/13089 latest edit says "not ready for review" - but yes this one looks good as well

**Comment by daniloercoli** [comment]
> not sure why we update gutenberg submodule here though?

Hey @tug, the GB update is necessary since there are some problems on the `Code` and `More` blocks. The major problem in those blocks is about the `Enter.Key` detection, and we've decided to keep them disabled in production mostly because of it. 
Unfortunately the new GB update is not working fine on Android, and then I decided to add the "not ready for ready`, until I found a fix for it.

**Comment by daniloercoli** [comment]
Closing this PR since we've decided to wait a bit more on porting the blocks `Code` and `More`, since we'd like to share more code/use the same code of the web, and we're testing the new approach on lists block. 
This PR is also very simple to replicate.

**Pull request closed without merging**
