### PR TITLE
Tapping twice no longer removes focus.

### LINKED ISSUE #190: Problem with focus
I noticed that our focus action seems to be off, at least for paragraphs and headings.

It is my understanding that tapping again on a paragraph or heading should not unfocus it.

Here's an example of what I'm seeing (keep an eye on the bottom toolbar, which I believe is what we call the inserter?).

problemswithdoublefocus

I think we can safely switch [this line](
https://github.com/wordpress-mobile/gutenberg-mobile/blob/master/src/store/reducers/index.js#L91) to always set to `true`.  I tried that and it works fine (unless there's a scenario I'm missing).

### PR DESCRIPTION
**Pull request by diegoreymendez**
### Description:

Fixes #190 

Tapping twice on the same block no longer removes focus from it.

### Testing:

Just tap multiple times in the same text block and make sure the bottom toolbar is never removed.

### CODE REVIEW

**Comment by diegoreymendez** [comment]
> The travis error seems to be just a lint issue

Yes.  I'll change the code to fix this.

> There is not current way to deselect all blocks other than switching to html view and back. But I didn't find a way to deselect all from the mobile web version either. 🤔

My opinion is that it may not be a requirement at all to be able to "unfocus" all blocks.

If you think of Aztec and most mobile editors there's no way to remove the caret / focus / responder status from them.

**Comment by iamthomasbishop** [comment]
> My opinion is that it may not be a requirement at all to be able to "unfocus" all blocks.

Tapping outside of a focused block should in theory unfocus all blocks. For example: if you're focused on a block, you have to tap once outside the block to unfocus it. That means at this time, no blocks are focused. You then can tap on another block to focus that one. 

The nature of the block editor means a slight shift in approach vs. a typical single-stream editor, but if this adds too much friction in practice, I'm all for adjusting.

**Comment by etoledom** [comment]
The problem I see with the `tapping outside to unfocus` approach, is that on mobile, unless you are at the very top or very bottom of the post, any space outside the current focused block, will be another block, and taping on it will focus that other block instead.

They use all the width of the screen and they are vertically pasted each other.

As a user, I'd like to give a fast preview of what I'm writing without the tool bars. 
But again, not important at all for Alpha, and we will have a better insight later on. 👍

**Comment by diegoreymendez** [comment]
> Tapping outside of a focused block should in theory unfocus all blocks

That doesn't match [this requirement](https://github.com/wordpress-mobile/gutenberg-mobile/issues/166), though.

Are you sure we want to have to tap twice to move the focus from block to block?

**Comment by iamthomasbishop** [comment]
> Are you sure we want to have to tap twice to move the focus from block to block?

There are a lot of things at play with this interaction that are hard to articulate, but I'm not 100% tied to this if it adds too much friction – especially in terms of getting us to the initial version of Mobile GB. The most important thing to me is that we ensure that switching across blocks isn't jarring, whether via single or multiple taps.

I agree with @etoledom that an intermediate writing state where we remove all focus is desired. But as @koke pointed out, this could very well be achieved by adding the `dismiss keyboard` button on the toolbar (the original designs didn't have that, so it's now a consideration and maybe much less of a concern).

**Pull request merged**
