### PR TITLE
Initial HTML E2E test

### LINKED ISSUE #26146: Add a React Native E2E test to render the initial html content
**Is your feature request related to a problem? Please describe.**
Lately, we've been having some broken features due to changes that affect mobile code but the current mobile E2E that's running now `Gallery` doesn't cover any of those.

**Describe the solution you'd like**
We should replace the `Gallery` test with a new test that basically just renders the `initial-html.js` content. This way we keep only having just one test but covering the rendering of the blocks in mobile.

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes https://github.com/WordPress/gutenberg/issues/26146

Gutenberg PR https://github.com/WordPress/gutenberg/pull/26405

To test:
Utilize this PR https://github.com/WordPress/gutenberg/pull/26405

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by cameronvoell** [comment]
Hi @jd-alexander , we'll be cutting the 1.40 release branch at the beginning of this week. Please try to get this merged Monday or bump the milestone. Thanks much 🙇

**Comment by ceyhun** [comment]
Bumping the milestone to 1.42, feel free to ping me if it needs to make it to 1.41 this week.

**Comment by cameronvoell** [comment]
Bumping the milestone to 1.43, feel free to ping me if it needs to make it to 1.42 this week.

**Comment by jd-alexander** [comment]
Bumping the milestone to 1.44.

**Comment by hypest** [comment]
Judging from the longish sequence of milestone bumps, I'll go ahead and remove the milestone.

**Review by ceyhun — APPROVED** [review]

**Pull request merged**
