### PR TITLE
Fix crash when deleting a block

### LINKED ISSUE #2886: Crash when deleting block from page template
**Describe the bug**
When I create a page using a template and then delete a block, the app crashes - and not very gracefully. 

**To Reproduce**
1. In the app, create a new page using a template for a site with Jetpack installed. - I can only repro this on JP sites so far 
2. In the editor, delete a pre-set block
Crash
https://cloudup.com/ctvbVn5iqHn

**Expected behavior**
Block deletes with no crash

**Screenshots**
https://cloudup.com/cN4cvHBFV0e

**Smartphone (please complete the following information):**
iPhone 12 Pro, iOS 14.2.1, WP 16.3 beta

**Additional context**

### PR DESCRIPTION
**Pull request by geriux**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/2886

`Gutenberg PR` -> https://github.com/WordPress/gutenberg/pull/27683

To test check the `Gutenberg` PR description.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by antonis — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/27683#pullrequestreview-550309710

**Comment by guarani** [comment]
👋 Hi @geriux, I came across this PR while checking to make sure 1.42.2 release code was brought back into development branches. 

It looks like this is held up by the Check Correctness step which also gave us issues during the release and was solved by invalidating the CircleCI cache (probably not the correct solution). I've just tried re-starting the failing job now, but could you please ping me once this is merged, just to check off this item from the 1.42.2 release checklist?

**Comment by geriux** [comment]
Hey @guarani sorry I didn't merge this when I merged the `Gutenberg` PR. Since other PRs have already updated the commit reference I'll close this one.

**Comment by guarani** [comment]
Ok thanks @geriux!

**Pull request closed without merging**
