### PR TITLE
Update PR Template For Accessibility

### PR DESCRIPTION
**Pull request by jd-alexander**
#### Proposal 

I am proposing that we incorporate accessibility checks within our pull request review process by amending the pull request template as seen in this PR. Enforcement of these accessibility processes and principles will further our commitment to creating products that are accessible end to end.

#### Pull Request Process Changes

The process that would support this change is:

* The reviewer of the PR would verify that the feature was made accessible using the accessibility guidelines and testing tools. 
* If making a component accessible is difficult or not enough time is left in a sprint to allow it, then an issue should be created so that it can be tracked and included in future Accessibility projects. 

#### Benefits
These are the benefits of this approach: 

* It’s likely that the person who is developing a feature has the most context about it, and will be able to think more deeply about how it should be accessible than someone who might try to make it accessible at a later date.
* Decreased accessibility-related tickets as users who utilize accessibility services will be better served.
* It lessens the work that gets done in Accessibility projects, thus allowing more focus to be placed on areas or features that require more effort and attention.

### CODE REVIEW

**Comment by jd-alexander** [comment]
@hypest I fixed the build issue on this PR. You can check it out when you get a chance 😉

**Comment by hypest** [comment]
Thanks for this PR @jd-alexander! Adding a nudge in the PR template is probably a good start for raising awareness among the devs.

> I have considered adding accessibility improvements for my changes

I'm not sure how actionable the prompt is. What do you think about adding a section in the README.md that will harbor details about what such improvements could look , the guidelines and the tools, and then link to that section in the PR template?

**Comment by jd-alexander** [comment]
> I'm not sure how actionable the prompt is. What do you think about adding a section in the README.md that will harbor details about what such improvements could look , the guidelines and the tools, and then link to that section in the PR template?

That sounds like a great idea @hypest 😄 
I am not totally familiar with how accessibility is handled within Gutenberg so I would spend some time investigating that. There are links to the guidelines for Android & iOS readily available so those could be leveraged especially for testing.

**Comment by hypest** [comment]
> There are links to the guidelines for Android & iOS readily available so those could be leveraged especially for testing.

Can we add those links directly in the prompt so people can jump to them quickly?

**Comment by jd-alexander** [comment]
> Can we add those links directly in the prompt so people can jump to them quickly?

Yes, that can be done. I will add them. Thanks 🙏

**Comment by hypest** [comment]
👋 @jd-alexander , thanks for the links! Noticed though that those are referring to the native side mainly. I understand that many of the principals mentioned there hold for any platform (including RN) feels to me that they still aren't actionable on the RN/JS realm. I mean, for a PR template checklist here, I'd expect guidelines that refer to RN specific ways of adding a11y. I fear that otherwise, PR authors in this repo will too-quickly just check-off the items as "not-applicable" and effectively ignore them.

What do you think about _not adding_ such prompts until we find some React Native and Gutenberg specific guidelines? Alternatively, can we expand the ones in WPAndroid and WPiOS to include RN specific guidelines?

By the way, the Gutenberg repo (in which almost all gutenberg-mobile works have a corresponding PR) already has a prompot for a11y (See `- [ ] My code follows the accessibility standards. <!-- Guidelines: https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/ -->` in https://raw.githubusercontent.com/WordPress/gutenberg/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by jd-alexander** [comment]
> 👋 @jd-alexander , thanks for the links! Noticed though that those are referring to the native side mainly. I understand that many of the principals mentioned there hold for any platform (including RN) feels to me that they still aren't actionable on the RN/JS realm. I mean, for a PR template checklist here, I'd expect guidelines that refer to RN specific ways of adding a11y. I fear that otherwise, PR authors in this repo will too-quickly just check-off the items as "not-applicable" and effectively ignore them. 
What do you think about not adding such prompts until we find some React Native and Gutenberg specific guidelines? Alternatively, can we expand the ones in WPAndroid and WPiOS to include RN specific guidelines?

This is a sensible next step for sure! 

I will check out the Gutenberg prompt and also check to see what React Native guidelines are out there that can give inspiration. Thanks for the insights @hypest

**Comment by marecar3** [comment]
We're freezing `1.24.0 `today. If you think it is ready and if you'd like to ship it with `1.24.0`please merge it into develop branch. Otherwise, we can bump it to `1.25.0.` @jd-alexander

**Comment by jd-alexander** [comment]
@marecar3 bump to 1.25.0. Thanks!

**Comment by marecar3** [comment]
> @marecar3 bump to 1.25.0. Thanks!

Thanks @jd-alexander, bumped to `1.25.0`

**Comment by jd-alexander** [comment]
@hypest I haven't completed this as yet because I have been busy working on team projects. Is it okay that it is still open? Let me know. Thanks.

**Comment by hypest** [comment]
Thanks for the update @jd-alexander !

What do you think about closing the PR as "paused" at this stage and reopening when anyone or you can pick it again? Suggesting closing only to move it to the side for a bit.

**Comment by jd-alexander** [comment]
Yes, closing as paused. If I can I will pick up once I am done with my current project!

**Pull request closed without merging**
