### PR TITLE
Release 1.56.0

### PR DESCRIPTION
**Pull request by geriux**
Release for Gutenberg Mobile 1.56.0

## Related PRs

- Gutenberg: https://github.com/wordpress-mobile/gutenberg-mobile/pull/3664
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14936
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16752

- Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/
- Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

* [Tablet view fixes for inserter button](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3602). 
* [Fixed an issue where pressing enter inside a text-based block was not creating a new block when using Gboard](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3590).
* [Tweaks to the badge component's styling, including change of background color and reduced padding](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3642).
* [New block: Layout grid](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3513).
* [Upgrade to RN 0.64.0](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3430)

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [ ] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release.
- [ ] Bundle package of the release is updated.

### CODE REVIEW

**Comment by SiobhyB** [comment]
LGTM! :)

**Review by SiobhyB — APPROVED** [review]

**Comment by geriux** [comment]
### 🟢  Writing Flow checklist (iOS)

**Build**: 17.7.0.1
**Device**: iPhone 12 Pro OS 14.6

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by geriux** [comment]
### 🟢  Unsupported Block Tests (iOS)

**Build**: 17.7.0.1
**Device**: iPhone 12 Pro OS 14.6

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [ ] ~TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites~(skipped https://github.com/wordpress-mobile/gutenberg-mobile/issues/3544)
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by geriux** [comment]
### 🟢 New features/changes (iOS)

**Build**: 17.7.0.1
**Device**: iPhone 12 Pro OS 14.6

- [x] Tablet view fixes for inserter button.
- [x] ~Fixed an issue where pressing enter inside a text-based block was not creating a new block when using Gboard.~ _(Only for Android)_
- [x] ~Tweaks to the badge component's styling, including change of background color and reduced padding.~ _(Only for Android)_
- [x] New block: Layout grid.

**Comment by SiobhyB** [comment]
### 🟢 Writing Flow checklist (Android)

**Build**: 17.7.0.1
**Device**: Pixel 5, Android 11

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
  - [x] Quote block
  - [x] Verse block
  - [x] Preformatted block
  - [x] Pullquote block
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by SiobhyB** [comment]
### 🟢  Unsupported Block Tests (Android)

**Build**: 17.7.0.1
**Device**: Pixel 5, Android 11
- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by SiobhyB** [comment]
### ⚪ New features/changes (Android)

**Build**: 17.7.0.1
**Device**: Pixel 5, Android 11

- [x] Tablet view fixes for inserter button.
- [x] Fixed an issue where pressing enter inside a text-based block was not creating a new block when using Gboard.
- [x] Tweaks to the badge component's styling, including change of background color and reduced padding.
- [x] New block: Layout grid.

**Comment by antonis** [comment]
## 🟢   iOS: Sanity Testing (Test Suite 2, Story Block 1)

**Build**: 17.7.0.1 from Testflight
**Device**: iPhone SE 2020 / iOS 14.4.1

### DarkMode - 1

- [x] Gallery block - Dark mode - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

### Group - 1

- [x] Group - AppenderButton is rendered - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Deep nesting is possible (iOS only) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [x] Group - Check if Group placeholder is visible for the unselected state - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] Group - Nested block have proper margins values - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)

### Spacer - 1

- [x] Spacer block - Spacer is rendered without crash - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

### Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)

### Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

### Buttons-3

- [x] Buttons block - Wrapping Buttons - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

### Button-6

- [x] Buttons block - Settings: Open in new tab - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [x] Buttons block - Settings: Synchronize with button options - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

### Color Settings - 1
- [x] Colors Segmented Controls - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] Scroll color palette to start - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

### Image - 1
- [x] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc001)
- [x] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc002)
- [x] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc003)
- [x] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc004)
- [x] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc005)

### Story block - 1
- [x] Story block - Verify is available in Block Picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc001)
- [x] Story block - Verify is not available in Block Picker- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc002)
- [x] Story block - Add media to empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc003)
- [x] Story block - Add media to non-empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc004)
- [x] Story block - Close/Re-open post with an ongoing Story upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc005)

**Comment by mkevins** [comment]
## Android Sanity Tests - Test Suite 1
Build: [17.7-rc-1](https://github.com/wordpress-mobile/WordPress-Android/releases/download/17.7-rc-1/wordpress-17.7-rc-1.apk)
Device: Pixel 3a (physical device)

:question: I observed some issues while uploading videos (noted below in the Media & Text block tests)
Also, this isn't a _new_ issue, but for posterity, I also reproduced the stale preview issue described here: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2207#issuecomment-828414392

### Gallery - 1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC04](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Adding Column with AppenderButton - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


### Columns - 2
- [x] Columns - Max limit of Column number - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Column - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [ ] Columns - Deep nesting is possible (iOS only)- [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is stretched to content in nested structure- [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### MediaText - 1

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

:question: Note: Videos thumbnails are not displaying in the device picker.

<details>
<summary>Screenshot</summary>


</details>

Also, although not part of these tests, for a successful upload, the video URL seems to be incorrect, and the video does not play on the front-end.


<details>
<summary>Steps</summary>

* Add a MediaText block
* Add media with "choose from device"
* Select a video and confirm uploads
* Wait for upload to complete, and save post
* View post in either preview, or as a published post
  * Observe that the video does not play

</details>

- [x] Media Text block - Insert video from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload - 1

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

### Cover - 1

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

### Editor Theme - 1

- [x] Default Colors - Check that default colors still load - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [x] Default Gradients - Check that default gradients still load - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)

### Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by geriux** [comment]
Hey @mkevins 👋 thanks for testing!

> Also, although not part of these tests, for a successful upload, the video URL seems to be incorrect, and the video does not play on the front-end.

By the URL being incorrect what do you mean? Was it a local URL? I wonder if the video got stuck processing 🤔. Also what kind of site were you using?

**Comment by mkevins** [comment]
> By the URL being incorrect what do you mean? Was it a local URL?

Ah, I should have clarified. It was not a local (`file://`) URL, but instead a URL which ended with "-mp4/", which did not load. Also, when right clicking the video and "copy video address" in the browser, it copied the same URL, but did not load when visited in a new tab.

>  I wonder if the video got stuck processing . Also what kind of site were you using?

I'm not sure, but I know it fully updated, since I can find the videos in my media library. This was on a .com site with a business plan. In the media library, I can see that the video URL is actually supposed to end with ".mp4" not "-mp4/", so maybe that's a clue. Also, the metadata listed there looks wrong though :thinking: . Fields for "FILE NAME" and "FILE TYPE" are blank, and "FILE SIZE" is "0.00 B".. so perhaps that is also a clue.

**Comment by geriux** [comment]
> > By the URL being incorrect what do you mean? Was it a local URL?
> 
> Ah, I should have clarified. It was not a local (`file://`) URL, but instead a URL which ended with "-mp4/", which did not load. Also, when right clicking the video and "copy video address" in the browser, it copied the same URL, but did not load when visited in a new tab.
> 
> > I wonder if the video got stuck processing . Also what kind of site were you using?
> 
> I'm not sure, but I know it fully updated, since I can find the videos in my media library. This was on a .com site with a business plan. In the media library, I can see that the video URL is actually supposed to end with ".mp4" not "-mp4/", so maybe that's a clue. Also, the metadata listed there looks wrong though 🤔 . Fields for "FILE NAME" and "FILE TYPE" are blank, and "FILE SIZE" is "0.00 B".. so perhaps that is also a clue.

Thanks for the information, I tried to upload a video using the Media&Text block in both free and premium site and it worked correctly, so I wonder if it was something specific for that video file?

**Comment by fluiddot** [comment]
I've just added the `Upgrade to RN 0.64.0` PR to the changes section in the PR description, as it's a major change.

**Comment by mkevins** [comment]
> it worked correctly

@geriux :wave: :smiley:  Out of curiousity, when you look at the final markup for the video after it uploaded successfully, does it end with ".mp4", or "-mp4/" in your case? Or something else? Btw, I encountered this issue on a Business site.

> I wonder if it was something specific for that video file?

I'm not sure, but I don't think so? I used a 10 second clip from Big Buck Bunny, and the video is actually available in the media library afterwards, so I know it uploaded. :thinking:

**Comment by geriux** [comment]
> Out of curiousity, when you look at the final markup for the video after it uploaded successfully, does it end with ".mp4", or "-mp4/" in your case? Or something else? Btw, I encountered this issue on a Business site.

For me, it ends with `.mp4` and it's a business site.

> I'm not sure, but I don't think so? I used a 10 second clip from Big Buck Bunny, and the video is actually available in the media library afterwards, so I know it uploaded. 🤔

Interesting, when I tested I used the camera to record a 4 seconds video.

**Pull request merged**
