### PR TITLE
Release v1.28.0

### PR DESCRIPTION
**Pull request by mchowning**
Release for Gutenberg Mobile v1.28.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/22350
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/11894
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/14099

- Aztec-iOS: N/A
- Aztec-Android: N/A

## Extra PRs that Landed After the Release Was Cut

 - Update [to page templates](https://github.com/WordPress/gutenberg/pull/22321/files).
 - Correct [margins on post-title](https://github.com/WordPress/gutenberg/pull/22331).
 - Fix [Buttons Appender on Android](https://github.com/WordPress/gutenberg/pull/22362) 

## Changes

1. New block: Pullquote (https://github.com/WordPress/gutenberg/pull/21930)
2. Add support for changing background and text color in Buttons block (https://github.com/wordpress-mobile/gutenberg-mobile/pull/2096)
3. Fix the icons and buttons in Gallery, Paragraph, List and MediaText block on RTL mode (https://github.com/WordPress/gutenberg/pull/21502)
4. Remove Subscription Button from the Blog template since it didn't have an initial functionality and it is hard to configure for users. (https://github.com/WordPress/gutenberg/pull/22129)4
5. [iOS] Add support for the subscript `<sub>` and superscript `<sup>`HTML elements in text blocks (https://github.com/wordpress-mobile/gutenberg-mobile/pull/2226)
6. Update page templates to use recently added blocks (https://github.com/wordpress-mobile/gutenberg-mobile/pull/2179)

## Test plan

- Use the main WP apps to test the changes above. 
- Check WPAndroid and WPiOS PRs if there are specific tests to run.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [X] Release number was bumped
- [X] Aztec dependencies are pointing to a stable release
  - iOS: 'grep WordPressAztec-iOS RNTAztecView.podspec'
  - Android: 'grep aztecVersion react-native-aztec/android/build.gradle'
- [x] Gutenberg 'Podfile' and 'Podfile.lock' inside './ios/' are updated to the release number
- [x] Bundle package of the release is updated 
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release

### CODE REVIEW

**Comment by lukewalczak** [comment]
### Sanity Testing (IOS)

**Shortcode-1**

- [X] - Shortcode block - Add a youtube link ✅ 

**Cover-2**

- [ ] - Cover - Add Video Background from WordPress Media library
- [ ] - Cover - Replace media
- [ ] - Cover - Gradient background is rendered properly
- [ ] - Cover - Gradient overlay is rendered properly

**Columns - 2**

- [ ] - Columns - Check if Column placeholders is visible for the unselected state
- [ ] - Columns - Appearance in vertical device position (vertical layout)
- [ ] - Columns - Appearance in horizontal device position (horizontal layout)
- [ ] - Columns - Mover direction
- [ ] - Columns - Check if Column placeholder is render in nested structure
- [ ] - Columns - Unselected Column placeholder is streched to content in nested structure

**Columns - 3**

- [ ] - Columns - Check if in DarkMode all components gets proper colors

**MultipleUpload-1**

- [ ] - Simultaneous uploads

**MediaText-1**

- [ ] - Media Text block - Insert image from device (failing)
- [ ] - Media Text block - Close/Re-open post with an ongoing image upload

**MediaText-2**

- [ ] - Media Text block - Insert video from device (cancel)
- [ ] - Media Text block - Insert image from device (cancel)

**MediaText-3**

- [ ] - Media Text block - Insert video from device (failing)
- [ ] - Media Text block - Close/Re-open post with an ongoing video upload

**MediaText-4**

- [ ] - Media Text block - Media & Text alignment
- [ ] - Media Text block - Vertical alignment

**Comment by jbinda** [comment]
I have provided smoke tests on Android emulator because of CI issue during prepare production build. Below are the results:

LEGEND:
✖️ - not proceeded because it need production build to test
❓ - not proceeded because previous step disallow to test it
❌ - failed


#### Cover-1
❌ - Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)

❓ - Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)

❓- Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)

✖️- Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)

 ✖️- Cover - Custom color is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)


I had an issue with add image to Cover block on Android. I see the option to choose the Media source but nothing happens after press on any option ( `Wordpress Media Library` as well as the others) .

It works fine on iOS.

#### Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)

#### Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

#### Buttons-3

- [x] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

#### Buttons-4

✖️-  Buttons block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)

✖️-  Buttons block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)

✖️-  Buttons block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)

✖️-  Buttons block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)

✖️-  Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

**Comment by geriux** [comment]
### Sanity tests (iOS)

Gallery-1

- [ ] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [ ] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [ ] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [ ] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-3

- [ ] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [ ] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [ ] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

Gallery-4

- [ ] Gallery block - Settings: Link to - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc012)
- [ ] Gallery block - Settings: Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc013)
- [ ] Gallery block - Settings: Crop images - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc014)

Columns - 1

- [ ] Columns - Columns block is added with default number of Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc001)
- [ ] Columns - Adding Column with AppenderButton- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [ ] Columns - Adding and removing Column with BottomSheet Stepper control - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)
- [ ] Columns - Max limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [ ] Columns - Min limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [ ] Columns - Removing Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [ ] Columns - Removing the only one left Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [ ] Columns - Changing alignment on Columns - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [ ] Columns - Changing alignment on individual Columnn - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [ ] Columns - Alignment attribute is properly passed when adding Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [ ] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

**Comment by pinarol** [comment]
> I had an issue with add image to Cover block on Android. I see the option to choose the Media source but nothing happens after press on any option ( Wordpress Media Library as well as the others) .

@jbinda are you trying this with the Android demo app? If so, that functionality won't work there.

**Comment by jbinda** [comment]
> @jbinda are you trying this with the Android demo app? If so, that functionality won't work there.

yes with the demo app

**Comment by pinarol** [comment]
Tested on WPAndroid using the apk in [this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/11893). They all seem fine.

#### Cover-1
- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)

- [x] Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)

- [x] Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)

- [x] Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)

- [x] Cover - Custom color is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

#### Buttons-4

- [x] Buttons block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc017)

- [x] Buttons block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc016)

- [x] Buttons block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc018)

- [x] Buttons block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc020)

- [x] Buttons block - The newly created Buttons has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc021)

**Comment by chipsnyder** [comment]
Tested on WPAndroid with [this APK](https://50728-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11894-build-50728.apk) 

### DarkMode-1

- [ ] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [ ] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [ ] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

### DarkMode-2

- [ ] Spacer block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc004)
- [ ] Buttons block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc005)
- [ ] Group - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)
- [ ] Columns - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc007)

### Group-1

- [ ] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [ ] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002)
- [ ] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [ ] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [ ] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [ ] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [ ] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)
- [ ] Group - Navigation up button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc009)
- [ ] Group - Navigation down works according to parent-first approach - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc010)
- [ ] Group - Cross navigation between blocks works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc011)
- [ ] Group - Ungroup button works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc012)
- [ ] Group - Check if in DarkMode all components gets proper colors - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc013)
- [ ] Group - Check if nested Placeholder block can be replaced - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc014)

### Spacer-1

- [ ] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [ ] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [ ] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)
- [ ] Spacer block - Settings: Available height range is correct - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc004)
- [ ] Spacer block - Settings: Height range extends if Spacer comes from the web is higher than 500px - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc005)
- [ ] Spacer block - Spacer in horizontal layout works as expected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc006)

**Comment by chipsnyder** [comment]
Most of the tests look good I ran into an issue with switching between dark mode:
This is on WPAndroid with [this APK](https://50728-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-11894-build-50728.apk) running on a Pixel 3a  Android 10

1) Open the editor in either mode.
2) Navigate to settings and switch to the other mode
3) Select the block inserter

- Notice the block inserter is still in the other mode

| Light mode | Dark mode |
| --- | --- |
| <kdb></kdb>|<kdb></kdb> |

Leaving the editor and coming back in will correct the display.

**Comment by mchowning** [comment]
> I ran into an issue with switching between dark mode

Thanks for catching this @chipsnyder . :bow: Do you think this is the same as #2108 or is it a slightly different issue? Either way, I don't think this should be a blocker since it is fixed once you leave and return to the editor. Let me know if you disagree.

**Comment by chipsnyder** [comment]
> Do you think this is the same as #2108 

Yup, that sounds like the same thing. I missed that one initially. 

> Either way, I don't think this should be a blocker since it is fixed once you leave and return to the editor

I agree this seems minor and defiantly not a blocker in my mind.

**Comment by guarani** [comment]
Text alignment seems broken on the Pull Quote block on both iOS and Android (cc @ceyhun).
I noticed this on `develop` (both platforms), and came here and also tested the Android demo build for this release.

<kbd>

</kbd>

**Comment by SergioEstevao** [comment]
>Text alignment seems broken on the Pull Quote block on both iOS and Android (cc @ceyhun).
I noticed this on develop (both platforms), and came here and also tested the Android demo build for this release.

@guarani if you check the behaviour of the pullquote on the web you will see that the alignment is not for the text itself but for the position of the full pullquote when presented. 

While we can improve the way we show the block on the editor I don't think it's a blocker.

@ceyhun what do you think?

**Comment by SergioEstevao** [comment]
Tested on iOS the **Writing Flow**:

[x] TC1 - Block insertion flow

**Comment by ceyhun** [comment]
> @ceyhun what do you think?

@SergioEstevao I agree it's not a blocker. 
But I realised another thing. On the web there are more options for the alignment of `Pullquote`. 

alignment
"Wide width" and "Full width" are not present on mobile. 

If you create a  `Pullquote` from web with these alignments, it is rendered without errors on mobile for, so I think it's OK for the release. 

The same options are missing from `Column`, `Media&Text`, `Gallery`, `Group` blocks as well.

**Comment by mchowning** [comment]
Tested the **Writing Flow** on Android:

- [ ] TC001 - Block insertion flow 
- [ ] TC001 - Paste formatted text copied from website
- [ ] TC001 - Multiline components
- [ ] Rich Text Format
  - [ ] TC001 - Bold, Italic, strikethrough buttons
  - [ ] TC002 - Alignment buttons
  - [ ] TC003 - Alignment Split
  - [ ] TC004 - Link button works without selection
  - [ ] TC005 - Link button works with a selected word
  - [ ] TC006 - Adding a link from a copied URL
  - [ ] TC007 - Test format detection under the cursor
  - [ ] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [ ] Splitting and merging
  - [ ] TC001 - Merge after writing
  - [ ] TC002 - Merge after selection
  - [ ] TC003 - Merge after deleting text
  - [ ] TC004 - Merge after deleting all
  - [ ] TC005 - Merge multiple blocks
  - [ ] TC006 - Splitting/merge list block
- [ ] Undo / Redo - Test Cases
  - [ ] TC001 - Undo/redo block actions
  - [ ] TC002 - Undo/redo text
  - [ ] TC003 - Undo/redo text format

**Comment by SergioEstevao** [comment]
>  observed splitting a heading block would lose the text after the split, adding an empty paragraph block instead of a heading block with the post-split text. This did not happen consistently for me, but it seemed to happen pretty consistently if I

I tried to reproduce this on my test Android device and I couldn't, I even tried with different keyboards to see if it made any difference.

**Comment by mchowning** [comment]
> I tried to reproduce this on my test Android device and I couldn't, I even tried with different keyboards to see if it made any difference.

Your comment helped me realize that I can only see the issue if I enter text by swiping. If I type the letters I don't see the issue.

**Comment by mchowning** [comment]
There's no need to regenerate the bundle because the just-merged jitpack changes just deal with the Android build process and do not affect the creation of the js bundle.

**Pull request merged**
