### PR TITLE
Issue/1966 Disable whitespace collapse in Aztec

### LINKED ISSUE #1966: Bolding text using the toolbar causes whitespace to be lost
### Description
When bolding text using the toolbar button on iOS or Android, any whitespace present at the beginning of the line is removed causing the the text to jump to the left and the whitespace to be lost. This affects the pre-formatted block, the verse block, and, to a lesser extent, the paragraph block. **This issue is not present on Gutenberg web.**

On iOS, bolding through the native iOS edit menu (the toolbar menu that displays selection options) is not affected by this bug.

The same bug is present for italics or strikethrough.

### Steps to Reproduce

There are two distinct scenarios where this bug is present.

#### Scenario 1: Styling non-selected text

In a paragraph block, type some spaces, then tap the toolbar bold button and observe that the cursor jumps back to the start of the line. The cursor should stay put when the bold button is tapped.

#### Scenario 2: Styling selected text

1. In a paragraph (or verse or pre-formatted) block, type some spaces and then text, such as:
```
    Hello
```
2. Bold the Hello portion of the line using the toolbar bold **B** button (on iOS, don't use the native iOS edit menu)
3. Observe the text has shifted to the left and the whitespace has disappeared 
4. The same occurs for the toolbar italics and strikethrough options

iOS | Android
-|-
 | 

### Expected Behavior
Applying bold/italics/strikethrough to text should not affect leading whitespace or reposition the text in any way.

## Devices
| | iOS | Android
--|--|--
**Device** | iPhone 7 | Google Pixel Emulator
**OS** | iOS | Android 10
**OS Version** | 13.3.1 | API 29 Version Q 

## Additional Context

This bug is present in the Gutenberg editor in the WordPress for iOS app **and** in the Gutenberg example iOS and Android projects in this repo. It is **not** present on the Aztec for iOS example app or the WordPress for iOS Classic editor.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1966 

Related PRs:
 - Aztec iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1277
 - Aztec Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull/905
 - GB: https://github.com/WordPress/gutenberg/pull/21469

This PR fixes a bug where white space inserted at the start of text blocks ( Paragraph, Heading, Lists) were removed when applying a formatting option ( Bold, Italic, Strike).

The underlying issue was a sync issue between the content representation in the JS side and the Aztec content. 

Aztec by default removes extra spaces (like most browsers do), but GB internal format doesn't do that, so when spaces were sent to Aztec they were removed and then when we apply formats Aztec will send the content back with all the extra space removed.

This PR links a new version of Aztec that allows disabling the removal/collapse of extra spaces. 

To test:
 - Start the demo app
 - Add a text block, paragraph for example
 - Type some spaces, then write some text
 - Select the text and apply one format, for example, bold
 - Check that the white space aren't removed.
 - Repeat the test but without adding any text, just spaces, and then apply bold, to see if spaces are kept
 - Try to merge two paragraphs that have extra space at the start of the paragraph and on the end.
 - Check on the other blocks like Heading and Lists.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@marecar3 and @hypest we will need someone from Aztec android to implement a similar option for disabling of the collapse of white spaces on Android.

**Comment by guarani** [comment]
Tests using Gutenberg example project on iOS 7:

**Copy Paste - Test Cases**
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/copy-paste.md#tc001): Past formatted text copied from website

**Multiline components - Test Cases**
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/multiline-components.md#tc001): New line on multiline components
 
**Rich Text Formatting - Test Cases**
- [x] [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc001): Bold, Italic, strikethrough buttons
- [x] [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc002): Alignment buttons
- [x] [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc003): Alignment split
- [x] [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc004): Link button works without selection
- [x] [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc005): Link button works with a  selected word
- [x] [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc006): Adding a link from a copied URL
- [x] [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/rich-text-formatting.md#tc007): Test format detection under the cursor

**Splitting and merging - Test Cases**
- [x][TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001): Merge after writing
- [x][TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc002): Merge after selection
- [x][TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc003): Merge after deleting text
- [x][TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc004): Merging multiple blocks
- [x][TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc005): Splitting/merge list block

@SergioEstevao, I noticed a tiny, but expected, difference in behavior here when splitting blocks: Previously, splitting blocks would strip any leading/trailing whitespace from the content that will populate the new block, but now, whitespace is preserved.

**Comment by pinarol** [comment]
I am changing the milestone of this PR as 1.27 because the 1.26 release branch will be cut quite soon. Let me know if you instead wanted to include this to 1.26.

**Comment by guarani** [comment]
> It would be great to add this corner case to the manual tests!

@etoledom I'm not sure if this would be appropriate as a general observation in [the splitting/merging test cases](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) – let me know what you think. Otherwise, we could just leave it out since this new behavior feels quite normal.

**Comment by etoledom** [comment]
> > It would be great to add this corner case to the manual tests!
> 
> @etoledom I'm not sure if this would be appropriate as a general observation in [the splitting/merging test cases](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc001) – let me know what you think. Otherwise, we could just leave it out since this new behavior feels quite normal.

Oh! I meant to add the main issue that this PR solves: "Adding format with many empty spaces at the beginning":

```
- Add a text block, paragraph for example
- Type some spaces, then write some text
- Select the text and apply one format, for example, bold
- Check that the white space aren't removed.```

**Comment by guarani** [comment]
> Oh! I meant to add the main issue that this PR solves: "Adding format with many empty spaces at the beginning":

Gotcha! Sorry for the misunderstanding. I'll add that test case now.

@SergioEstevao, do you think I should run through more manual test cases on this? Otherwise I'd be happy to mark approved 💯.

**Comment by SergioEstevao** [comment]
@guarani at the moment we are just waiting for @marecar3 to have some time to solve this in Android too.

**Comment by marecar3** [comment]
> @guarani at the moment we are just waiting for @marecar3 to have some time to solve this in Android too.

Hey @guarani @SergioEstevao 
I have fixed the Android side, so @guarani you are able to test on both platforms. Thanks and sorry for the delay.

**Comment by guarani** [comment]
Thanks very much @marecar3! I'll give it a test.

**Comment by SergioEstevao** [comment]
@marecar3 thanks for your work on this! If CI goes green I'm going to merge it!

**Pull request merged**
