### PR TITLE
[TEST] Test build for 1.66.0 alpha

### PR DESCRIPTION
**Pull request by fluiddot**
This PR is to test the current changes in `develop` for the `1.66.0` release.

To test use the following PRs:
- **WordPress-iOS:** https://github.com/wordpress-mobile/WordPress-iOS/pull/17439#issuecomment-963967867
- **WordPress-Android:** https://github.com/wordpress-mobile/WordPress-Android/pull/15545#issuecomment-963982691

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
## 🟢  Writing Flow checklist (iOS)
**Build**: [59928](https://github.com/wordpress-mobile/WordPress-iOS/pull/17439#issuecomment-963967867)
**Device**: iPhone 11 (15.1)

#### General
- [x] TC001 - Block insertion flow
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

**Comment by fluiddot** [comment]
## 🟢 Unsupported Block Tests (iOS)
**Build**: [59928](https://github.com/wordpress-mobile/WordPress-iOS/pull/17439#issuecomment-963967867)
**Device**: iPhone 11 (15.1)

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by jhnstn** [comment]
### 🟢Writing Flow checklist (Android)

Build: [15545](https://github.com/wordpress-mobile/WordPress-Android/pull/15545#issuecomment-963982691)
Device: Pixel 5 (Android 12)

#### General
- [x] TC001 - Paste formatted text copied from website *
- [x] TC001 - Multiline components
#### Rich Text Format
- [x] TC001 - Bold, Italic, strikethrough buttons
- [x] TC002 - Alignment buttons
- [x] TC003 - Alignment Split
- [x] TC004 - Link button works without selection
- [x] TC005 - Link button works with a selected word
- [x] TC006 - Adding a link from a copied URL * *
- [x] TC007 - Test format detection under the cursor
- [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
- [x] TC001 - Merge after writing
- [x] TC002 - Merge after selection
- [x] TC003 - Merge after deleting text
- [x] TC004 - Merge after deleting all
- [x] TC005 - Merge multiple blocks
- [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
- [x] TC001 - Undo/redo block actions
- [x] TC002 - Undo/redo text
- [x] TC003 - Undo/redo text format

* On General-TC001 pasting from the Gboard clipboard did not paste the individual blocks.
* * On Rich Text Format-TC006 copying from the ellipsis > "Copy Link" does not auto populate the link input.

**Comment by jhnstn** [comment]
### 🟢  Unsupported Block Tests (Android)

Build: [15545](https://github.com/wordpress-mobile/WordPress-Android/pull/15545#issuecomment-963982691)
Device: Pixel 5 (Android 12)
### Unsupported Block Tests
- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by fluiddot** [comment]
Closing the PR as the testing has been completed and succeeded 🟢 .

**Pull request closed without merging**
