### PR TITLE
Try iOS device tests on Circle

### PR DESCRIPTION
**Pull request by JavonDavis**
Fixes #

To test:

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
👋 @JavonDavis , any context you can add about why closing the PR? Was it a unworkable maybe or will it be superseded by another PR?

**Comment by JavonDavis** [comment]
@hypest this was me experimenting to see if there's any additional benefit to configuring the tests to run a CircleCi instance. To achieve the same thing we currently have we'd need to do the following on Server

* Get the tests running against local instances
* Configure Selenium grid to get the tests running in Parallel
* Set up a video recording capability on CI

All of this doable but I'm not totally sure there's added benefit to it and I had shifted my focus to other areas with higher priority. I was thinking to open an issue for either myself or someone else can circle back to and complete

**Comment by hypest** [comment]
Thanks for elaborating @JavonDavis !

Just adding some thoughts, I think that trying to remove the dependency on SauceLabs and go to CircleCI, or even better TravisCI (more on this afterwards) is still a good goal. Ultimately, we'd like to be able to run all the native mobile tests on the Gutenberg CI, and that's where the TravisCI detail comes in. 

Did a cursory search for solution there and ran into at least one article that might be useful: https://twpower.github.io/109-travis-ci-appium-android-test-en. Then again, we might want to experiment with a docker based setup, perhaps resembling the recently introduced [WordPress e2e test infra](https://make.wordpress.org/core/2019/06/27/introducing-the-wordpress-e2e-tests/).

**Comment by JavonDavis** [comment]
@hypest thanks for the added detail here, I'm planning to make this one of my focuses for this week(Hack Week)

**Comment by mokagio** [comment]
Going to close this because it's stale and we're also moving away from CircleCI.

**Pull request closed without merging**
