### PR TITLE
Release 1.51.1

### PR DESCRIPTION
**Pull request by dcalhoun**
Release for Gutenberg Mobile 1.51.1

## Related PRs
* Gutenberg: https://github.com/WordPress/gutenberg/pull/31242
* WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/14536
* WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/16388
* ~Aztec-iOS: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/~
* ~Aztec-Android: https://github.com/wordpress-mobile/AztecEditor-Android/pull~

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

- Updates relative block-support asset path [WordPress/gutenberg#31184]

## Test plan

- Use the main WP apps to test the changes above.
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- Test the Unsupported Block Editor on WP Apps ([see steps](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases)).
- Sanity [test suites](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-suites/gutenberg/sanity-test-suites.md) for WP Apps should be completed for each platform.

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by enejb** [comment]
Tested Android APK Version pr-145360build-103701. 
On Pixel 2 - Android 11.

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by antonis** [comment]
> ## WPAndroid
> [build](https://103701-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-14536-build-103701.apk) from [PR](https://github.com/wordpress-mobile/WordPress-Android/pull/14536)
> **Device**: Pixel 5 (Android 11)
> 
> ### Writing Flow checklist ✅
> #### General
> * [x]  TC001 - Paste formatted text copied from website
> * [x]  TC001 - Multiline components
> 
> #### Rich Text Format
> * [x]  TC001 - Bold, Italic, strikethrough buttons
> * [x]  TC002 - Alignment buttons
> * [x]  TC003 - Alignment Split
> * [x]  TC004 - Link button works without selection
> * [x]  TC005 - Link button works with a selected word
> * [x]  TC006 - Adding a link from a copied URL
> * [x]  TC007 - Test format detection under the cursor
> * [x]  TC008 - Test formatting doesn't remove leading or trailing whitespace
> 
> ##### Splitting and merging
> * [x]  TC001 - Merge after writing
> * [x]  TC002 - Merge after selection
> * [x]  TC003 - Merge after deleting text
> * [x]  TC004 - Merge after deleting all
> * [x]  TC005 - Merge multiple blocks
> * [x]  TC006 - Splitting/merge list block
> 
> #### Undo / Redo - Test Cases
> * [x]  TC001 - Undo/redo block actions
> * [x]  TC002 - Undo/redo text
> * [x]  TC003 - Undo/redo text format
> 
> ### Confirmed that the **Localization** on block titles work ✅
> ### Confirmed that the page layouts are filtered to include only layouts with supported blocks ✅

**Review by antonis — APPROVED** [review]
Tested via the Android and iOS builds and the apps works as expected 👍
The supported layouts fix on Android is also working correctly 🎉

**Comment by enejb** [comment]
Tested iOS 
Build 46548
On iPhone 11 Pro - on iOS 14.5

### Writing Flow checklist

#### General
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by dcalhoun** [comment]
## 🔴 Android Unsupported Block Editor Tests (round 1)

* Samsung Galaxy S20
* Android 11
* Build `103701` from PR. https://github.com/wordpress-mobile/WordPress-Android/pull/14536#issuecomment-827680965

- [x] TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 - User can discard edits to an unsupported blocks on Simple WP.com sites
- [x] TC003 - Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 - Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [ ] TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
    🔴 The UBE is not presented as an option for self-hosted sites access via Jetpack. (https://github.com/wordpress-mobile/gutenberg-mobile/issues/3425)
- [x] TC006 - Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Comment by enejb** [comment]
iOS Unsupported Block Editor Tests (round 1)
Tested iOS
Build 46548
On iPhone 11 Pro - on iOS 14.5

- [x]  TC001 - User can edit unsupported blocks on Simple WP.com sites
- [x]  TC002- User can discard edits to an unsupported blocks on Simple WP.com sites
- [x]  TC003- Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x]  TC004- Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- 🔴  TC005 - Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x]  TC006- Editing unsupported blocks is disallowed on self-hosted sites accessed via their own username and password

**Comment by enejb** [comment]
Since `TC005` is not a regression it exists in 17.1 we are planning on moving forward with this release.

**Pull request merged**
