### PR TITLE
File block upload failure handling

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes # https://github.com/wordpress-mobile/gutenberg-mobile/issues/2910
`gutenberg` https://github.com/WordPress/gutenberg/pull/27795

To test:
Visit https://github.com/wordpress-mobile/WordPress-Android/pull/13635
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
Added the new 1.45.0 milestone in light of https://github.com/wordpress-mobile/WordPress-Android/pull/13635#issuecomment-754160507

**Comment by jd-alexander** [comment]
I will be fixing the Check Correctness issue tomorrow for this and other associated PRs.

**Comment by fluiddot** [comment]
👋  @jd-alexander, we're cutting the release now so I'll bump this to `1.47`. Please let me know if you think it needs to be included in this release and we can arrange that.

**Comment by jd-alexander** [comment]
Closed via https://github.com/WordPress/gutenberg/pull/27795#issuecomment-782212026

**Pull request closed without merging**
