### PR TITLE
Improve block inserter accessibility

### LINKED ISSUE #915: Improve Screen Reader support for Block Picker.
- The buttons content can be more friendly. (i.e. "Paragraph block. Button")
- Needs to set the `button` role.
- Mention that the block picker is scrollable.
- Give a hint when the picker is presented (currently it says nothing).

The Bottom Sheet accessibility improvements are marked separately on #914

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #915 
Improves accessibility of the Inserter. 

To test:
See https://github.com/WordPress/gutenberg/pull/25549
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by etoledom** [comment]
Hey @jd-alexander !

It seems this branch needs to be updated with develop. I experienced an issue fixed by this PR: https://github.com/wordpress-mobile/gutenberg-mobile/pull/2662

This is probably why CI is failing too.

Please let me know when it's ready! 🙏

**Comment by etoledom** [comment]
Hey @jd-alexander - I was talking a look to these CI errors. The failure from the. PR changes have definitely be fixed already 🎉

What I noticed is that the `gutenberg` side branch doesn't seem to be updated yet.
I'd recommend you to rebase that branch from `origin/master` (there seems to be a conflict there even, I tried locally). And then update once again the reference on this PR.

Having an updated `gutenberg-mobile` and an outdated `gutenberg` branch sounds like might arise problems.

This is what the Android UI Test look like on CI (not very helpful to me though):

Screenshot 2020-10-09 at 10 13 47

**Comment by jd-alexander** [comment]
Thanks much for your help @etoledom I will definitely follow these steps from now to ensure everything is in sync 🙏

**Review by etoledom — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/25549#pullrequestreview-507252100

**Pull request merged**
