### PR TITLE
Enable default keyboard as default on link picker text fields

### LINKED ISSUE #2733: [iOS] Can't add new Link Rel to Button because of wrong keyboard type
**Describe the bug**
Can't add new Link Rel to Button because of wrong keyboard type

**To Reproduce**

1. Add `Buttons` block
1. Open link [settings](https://github.com/wordpress-mobile/test-cases/blob/be95fab2c52f92f369bd7ac9b4a0377304e484ab/test-cases/resources/button-link-settings.png)
1. Edit `Button URL` field and add link
1. Switch on `Open in new tab`
1. Edit `Link Rel` field
1. Type space to add a new link rel
1. Can't type a space because the keyboard type is a URL entry keyboard

**Expected behavior**
Should be able to type space to add a new link rel

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14
 - Version 15.9

### PR DESCRIPTION
**Pull request by chipsnyder**
**Fixes** https://github.com/wordpress-mobile/gutenberg-mobile/issues/2733
`Gutenberg PR:` https://github.com/WordPress/gutenberg/pull/29087

## To test:

1. Add `Buttons` block or `Image` Block
1. Open link [settings](https://github.com/wordpress-mobile/test-cases/blob/be95fab2c52f92f369bd7ac9b4a0377304e484ab/test-cases/resources/button-link-settings.png)
1. Edit the URL field and add a link
1. Switch on `Open in new tab`
1. Edit `Link Rel` field
1. Type space to add a new link rel
1. **Expect** To see the default keyboard

## Screenshots

Before | After
--- | ---
<kbd><a href="https://user-images.githubusercontent.com/1845482/96280466-4a5ea000-0fd8-11eb-8e8d-926b334381c8.jpeg"></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/108255305-17fdb480-712a-11eb-97d2-41b74e012c39.png"></a></kbd>

## PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by geriux — APPROVED** [review]
Approved via https://github.com/WordPress/gutenberg/pull/29087#pullrequestreview-593099947

**Comment by geriux** [comment]
FYI there's a `package-lock.json` update in the PR. Was it intentional?

**Comment by chipsnyder** [comment]
> FYI there's a `package-lock.json` update in the PR. Was it intentional?

Yeah, the `Check Correctness` step kept failing with 
```
Message: package-lock.json has changed. Please run npm install and commit the diff
```

It's been 3 months 😬 since I made a change in this repo though so I just listened to the bots 🤖 😄

**Comment by chipsnyder** [comment]
I reverted it now and it's happy again so 🤷‍♂️

**Comment by geriux** [comment]
> I reverted it now and it's happy again so 🤷‍♂️

Magic! ✨

**Pull request merged**
