### PR TITLE
Release 1.44.1

### PR DESCRIPTION
**Pull request by cameronvoell**
Release for Gutenberg Mobile 1.44.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/28203
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13777
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15644

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

## Changes

 - Fix crash in mobile paragraph blocks with custom font size - https://github.com/WordPress/gutenberg/pull/28121
 - Fixed crash introduced from recent fontSize fix - https://github.com/WordPress/gutenberg/pull/28209
 - Add move to top bottom when long pressing block movers - https://github.com/WordPress/gutenberg/pull/27554

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by jd-alexander** [comment]
I am re-running the failed UI Tests for Android and iOS. The failure was due to the File Block UI tests that have failed in the past. I had created a PR that increased sleep time on Android before a click operation that was causing the failure. That change was just merged so it's not included here.  I will keep an eye out for this on other PRs to ensure it's not taking place.

**Comment by jd-alexander** [comment]
@cameronvoell for the bundle updates. Do we run the bundle update command every time we update the Gutenberg ref? I just noticed that after the last GB ref update it wasn't updated so let me know if that's expected. 

**Update**

This question was answered by @cameronvoell The bundles are only updated when the Gutenberg ref update contains code changes. The last Gutenberg ref update that was made is related to a changelog commit.

**Review by jd-alexander — APPROVED** [review]
LGTM 🚢

**Comment by cameronvoell** [comment]
> @cameronvoell for the bundle updates. Do we run the bundle update command every time we update the Gutenberg ref? I just noticed that after the last GB ref update it wasn't updated so let me know if that's expected.

The bundle has no changes and doesnt require an update because the latest changes were only to release-notes and gutenberg change log. In the future I'll try and avoid making those the last updates on the PR because I agree the reference update with no bundle update after looks scary. I re-ran the bundle command just to be extra sure and verified it shows no changes (since I ran it on my machine last and no updates to relevant files since then).

**Comment by cameronvoell** [comment]
I did [writing flow tests](https://github.com/wordpress-mobile/test-cases/edit/trunk/test-cases/gutenberg/writing-flow/readme.md) for iOS and Android just to be safe and everything looks good with no regressions 🎉 


#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Pull request merged**
