### PR TITLE
Remove the border-left from the toolbar

### LINKED ISSUE #639: Remove border-left from Quick Toolbar
img_1988

### PR DESCRIPTION
**Pull request by hypest**
Fixes #639 

Gutenberg side PR: https://github.com/WordPress/gutenberg/pull/20881

With the left border | Without the left border
-- | --
Screenshot 2020-03-13 at 17 01 35 | Screenshot 2020-03-13 at 17 01 10

To test:
1. Run the demo app and capture a screenshot of the app
2. Notice that there is no 1-pixel grey border to the left of the Inserter button

cc @iamthomasbishop in case you also want to try this out.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by marecar3** [comment]
We're freezing `1.24.0 `today. If you think it is ready and if you'd like to ship it with `1.24.0`please merge it into develop branch. Otherwise, we can bump it to `1.25.0.` @hypest  @cameronvoell

**Comment by hypest** [comment]
Moved to 1.25, although this PR will probably get closed in favor of https://github.com/wordpress-mobile/gutenberg-mobile/pull/2004

**Comment by SergioEstevao** [comment]
@hypest I'm moving this to 1.26, feel free to move it back to 1.25 if this is something that can be considered a regression.

**Comment by pinarol** [comment]
I am changing the milestone of this PR as 1.27 because the 1.26 release branch will be cut quite soon. Let me know if you instead wanted to include this to 1.26.

**Comment by mkevins** [comment]
Hi @hypest  wave smiley since this one is still awaiting review (and [will possibly be superseded](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2017#issuecomment-600084740)), I'll bump the milestone to 1.28. Please let me know if you wanted to get this into the 1.27 release.

**Comment by SergioEstevao** [comment]
@hypest do you still want to have this on 1.28 ?

**Comment by SergioEstevao** [comment]
I think this other [PR](https://github.com/WordPress/gutenberg/pull/20830) solved the original issue. 

Do you want to close this one @hypest ?

**Comment by hypest** [comment]
Will close this one to remove the confusion. Was waiting for #2004 to land first before closing but yeah, no real need to postpone.

**Pull request closed without merging**
