### PR TITLE
Update `react-native-reanimated` version to `2.4.1`

### LINKED ISSUE #4657: Update Reanimated library to 2.4.1
## Description

With the current version `2.2.4`, when connecting the app to the Chrome debugger it crashes on Android. In order to address this issue and re-enable debugging with the Chrome debugger, we should update `react-native-reanimated` package to version `2.4.1`.

### PR DESCRIPTION
**Pull request by fluiddot**
**Gutenberg PR:** https://github.com/WordPress/gutenberg/pull/39430

To test:
Follow the testing instructions from https://github.com/WordPress/gutenberg/pull/39430.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by fluiddot** [comment]
Heads up that I'll wait for version `2.4.1` to be merged and a Git tag creation, before creating the WordPress-Android and WordPress-iOS PRs.

**Comment by fluiddot** [comment]
@geriux let me know if you could take a look at this PR, thanks 🙇 ! I'd like to note that as version `1.72.0` has been recently cut, I'm planning to merge the [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/pull/16106) and [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/18137) PRs into `gutenberg/after_1.72.0`.

**Review by geriux — APPROVED** [review]
LGTM! I tested this locally with WordPress iOS app.

**Comment by geriux** [comment]
> @geriux let me know if you could take a look at this PR, thanks 🙇 ! I'd like to note that as version `1.72.0` has been recently cut, I'm planning to merge the [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/pull/16106) and [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/18137) PRs into `gutenberg/after_1.72.0`.

Sounds good! I'll approve those now.

**Comment by fluiddot** [comment]
Heads up that the Gutenberg ref has been updated when updating with `trunk` ([reference](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4653/commits/02aa6e0a579d2fbc50fe4a62cab182db0b4b3637)). Since the [recent change introduced is just related to E2E tests](https://github.com/WordPress/gutenberg/commit/6b28f0e92be69c71f819cf161dd5c007d32e749d), I won't generate a new JS bundle for iOS.

**Pull request merged**
