### PR TITLE
Issue/697 change color of text and links

### LINKED ISSUE #697: Refine/align coloring of body text and inline text links
Current vs. Proposed

image

## Body Text

Currently, all body-text (headings, paragraph text, image captions, etc) are set to `#000000` (black), which is a bit too strong. To align with an upcoming colors refactor in the apps, let's align with that proposal of `#1A1A1A` aka `$gray-900` – from [this palette](https://automattic.github.io/color-studio/).

## Inline Text Links

The color of inline text links is currently something around `#027AFF` (see left on example above). Let's switch to use `$blue-500` (`#016087`) for alignment. 

I've voiced a concern that this blue feels like it doesn't provide enough contrast against the `$gray-900` text, especially when not underlined, but it's an improvement, and it passes color contrast tests on a white background.

Note: we _aren't currently underlining text links on Android_ – we should change this for accessibility sake.

## Punch List

- [ ] Change body text to `#1A1A1A` aka `$gray-900` in [this palette](https://automattic.github.io/color-studio/)
- [ ] Change inline link color to `#016087` aka `$blue-500` in [this palette](https://automattic.github.io/color-studio/)
- [ ] Force underline to links in Android

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #697 

Related GB PR: https://github.com/WordPress/gutenberg/pull/16016

Simulator Screen Shot - iPhone Xʀ - 2019-06-06 at 14 40 39

This PR updates the RCTAztecView component to support the setting of base text color and the color for links.

To test:
 - Run the demo app
 - Check that the default body text on text blocks (paragraph/list/quotes) is using the new gray 900 color.
 - Check that links are being draw with the new blue-500 color

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@danilo or @mkevins I need help to support the link color on Android. It would also be nice to add underlines to links on Android.

**Comment by iamthomasbishop** [comment]
Looks great! Once we get Android set up, feel free to ping me for review. :shipit:

**Comment by etoledom** [comment]
Would it be worth it to ship this one for iOS and add a ticket to handle the Android side on a separated PR? 🤔

**Comment by iamthomasbishop** [comment]
@etoledom I think so, but I’m not sure what the timeline of getting this to work on Android is looking like.

**Comment by SergioEstevao** [comment]
@marecar3 do you think you can handle this?

**Comment by marecar3** [comment]
Hey @SergioEstevao, I am not sure what is the scope of the work regarding Android, let me check and I will be back with some comment. Tnx.

**Comment by SergioEstevao** [comment]
@etoledom Android part merged in, do you want to give it another look?

**Comment by iamthomasbishop** [comment]
@etoledom I noticed that bullet color too but haven't had a chance to submit a new issue. Would you mind creating an issue for this? 🙃

**Comment by etoledom** [comment]
@iamthomasbishop ready!
https://github.com/wordpress-mobile/gutenberg-mobile/issues/1111

**Comment by iamthomasbishop** [comment]
@etoledom thank you!

**Pull request merged**
