### PR TITLE
Release 1.41.0

### PR DESCRIPTION
**Pull request by ceyhun**
Release for Gutenberg Mobile 1.41.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/26817
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13322
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15257

## Extra PRs that Landed After the Release Was Cut

- Remove flex from range cell container (https://github.com/WordPress/gutenberg/pull/26777)
- Correct ios back icon (https://github.com/WordPress/gutenberg/pull/26690)
- Fix Dark mode style for preformatted/shortcode blocks (https://github.com/WordPress/gutenberg/pull/26898)

## Changes

* [***] Faster editor start and overall operation on Android. [#2780]
* [*] [Android] Enable multiple upload support for Image block. [#2530]

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Aztec dependencies are pointing to a stable release.
  - iOS: Aztec dependencies match in `RNTAztecView.podspec` and `gutenberg/packages/react-native-aztec/RNTAztecView.podspec`.
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by lukewalczak** [comment]
**SANITY TESTING IOS**

Gallery-1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

Gallery-2

- [x] Gallery block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

Gallery-3

- [x] Gallery block - Add Gallery Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

Columns - 1


- [x] Columns - Columns percentage mechanism - column's preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Columns block is added with default number of Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc001)
- [x] Columns - Adding Column with AppenderButton - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


Columns - 2
- [x] Columns - Max limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Columnn - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [x] Columns - Deep nesting is possible (iOS only)- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

Columns - 3

- [x] Columns - Check if Column placeholders is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is streched to content in nested structure- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

MediaText-1

- [x] Media Text block - Insert image from device (failing) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

MediaText-2

- [x] Media Text block - Insert video from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (cancel) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

MultipleUpload-1

- [x] Simultaneous uploads - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)

Cover-1

- [x] Cover - Add image background from WordPress Media library - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)


Editor Theme - 1

**Note**: It's a known [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2637). 
- [X] Default Colors - Check that default colors still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [X] Default Gradients - Check that default gradients still load - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [X] Custom Colors - Check that custom colors load in the editor - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)

> When you switch theme in the app the theme color palette does not change. If you close the editor and reopen it, the theme changes are applied.

Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by ceyhun** [comment]
Tested with iPhone 11 Pro, iOS 14.2, build 37501:

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components
- [x] Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [x] Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
- [x] Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by mkevins** [comment]
## Sanity testing Android

Tested via [generated apk](https://81371-9306568-gh.circle-artifacts.com/0/Artifacts/WordPress-pr-13322-build-81371.apk) on Pixel 3a (physical device)

### DarkMode-1

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [ ] :x: Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)

For shortcode block, there is a white input box instead of black:



- [x] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)

### Spacer-1

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)

### Buttons-1

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
- [x] Buttons block - Button's wrapper grows properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)

### Buttons-2

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

Note: The steps should be updated for these tests, because the trash button is no longer present. Instead, we tap the "dots" and select "Remove block" from the bottomsheet.

### Buttons-3

- [x] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

### Button-6

- [x] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)

Update Test: Open post in preview mode, click browser button (globe), then click button

- [x] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] :question: Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)

I did not see a remove link button, but I believe the sanity test needs to be updated here.

- [x] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)

### Group-1

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] :question: Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)

I did not see nested outlines for the inner groups on nested groups (the outline was only 1 layer deep). If this is expected, the sanity test needs to be updated. Here is a screen recording:



- [x] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)

- [x] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)



### Color Settings - 1
- [x] Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
- [x] Scroll color palette to start - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- [x] Scroll color palette to the end - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)

**Comment by ceyhun** [comment]
Thanks for testing @mkevins!

> I did not see a remove link button, but I believe the sanity test needs to be updated here.

There are 2 ways to change button link settings:
1. From button settings gear icon
1. From link settings in the toolbar: https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/resources/button-link-settings.png
Remove link option was available in the 2. option for me. Did you maybe try with the 1st one?

>I did not see nested outlines for the inner groups on nested groups (the outline was only 1 layer deep).

The nested outlines only appeared for me if there were no other blocks inside groups other than group blocks. @iamthomasbishop can you please confirm if this look is correct?

**Comment by cameronvoell** [comment]
Samsung S10+ , Android 10, WordPress-pr-13322-build-81371.apk

**Writing Flow** checklist:

- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [X] TC001 - Multiline components
- [X] Rich Text Format
  - [X] TC001 - Bold, Italic, strikethrough buttons
  - [X] TC002 - Alignment buttons
  - [X] TC003 - Alignment Split
  - [X] TC004 - Link button works without selection
  - [X] TC005 - Link button works with a selected word
  - [X] TC006 - Adding a link from a copied URL
  - [X] TC007 - Test format detection under the cursor
  - [X] TC008 - Test formatting doesn't remove leading or trailing whitespace
- [X] Splitting and merging
  - [X] TC001 - Merge after writing
  - [X] TC002 - Merge after selection
  - [X] TC003 - Merge after deleting text
  - [X] TC004 - Merge after deleting all
  - [X] TC005 - Merge multiple blocks
  - [X] TC006 - Splitting/merge list block - <strike>Matches web behavior but this changed since last release</strike>
- [X] Undo / Redo - Test Cases
  - [X] TC001 - Undo/redo block actions
  - [X] TC002 - Undo/redo text
  - [X] TC003 - Undo/redo text format

<strike>All Green except [Splitting/merge list block](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/writing-flow/splitting-merging.md#tc006). The new behavior matches what I see on web, so I'm not sure if this was an intentional update on the web side or not. Basically hit enter twice in a list block does not create a paragraph block in between, it just keeps making additional list items.</strike> I misread one of the steps here. The behavior matches iOS, and I was able to complete the test successfully: "Put the caret by the half of them (**at the end of the item**) and press Enter to create a new item."

**Comment by iamthomasbishop** [comment]
@ceyhun thanks for the ping! 

> I did not see nested outlines for the inner groups on nested groups (the outline was only 1 layer deep). If this is expected, the sanity test needs to be updated. Here is a screen recording:

> The nested outlines only appeared for me if there were no other blocks inside groups other than group blocks. @iamthomasbishop can you please confirm if this look is correct?

I know the bordering logic can get quite complex, so I'm not 100% sure if I'm missing something, but that looks correct to me and I don't think it has changed recently (@lukewalczak, can you confirm/deny?). I don't think we typically want/need to show more than 1 level deep — which is basically what I'm seeing in the examples above. The one exception seems to be if there is an empty group (also the case on nested Columns), in which case we are showing the additional level — I can't remember if there was a special reason for this, and it's not causing _that_ much harm, but we can probably de-clutter things a little bit by hiding that second level nesting border (to be clear, this work can be tackled in a future release if it's not a new change or regression).

I also noticed something when trying out Columns (specifically the new `UnitControl`): We shouldn't be using this `Menu` component for the `unit` selector ([screenshot](https://cloudup.com/cX-nf3WI-8v)). Instead we should be using the `BottomSheet` on Android. This made me wonder if we're not including @lukewalczak's latest work on the new `UnitControl` component. If it's not a pain, I'd like to address this before including this in a release.

(Context: We were exploring this third-party component with the intention of using for the `unit` selector but decided to stick with `BottomSheet` (again, only on Android) because it was going to require a bunch of design tweaks.)

**Comment by mkevins** [comment]
Re nested innerblocks outlines

> but that looks correct to me and I don't think it has changed recently

This is quite possibly the case. Since each round of sanity tests only covers a subset of the test cases, updated designs and behavior can leave the test cases out of date by the time they are encountered again, so thanks for confirming. I'll update the test case to reflect that the outline only shows 1 layer of depth for the nested groups.

**Comment by mkevins** [comment]
Hi @ceyhun :wave: :smile: 

> There are 2 ways to change button link settings:
> 
> 1. From button settings gear icon
> 2. From link settings in the toolbar: https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/resources/button-link-settings.png
>    Remove link option was available in the 2. option for me. Did you maybe try with the 1st one?

You are right! :man_facepalming: , I used the gear icon. I tried via the link settings button, and it works as expected. :+1:

**Review by cameronvoell — APPROVED** [review]
Looks like all status checks are green!

**Pull request merged**
