### PR TITLE
Jetpack Tiled Gallery: Inner blocks implementation

### LINKED ISSUE #4000: Jetpack Tiled Gallery: Inner blocks implementation
Migrate the Jetpack Tiled Gallery block to use the [InnerBlocks API](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/inner-blocks/README.md).

Related:
- https://github.com/wordpress-mobile/gutenberg-mobile/issues/3874

### PR DESCRIPTION
**Pull request by guarani**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/4000

Related:
- https://github.com/Automattic/jetpack/pull/21135

### To test

1. In the terminal, run `npm run start:reset` 
2. In another terminal window, run `npm run core ios`
3. Add the Tiled Gallery block
4. Verify that you can add, remove, re-arrange images and that each is an inner block
5. Repeat the above steps for Android, running `npm run core android` in Step 2

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by guarani** [comment]
👋 Hi @illusaen, I've marked this ready for review. I'd like to add an integration test, but will do that in follow-up PRs.

**Comment by guarani** [comment]
I've restarted the failing buildkite tests 🤞

**Comment by guarani** [comment]
Pushing an empty commit fixed the buildkite error.

**Review by illusaen — APPROVED** [review]
LGTM!

**Pull request merged**
