### PR TITLE
Dock the keyboard hide button to the right side of the screen

### PR DESCRIPTION
**Pull request by pinarol**
Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/350

This PR docks the keyboard hide button to the right side of the screen. Depends on https://github.com/WordPress/gutenberg/pull/13415

Android:
keyboard1and

iOS:
keyboard1ios

**To Test**

Testing prerequisites

For WPiOS

Checkout the PRs branch to any arbitrary folder and cd .. to it
run yarn install, yarn start
Open XCode WPiOS on the latest develop
Clean build folder on Xcode, and then run the app

For WPAndroid

open grade.properties at WordPress-Android folder
add wp.BUILD_GUTENBERG_FROM_SOURCE = true to grade.properties
checkout the PRs branch in the subrepo of WordPress-Android repo
cd to WordPress-Android/libs/gutenberg-mobile
run yarn install, yarn start
yarn wpandroid on a separate terminal in the same directory

Test steps

Check with different blocks and verify keyboard hide button is docked to the right side of the screen while other buttons can be scrolled horizontally
Verify also there's no UI anomaly due to https://github.com/wordpress-mobile/gutenberg-mobile/pull/480#issuecomment-455620000

### CODE REVIEW

**Comment by iamthomasbishop** [comment]
@pinarol Looking good! I have a couple minor notes:

* We can remove the last divider on the inline tools list
* I think the sizing of the `keyboard-hide` button is a little too wide. I believe it should be 44x44, and the icon inside 24x24
* The icon itself is bumped down 1pt in order to provide better visual alignment – so the margin on this one is 11/10/9/11 (top/right/bottom/left). Note: IIRC, we used a slightly smaller icon here (20x20?), so if that's the case, I would just make sure it's centered horizontally and vertically in the button and then bump it 1pt downward.

Details:

image

**Comment by pinarol** [comment]
Hi @iamthomasbishop ,
I tried to address your feedbacks, I think it is ready for another look:

keyboard2ios

**Comment by iamthomasbishop** [comment]
Looks great, @pinarol! :shipit:

**Comment by pinarol** [comment]
Hey @marecar3, this is ready for another look.

**Comment by marecar3** [comment]
Hey @pinarol 
Looks good to me :)

**Pull request merged**
