### PR TITLE
Release 1.89.1

### PR DESCRIPTION
**Pull request by dcalhoun**
Release for Gutenberg Mobile 1.89.1

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/48643
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/18028
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/20231

## Extra PRs that Landed After the Release Was Cut

No extra PRs yet. 🎉

### Change 1
- **PR:** https://github.com/WordPress/gutenberg/pull/48435
- **Issue:** https://github.com/WordPress/gutenberg/issues/47966
- **Issue:** https://github.com/WordPress/gutenberg/issues/48298

## Test plan

Once the installable builds of the main apps are ready, perform a quick smoke test of the editor on both iOS and Android to verify it launches without crashing. We will also complete the UBE test cases. 

## Release Submission Checklist

- [x] Verify Items from test plan have been completed
- [x] Check if `RELEASE-NOTES.txt` is updated with all the changes that made it to the release. Replace `Unreleased` section with the release version and create a new `Unreleased` section.
- [x] Check if `gutenberg/packages/react-native-editor/CHANGELOG.md` is updated with all the changes that made it to the release. Replace `## Unreleased` with the release version and create a new `## Unreleased`.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by dcalhoun** [comment]
## 🟢 Included Changes (Android)
**Build**: [`jetpack-installable-build-pr18028-cb9e59f.apk`](https://github.com/wordpress-mobile/WordPress-Android/pull/18028#issuecomment-1450436911) 
**Device**: Samsung Galaxy S20 5G FE

* [x] https://github.com/WordPress/gutenberg/issues/47966
* [x] https://github.com/WordPress/gutenberg/issues/48298

**Comment by dcalhoun** [comment]
## 🟢 Unsupported Block Tests (Android)
**Build**: [`jetpack-installable-build-pr18028-cb9e59f.apk`](https://github.com/wordpress-mobile/WordPress-Android/pull/18028#issuecomment-1450436911) 
**Device**: Samsung Galaxy S20 5G FE

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by dcalhoun** [comment]
Friendly note that the 1.89.1 release notes were mistakenly set in the bug fix PR: https://github.com/wordpress-mobile/gutenberg-mobile/commit/541598781014e93e0e04027ebfbfa5934dd37aa6. That is why they are not explicitly changing in this PR.

**Comment by dcalhoun** [comment]
## 🟢 Unsupported Block Tests (iOS)
**Build**: [`pr20231-a9f3845`](https://github.com/wordpress-mobile/WordPress-iOS/pull/20231#issuecomment-1450645529) 
**Device**: iPhone SE (iOS 16.4)

- [x] TC001 User can edit unsupported blocks on Simple WP.com sites
- [x] TC002 User can discard edits to an unsupported block on Simple WP.com sites
- [x] TC003 Editing unsupported blocks is allowed on Gutenberg-enabled Atomic sites
- [x] TC004 Editing unsupported blocks is disallowed on Classic-enabled Atomic sites
- [x] TC005 Editing unsupported blocks is enabled on self-hosted sites accessed via Jetpack
- [x] TC006 Editing unsupported blocks is disallowed on self-hosted sites access via their own username and password

**Comment by dcalhoun** [comment]
## 🟢 Included Changes (iOS)
**Build**: [`pr20231-a9f3845`](https://github.com/wordpress-mobile/WordPress-iOS/pull/20231#issuecomment-1450645529) 
**Device**: iPhone SE (iOS 16.4)

* [x] https://github.com/WordPress/gutenberg/issues/47966
* [x] https://github.com/WordPress/gutenberg/issues/48298

**Review by twstokes — APPROVED** [review]
LGTM @dcalhoun!

**Pull request merged**
