### PR TITLE
Issue/874 fix nested lists handling

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes: #874

Related GB PR: https://github.com/WordPress/gutenberg/pull/15566
Relate Aztec PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1181

This PR updates the list code to support the following:
 - Activates the indent/outdent buttons on the UI for the list block
 - Improves the handling of the Enter character and make sure the format of text between Aztec and the format library is consistent 
 - Makes the handling of delete of new lines to be handled by the rich text format structure, instead of the native side.

How to test:
 - First of all try, the issue stated on #874 to see if it's working correctly
 - Then try to use the indent and outdent buttons and see if they work correctly
 - Try to delete list items and see if it works correctly

### CODE REVIEW

**Comment by etoledom** [comment]
@SergioEstevao - Thanks for handling this!

I did a smoke test on the issue, and it seems to be resolved 🎉 
There is one detail that I found:
- Press enter on a nested list item to create a new empty item.
- Try to delete the new list, it removes the indentation (that looks OK), but also creates a new list item with the same indentation as before, next to the current one (that does not look good).

Check the gif for a better visual explanation:

delete_list_item

**Comment by etoledom** [comment]
The web side has a similar (but not completely the same) behavior, so it's probably an issue in the web side that is affecting us.

web_list_issue

**Comment by SergioEstevao** [comment]
I saw similar things, with the system showing two bullets in the same line,
I will check the HTML produced and if what the app is showing makes sense,
I will merge this.

**Comment by SergioEstevao** [comment]
@etoledom I just printed the HTML being produced by the JS side and the HTML we are producing in Aztec looks right. Not sure what to do.

**Comment by SergioEstevao** [comment]
Closing in favour of: https://github.com/wordpress-mobile/gutenberg-mobile/pull/991

**Pull request closed without merging**
