### PR TITLE
Tiled Gallery Block: Aspect Ratio for Square Layout

### PR DESCRIPTION
**Pull request by SiobhyB**
`Jetpack`: https://github.com/Automattic/jetpack/pull/21166

## Description

Fixes: https://github.com/wordpress-mobile/gutenberg-mobile/issues/4010

This PR is one part of a wider effort to port the Jetpack Tiled Gallery block to Mobile Gutenberg. It will be merged into a feature branch, `add/tiled-gallery-block`.

For this PR chain, the overarching purpose is to define the aspect ratio of images in the editor, so that they appear as squares.

## Testing

Please refer to [the Jetpack PR](https://github.com/Automattic/jetpack/pull/21166) as the central PR with the most up-to-date testing instructions.

<hr />

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by guarani — COMMENTED** [review]
I reviewed the Jetpack PR [here](https://github.com/Automattic/jetpack/pull/21166#pullrequestreview-767314889) but will hold off reviewing the Gutenberg PR to give others a chance to validate the approach (because it involves adding changes to the core blocks).
Feel free to re-request a review here when the Jetpack and Gutenberg PRs are ready for review again.

While it would be nice to add integration tests to our Gutenberg Mobile PRs such as this, I don't think verifying the aspect ratio would be a suitable thing to test. It doesn't affect the HTML representation of the block – it's just a visual in-editor change – so it seems like a difficult piece of code to test, at least with integration tests.

**Comment by guarani** [comment]
> The following sibling PRs include complementary changes:

Should the above be deleted or are there sibling PRs here?

On a different topic, would it make sense to use the [`Fixes` keyword](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in the PR description to close https://github.com/wordpress-mobile/gutenberg-mobile/issues/4010?

**Review by guarani — COMMENTED** [review]
Reviewed via https://github.com/Automattic/jetpack/pull/21166#pullrequestreview-792158532

**Comment by SiobhyB** [comment]
> Should the above be deleted or are there sibling PRs here?

You're right, I overlooked this line when editing the PR description, updated now. Thanks for pointing that out!

> On a different topic, would it make sense to use the Fixes keyword in the PR description to close #4010?

Sounds good to me, added that now.

**Review by guarani — APPROVED** [review]
Approved via https://github.com/Automattic/jetpack/pull/21166#pullrequestreview-793095462. I think the failures here are related to the single Tiled Gallery integration test. This test will be disabled in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4143 so it might be worth checking the state of that PR and seeing if it resolves the failures here.

cc @illusaen

**Comment by SiobhyB** [comment]
I think the error may be related to the fact I recently updated the feature branch from `develop` as well as the changes to the Jetpack tests in https://github.com/wordpress-mobile/gutenberg-mobile/pull/4008. It looks like this file on our feature branch should be deleted: https://github.com/wordpress-mobile/gutenberg-mobile/blob/add/tiled-gallery-block/src/jetpack/test/tiled-gallery.js

That said, I expect that there are probably other changes that will also be needed, maybe warranting their own PR. I'll be happy to do some more digging into that on Monday unless others have insights before then.

**Pull request merged**
