### PR TITLE
Track unsupported blocks

### LINKED ISSUE #1174: Track unsupported blocks from the apps
We have some data on how many published blocks there are of each type on WordPress.com, which is a nice proxy, but it’d be better to know exactly what are users encountering as unsupported in the apps

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR fixes #1174 by receiving the list of unsupported blocks from GB when opening a post. 
Basically this PR updates the native bridge and the Android glue code to deal with the changes made in GB. Previously GB was only sending a flag to the bridge, to notify the presence or not of unsupported blocks.

GB side PR: https://github.com/WordPress/gutenberg/pull/16434

I will update `wp-android` and bump the analytics accordingly to the new signature when this PR  is merged. 

To test:
- Open the demo post in the demo app
- Put a breakpoint [here](https://github.com/wordpress-mobile/gutenberg-mobile/compare/issue/1174-track-unsupported-blocks?expand=1#diff-790122ff7222773fbfe709696f8eedc5R73) and check the the array of unsupported block is correct

Update release notes:

- [ x ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by etoledom** [comment]
I added the changes needed for iOS.
This can be tested by:

- Running the demo app from Xcode (`open ios/gutenberg.xcodeproj`)
- After the content is loaded, filter the log on Xcode with `gutenbergDidMount`
- You should read the list of unsupported blocks sent by the bridge.

`gutenbergDidMount(unsupportedBlockNames: ["core/title", "core/p4ragraph", "core/gallery", "core/spacer", "wporg/download-button", "core/spacer", "core/gallery", "core/spacer", "core/spacer", "core/columns", "core/spacer", "core/spacer", "wporg/download-button", "core/spacer"])`

**Comment by etoledom** [comment]
Question: Do we want repeated instances of the same unsupported block?

**Comment by daniloercoli** [comment]
> Question: Do we want repeated instances of the same unsupported block?

I guess yes, so the host apps can implement their own logic around the info. I.E: count the number of unsupported block per any type.  I know that we can do this JS side as well.

**Comment by daniloercoli** [comment]
@etoledom Tested the iOS and works as expected.
I've updated this branch by merging `develop` into it, and the GB side branch by merging `master`.

Feel free to give this a last test and then merge. I will start working on the Android side, to update the app with the new interface signature.

**Comment by etoledom** [comment]
GitHub automatically closed this since it was marked as `fix ...` on the gutenberg PR.
Reopening to merge.

**Comment by etoledom** [comment]
Updated to gutenberg master after merging https://github.com/WordPress/gutenberg/pull/16434.
Tested on iOS and it's 👍
Smoke tested on Android and it looked good too.

Merging now.

**Pull request merged**
