### PR TITLE
Enable Button block in production

### PR DESCRIPTION
**Pull request by lukewalczak**
Unblocking a `Button` block in the production

Ref to gutenberg: https://github.com/WordPress/gutenberg/pull/20093

To test:
* ios - https://github.com/wordpress-mobile/WordPress-iOS/pull/13397
* android - https://github.com/wordpress-mobile/WordPress-Android/pull/11256

https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

**Comment by pinarol** [comment]
I am copy/pasting test cases here to be checked after testing:

**WPiOS:**

- [ ] Button block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc011)
- [ ] Button block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc010)
- [ ] Button block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc012)
- [ ] Button block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc015)
- [ ] Button block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc003)
- [ ] Button block - Fallback to default colors in case theme colors are used - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc013)
- [ ] Button block - New Buttons are created with the blue color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc014)
- [ ] Button block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc009)
- [ ] Button block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc005)
- [ ] Button block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc006)
- [ ] Button block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc004)
- [ ] Button block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc008)
- [ ] Button block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc007)
- [ ] Button block - Link in the clipboard is automaticially added into the empty URL field - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc002)
- [ ] Button block - Button max width is calculated OK inside inner blocks(iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc001)

**WPAndroid:**

- [ ] Button block - Render custom text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc011)
- [ ] Button block - Render custom background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc010)
- [ ] Button block - Render gradient background color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc012)
- [ ] Button block - Check if selection / caret color matches font color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc015)
- [ ] Button block - Edit text styles - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc003)
- [ ] Button block - Fallback to default colors in case theme colors are used - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc013)
- [ ] Button block - New Buttons are created with the blue color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc014)
- [ ] Button block - Settings: Change Button border radius - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc009)
- [ ] Button block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc005)
- [ ] Button block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc006)
- [ ] Button block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc004)
- [ ] Button block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc008)
- [ ] Button block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc007)
- [ ] Button block - Link in the clipboard is automaticially added into the empty URL field - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/button.md#tc002)

**Comment by pinarol** [comment]
@geriux -> WPAndroid
@dratwas -> WPiOS

Please use peril links in the parent PRs to install the app for testing. And check [these items](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866#issuecomment-583536329) when done. Keep in mind that you don't have to limit yourselves with those items, challenging the feature in different ways is always welcomed.

**Comment by iamthomasbishop** [comment]
Had a chance to go through and test extensively, here are my notes. Note: Most issues were present across both platforms (platform-specific issues are labeled as such).

## Blockers

* I think the fallback color should be a neutral gray (`#595959`), not blue. This is esp noticeable when using a theme like Twenty-Twenty, which has a strong background color (screenshot)
* Tapping `delete` key while button is empty should delete the block
* When button has link, toolbar button should have “active” button style (example)
* We should probably show the link button in the block toolbar while the block is selected. (Not only while richText is focused) (example)

## Non-blockers

* **[Android-only]** Left/right inner padding on buttons seems a bit larger on Android
* **[Android-only]** Android text selection highlight is appropriate color, but handles aren’t the same color as the button text. Not a blocker, but would be nice to match (screenshot)
* Button alignment settings are not honored, or shown in the block toolbar (screenshot)
* Button placeholder text seems a bit too strong, can we use white with alpha 43%? (screenshot)
* Can we move the highlight outline to “outside” the button itself, so that the left side of the button fill is aligned left, not the highlight? (screenshot)
* `Button URL` field on bottom sheets (link settings, block settings) should be changed to `Button Link URL`
* For color settings, we can probably remove the section header and leave only the footer note. Also, now that I see the footer note in context, I think it should instead read: “Button color settings are coming soon.” (example)
* We can remove the border-bottom on the `Link rel` cell (screenshot)

**Comment by lukewalczak** [comment]
Thanks @iamthomasbishop for the valuable feedback! 👌 

To avoid confusions I would like to ask for some details:

> I think the fallback color should be a neutral gray (#595959), not blue. This is esp noticeable when using a theme like Twenty-Twenty, which has a strong background color (screenshot)

Unfortunately, a screenshot is not loading and tbh I don't know what color you meant, because please note that `Button` bg color can be set in three different cases:

1. blue (#2271b1) - creating new `Button` block on mobile
2. grey (#595959) - fallback color when we cannot resolve color set on the web
3. custom color - color we are able to resolve

> [Android-only] Android text selection highlight is appropriate color, but handles aren’t the same color as the button text. Not a blocker, but would be nice to match

I think it can be related to the Android API version, but would like to get more insights from @chipsnyder who was working on that (is there any obstacle to support it?). On API level 27 handles have correct bg color, for the reference:

API 27 | API 29
--- | ---
Screenshot 2020-02-08 at 01 03 25 | Screenshot 2020-02-08 at 01 00 28

> Button alignment settings are not honored, or shown in the block toolbar

Didn't see that in the requirements, but I see no reason why don't support it ✌️ .

**Comment by iamthomasbishop** [comment]
> To avoid confusions I would like to ask for some details:

Sorry, I should have been clearer in my feedback. I meant to say that the background color should be gray both when the user creates a new button block on mobile **and** when there is a fallback. 

The reason for this is — and correct me if I’m wrong — is that when a user creates a new button on mobile, it is setting the background to the theme-default color. In other words, creating a new button on mobile results (on the front-end) in a button with the theme’s default style. For example, if I’m using the Twenty-Twenty theme and I create a button on mobile, it’s going to be a pink squared-off button. Because we don’t have access to that style information, we should keep the background color neutral.

> On API level 27 handles have correct bg color, for the reference:

Good to know. 👍

> Didn't see that in the requirements, but I see no reason why don't support it ✌️ .

I’m not sure if it was in the initial requirements, so it could be something to iterate on, but I just wanted to document it 😀

**Comment by lukewalczak** [comment]
**UPDATES - RESOLVE ALL BLOCKERS**:

1. Set bg color to grey (`#595959`), color displayed on preview comes from theme:


2. `delete` key is deleting the block when a button is empty:


3. Toolbar button has “active” button style when contains link:


4. The link button is presented in the block toolbar while the block is selected:
Screenshot 2020-02-10 at 10 18 48

**Comment by dratwas** [comment]
Tested the `peril` build in WP-iOS and every point seems to work :tada: Also tried changing the orientation etc

**Comment by geriux** [comment]
Tested on **Android** using https://github.com/wordpress-mobile/WordPress-Android/pull/11256#issuecomment-583329170

By following these test cases https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866#issuecomment-583536329

All working great ✅, orientation changes, using it within the `Group` block.. Couldn't break it =P great work! 👏

**Comment by geriux** [comment]
Couldn't test [the latest changes](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866#issuecomment-584031932) though since the latest build doesn't include them and those were marked as blockers by @iamthomasbishop

**Comment by chipsnyder** [comment]
> I think it can be related to the Android API version, but would like to get more insights from @chipsnyder who was working on that (is there any obstacle to support it?). On API level 27 handles have correct bg color, for the reference:

This is correct. The handles should be working in API 27. Although in API 28, there isn't a supported mechanism for it. Then in API 29 we would be able to support it once we bump Aztec to support API 29.

**Comment by lukewalczak** [comment]
**UPDATES - RESOLVE NON-BLOCKERS**

1. > [Android-only] Left/right inner padding on buttons seems a bit larger on Android

That's true and the problem exists in `RichText` since the inner text is overlapping the paddings. Notice that once `RichText` is filled with content it looks properly.



2. > [Android-only] Android text selection highlight is appropriate color, but handles aren’t the same color as the button text. Not a blocker, but would be nice to match

Please check the @chipsnyder's [answer](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866#issuecomment-584105717) above.

3. > Button alignment settings are not honored, or shown in the block toolbar (screenshot)

Via @pinarol: I see this as another iteration after shipping this version>

4. > Button placeholder text seems a bit too strong, can we use white with alpha 43%? (example)

I've updated the color (43% alpha of white)

light theme | dark theme
--- | ---
Screenshot 2020-02-10 at 10 43 33 | Screenshot 2020-02-10 at 10 43 07

5. > Can we move the highlight outline to “outside” the button itself, so that the left side of the button fill is aligned left, not the highlight? (screenshot)

I hope I understood it correctly and it looks properly right now:

default | selected
--- | ---
Screenshot 2020-02-10 at 14 40 06 | Screenshot 2020-02-10 at 14 43 36

6. > Button URL field on bottom sheets (link settings, block settings) should be changed to Button Link URL

Updated!

link settings | button options
--- | ---
Screenshot 2020-02-10 at 14 44 45 | Screenshot 2020-02-10 at 14 44 49

7. > For color settings, we can probably remove the section header and leave only the footer note. Also, now that I see the footer note in context, I think it should instead read: “Button color settings are coming soon.” (example)

Done 🎉 ! Please check the screenshot above on the right side.

8. > We can remove the border-bottom on the Link rel cell (screenshot)

Done 🎉! Also please take a look at the same screenshot!

**Comment by pinarol** [comment]
> Button alignment settings are not honored, or shown in the block toolbar (screenshot)

This is highly related with [Buttons block](https://github.com/wordpress-mobile/gutenberg-mobile/issues/1790) work, it'd be better if we handle that as a part of that work. And we shouldn't delay it much, because the standalone Button block is kinda deprecated and it should be used inside Buttons block only.

**Comment by lukewalczak** [comment]
**NEW TEST CASES**

**WPiOS:** and **WPAndroid:**

- [ ] Button block - New Button is created with the gray color - [steps](https://github.com/wordpress-mobile/test-cases/blob/button-test-after-review/test-cases/gutenberg/button.md#tc014)
- [ ] Button block - The newly created button has set background color to the theme-default color in preview - [steps](https://github.com/wordpress-mobile/test-cases/blob/button-test-after-review/test-cases/gutenberg/button.md#tc016)
- [ ] Button block - Tapping `delete` key removes block when Button is empty - [steps](https://github.com/wordpress-mobile/test-cases/blob/button-test-after-review/test-cases/gutenberg/button.md#tc017)
- [ ] Button block - Toolbar link button is active when Button has link - [steps](https://github.com/wordpress-mobile/test-cases/blob/button-test-after-review/test-cases/gutenberg/button.md#tc018)

**Comment by dratwas** [comment]
Tested the new build with new test cases and everything works great, however, I found an issue related to the `link from the clipboard`. If i select text wit link in it i.e:
`
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris http://loremipsum.com
` The whole text is passed to the `URL` field. The issue is not only Button related since the paragraph link does the same.

Steps to reproduce:
1. copy the text above to the clipboard
2. create button / paragraph with link
3. open link settings
4. The URL is wrong since the whole text is passed to it

**Comment by pinarol** [comment]
Thanks for reporting that @dratwas. Right, it looks like a general problem about pasting links.
@lukewalczak Let's open an issue for [that](https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866#issuecomment-584216725) and add to [Mobile Gutenberg](https://github.com/orgs/wordpress-mobile/projects/43) board.

**Comment by geriux** [comment]
Tested again with the new cases and all working great! 🎉

✅ Button block - New Button is created with the gray color
✅ Button block - The newly created button has set background color to the theme-default color in preview 
✅ Button block - Tapping delete key removes block when Button is empty
✅ Button block - Toolbar link button is active when Button has link

By the way regarding to this:

> Tested the new build with new test cases and everything works great, however, I found an issue related to the `link from the clipboard`. If i select text wit link in it i.e:
> `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris http://loremipsum.com` The whole text is passed to the `URL` field. The issue is not only Button related since the paragraph link does the same.

Happens with any text even if they don't have any link in it. So you can add it in the issue as well @dratwas =)

**Comment by iamthomasbishop** [comment]
Most everything is looking good, so I think we can ship the block now and iterate. I have one clarification regarding the selection outline, which isn't a blocker.

I'm still seeing the outline as "inside" the button, whereas I was hoping that it could be "outside" (similar to how box-shadow is applied, to the _outside_ of the element). Here's a diagram to better explain the preferred styling:

<a href="https://user-images.githubusercontent.com/1200432/74179195-93b54f00-4c02-11ea-8c71-72b1476302fb.jpeg"></a>

The benefit of placing the outline _outside_ would be that it should prevent the button from "jumping" on the canvas — it stays in place.

------- 

I also agree with @pinarol's comment regarding alignment. I had forgotten that the Buttons block was recently introduced and will "deprecate" the Button block:

> This is highly related with Buttons block work, it'd be better if we handle that as a part of that work.

**Comment by lukewalczak** [comment]
@iamthomasbishop thanks for an explanation! I think I've found the desired solution:

unselected | selected
--- | ---
Screenshot 2020-02-10 at 22 31 32 | Screenshot 2020-02-10 at 22 31 30

**Comment by iamthomasbishop** [comment]
That's looking great, just tried out the newest test build! :shipit: !

**Comment by geriux** [comment]
LGTM! Tested again on Android with the latest changes. Great work!

**Comment by dratwas** [comment]
Tested on iOS and everything works as expected :) Good job @lukewalczak 🎉

**Pull request merged**
