### PR TITLE
Remove test case from Test Suite 4

### PR DESCRIPTION
**Pull request by fluiddot**
Removes `Link from the clipboard is presented as an option in the link picker` test case as it's already covered in an integration test ([reference](https://github.com/WordPress/gutenberg/blob/97ab6b167cc0d9da6c5f0ecf6be9457570d33731/packages/components/src/mobile/link-settings/test/edit.native.js#L210-L255)).

**To test:**
* Check that all CI jobs succeed.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by geriux** [comment]
Thanks for removing this one! Could we also remove the test images from the repo?

**Comment by fluiddot** [comment]
> Thanks for removing this one! Could we also remove the test images from the repo?

Ah, true. I'll remove them asap.

**Comment by fluiddot** [comment]
> > Thanks for removing this one! Could we also remove the test images from the repo?
> 
> Ah, true. I'll remove them asap.

Done in https://github.com/wordpress-mobile/gutenberg-mobile/pull/5795/commits/43af4affcb837028037edce72131dea5ad28dab5. cc @geriux

**Review by geriux — APPROVED** [review]
LGTM! 🚀

**Review by geriux — APPROVED** [review]
LGTM! 🚀

**Review by dcalhoun — APPROVED** [review]
🚀 

~I'm restarting the failing [Android Native Unit Tests task](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/20446/workflows/9be43f93-d2d2-4c9e-8e30-05dff8a09c81/jobs/116104?invite=true#step-109-145). 🤞🏻~ It can't be restarted until the sibling tasks finish. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@wordpress_react-native-aztec:generateReleaseRFile'.
> A failure occurred while executing com.android.build.gradle.internal.res.GenerateLibraryRFileTask$GenerateLibRFileRunnable
   > /home/circleci/project/gutenberg/packages/react-native-aztec/android/build/intermediates/merged_manifest/release/AndroidManifest.xml
```

**Comment by fluiddot** [comment]
> 🚀
> 
> ~I'm restarting the failing [Android Native Unit Tests task](https://app.circleci.com/pipelines/github/wordpress-mobile/gutenberg-mobile/20446/workflows/9be43f93-d2d2-4c9e-8e30-05dff8a09c81/jobs/116104?invite=true#step-109-145). 🤞🏻~ It can't be restarted until the sibling tasks finish.

I went ahead and restart it.

**Pull request merged**
