### PR TITLE
Experiment - Android X migration

### PR DESCRIPTION
**Pull request by marecar3**
Issue: https://github.com/wordpress-mobile/gutenberg-mobile/issues/1062

With this PR we are migrating `gutenberg-mobile` android application to [AndroidX](https://developer.android.com/jetpack/androidx).

RN already provided AndroidX support so we are targeting[ RN60 with @jtreanor's patch for cocoapods](https://github.com/jtreanor/react-native#v0.60.0-patched) in this PR 

Libraries that are also migrated to AndroidX:

1. [Aztec-Android ](https://github.com/wordpress-mobile/AztecEditor-Android/pull/825/files)

2. [react-native-video](https://github.com/wordpress-mobile/react-native-video/commit/7d5905c76229e71c3ec519952a5fc3572c79feb4)

3. [react-native-recyclerview-list](https://github.com/wordpress-mobile/react-native-recyclerview-list/compare/master...wordpress-mobile:experiment/android_x_migration)

[WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/pull/10020) against this PR.

**Note:** As we are using the newest version of `jsc-android` 241213, should we push it on : https://dl.bintray.com/wordpress-mobile/react-native-mirror/org/webkit/android-jsc/ ? @hypest @jtreanor (not sure)

~~**Not working:**~~  Working ✅ 

1. Gutenberg mobile tests, `enzyme` complains that adapter isn't set, I assume that it's something with RN60 version, maybe @etoledom can help here with some hint?

2. WordPress-Android tests -> jitpack.io can't build `react-native-video-wordpress` as it can't find RN60 at https://dl.bintray.com/wordpress-mobile/react-native-mirror/com/facebook/react/react-native/

@hypest I am curios should we push RN60 there or maybe I just wrongly configured `react-native-video` https://github.com/wordpress-mobile/react-native-video/compare/enable-android-build-of-standalone-package...wordpress-mobile:experiment/android_x_migration#diff-3a56ae3cf3e05886fec69653e96f2456R53

I must admit that I am not sure how build.gradle file should be configured as I saw that jitpack is trying to call this command: `./gradlew clean -Pgroup=com.github.wordpress-mobile -Pversion=57ad4e840a -xtest -xlint install` in `react-native-video`.
  
Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

**Comment by hypest** [comment]
Update: I pushed RN v0.60.0-rc.1, JSC-r241213 to the Bintray mirror.

**Comment by hypest** [comment]
WPAndroid PR, at least for testing purposes: https://github.com/wordpress-mobile/WordPress-Android/pull/10022

**Comment by hypest** [comment]
I tried to build the latest gutenberg-mobile develop with the wpandroid develop using binary artifacts (source mode off) and it works (including running the app and the editor) so, this PR is not a blocker for the v1.7 code freeze. Besides, this PR updates React Native to a RC version which we don't want to ship yet so, better to postpone anyway.

**Comment by jtreanor** [comment]
Just FYI, you can follow the RN v0.60.0 release discussion here: https://github.com/react-native-community/releases/issues/116

**Comment by marecar3** [comment]
> WPAndroid PR, at least for testing purposes: [wordpress-mobile/WordPress-Android#10022](https://github.com/wordpress-mobile/WordPress-Android/pull/10022)

Hey @hypest, should I decline this WPAndroid PR : https://github.com/wordpress-mobile/WordPress-Android/pull/10020/files

**Comment by mkevins** [comment]
One issue I've encountered is that Appium tests are failing. It seems that there is a Selenium error `NoSuchElement` when trying to locate the various UI elements via `AccessibilityId`.

I've investigated this, and so far, I've found that `cont-desc` has a comma and a space (`, ` ) appended to all the accessibility ids. When appending `, ` to the identifier, I am able to get the element locator code paths working. I will investigate further to see how to best proceed.

**Comment by hypest** [comment]
> Hey @hypest, should I decline this WPAndroid PR : https://github.com/wordpress-mobile/WordPress-Android/pull/10020/files ?

👋 @marecar3 , we can actually go back to using #10020, perhaps after removing the packaging related options and just update the JSC version, like in #10022. We can then close #10022. WDYT?

**Comment by maxme** [comment]
>     3\. react-native-recyclerview-list

I'm curious about this, is it still used in `gutenberg-mobile`?

**Comment by hypest** [comment]
> I'm curious about this, is it still used in gutenberg-mobile?

👋 @maxme , nope, it's there in the deps but we're not using it during runtime.

**Comment by hypest** [comment]
We also need to make this work with the source-mode flag on and using `wasabiDebug` on wpandroid. I think wpandroid currently crashes with

```
2019-06-12 17:06:40.384 24771-24771/org.wordpress.android.beta E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk"],nativeLibraryDirectories=[/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/lib/arm, /data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5798)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

and 

```
2019-06-12 17:06:40.440 24771-24771/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 24771
    java.lang.RuntimeException: Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk"],nativeLibraryDirectories=[/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/lib/arm, /data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6445)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk"],nativeLibraryDirectories=[/data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/lib/arm, /data/app/org.wordpress.android.beta-FCuEL6qFKjk6jIYj9faokg==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6429)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5987) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5902) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by marecar3** [comment]
> > Hey @hypest, should I decline this WPAndroid PR : https://github.com/wordpress-mobile/WordPress-Android/pull/10020/files ?
> 
> 👋 @marecar3, we can actually go back to using #10020, perhaps after removing the packaging related options and just update the JSC version, like in #10022. We can then close #10022. WDYT?

I have closed this one: https://github.com/wordpress-mobile/WordPress-Android/pull/10022
in favor of  https://github.com/wordpress-mobile/WordPress-Android/pull/10020

**Comment by marecar3** [comment]
It seems that tests are fixes which is a good step forward. Thanks, @mkevins 
cc: @hypest

**Comment by etoledom** [comment]
Please do not merge yet.
Because of the RN update, there are some work yet to be done on the iOS side.

**Comment by marecar3** [comment]
This PR now points to RN-60-RC2.
I didn't find any major issues in Android Demo and WPAndroid applications.
@daniloercoli @hypest @etoledom

**Comment by etoledom** [comment]
RC2 didn't fix the problems on iOS. We might get unblocked thanks to the great job from @jtreanor here: https://github.com/facebook/react-native/pull/25393

**Comment by hypest** [comment]
Moving this to the next milestone since it is blocked.

**Comment by marecar3** [comment]
Hey 👋 @etoledom @daniloercoli @hypest @jtreanor 
I have updated RN version to RN-60-RC-3. 
It would be good if we can do another round of testing to make sure that everything is in the place.

**Comment by etoledom** [comment]
iOS side looks good to go! ✅ 🎉 

Tested on the demo app and WPiOS via https://github.com/wordpress-mobile/WordPress-iOS/pull/12056

**Comment by hypest** [comment]
As far as I can see, the Aztec PR is not green yet and needs more migration of the testsuites. I pushed a commit to fix some of them but more work is needed. Let's get it green before we merge the rest of the PR set so we can be more confident we haven't broken something.

**Comment by marecar3** [comment]
> As far as I can see, the Aztec PR is not green yet and needs more migration of the testsuites. I pushed a commit to fix some of them but more work is needed. Let's get it green before we merge the rest of the PR set so we can be more confident we haven't broken something.

Ok, I will take care of that one @hypest

**Comment by hypest** [comment]
👋 @daniloercoli , can you do another round of testing to mainly verify I didn't break something with 4107bf6? Thanks!

**Pull request merged**
