### PR TITLE
Update Gutenberg to master

### PR DESCRIPTION
**Pull request by koke**
There seems to be a breaking change in https://github.com/WordPress/gutenberg/pull/15120

```
error: bundling failed: Error: transform-react-jsx: pragma has been set but pragmafrag has not been set
    at PluginPass.exit (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/plugin-transform-react-jsx/lib/index.js:117:15)
    at newFn (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/koke/a8c/gutenberg-mobile/node_modules/@babel/traverse/lib/index.js:94:17)
```

### CODE REVIEW

**Comment by koke** [comment]
In 16c1a79e15e491b28575ff1b5164f2aaeb7f3d27 I tried adding the [recommended configuration](https://github.com/WordPress/gutenberg/commit/13a2d6fa8d09703e93d77b2b4dba1f0571095123?short_path=d3744cf#diff-d3744cf965b449287acc829243484735), but I'm still getting an error:

```
ReferenceError: Can't find variable: Fragment

This error is located at:
    in SlotComponent (at slot.js:95)
    in Slot (at slot-fill/index.js:16)
    in BlockControlsSlot (at block-toolbar.js:86)
    in RCTScrollContentView (at ScrollView.js:953)
    in RCTScrollView (at ScrollView.js:1092)
    in ScrollView (at block-toolbar.js:57)
    in RCTView (at View.js:45)
    in View (at block-toolbar.js:56)
    in BlockToolbar (at with-dispatch/index.js:122)
    in ComponentWithDispatch (at with-dispatch/index.js:129)
    in WithDispatch(BlockToolbar) (at with-select/index.js:187)
    in ComponentWithSelect (at with-select/index.js:196)
    in WithSelect(WithDispatch(BlockToolbar)) (at block-manager.js:278)
    in RCTView (at View.js:45)
    in View (at KeyboardAvoidingView.js:207)
    in KeyboardAvoidingView (at keyboard-avoiding-view.ios.js:23)
    in KeyboardAvoidingView (at block-manager.js:274)
    in RCTView (at View.js:45)
    in View (at block-manager.js:251)
    in RCTSafeAreaView (at SafeAreaView.js:45)
    in SafeAreaView (at block-manager.js:291)
    in BlockManager (at with-dispatch/index.js:122)
    in ComponentWithDispatch (at with-dispatch/index.js:129)
    in WithDispatch(BlockManager) (at with-select/index.js:187)
    in ComponentWithSelect (at with-select/index.js:196)
    in WithSelect(WithDispatch(BlockManager)) (at AppContainer.js:180)
    in SlotFillProvider (at provider/index.native.js:130)
    in BlockEditorProvider (at provider/index.native.js:21)
    in WithRegistry(BlockEditorProvider) (at with-dispatch/index.js:122)
    in ComponentWithDispatch (at with-dispatch/index.js:129)
    in WithDispatch(WithRegistry(BlockEditorProvider)) (at AppContainer.js:174)
    in AppContainer (at with-dispatch/index.js:122)
    in ComponentWithDispatch (at with-dispatch/index.js:129)
    in WithDispatch(AppContainer) (at with-select/index.js:187)
    in ComponentWithSelect (at with-select/index.js:196)
    in WithSelect(WithDispatch(AppContainer)) (at App.js:33)
    in AppProvider (at src/index.js:69)
    in RootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

render
    slot.js:85:3
finishClassComponent
    ReactNativeRenderer-dev.js:11581:21
updateClassComponent
    ReactNativeRenderer-dev.js:11509:4
performUnitOfWork
    ReactNativeRenderer-dev.js:17276:21
workLoop
    ReactNativeRenderer-dev.js:17316:41
renderRoot
    ReactNativeRenderer-dev.js:17417:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:18423:17
performWork
    ReactNativeRenderer-dev.js:18324:24
performSyncWork
    ReactNativeRenderer-dev.js:18285:14
requestWork
    ReactNativeRenderer-dev.js:18169:19
scheduleWork
    ReactNativeRenderer-dev.js:17969:16
scheduleRootUpdate
    ReactNativeRenderer-dev.js:18642:15
render
    ReactNativeRenderer-dev.js:19512:20
renderApplication
    renderApplication.js:61:34
run
    AppRegistry.js:104:10
runApplication
    AppRegistry.js:198:26
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
```

@sirreal is there any required change that I'm missing?

**Comment by koke** [comment]
Importing the plugins directly in f8c10a7 seems to work for running the app, but the tests are failing, and I'm not sure why. It looks like the main issue is that the `@wordpress/babel-plugin-import-jsx-pragma` with the changes hasn't been published yet.

**Comment by sirreal** [comment]
We've been chatting via other channels, but for the record:

- https://github.com/WordPress/gutenberg/commit/39f568faf2e62c57736bb80d7088a996eb067944 introduces a change that requires an unpublished version of the `@wordpress/babel-plugin-import-jsx-pragma` package.
- That change is fine within the Gutenberg monorepo, because the local package is used and doesn't need to be published.
- That's causing breakage here because the required (unpublished) version of the package can't be used.
- Attempting to use the local (git submodule) version of that package leads to other problems, like its dependencies not being installed or found (`@babel/plugin-proposal-async-generator-functions`)

If possible, I'd encourage waiting for the packages to be published. I don't have any say, but I've been told they should be published soon.

**Comment by sirreal** [comment]
Updating to `d8f1875c229f49f9af501c3259bbd16461aa6aae` works fine in my testing. That's from yesterday and is pretty close to the current master HEAD.

**Pull request merged**
