### PR TITLE
Release 1.46.0

### PR DESCRIPTION
**Pull request by fluiddot**
Release for Gutenberg Mobile 1.46.0

## Related PRs

- Gutenberg: https://github.com/WordPress/gutenberg/pull/28634
- WPAndroid: https://github.com/wordpress-mobile/WordPress-Android/pull/13927
- WPiOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/15752

## Extra PRs that Landed After the Release Was Cut

- Correct condition in setting blockWidth - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3079
- Fix height of the bottom-sheet after using back button - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3080
- Audio Block - I - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2854
- Enable Audio Block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3070
- Move custom indicator to be rendered above the colors - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3098
- Fix download button in File block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3102

## Changes

- Correct full width buttons - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3077
- Disable Unsupported block editor for Reusable blocks - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3067
- Audio Block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2854
- Add proper handling for single use blocks such as the more block - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3042
- Reusable blocks - Present block content (preview mode) - https://github.com/wordpress-mobile/gutenberg-mobile/pull/2953
- Add Array.prototype.flatMap polyfill - https://github.com/wordpress-mobile/gutenberg-mobile/pull/3035

## Test plan

- Use the main WP apps to test the changes above. 
- Smoke test the main WP apps for [general writing flow](https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).

## Release Submission Checklist

- [x] Approve and run optional Android and iOS UI tests
- [x] Check if `RELEASE-NOTES.txt` and `gutenberg/packages/react-native-editor/CHANGELOG.md` are updated with all the changes that made it to the release.
- [x] Bundle package of the release is updated.

### CODE REVIEW

**Comment by fluiddot** [comment]
### Android: Writing Flow checklist 🟡

**Tested on Samsung Galaxy S20 FE 5G, Android 10**

#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components 🟡  
    - **Text flickering**: When a line is deleted in any component the text jumps for a frame.
    - **Quote block splits it on new line**: Tapping `enter` on an empty line splits the block, I'm not sure if this is expected but the rest of multiline blocks don't behave this way.
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by ceyhun** [comment]
### iOS Writing Flow checklist 🟡

Tested on iPhone 11 Pro, iOS 14.3

#### General
- [x] TC001 - Paste formatted text copied from website. 
**Note:** The image behind "Join us!" was not copied over but this might be the current case because the [How We Work](https://automattic.com/how-we-work/) page was recently updated. I tried copying https://wordpress.com/blog/2021/01/25/building-single-page-websites-on-wordpress-com/ instead and images were also pasted.
- [x] TC001 - Multiline components 🟡
**Quote Block**: Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Cursor jumps back to quote instead of citation.
**Pullquote Block**: Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Pullquote block is selected instead of cursor moving back to citation.
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

**Comment by fluiddot** [comment]
> Note: The image behind "Join us!" was not copied over but this might be the current case because the How We Work page was recently updated. I tried copying https://wordpress.com/blog/2021/01/25/building-single-page-websites-on-wordpress-com/ instead and images were also pasted.

I also noticed this issue but I think it's not copying it because the image is a background image.

**Comment by fluiddot** [comment]
>**Quote Block:** Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Cursor jumps back to quote instead of citation.
**Pullquote Block:** Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Pullquote block is selected instead of cursor moving back to citation.

I also reproduced this issue on Android but I didn't report it because there's already an [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/2498) that is linked in the test cases. If it's happening on iOS too we could update it including the new case.

**Comment by ceyhun** [comment]
>I also reproduced this issue on Android but I didn't report it because there's already an issue that is linked in the test cases. If it's happening on iOS too we could update it including the new case.

I think it's not the same issue. This happens when merging a paragraph block into quote block. I just tested on WPiOS 16.6.20210129 and 16.5.20210129 and it's also present there, so it's not a regression in this version. I'll create separate issues for these.

**Comment by fluiddot** [comment]
> > I also reproduced this issue on Android but I didn't report it because there's already an issue that is linked in the test cases. If it's happening on iOS too we could update it including the new case.
> 
> I think it's not the same issue. This happens when merging a paragraph block into quote block. I just tested on WPiOS 16.6.20210129 and 16.5.20210129 and it's also present there, so it's not a regression in this version. I'll create separate issues for these.

Oh sorry, I misunderstood the steps, right, it's not the same issue. By the way, I've just checked this on Android and it's happening there too.

**Comment by ceyhun** [comment]
Quote issue is same on the web, it might be an expected behavior. But not the Pullquote one, I've created an issue for this: https://github.com/wordpress-mobile/gutenberg-mobile/issues/3089

**Comment by chipsnyder** [comment]
Hey 👋 I'll be starting the Sanity-Tests on iOS. For each of these I'll be testing on an iPhone 11 running 13.5.1 and testing against build `41359` from: https://github.com/wordpress-mobile/WordPress-iOS/pull/15752#issuecomment-770893524

### Gallery - 1

- [x] Gallery block - Close/Re-open post with an ongoing image upload - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc001)
- [x] Gallery block - Close post with an ongoing image upload - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc002)

### Gallery - 2

- [x] Gallery block - Insert image from device (failing) - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc006)
- [x] Gallery block - Insert image from device (cancel) - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc009)

### Gallery - 3

- [x] Gallery block - Add Gallery Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc003)
- [x] Gallery block - Add Gallery Image Caption - [TC04](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc004)
- [x] Gallery block - Try adding same images from WP Media library and moving the images around - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/gallery.md#tc010)

### Columns - 1

- [x] Columns - Columns percentage mechanism - column's preview - [TC019](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc019)
- [x] Columns - Columns percentage mechanism - column's slider input - [TC020](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc020)
- [x] Columns - Columns percentage mechanism - predefined percentage values are rendered correctly on frontend- [TC021](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc021)
- [x] Columns percentage mechanism - custom percentage values are rendered correctly on frontend- [TC022](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc022)
- [x] Columns - Multiple slider in columns parent - [TC023](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc023)
- [x] Columns - Adding Column with AppenderButton - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc003)
- [x] Columns - Adding and removing Column with BottomSheet Stepper control - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc004)


### Columns - 2
- [x] Columns - Max limit of Column number - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc005)
- [x] Columns - Min limit of Column number - [TC006](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc006)
- [x] Columns - Removing Column with remove button - [TC007](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc007)
- [x] Columns - Removing the only one left Column with remove button - [TC008](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc008)
- [x] Columns - Changing alignment on Columns - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc009)
- [x] Columns - Changing alignment on individual Column - [TC010](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc010)
- [x] Columns - Alignment attribute is properly passed when adding Column - [TC011](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc011)
- [x] Columns - Deep nesting is possible (iOS only)- [TC012](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc012)

### Columns - 3
- [x] Columns - Check if Column placeholders is visible for the unselected state - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc002)
- [x] Columns - Appearance in vertical device position (vertical layout) - [TC013](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc013)
- [x] Columns - Appearance in horizontal device position (horizontal layout) - [TC014](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc014)
- [x] Columns - Mover direction - [TC015](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc015)
- [x] Columns - Check if Column placeholder is render in nested structure - [TC016](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc016)
- [x] Columns - Unselected Column placeholder is stretched to content in nested structure- [TC017](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/columns.md#tc017)

### MediaText - 1

- [x] Media Text block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc001-i)
- [x] Media Text block - Close/Re-open post with an ongoing image upload - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc003-i)

### MediaText - 2

- [x] Media Text block - Insert video from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-v)
- [x] Media Text block - Insert image from device (TC002) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-text.md#tc002-i)

### MultipleUpload - 1

- [x] Simultaneous uploads - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/media-interaction.md#tc001)


### Cover - 1

- [x] Cover - Add image background from WordPress Media library - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc001)
- [x] Cover - Change Minimum height in pixels - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc002)
- [x] Cover - Change Background Opacity - [TC009](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc009)
- [x] Cover - Image focal point is rendered properly - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc003)
- [x] Cover - Custom color is rendered properly - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/cover.md#tc004)

### Editor Theme - 1

- [x] Default Colors - Check that default colors still load - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc001)
- [x] Default Gradients - Check that default gradients still load - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc002)
- [x] Custom Colors - Check that custom colors load in the editor - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/editor-theme.md#tc003)

### Social Icons - 1
- [x] The newly created Social Icons block is added with 4 icons - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc001)
- [x] Active icon gets product color - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc002)
- [x] Only active icons are visible when not selected - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/social-icons.md#tc003)

**Comment by enejb** [comment]
Hey 👋 I'll be starting the Sanity-Tests on Android. For each of these I'll be testing on an Samsung Galaxy A8 running Android 9 and testing against build from: https://github.com/wordpress-mobile/WordPress-Android/pull/13927


**DarkMode-1**

- [x] Gallery block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc001)
- [x] Shortcode block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc002)
- [x] Media Text block - Dark mode - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/darkmode.md#tc003)
Note: The vertical aligmnet options are not inline any more. 


**Group-1**

- [x] Group - AppenderButton is rendered - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc001)
- [x] Group - Deep nesting is possible (iOS only) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc002) Didn't test. 
- [x] Group - Check if Group placeholder is visible for the unselected state - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc003)
- [x] Group - Check if Group placeholder is render in nested structure - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc004)
- [x] Group - Nested block have proper border styling - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc005)
- [x] Group - Nested block have proper margins values - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc006)
- [x] Group - Breadcrumbs on FloatingToolbar is properly displayed - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/group.md#tc008)


**Spacer-1**

- [x] Spacer block - Spacer is rendered without crash - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc001)
- [x] Spacer block - Settings: Control spacer height using the slider - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc002)
- [x] Spacer block - Settings: Control spacer height using the text input - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/spacer.md#tc003)



**Buttons-1**

- [x] Buttons block - Buttons block is added with focused Button with gray background color and white text color - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc001)
- [x] Buttons block - Buttons inline appender - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc002)
- [x] ????  Buttons block - Add another Button inside Buttons using inserter - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc003)
I think this might be working as described. Since I tested this on the column block. But it didn't work quite as expected for me. When I have the "Buttons" (not singular) selected the inverter shows me all the blocks. but if I have a single button selected the inserted shows me just the ability to insert a button block. 

- [x] Buttons block - Button's wrapper grows properly - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc023)

**Buttons-2**

- [x] Buttons block - Removing Button along with Buttons block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc004)
- [x] Buttons block - Removing exactly one Button (when Buttons contain more of them) - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc005)

**Buttons-3**

- [x] Buttons block - Wrapping Buttons - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc006)
- [x] Buttons block - Buttons alignment options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc007)

**Button-6**

- [x] Buttons block - Settings: Open in new tab - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc011)
- [x] Buttons block - Settings: Link rel - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc012)
- [x] Buttons block - Settings: Link URL - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc010)
- [x] Buttons block - Settings: Remove link - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc014)
- [x] Buttons block - Settings: Synchronize with button options - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/buttons.md#tc013)



**Color Settings - 1** 
- 👎 Colors Segmented Controls - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001)
I am able to crash the app by switching between the gradient and solid colour really quickly. Eventually the app crashed and I am not able to continue. I have to restart the app.

- [x] Scroll color palette to start - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc002)
- 👎  Scroll color palette to the end - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc003)
It doesn't scroll to the end for me 

**Image - 1**
- [x] Image block - Insert image from device (failing) - [TC001](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc001)
- [x] Image block - Insert image from device (cancel) - [TC002](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc002)
- [x] Image block - Add Caption - [TC003](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc003)
- [x] Image block - Close/Re-open post with an ongoing image upload - [TC004](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc004)
- [x] Image block - Close post with an ongoing image upload - [TC005](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/image.md#tc005)


**Story block - 1**
- [x] Story block - Verify is available in Block Picker - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc001)
- [x] Story block - Verify is not available in Block Picker- [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc002)
- [x] Story block - Add media to empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc003)
- [x] Story block - Add media to non-empty Story block - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc004)
- [x] Story block - Close/Re-open post with an ongoing Story upload - [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/jetpack/story.md#tc005)

**Comment by fluiddot** [comment]
After the first round of manual tests we found so far the following issues:

## iOS & Android

<details><summary><strong>Quote block splits on new line ✅</strong></summary>

### Description
Tapping enter on an empty line splits the block.

### Next steps
This was checked on the web version and this behaviour is expected so we shouldn't consider this an issue.

</details>

<details><summary><strong>Image not copied when pasting formatted text copied from website ✅</strong></summary>

### Description

The image behind "Join us!" was not copied over but this might be the current case because the How We Work page was recently updated. When copying content from other site like https://wordpress.com/blog/2021/01/25/building-single-page-websites-on-wordpress-com/, the images were also pasted.

### Next steps
The image from How We Work page is not copied because it's rendered as a background images so we shouldn't consider this an issue.

</details>

<details><summary><strong>Quote Block - Wrong cursor position when merging back ✅</strong></summary>

### Description
Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Cursor jumps back to quote instead of citation.

### Next steps
This was checked on the web version and this behaviour is expected so we shouldn't consider this an issue.

</details>

<details><summary><strong>Pullquote Block - Wrong cursor position when merging back 🟡 </strong></summary>

### Description
Split by pressing enter to create a new line at the end of citation and merge back pressing backspace -> Pullquote block is selected instead of cursor moving back to citation.

### Next steps
This behaviour is not expected, however it's also reproducible on released versions like WPiOS 16.6 and 16.5 and WPAndroid 16.6 so this version is not introducing it.

An [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3089) has been created to address it.

</details>

<details><summary><strong>MediaText Block - Vertical alignment options are no longer inlined 🟡 </strong></summary>

### Description
The screenshot of the test case shows the vertical alignment options as inlined, looks like this has been changed in a recent version.

### Next steps
If this change was made on purpose we should update the screenshot.

</details>

## Only iOS
None 🎊 .

## Only Android

<details><summary><strong>Text flickering when removing a line on some multiline blocks 🟡 </strong></summary>

### Description
When a line is deleted in some multiline blocks, specifically the Quote, Preformatted and Verse, the text lines position moves some pixels down for a frame and then goes back to the original position.

### Next steps
This was  checked on latest release candidate version (`16.6-rc-2`) and this issue is also reproducible there so this version is not introducing it.

An [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3096) has been created to address it.

</details>

<details><summary><strong>Colors Segmented Controls crash 🟢  (fixed by @lukewalczak)</strong></summary>

**Fixed in [`gutenberg` PR](https://github.com/WordPress/gutenberg/pull/28698) 🎊 .**

### Description
When switching between the gradient and solid colour really quick the app crashes.

Here are the related [steps](https://github.com/wordpress-mobile/test-cases/blob/master/test-cases/gutenberg/color-settings.md#tc001).

### Next steps
This was checked on release candidate version (`16.6-rc-2`) and this issue is also reproducible there so this version is not introducing it.

Since this is producing a crash it would be nice to fix it in this version. An [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3097) has been created to address it as soon as possible.

</details>

**Comment by fluiddot** [comment]
> 👎 Scroll color palette to the end - steps
It doesn't scroll to the end for me

👋 @enejb I tried to reproduce the issue you commented but so far it's not happening to me, could you try it again?

I did the test on a Samsung Galaxy S20 FE 5G and build `93717`.

https://user-images.githubusercontent.com/14905380/106737350-d7287a80-6616-11eb-94e9-cefd26456a74.mp4

**Comment by fluiddot** [comment]
## Status update

- Colors Segmented Controls crash has been [fixed](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3098) 🎊 
- The issues spotted during the first round of manual tests have been considered as non release blockers so they will addressed in the future:
    - **Pullquote Block - Wrong cursor position when merging back** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3089
    - **MediaText Block - Vertical alignment options are no longer inlined** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3103
    - **Text flickering when removing a line on some multiline blocks** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3096
- The issue on Android related to ["Scroll color palette to the end - It doesn't scroll to the end for me"](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3078#issuecomment-772092411) has been tested but I couldn't reproduce it, at least following the test case instructions. However I managed to reproduce it when testing gradient colors, I've opened an [issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3104) to address it in the future.

**Next step will be to:**
- Test the fix related to ["Colors Segmented Controls crash"](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3098) ✅ 
- Test the fix related to ["Fix download button in File block"](https://github.com/wordpress-mobile/gutenberg-mobile/pull/3102) ✅
- Run a second round of manual tests in both platforms (iOS and Android).
- Review the release PRs

**Comment by fluiddot** [comment]
### Android: Writing Flow checklist [2nd round] 🟡

**Tested on Samsung Galaxy S20 FE 5G, Android 10 - Build 94309**

#### General
- [x] TC001 - Block insertion flow 
- [x] TC001 - Paste formatted text copied from website
- [x] TC001 - Multiline components 🟡  
    - **Text flickering when removing a line on some multiline blocks** - #3096
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection 🟡
    - **Heading block stops being rendered as a header when deleting the first word** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3106
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format

### Result

I found a new issue but it's not related to recent changes, I'm afraid I missed to test the Heading block in the first round for the test case `Splitting and merging` 😞 .

## Extra PRs tested:
  - [x] Move custom indicator to be rendered above the colors - #3098
  - [x] Fix download button in File block - #3102

**Comment by ceyhun** [comment]
### iOS Writing Flow checklist [2nd round] 🟡

Tested on iPhone 11 Pro, iOS 14.3, 41557

#### General
- [x] TC001 - Paste formatted text copied from website. 
- [x] TC001 - Multiline components 🟡
    - **Tapping backspace to merge a paragraph into pullquote block dismisses keyboard:** https://github.com/wordpress-mobile/gutenberg-mobile/issues/3089
#### Rich Text Format
  - [x] TC001 - Bold, Italic, strikethrough buttons
  - [x] TC002 - Alignment buttons
  - [x] TC003 - Alignment Split
  - [x] TC004 - Link button works without selection
  - [x] TC005 - Link button works with a selected word
  - [x] TC006 - Adding a link from a copied URL
  - [x] TC007 - Test format detection under the cursor
  - [x] TC008 - Test formatting doesn't remove leading or trailing whitespace
##### Splitting and merging
  - [x] TC001 - Merge after writing
  - [x] TC002 - Merge after selection
  - [x] TC003 - Merge after deleting text
  - [x] TC004 - Merge after deleting all
  - [x] TC005 - Merge multiple blocks
  - [x] TC006 - Splitting/merge list block
#### Undo / Redo - Test Cases
  - [x] TC001 - Undo/redo block actions
  - [x] TC002 - Undo/redo text
  - [x] TC003 - Undo/redo text format


## Extra PRs tested:
  - [x] Move custom indicator to be rendered above the colors - #3098
  - [x] Fix download button in File block - #3102

**Comment by enejb** [comment]
👋  @fluiddot. I just tested it again and it looks like both Colour issues (Crash and not advancing to the end) are fixed for me. 🥳

**Comment by fluiddot** [comment]
## Status update
The second round of manual tests is finished, no critical issues have been found and latest changes have been verified 🎊 .

Here are the list of issues found in this release that should be addressed in the future:
- **Pullquote Block - Wrong cursor position when merging back** - #3089
- **MediaText Block - Vertical alignment options are no longer inlined** - https://github.com/wordpress-mobile/test-cases/issues/67
- **Text flickering when removing a line on some multiline blocks** - #3096
- **Switching from Solid to Gradient doesn't scroll to end when having customised gradient** - https://github.com/wordpress-mobile/gutenberg-mobile/issues/3104
- **Heading block stops being rendered as a header when deleting the first word** - #3106

### Next steps
- Review and approve the PRs of the release branches.
- Run the last day steps for merging the release into the WordPress app repositories.

**Review by ceyhun — APPROVED** [review]
Things are looking good :shipit:

**Pull request merged**
