### PR TITLE
Workaround React Native 0.71 and XCFramework setup issues

### PR DESCRIPTION
**Pull request by mokagio**
~~Same as #5908 but without Hermes, just to see how it works in Jetpack/WordPress.~~

~~I disabled Hermes because adding it required some additional setup (see #5908) which [I'm not sure I have worked out yet](https://buildkite.com/automattic/gutenberg-mobile/builds/6349#018901de-9250-49b3-892b-7eb9aea45b95).~~

This is the first build I get to compile and run successfully on my machine when integrated. A WordPress CI build is running [here](https://buildkite.com/automattic/wordpress-ios/builds/15067).

**Update**: I have builds that compile and on which I can load the editor for both implementations, with and without Hermes. I made whether to use engine configurable at build time with the `HERMES_ENABLED` environment variable. It's now on by default because my understanding is that is the preferred solution.

### CODE REVIEW

**Comment by fluiddot** [comment]
iOS Ci jobs are passing with this workaround 🎊 (we can omit `Test iOS on Device - Canaries` as it's also failing in the base branch). @mokagio In order to unblock the iOS installable build, we'd like to set this PR ready to review, and eventually merge it. Let us know if you have any concerns about this, thanks 🙇 !

**Comment by mokagio** [comment]
@fluiddot sorry to hold you up. I've been investigating this branch for a good part of my day, starting from CI to run the tests when [using the XCFramework built from `f2d1b716bcf0ec89c637dd0f035c0188dcce6f38`](https://github.com/wordpress-mobile/WordPress-iOS/commit/b8fd2c13383aa9dc566b806dfbdcf6d5c6aa4ed5):

image

The problem, as can be seen when using that version [locally](https://github.com/wordpress-mobile/WordPress-iOS/pull/20845/commits/b8fd2c13383aa9dc566b806dfbdcf6d5c6aa4ed5), is that Hermes cannot be found

```
dyld[99988]: Library not loaded: @rpath/hermes.framework/hermes
  Referenced from: <931F58EC-3AC7-39DE-BEB7-1D44D8A5CF15> /Users/gio/Library/Developer/CoreSimulator/Devices/90F54127-B854-4ED8-93FA-D58167331941/data/Containers/Bundle/Application/3DA26EC7-B308-4029-9974-426839535542/WordPress.app/Frameworks/Gutenberg.framework/Gutenberg
```

I _think_ what happened is that the fix for that issue that I had implemented in https://github.com/wordpress-mobile/gutenberg-mobile/commit/b77ceee2192b97f31be5074d997f3b43ffe66acf got lost when I ported over the work from #5908 to this PR.

I'm working on addressing that... Apologies for the delay.

**Comment by fluiddot** [comment]
> I _think_ what happened is that the fix for that issue that I had implemented in [b77ceee](https://github.com/wordpress-mobile/gutenberg-mobile/commit/b77ceee2192b97f31be5074d997f3b43ffe66acf) got lost when I ported over the work from #5908 to this PR.
> 
> I'm working on addressing that... Apologies for the delay.

@mokagio No worries, let me know if I can help any how on this workaround 🙇 . I tried exploring part of my day building the WP-iOS app using Gutenberg locally, but no luck so far. For now, and for the sake of unblocking the iOS builds for the RN upgrade, I'd advocate focusing on the CI installable builds. After that, we could explore how to enable local builds.

**Comment by mokagio** [comment]
FYI, I am working on the said fixes in https://github.com/wordpress-mobile/gutenberg-mobile/pull/5924 

> For now, and for the sake of unblocking the iOS builds for the RN upgrade, I'd advocate focusing on the CI installable builds. After that, we could explore how to enable local builds.

+1

**Comment by mokagio** [comment]
Closing in favor of #5924

**Pull request closed without merging**
