### PR TITLE
Update minimum `node` and `npm` versions

### PR DESCRIPTION
**Pull request by fluiddot**
Following the changes introduced in https://github.com/WordPress/gutenberg/pull/53426. We update the `node` and `npm` versions to use:
* node 16
* npm 8

**To test:**
* Observe that all CI jobs pass.

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by SiobhyB — APPROVED** [review]
Verified the changes look good, as well as the fact I'm able to build the demo apps with them applied. Thank you for updating this @fluiddot 🙇‍♀️

**Comment by noahtallen** [comment]
By the way, I'd highly recommend running `npm dedupe` to reduce the number of changes in the package-lock file!

**Comment by fluiddot** [comment]
> By the way, I'd highly recommend running `npm dedupe` to reduce the number of changes in the package-lock file!

Oh, I didn't know about that command, thanks for the recommendation Noah 🙇 ! I'll create another PR to apply this suggestion.

**Comment by fluiddot** [comment]
> Oh, I didn't know about that command, thanks for the recommendation Noah 🙇 ! I'll create another PR to apply this suggestion.

Done here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/6054.

**Pull request merged**
