### PR TITLE
build: XCFramework includes local resources

### LINKED ISSUE #21620: Unsupported block fails to open for editing
An exception on step 5 of TC001 in [unsupported-block-editing---test-cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).

Screenshot 2023-09-21 at 5 06 53 PM

```
WordPress/GutenbergWebViewController.swift:104: Fatal error: Failed to load `extra-localstorage-entries` JS script for Unsupported Block Editor: sourceFileNotFound("extra-localstorage-entries.js")
```

When I comment out the assertions, it doesn't crash, but the page doesn't load and there is the following message in the consul:

```
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=54, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'window.wp.data'), WKJavaScriptExceptionColumnNumber=16, WKJavaScriptExceptionSourceURL=user-script:2, NSLocalizedDescription=A JavaScript exception occurred}
```

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/f5d7a603-cf42-4882-b8f4-b6031b7afd23

### Steps to reproduce the behavior
 
Follow the linked TC.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

iPhone Simulator, iOS 17
23.3 RC (compiled from 9bfba439f1e91f68867af7e1a6f41a3b317f73bf)

### PR DESCRIPTION
**Pull request by dcalhoun**
## Description

These resource files were not included during the XCFramework build
phase. The absence resulted in a crash when the unsupported block 
editor (UBE) attempted to load the asset.

Fixes https://github.com/wordpress-mobile/WordPress-iOS/issues/21620.

## Testing Instructions

Clone [WordPress-iOS](https://github.com/wordpress-mobile/WordPress-iOS) and switch to the `trunk` branch. 

1. Launch Xcode. 
1. [Clear Xcode’s Derived Data](https://stackoverflow.com/a/39495772/378228) directory. 
1. Quit Xcode. 
1. In your WordPress-iOS clone…
    ```
    rm -rf build/
    rm -rf Pods/
    bundle exec pod install
    ```
1. Build the project with Xcode. 
1. Use the editor to open a post containing an unsupported block. 
1. Attempt to use the unsupported block editor to [modify](https://github.com/wordpress-mobile/test-cases/blob/698996af2bb0216fd95c5f65fea43d0f2075640a/test-cases/gutenberg/unsupported-block-editing.md#tc001) the block. 

Note the crash while loading the local asset. 

Modify `Gutenberg/config.yml` to point to the commit from this branch. 

<details><summary>Modification Diff</summary>

```diff
diff --git a/Gutenberg/config.yml b/Gutenberg/config.yml
index d7d70cc490..c8aefe3771 100644
--- a/Gutenberg/config.yml
+++ b/Gutenberg/config.yml
@@ -9,6 +9,7 @@
  #
  #   LOCAL_GUTENBERG=../my-gutenberg-fork bundle exec pod install
 ref:
-  tag: v1.112.0
+  # tag: v1.112.0
+  commit: 24868f25b546527d70fbd3ec2a6c21edb264f775
 github_org: wordpress-mobile
 repo_name: gutenberg-mobile

```

</details>

Repeat the aforementioned steps. Note the crash no longer occurs. 

---

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/trunk/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Review by mokagio — COMMENTED** [review]
Looking good from the looks of the Xcode project file changes.

I wonder if there's a way to prevent future issues of this kind by referencing the folder instead of the individual files 🤔

**Comment by fluiddot** [comment]
> I wonder if there's a way to prevent future issues of this kind by referencing the folder instead of the individual files 🤔

I thought about this too. I haven't checked but I presume that referencing the folder instead might require changing the paths used in WP-iOS for accessing those files. I support exploring this solution but I'd do it in a separate PR, as this one aims to solve a potential crash that would be great to already have it addressed sooner rather than later.

**Review by fluiddot — APPROVED** [review]
LGTM 🎊 ! I confirmed the crash is no longer happening after adding these files, thanks @dcalhoun for fixing it 🏅 .

**Comment by mokagio** [comment]
@fluiddot 

> I support exploring this solution but I'd do it in a separate PR, as this one aims to solve a potential crash that would be great to already have it addressed sooner rather than later.

Oh, for sure. I should have been clear that was more of an idea than something to do in the context of this PR.

**Pull request merged**
