### PR TITLE
Splitting block loses word

### LINKED ISSUE #2373: Splitting Block Before Swiped Word Loses Word
### Describe the bug

On Android, splitting a paragraph block with the cursor immediately before a swiped word causes that word to be lost.

losing_word_on_split mp4

### To Reproduce

1. Add multiple words to a paragraph block by "swiping"
2. Place the cursor directly in front of one of the words you entered by swiping
3. Tap Enter to split the block
4. Observe that the word the cursor was immediately in front of was lost in the split

### Expected behavior

Splitting a block should never lose content.

### Smartphone
 - Device: Pixel 1
 - OS: Android X
 - Version: 1.30 release testing (c2a85e0)

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes #2373

When we press enter in front of swipes words, it causes the cursor to go on the new line but the text that follows is deleted. The Gutenberg PR contains a solution for this issue. 

To test:
Visit this [PR](https://github.com/WordPress/gutenberg/pull/26701)
PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes [more info](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/docs/Release-notes.md) and have added them to [RELEASE-NOTES.txt](https://github.com/wordpress-mobile/gutenberg-mobile/blob/develop/RELEASE-NOTES.txt) if necessary.

### CODE REVIEW

**Comment by ceyhun** [comment]
Bumping the milestone to 1.42, feel free to ping me if it needs to make it to 1.41 this week.

**Review by guarani — COMMENTED** [review]
Left a comment here: https://github.com/WordPress/gutenberg/pull/26701#pullrequestreview-526502752

**Comment by cameronvoell** [comment]
Bumping the milestone to 1.43. feel free to ping me if it needs to make it to 1.42 this week.

**Comment by jd-alexander** [comment]
Closed via https://github.com/WordPress/gutenberg/pull/26701#issuecomment-740208303

**Pull request closed without merging**
