### PR TITLE
Upgrade to React Native v0.59.0

### PR DESCRIPTION
**Pull request by hypest**
This PR tracks the effort to upgrade to the v0.59.x version of React Native.

Known issues:
1. ~On the android side of things, the demo app fails to keep the title block to its original value. It seems that there is a "stray" `AppContainer.setTitleAction()` call that empties the title, but trying to follow the callstack in the debugger shows things that don't make sense. Looks like the JS files could be mixed up somehow. Thing is, the RN app works fine inside wpandroid so, we can probably tackle this issue separately~. Seems fixed after updating with a recent `develop`.
2. When using a JS Debugger in Android, the stacktrace seems like it's pointing to the wrong source files. Example:
```
  * Place a `debugger;` statement in the beginning of the `SplitBlock()` in `paragraph/edit.native.js`
  * Run the android demo app and enable JS debugging
  * Place the caret inside a paragraph block and hit "Enter" to split it
  * Notice the debugger pausing on a "SplitBlock" method alright (check the stacktrace panel) but the file pointed at is `image/index.js` which makes no sense.
```

### CODE REVIEW

**Comment by etoledom** [comment]
First tests looks good.
Wanted to highlight that this seems to fix: https://github.com/wordpress-mobile/gutenberg-mobile/issues/729 🎉

I'll also test integration with WPiOS. @SergioEstevao is there a branch for this?

**Comment by etoledom** [comment]
WPiOS looks good too. I'll publish a branch if there's any.

**Comment by marecar3** [comment]
Hey @hypest, nice work here :)

1. I found some glitch in the demo app. I have tested the application on my Nexus 5x, Android 8.0
and when I try to tap on the Header block it automatically switches focus to the upper next Paragraph block

ezgif com-video-to-gif (2)

2. On WPAndroid there is a similar glitch when keyobard is dismissed I want to focus the last paragraph but focus is lost.
ezgif com-video-to-gif (3)

**Comment by hypest** [comment]
Thanks for taking this for a test drive @marecar3 !

Nice find about the focus. What I actually see is that the focus seems to move _as you scroll_ even! This can "explain" why the focus moves when the keyboard comes up and such. Quite frustrating. Will look into it.

**Comment by etoledom** [comment]
I couldn't reproduce any of those issues on iOS. (both example and WPiOS apps).

I do think that is necessary a new JS Bundle, since currently WPiOS is broken without metro running.

**Comment by etoledom** [comment]
Opent WPiOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/11271

**Comment by hypest** [comment]
There's this issue on the ReactNative repo https://github.com/facebook/react-native/issues/23916 that is probably related to the scrolling/focus issue we're seeing here.

**Comment by hypest** [comment]
I pushed c2d1889 that has a workaround for the losing-focus-on-scroll issue, by disabling the Flatlist's optimization of destroying the views when they get out of the viewport. That's a real bummer of course but, we apparently will need to implement a proper support for Views recycling that is more compatible with focus preservation.

For reference, this is the PR that sets that prop to default true for Android in React Native: https://github.com/Rachelmorrell/react-native/pull/170

**Comment by hypest** [comment]
@marecar3 , I think the No1, No2, No3 findings you mentioned got fixed with c2d1889. Can you recheck?

Regarding finding No4 (`Missing padding on placeholder`), I'm not able to replicate. Tried Pixel 2XL (Android 9.0) and Nexus 5X Emulator (Android 8.0.0). Can you try again or maybe share more info about the device/OS you tried it on? Thanks!

**Comment by marecar3** [comment]
@hypest nice that we fixed those, I will try the branch now and will come back with the new feedback.

**Comment by marecar3** [comment]
Hey @hypest I have pointed this branch to the latest GB develop - 3f234faf8b811bdfd8ada5899836b3521d886163 but getting the below error : 

Screen Shot 2019-03-14 at 1 30 40 PM

Not sure if it's something wrong only on my laptop

**Comment by hypest** [comment]
I've updated from current `develop` and pushed.

Fortunately, that fixed one known issue.

The Android demo app and wpandroid look good during my testing. @SergioEstevao can you do another round of smoke testing on the iOS side of things to make sure this will not disrupt anything if we merge? Thanks!

**Pull request merged**
